/**
 *  @file
 *
 *  @brief      Top level application manager.
 *
 *  @copyright  Copyright 2015-2018 Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------
//-------------------------------------- Include Files ----------------------------------------------------------------
// -- This Module --
#include "SystemConfig.h"
#include "ApplianceMgr.h"
#include "ApplianceMgr_prv.h"

// -- Other Modules --
#if (SYSTEM_ACU_EXPANSION_HANDLING == ENABLED)
    #include "ACUExpLoadMonitor.h"
#endif
#if (TIME_ESTIMATION_FEATURE == ENABLED)
    #include "Estimator.h"
#endif
#include "Hbl.h"
#include "Mode.h"
#if (SYSTEM_ACU_HANDLING == ENABLED)
    #include "Log.h"
	#include "Millis.h"
    #include "RegulationAccept.h"
    #include "Supervisor.h"
#endif

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
#if (SYSTEM_ACU_HANDLING == ENABLED)
    //! Counter for determining a millisecond has elapsed using Millis free running counter.
    static uint32 Millisecond_Counter;

    //! Number of deciseconds since power up. Used to wait for Input settling before running a cycle.
    static uint16 Deciseconds_Since_Power_Up;

    //! Maximum number of seconds to wait for system to stabilize before running cycles.
    #define POWER_UP_STABILIZATION_TIME_MAX (60.0)

    //! Default number of seconds to wait for system to stabilize before running cycles. Disables time feature if used.
    #define POWER_UP_STABILIZATION_TIME_DEFAULT (0.0)

    //! Set time feature to default (disabled) if not defined.
    #ifndef POWER_UP_STABILIZATION_TIME
        #define POWER_UP_STABILIZATION_TIME (POWER_UP_STABILIZATION_TIME_DEFAULT)
    #endif

    #define POWER_UP_STABILIZATION_DECISECONDS ((uint16)(POWER_UP_STABILIZATION_TIME * 10))
    #define POWER_UP_STABILIZATION_MAX_DECISECONDS ((uint16)(POWER_UP_STABILIZATION_TIME_MAX * 10))

    // Verify power up stabilization is less than or equal to the maximum allowed.
    CT_ASSERT (POWER_UP_STABILIZATION_DECISECONDS <= POWER_UP_STABILIZATION_MAX_DECISECONDS);

    //! Set default (disabled) power up stabilization guard.
    #ifndef POWER_UP_STABILIZATION_GUARD
        #define POWER_UP_STABILIZATION_GUARD (TRUE)
    #endif

    //! If macro is not defined, define as empty
    #ifndef CALL_PRE_MONITORS_STABLE
        #define CALL_PRE_MONITORS_STABLE()
    #endif

    //! If macro is not defined, define as empty
    #ifndef CALL_POST_MONITORS_STABLE
        #define CALL_POST_MONITORS_STABLE()
    #endif

    // --- LOG MODULE SETTINGS ---------------------------
    //! The name of this module for use by the Log module.
    #define MODULE_NAME MODULE_APPLIANCE_MANAGER

    //! A list of log message IDs that are generated by this module.
    typedef enum MODULE_APPLIANCE_MANAGER_LOG_MESSAGE_ID_ENUM
    {
        MAX_TIMEOUT_REACHED = 1,    //!< POWER_UP_STABILIZATION_TIME_MAX before timeout or guard reached.
    } MODULE_APPLIANCE_MANAGER_LOG_MESSAGE_ID_TYPE;

    //! Tracks whether the system is stable (TRUE) or not yet stable (FALSE)
    static BOOL_TYPE System_Stable;
#endif

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
#if (SYSTEM_ACU_HANDLING == ENABLED)
    static BOOL_TYPE SystemStable(void);
#endif

//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the module ApplianceMgr and its variables.
 *              Initialize top application layer modules in a cascading manner.
 *
 */
void ApplianceMgr__Initialize(void)
{
    INIT_MONITORS();

    #if (SYSTEM_ACU_HANDLING == ENABLED)
        Millisecond_Counter = Millis__GetFreeRunningCounter();
        Deciseconds_Since_Power_Up = 0;
        Supervisor__Initialize();                   // Calls interpreter initialize which calls all process initializers.
    #endif

    #if (TIME_ESTIMATION_FEATURE == ENABLED)
        Estimator__Initialize();
    #endif

    #if (SYSTEM_ACU_EXPANSION_HANDLING == ENABLED)
        ACUExpLoadMonitor__Initialize();
    #endif
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Implements Appliance Manager Behavior.
 *
 */
void ApplianceMgr__Handler(void)
{
    if (Mode__GetSubMode() == SUBMODE_NORMAL_SUPERVISOR)
    {
        Hbl__FlushRequestBuffer();

        #if (SYSTEM_ACU_HANDLING == ENABLED)
            CALL_PRE_MONITORS();

            SystemStable();
            if (System_Stable == TRUE)
            {
                CALL_PRE_MONITORS_STABLE();
                if (Supervisor__IsTestCycleActive() == FALSE)
                {
                    for (uint8 compartment = 0; compartment < APPLIANCE_MAX_COMPARTMENTS; compartment++)
                    {
                        Supervisor__Run(compartment);
                    }
                }
                else
                {
                    // Run only compartment 0 while test cycle is active.
                    Supervisor__Run(0);
                }
                CALL_POST_MONITORS_STABLE();
            }
        #endif

        CALL_POST_MONITORS();

        #if (SYSTEM_ACU_EXPANSION_HANDLING == ENABLED)
            ACUExpLoadMonitor__Execute();
        #endif

        #if (SYSTEM_ACU_HANDLING == ENABLED)
            // Accept all regulations that should always be accepted but have not yet been accepted.
            RegulationAccept__Background();
        #endif

        #if (TIME_ESTIMATION_FEATURE == ENABLED)
            Estimator__Background();
        #endif
    }
}

#if (SYSTEM_ACU_HANDLING == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Public API to indicate if system inputs have settled and are ready to run cycles.
 *
 *  @retval     TRUE - System inputs are stable and ready for use.
 *  @retval     FALSE - System inputs are not ready for use.
 */
BOOL_TYPE ApplianceMgr__IsStable(void)
{
    return(System_Stable);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Initializes the stability status for the system.
 *
 *  @details    This information is initialized separately from the ApplianceMgr__Initialize() function because
 *              the system must be initialized as "not stable" before any module requests the status of the stability.
 *              This function must be called during the initialization of the communication thread to ensure that the
 *              system is initialized to "not stable", until it can be determined that it is stable.
 */
void ApplianceMgr__InitializeStable(void)
{
    System_Stable = FALSE;
}
#endif


//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================
#if (SYSTEM_ACU_HANDLING == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Indicates when system inputs have settled to a stable state using a configurable time and guard.
 *
 *  @details    Supervisor will start regardless of delay or guard after POWER_UP_STABILIZATION_TIME_MAX.
 *              An exception will be logged if POWER_UP_STABILIZATION_TIME_MAX reached.
 *
 *  @return     BOOL_TYPE system_stable
 *  @retval     TRUE - System inputs are stable and ready for use.
 *  @retval     FALSE - System inputs are not ready for use.
 */
static BOOL_TYPE SystemStable(void)
{
    if (Deciseconds_Since_Power_Up < POWER_UP_STABILIZATION_MAX_DECISECONDS)
    {
        if ((Millis__GetFreeRunningCounter() - Millisecond_Counter) >= 100)
        {
            Millisecond_Counter += 100;
            Deciseconds_Since_Power_Up++;
            if (Deciseconds_Since_Power_Up >= POWER_UP_STABILIZATION_MAX_DECISECONDS)
            {
                LOG_ADD_EXCEPTION(MAX_TIMEOUT_REACHED, Deciseconds_Since_Power_Up);
            }
        }

        if (POWER_UP_STABILIZATION_GUARD == TRUE)
        {
            if ((POWER_UP_STABILIZATION_DECISECONDS == 0) ||
                (Deciseconds_Since_Power_Up >= POWER_UP_STABILIZATION_DECISECONDS))
            {
                Deciseconds_Since_Power_Up = POWER_UP_STABILIZATION_MAX_DECISECONDS;
                System_Stable = TRUE;
            }
        }
    }
    else
    {
        System_Stable = TRUE;
    }

    return (System_Stable);
}
#endif // (SYSTEM_ACU_HANDLING == ENABLED)
