/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------
/*
@startuml{Heat_sm.jpg}
        title Heat State Machine

        [*] --> Initialize

        Initialize : entry / ReadProcessParameters()  \n CheckProcessCall()
        Initialize --> TargetTemp : TargetTemp
        Initialize --> HysteresisControl : hysteresysTemp

        TargetTemp: do / ChecktargetT1() \n checkTimeout() / ActivateHeater
        TargetTemp --> Exit : CheckTargConditionTrue

        HysteresisControl : do / CheckbothTarget()  \n checkTimeout()  / ActivateHeater
        HysteresisControl --> Exit: CheckTimeoutTrue

        Exit: do / returnTRUE()

        @enduml
*/
//-------------------------------------- Include Files ----------------------------------------------------------------
#include "C_Extensions.h"
#include "Heat.h"
#include "Heat_prv.h"

#include "Fault.h"
#include "Micro.h"
#include "NVData.h"
#include "StatisticsDish.h"

//=====================================================================================================================
//=== StateEngineCrank (v2.8) Auto-Generated Definitions for Heat State Machine
//=====================================================================================================================
// !! StateEngineCrank cannot update this code if you change the header !!


//! Unique names used to identify states of the Heat state machine.
typedef enum HEAT_STATE_ENUM
{
    STATE_HEAT_NONE               = 0,

    STATE_HEAT_INITIALIZE         = 1,              //!< (initial_state)
    STATE_HEAT_TARGET_TEMP        = 2,
    STATE_HEAT_HYSTERESIS_CONTROL = 3,
    STATE_HEAT_EXIT               = 4,

    STATE_HEAT_END                = 5
} HEAT_STATE_TYPE;

//! The state variable for the Heat state machine.
//! State machines with a history pseudostate may write to this variable during initialization.
//! Other state machines must only write to this variable through auto-generated functions.
static HEAT_STATE_TYPE Heat_State;

//! The transition variable for the Heat state machine.
//! Flag used by the state machine to track when a transition occurs in the middle of a state's
//! Entry() or Do() action that contains more than one function.
static BOOL_TYPE Heat_Transitioned;

// -- Private Function Prototypes used by the state machine for customization functions --
static void ActivateHeater(void);
static void CheckbothTarget(void);
static void CheckProcessCall(void);
static void ChecktargetT1(void);
static void CheckTimeout(void);
static void ReadProcessParameters(void);
static void ReturnTRUE(void);

// -- Private Function Prototypes used by the state machine for standard state machine functions --
static void EventCheckTargConditionTrue(void);
static void EventCheckTimeoutTrue(void);
static void EventHysteresysTemp(void);
static void EventTargetTemp(void);
static void HeatExecute(void);
static void HeatInitialize(void);
static void HeatTerminate(void);

// !! StateEngineCrank cannot update this code if you change the footer !!
// End of StateEngineCrank Auto-Generated Code.

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------
//! The RAM data structure required for each instance of the Heat process.

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------


//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_HEAT

//! Displacement value that indicates that the feature is not used.
#define UNUSED_FEATURE 0xFF

// number of process calls per second
#define HEAT_CALL_RATE 10

// timeout resolution in sec
#define HEAT_TIMEOUT_RES 10

//! The types of Heat variations that are available.
typedef enum HEAT_OPTION_ENUM
{
    HEAT_OPTION_TARGET,                   //!< F1=0, F0=0
    HEAT_OPTION_RANGE,                    //!< F1=0, F0=1
    HEAT_OPTION_COUNT
} HEAT_OPTION_TYPE;

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_HEAT_LOG_MESSAGE_ID_ENUM
{
    ERROR_PROCESS_CONTROL       = 1,
    ERROR_LOADING_PARAMETERS
} MODULE_HEAT_LOG_MESSAGE_ID_TYPE;

typedef enum HEATER_STATE_ENUM
{
    HEATER_STATE_OFF = 0,
    HEATER_STATE_ON
}HEATER_STATE_TYPE;

//! The data structure of the Heat process parameters as they are found in the setting file.
typedef PACKED struct HEAT_PARAMETER_STRUCT
{
    uint16 Target_Upper_Thr_Temp;
    uint8 Target_Modifier_Table_Index;
    uint8 Lower_Modifier_Table_Index;
    uint16 Lower_Thr_Temp;
    uint16 TimeOut;
    uint8 Timeout_Modifier_Table_Index;
    struct CFG_FLAGS_STRUCT
    {
        uint8 Check_Heater_Not_Heating	:1;
        uint8 Unused					:7;
    } Cfg_Flags;
} HEAT_PARAMETER_TYPE;

// -- Private Variable Definitions --

typedef struct HEAT_INSTANCE_STRUCT
{
    uint16 Target_Upper_Thr_Temp;
    uint16 Lower_Thr_Temp;
    uint16 TimeOut;
    uint8 Heater_Was_ON                 :1;
    uint8 Check_Heater_Not_Heating		:1;
} HEAT_INSTANCE_TYPE;

#pragma location = "_appliance_segment"
static uint16 Heat_Remaining_Time;  // 1 sec resolution

#pragma location = "_appliance_segment"
static HEAT_INSTANCE_TYPE Heat;

#pragma location = "_appliance_segment"
static BOOL_TYPE Upper_Target_Reached;

static BOOL_TYPE Process_Completed;

//! The process control structure used by all the state machine functions.
static PROCESS_CONTROL_TYPE* Control;

static BOOL_TYPE Heat_Ready_To_Exit;

static HEATER_STATE_TYPE Heater_Request;

static BOOL_TYPE Heat_Process_Initialized;

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------

static void ReadHeatParameters(SETTINGFILE_LOADER_TYPE* loader, HEAT_INSTANCE_TYPE* data);

//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

void Heat__Initialize(void)
{
	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		if (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != (NVDATA_RESTORE_TYPE)NVDATA_RESTORE_OKAY)
		{
			Heat_Remaining_Time = 0;
			Upper_Target_Reached = FALSE;
		}

		Heat_Process_Initialized = FALSE;
	}
}


PROCESS_RESULT_TYPE Heat__Process(PROCESS_CONTROL_TYPE* control)
{
    PROCESS_RESULT_TYPE result = PROCESS_COMPLETE;
    HEAT_OPTION_TYPE option = (HEAT_OPTION_TYPE)control->F1_F0_Flags;
    if ((control == NULL ) ||
        (control->Compartment >= APPLIANCE_MAX_COMPARTMENTS) ||
        (option >= HEAT_OPTION_COUNT))
    {
        LOG_ADD_EXCEPTION(ERROR_PROCESS_CONTROL, (control != NULL));
    }
    else
    {
        Control = control;
        if (((uint8)control->Step_Initializing == (uint8)TRUE) ||
        	((uint8)control->Resume_From_Reset == (uint8)TRUE) ||
			(((uint8)control->Resume_From_Pause == (uint8)TRUE) && (Heat_Process_Initialized == FALSE)))
        {
            // Initialize this instance of the Heat process.
        	Heat_Ready_To_Exit = FALSE;
            Heater_Request = HEATER_STATE_OFF;

            HeatInitialize();
           	StatisticsDish__ResetHeatDurationCounter();

            Process_Completed = FALSE;
        }
        else
        {
            HeatExecute();
        }

    }//*/

    if((uint8)Heat_Ready_To_Exit == (uint8)TRUE)
    {
    	result = PROCESS_COMPLETE;

    	if(Process_Completed == FALSE)
    	{
    		StatisticsDish__UpdateHeatRelatedMeasures();
    		Process_Completed = TRUE;
    	}
    }
    else
    {
    	StatisticsDish__UpdateHeatRelatedMeasures();
    	StatisticsDish__UpdateHeatDurationCounter();
    	result = PROCESS_BUSY;
    }

    return result;
}


void Heat__ResetHeatTimeoutFault(void)
{
	Fault__ConditionRemoved(FAULT_ID_HEATER_NOT_HEATING_WATER);
}

//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 * Read the setting file parameters for this instance of the Heat process.
 * @param control = The process control parameters from the Interpreter.
 */

static void ReadHeatParameters(SETTINGFILE_LOADER_TYPE* loader, HEAT_INSTANCE_TYPE* data)
{
    HEAT_PARAMETER_TYPE* parameter;
    uint8 modifier_index;
    sint16 Current_Temp;
    sint32 modified_value;

    parameter = (HEAT_PARAMETER_TYPE*)(void*)loader->Data;
    modifier_index = parameter->Target_Modifier_Table_Index;
    // Apply modifier on calculated temperature.
    if ((uint8)UNUSED_FEATURE != modifier_index)
    {
        modified_value = Modifier__GetValue((sint32)(parameter->Target_Upper_Thr_Temp), parameter->Target_Modifier_Table_Index);
		if (modified_value < 0)
		{
			modified_value = 0;
		}
    	Heat.Target_Upper_Thr_Temp = (uint16)modified_value;
    }
    else
    {
        Heat.Target_Upper_Thr_Temp = parameter->Target_Upper_Thr_Temp;
    }

    modifier_index = parameter->Lower_Modifier_Table_Index;
    // Apply modifier on calculated temperature.
    if ((uint8)UNUSED_FEATURE != modifier_index)
    {
        if ((HEAT_OPTION_TYPE)HEAT_OPTION_RANGE == (HEAT_OPTION_TYPE)Control->F1_F0_Flags)
        {
            modified_value = Modifier__GetValue((sint32)(parameter->Lower_Thr_Temp), parameter->Lower_Modifier_Table_Index);
    		if (modified_value < 0)
    		{
    			modified_value = 0;
    		}
        	Heat.Lower_Thr_Temp = (uint16)modified_value;
        }
    }
    else
    {
        if ((HEAT_OPTION_TYPE)HEAT_OPTION_RANGE == (HEAT_OPTION_TYPE)Control->F1_F0_Flags)
        {
            Heat.Lower_Thr_Temp = parameter->Lower_Thr_Temp;
        }
    }

    modifier_index = parameter->Timeout_Modifier_Table_Index;
    // Apply modifier on calculated temperature.
    if ((uint8)UNUSED_FEATURE != modifier_index)
    {
        modified_value = Modifier__GetValue(((sint32)parameter->TimeOut*(sint32)HEAT_TIMEOUT_RES),parameter->Timeout_Modifier_Table_Index);
		if (modified_value < 0)
		{
			modified_value = 0;
		}
        Heat.TimeOut = (uint16)modified_value;
    }
    else
    {
        Heat.TimeOut = (uint16)(parameter->TimeOut*(uint16)HEAT_TIMEOUT_RES);
    }

    if ((HEAT_OPTION_TYPE)HEAT_OPTION_RANGE == (HEAT_OPTION_TYPE)Control->F1_F0_Flags)
    {
        Current_Temp = (sint16)Hbl__GetGIDataConvertedByIndex((HBL_GENERIC_INPUT_ENUM_TYPE)Hbl__GetGIIndexByGIID(HBL_GI_WASHING_PROBE));
        if (((sint32)Current_Temp >= (sint32)Heat.Lower_Thr_Temp) && ((sint32)Current_Temp <= (sint32)Heat.Target_Upper_Thr_Temp))
        {
            Heat.Heater_Was_ON = TRUE;
        }
        else
        {
            Heat.Heater_Was_ON = FALSE;
        }
    }
    else
    {
        Heat.Heater_Was_ON = FALSE;
    }

    Heat.Check_Heater_Not_Heating = parameter->Cfg_Flags.Check_Heater_Not_Heating;
}


//=====================================================================================================================
//  --- Private State Machine Customization Functions -----------------------------------------------------------------
//=====================================================================================================================



//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void ActivateHeater(void)
{
    HEATER_STATE_TYPE heater_state;
    if (HEATER_STATE_ON == Heater_Request)
    {
        heater_state = HEATER_STATE_ON;
        (void)Hbl__SetLoadRequestByLoadID(HBL_LOAD_WASHING_HEATER, HBL_PRIORITY_APPLICATION_HI, (uint8 *) &heater_state);
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void CheckbothTarget(void)
{
    sint16 Current_Temp;
    Current_Temp = (sint16)Hbl__GetGIDataConvertedByIndex((HBL_GENERIC_INPUT_ENUM_TYPE)Hbl__GetGIIndexByGIID(HBL_GI_WASHING_PROBE));
    if ((sint32)Current_Temp <= (sint32)Heat.Lower_Thr_Temp)
    {
        Heater_Request = HEATER_STATE_ON;
        Heat.Heater_Was_ON = TRUE;
    }
    else if (((sint32)Current_Temp <(sint32) Heat.Target_Upper_Thr_Temp) && ((uint8)Heat.Heater_Was_ON == (uint8)TRUE))
    {
        Heater_Request = HEATER_STATE_ON;
    }
    else
    {
        Heater_Request = HEATER_STATE_OFF;
        Heat.Heater_Was_ON = FALSE;
    }

    if ((sint32)Current_Temp >= (sint32)Heat.Target_Upper_Thr_Temp)
    {
    	if (Upper_Target_Reached == FALSE)
    	{
			// When the upper target temperature is reached, this call is used to remove a possible fault
			// that might have been declared in a previous Heat instance in the same cycle.
			Fault__ConditionRemoved(FAULT_ID_HEATER_NOT_HEATING_WATER);

			Upper_Target_Reached = TRUE;
    	}
    }

}


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void CheckProcessCall(void)
{
    sint32 Current_Temp;
    Current_Temp = Hbl__GetGIDataConvertedByIndex((HBL_GENERIC_INPUT_ENUM_TYPE)Hbl__GetGIIndexByGIID(HBL_GI_WASHING_PROBE));

    if (Current_Temp != LONG_MAX)
    {
        if ((HEAT_OPTION_TYPE)Control->F1_F0_Flags == (HEAT_OPTION_TYPE)HEAT_OPTION_TARGET)
        {
            if ((sint32)Current_Temp < (sint32)Heat.Target_Upper_Thr_Temp)
            {
                Heater_Request = HEATER_STATE_ON;
                ActivateHeater(); // if previous step activated heater, keep it active
            }

            EventTargetTemp();
            Heat_Remaining_Time = Heat.TimeOut;
    		Upper_Target_Reached = FALSE;
        }
        else if ((HEAT_OPTION_TYPE)Control->F1_F0_Flags == (HEAT_OPTION_TYPE)HEAT_OPTION_RANGE)
        {
            if ((sint32)Current_Temp <= (sint32)Heat.Lower_Thr_Temp)
            {
                Heater_Request = HEATER_STATE_ON;
                ActivateHeater(); // if previous step activated heater, keep it active
            }
			else if (((sint32)Current_Temp < (sint32)Heat.Target_Upper_Thr_Temp) && ((uint8)Heat.Heater_Was_ON == (uint8)TRUE))
            {
                Heater_Request = HEATER_STATE_ON;
                ActivateHeater(); // if previous step activated heater, keep it active
            }
            else
            {
                //nothing to do
            }

            EventHysteresysTemp();
            Heat_Remaining_Time = Heat.TimeOut;
    		Upper_Target_Reached = FALSE;
        }
        else
        {
            // nothing to do
        }
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void ChecktargetT1(void)
{
    sint16 Current_Temp;
    Current_Temp = (sint16)Hbl__GetGIDataConvertedByIndex((HBL_GENERIC_INPUT_ENUM_TYPE)Hbl__GetGIIndexByGIID(HBL_GI_WASHING_PROBE));
    if ((sint32)Current_Temp >= (sint32)Heat.Target_Upper_Thr_Temp)
    {
    	// When the target temperature is reached, this call is used to remove a possible fault
    	// that might have been declared in a previous Heat instance in the same cycle.
    	Fault__ConditionRemoved(FAULT_ID_HEATER_NOT_HEATING_WATER);

		Upper_Target_Reached = TRUE;

		Heat_Ready_To_Exit = TRUE;

		EventCheckTargConditionTrue();
    }
    else
    {
        Heater_Request = HEATER_STATE_ON;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void CheckTimeout(void)
{
    static uint8 tick = 0;

    tick++;
    if (tick >= (uint8)HEAT_CALL_RATE)
    {
        tick = 0;
        if (Heat_Remaining_Time > (uint16)0)
        {
            Heat_Remaining_Time--;
        }
    }
    if (Heat_Remaining_Time == (uint16)0)
    {
        if (Heat_State == STATE_HEAT_TARGET_TEMP)
        {
        	if ((uint8)Heat.Check_Heater_Not_Heating == (uint8)TRUE)
        	{
        		Fault__ConditionDetected(FAULT_ID_HEATER_NOT_HEATING_WATER);
        	}

        	Heat_Ready_To_Exit = TRUE;

            EventCheckTargConditionTrue();
        }
        if (Heat_State == STATE_HEAT_HYSTERESIS_CONTROL)
        {
        	if (((uint8)Heat.Check_Heater_Not_Heating == (uint8)TRUE) && (Upper_Target_Reached == FALSE))
        	{
        		Fault__ConditionDetected(FAULT_ID_HEATER_NOT_HEATING_WATER);
        	}

        	Heat_Ready_To_Exit = TRUE;

            EventCheckTimeoutTrue();
        }
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void ReadProcessParameters(void)
{
    SETTINGFILE_LOADER_TYPE loader;
    HEAT_INSTANCE_TYPE parameter;

    // Get the Maintain process parameters from the setting file.
    if (SettingFile__MSettingBasicLoader(Control->Setting_File_Index,
                                         SF_PTR_ACU_PROCESS_HEAT,
                                         Control->Data_Field_Index,
                                         &loader) == FAIL)
    {
        LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, Control->Data_Field_Index);
    }
    else
    {
        // Read the setting file data into local variables for convenience.
        ReadHeatParameters(&loader, &parameter);

        Heat_Process_Initialized = TRUE;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void ReturnTRUE(void)
{
	Heat_Ready_To_Exit = TRUE;
    HeatTerminate();
}

//=====================================================================================================================
//=== StateEngineCrank (v2.8) Auto-Generated Functions for Heat State Machine
//=====================================================================================================================
// !! StateEngineCrank cannot update this code if you change the header !!


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Check Targ Condition True Event for the Heat state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventCheckTargConditionTrue(void)
{
    switch (Heat_State)
    {
        case STATE_HEAT_TARGET_TEMP:
            Heat_State = STATE_HEAT_EXIT;
            Heat_Transitioned = TRUE;
            break;

        default:
            // Event is ignored for all other values of Heat_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Check Timeout True Event for the Heat state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventCheckTimeoutTrue(void)
{
    switch (Heat_State)
    {
        case STATE_HEAT_HYSTERESIS_CONTROL:
            Heat_State = STATE_HEAT_EXIT;
            Heat_Transitioned = TRUE;
            break;

        default:
            // Event is ignored for all other values of Heat_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Hysteresys Temp Event for the Heat state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventHysteresysTemp(void)
{
    switch (Heat_State)
    {
        case STATE_HEAT_INITIALIZE:
            Heat_State = STATE_HEAT_HYSTERESIS_CONTROL;
            Heat_Transitioned = TRUE;
            break;

        default:
            // Event is ignored for all other values of Heat_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Target Temp Event for the Heat state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventTargetTemp(void)
{
    switch (Heat_State)
    {
        case STATE_HEAT_INITIALIZE:
            Heat_State = STATE_HEAT_TARGET_TEMP;
            Heat_Transitioned = TRUE;
            break;

        default:
            // Event is ignored for all other values of Heat_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * The main execution function for the Heat state machine.
 * This function should be called periodically while the state machine is running.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void HeatExecute(void)
{
    Heat_Transitioned = FALSE;
    switch(Heat_State)
    {
        case STATE_HEAT_TARGET_TEMP:
            ChecktargetT1();                        // Do function.
            if (Heat_Transitioned == FALSE)
            {
                CheckTimeout();                     // Do function.
                if (Heat_Transitioned == FALSE)
                {
                    ActivateHeater();               // Do function.
                }
            }
            break;

        case STATE_HEAT_HYSTERESIS_CONTROL:
            CheckbothTarget();                      // Do function.
            if (Heat_Transitioned == FALSE)
            {
                CheckTimeout();                     // Do function.
                if (Heat_Transitioned == FALSE)
                {
                    ActivateHeater();               // Do function.
                }
            }
            break;

        case STATE_HEAT_EXIT:
            ReturnTRUE();                           // Do function.
            break;

        default:
            // There is nothing to do for all other values of Heat_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * The initialization function for the Heat state machine.
 * This function resets the state machine to the initial state and executes the initial state's
 * entry function.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void HeatInitialize(void)
{
    Heat_State = STATE_HEAT_INITIALIZE;
    Heat_Transitioned = FALSE;
    ReadProcessParameters();                        // Entry Function.
    if (Heat_Transitioned == FALSE)
    {
        CheckProcessCall();                         // Entry Function.
    }
    Heat_Transitioned = TRUE;
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * The termination function for the Heat state machine.
 * This function disables the state machine. Calls to StateMachineExecute() will have no effect.
 * The StateMachineInitialize() function must be called again to restart the state machine.
 * If the current state has an exit function, it will be called.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void HeatTerminate(void)
{
    // None of the states have an Exit function.
    Heat_State = STATE_HEAT_NONE;
    Heat_Transitioned = TRUE;
}


// !! StateEngineCrank cannot update this code if you change the footer !!
// End of StateEngineCrank Auto-Generated Code.

