/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "C_Extensions.h"
#include "StabilityControl.h"

#include <limits.h>

#include "AirlockMonitor.h"
#include "Fill.h"
#include "Fault.h"
#include "HeaterCalcificationDetectionMonitor.h"
#include "Interpreter.h"
#include "JumpIf.h" // CYCLE_PHASE_STATEMENT_TYPE
#include "Micro.h"
#include "NormalFill.h"
#include "NVData.h"
#include "PluggingMonitor.h"
#include "SettingFile.h"
#include "StabilityControlLoopMonitor.h"
#include "StatisticsDish.h"
#include "SubCycle.h"
#include "Variable.h"
#include "Vwi.h"

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------
#pragma location = "_appliance_segment"
//! Counters of the number of executions of the subcycles used as reactions
uint8 SC_Subcycle_Execution_Counters[SC_SUBC_EXEC_COUNTERS_NUM];

#pragma location = "_appliance_segment"
//! Bitmap to mark the triggered reactions
uint8 Stability_Control_Flags;


//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_STABILITY_CONTROL

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_STABILITY_CONTROL_LOG_MESSAGE_ID_ENUM
{
	ERROR_LOADING_PARAMETERS       = 1,
} MODULE_STABILITY_CONTROL_LOG_MESSAGE_ID_TYPE;

//! Time that instability condition must be detected continuously before reacting to Instability (macro to convert the setting file value to 100 ms units)
#define INSTABILITY_DETECTION_TIME_100MS 		(Common_Parameters_Ptr->Instability_Detection_Time_x2 * (uint16)5)
//! Time that no water condition must be detected continuously before reacting to No Water (macro to convert the setting file value to 100 ms units)
#define NO_WATER_DETECTION_TIME_100MS 			(Common_Parameters_Ptr->No_Water_Detection_Time_x2 * (uint16)5)
//! Time that no water condition must be detected to declare Very Low Water condition (macro to convert the setting file value to 100 ms units)
#define VERY_LOW_WATER_DETECTION_TIME_100MS 	(Common_Parameters_Ptr->Very_Low_Water_Detection_Time_x2 * (uint16)5)
//! If water is detected as present for this amount of time continuously, reset the timer monitoring for "Very Low Water" (macro to convert the setting file value to 100 ms units)
#define WATER_PRESENT_TIME_100MS 				(Common_Parameters_Ptr->Water_Present_Time_x2 * (uint16)5)

//! Value used to indicate that there is no limit in the number of subcycle executions
#define INVALID_MAX_SUBCYCLE_CALLS			255

//! Multiplier to get the actual speed from the setting file speed reduction minimum speed parameter
#define SETTING_FILE_SPEED_MULTIPLIER			25

//! Setting file parameters structure for a single instance of the stability Control Task
typedef PACKED struct STABILITY_CONTROL_INSTANCE_PARAMS_STRUCT
{
	uint8 Reaction_To_Very_Low_Water		:4; //! The reaction to trigger if Very Low Water is detected
	uint8 Reaction_To_Instability			:4; //! The reaction to trigger if Instability is detected

	uint8 Reaction_To_Air_Lock				:4; //! The reaction to trigger if Air Lock is detected
	uint8 Reaction_To_No_Water				:4; //! The reaction to trigger if No Water is detected

	uint8 Reaction_After_Max_Phase_Repeats	:4; //! The reaction to trigger when one of the other events has caused the phase to repeat the maximum number of times
	uint8 Reaction_To_Plugged_Filter		:4; //! The reaction to trigger if Plugged Filter is detected

	uint8 Phase_Where_To_Restart;			//! The phase of the current cycle where to jump if a Restart Phase reaction is triggered
	uint8 Phase_Where_To_Skip;				//! The phase of the current cycle where to jump if a Skip Phase reaction is triggered.

	uint8 Loop_Detection_Secondary_Reaction	:4; //! The reaction to trigger when Loop Detection secondary reaction is requested
	uint8 Loop_Detection_Primary_Reaction	:4; //! The reaction to trigger when Loop Detection primary reaction is requested

	uint8 Reaction_After_Max_Speed_Reduct	:4; //! The reaction to trigger when Loop Detection secondary reaction is requested
	uint8 Unused0							:4; //! Unused

	uint8 Unused;							//! Just for alignment
} STABILITY_CONTROL_INSTANCE_PARAMS_TYPE;

//! Setting file parameters structure for a speed reduction
typedef PACKED struct SPEED_REDUCTION_PARAMS_STRUCT
{
	uint8 Minimum_Speed; 				//! Minimum speed as result of speed reduction
	uint8 Fst_Reduction_Percentage; 	//! Percentage speed reduction the first time that Speed Reduction reaction is triggered
	uint8 Snd_Reduction_Percentage; 	//! Percentage speed reduction the second time that Speed Reduction reaction is triggered
	uint8 Unused;						//! Reserved for future expansions
} SPEED_REDUCTION_PARAMS_TYPE;

//! Structure for the maximum number of subcycle calls
typedef struct STABILITY_CONTROL_MAX_SUBCYCLE_CALLS_STRUCT
{
	uint8 Add_Water;		//! Maximum number of SC Add Water Subcycle calls
	uint8 Motor_Restart;	//! Maximum number of SC Motor Restart calls
	uint8 Filter_Plugged;	//! Maximum number of SC Filter Plugged Subcycle calls
	uint8 Defoaming;		//! Maximum number of SC Defoaming Subcycle calls
	uint8 Filter_Plugged_2;	//! Maximum number of SC Filter Plugged #2 Subcycle calls
} STABILITY_CONTROL_MAX_SUBCYCLE_CALLS_TYPE;

//! Instability events that can trigger a reaction by the Stability Control task
typedef enum INSTABILITY_EVENTS_ENUM
{
	SC_NO_INSTABILITY	= 0,
	SC_INSTABILITY,
	SC_VERY_LOW_WATER,
	SC_NO_WATER,
	SC_RIF_AIR_LOCK,
	SC_RIF_PLUGGED_FILTER,
	SC_SCL_PRIMARY_REACTION_REQ,
	SC_SCL_SECONDARY_REACTION_REQ
} INSTABILITY_EVENTS_TYPE;


#pragma location = "_appliance_segment"
//! Pointer to the setting file common parameters for the Stability Control task
static const STABILITY_CONTROL_COMMON_PARAMS_TYPE *Common_Parameters_Ptr;

#pragma location = "_appliance_segment"
//! Setting file parameters for the maximum number of subcycle calls
static STABILITY_CONTROL_MAX_SUBCYCLE_CALLS_TYPE SC_Max_Subcycle_Calls;

#pragma location = "_appliance_segment"
//! Pointer to the setting file parameters for the current instance of the Stability Control task
static const STABILITY_CONTROL_INSTANCE_PARAMS_TYPE *Instance_Parameters_Ptr;

#pragma location = "_appliance_segment"
//! Reaction to be triggered if a Speed Reduction is requested more than twice.
static STABILITY_CONTROL_REACTIONS_TYPE Reaction_After_Max_Speed_Reduct;

#pragma location = "_appliance_segment"
//! Maximum amount of water allowed in the tub
static uint16  Cliters_Max;

#pragma location = "_appliance_segment"
//! Cycle running when the Stability Control task is activated
static uint8 Activation_Cycle;

#pragma location = "_appliance_segment"
//! Speed reduction status
static SPEED_REDUCTION_STATUS_TYPE Speed_Reduction_Status;

#pragma location = "_appliance_segment"
//! Status of the Stability Control task
static ACTIVE_TYPE Stability_Control_Status;

//! The instability event currently detected by the Stability Control task
static INSTABILITY_EVENTS_TYPE Instability_Event;
//! Counter to debounce the INSTABILITY condition detection
static uint16 Instability_Counter;
//! Counter to debounce the NO WATER condition detection
static uint16 No_Water_Counter;
//! Counter to debounce the VERY LOW WATER condition detection
static uint16 Very_Low_Water_Counter;
//! Counter to reset the VERY LOW WATER condition detection
static uint16 Stable_Water_Counter;
//! Set to TRUE when the Stability Control algorithm is suspended (even if the task is still active)
static BOOL_TYPE Task_Suspended;

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
static void ResetInstabilityEvent(void);
static void UpdateInstabilityEvent(void);
static void PartialReactionUpdate(STABILITY_CONTROL_REACTIONS_TYPE *current_reaction_ptr, sint32 liters_in_tub, sint32 phase_repetitions);


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the Stability Control Task module and its variables
 *
 */
ACTIVE_TYPE StabilityControl__Initialize(uint8 compartment, uint8 sf_index, uint8 displacement)
{
	ACTIVE_TYPE ret_value;
    SETTINGFILE_LOADER_TYPE loader;
	CYCLE_PHASE_STATEMENT_TYPE cps;

    ret_value = INACTIVE;

    Common_Parameters_Ptr = NULL;
	Instance_Parameters_Ptr = NULL;
	Reaction_After_Max_Speed_Reduct = SC_REACTIONS_NUM;	// Default value for backward compatibility with old setting file
	Cliters_Max = 0;
	memset(&SC_Max_Subcycle_Calls, INVALID_MAX_SUBCYCLE_CALLS, sizeof(SC_Max_Subcycle_Calls));

	// Get Stability Control common parameters from setting file
	if (SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS, DISPL_STABILITY_CONTROL, &loader) == PASS)
	{
		Common_Parameters_Ptr = (const STABILITY_CONTROL_COMMON_PARAMS_TYPE *)(void *)loader.Data;

		if (loader.Length >= (uint16)12)
		{
			SC_Max_Subcycle_Calls.Add_Water = Common_Parameters_Ptr->Max_Add_Water_Subcycle_Calls;
			SC_Max_Subcycle_Calls.Motor_Restart = Common_Parameters_Ptr->Max_Motor_Restart_Subcycle_Calls;
			SC_Max_Subcycle_Calls.Filter_Plugged = Common_Parameters_Ptr->Max_Filter_Plugged_Subcycle_Calls;
			if (loader.Length >= (uint16)16)
			{
				SC_Max_Subcycle_Calls.Defoaming = Common_Parameters_Ptr->Max_Defoaming_Subcycle_Calls;
				SC_Max_Subcycle_Calls.Filter_Plugged_2 = Common_Parameters_Ptr->Max_Filter_Plugged_2_Subcycle_Calls;
			}
			else
			{
				// Old setting files: the parameters are not present in setting file, the default value is kept
			}
		}
		else
		{
			// Old setting files: the parameters are not present in setting file, the default value is kept
		}

		// Get the Fill parameters from setting file.
		if (SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS, DISPL_CLASS_A_FILL, &loader) == PASS)
		{
			// Class A Fill project

			// Convert Liters_Max in cl
			Cliters_Max = (((CLASS_A_FILL_PARAMETER_TYPE *)(void *)loader.Data)->Liters_In_Tub_Max) * (uint16)5;
		}
		else if (SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS, DISPL_FILL, &loader) == PASS)
		{
			// Non-Class A Fill project

			// Convert Liters_Max in cl
			Cliters_Max = ((const FILL_PARAMETER_TYPE *)(void *)loader.Data)->Liters_Max * (uint16)5;
		}
		else
		{
			// Fill data not present in setting file;
			loader.Data = NULL;
		}

		if (loader.Data != NULL)
		{
			// Get Stability Control instance specific parameters from setting file
			if (SettingFile__BasicLoader(SF_PTR_ACU_STABILITY_CONTROL_DATA, displacement, &loader) == PASS)
			{
				Instance_Parameters_Ptr = (const STABILITY_CONTROL_INSTANCE_PARAMS_TYPE *)(void *)loader.Data;
				if (loader.Length >= (uint16)8)
				{
					Reaction_After_Max_Speed_Reduct = (STABILITY_CONTROL_REACTIONS_TYPE)Instance_Parameters_Ptr->Reaction_After_Max_Speed_Reduct;
				}

				Stability_Control_Status = ACTIVE;
				ret_value = ACTIVE;

				// Enable and initialize Airlock and Plugging algorithms
				AirlockMonitor__Reset();
				AirlockMonitor__Start();

				PluggingMonitor__Start();
				PluggingMonitor__Reset();

				HeaterCalcificationDetectionMonitor__Reset();
				HeaterCalcificationDetectionMonitor__Start();
			}
			else
			{
				LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, (uint16)SF_PTR_ACU_STABILITY_CONTROL_DATA);
			}
		}
		else
		{
			LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, (uint16)DISPL_FILL);
		}

	}
	else
	{
		LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, (uint16)DISPL_STABILITY_CONTROL);
	}

	Fault__ConditionRemoved(FAULT_ID_VERY_LOW_WATER_OR_SUDS);

	ResetInstabilityEvent();

	cps = Interpreter__GetCurrentStatement(COMPARTMENT_DEFAULT);
	Activation_Cycle = cps.Cycle;

	Task_Suspended = FALSE;

	return (ret_value);
}

/**
 * @brief The function is called at the initialize of the task after NVdata restore
 *        It Initializes the Stability Control module and its variables
 *
 * @param compartment that run the task (unused)
 *
 * @return  None
 */
void StabilityControl__NVDataRestore(uint8 compartment)
{
	ResetInstabilityEvent();
	Task_Suspended = FALSE;
}

/**
 * The function called during the execution of the task
 * @param compartment that run the task (inside)
 * @return the status of the task (ACTIVE or INACTIVE)
 */
ACTIVE_TYPE StabilityControl__Task(uint8 compartment)
{
	CYCLE_PHASE_STATEMENT_TYPE cps;

	cps = Interpreter__GetCurrentStatement(COMPARTMENT_DEFAULT);

	if ((cps.Cycle != Activation_Cycle) || ((uint8)Fault__IsObserverActive(FAULT_ID_VERY_LOW_WATER_OR_SUDS) == (uint8)TRUE))
	{
		// PAUSE or Subcycle running (including reaction subcycle: Add water, Motor Restart, Filter Plugged), or
		// Fault Observer active with specific FAULT_ID_VERY_LOW_WATER_OR_SUDS fault ID: the task keeps running
		// but doesn't update inputs nor trigger any reaction.

		if (Task_Suspended == FALSE)
		{
			PluggingMonitor__Pause();
		}

		Task_Suspended = TRUE;
	}
	else
	{
		STABILITY_CONTROL_REACTIONS_TYPE selected_reaction;

		if ((uint8)Task_Suspended == (uint8)TRUE)
		{
			AirlockMonitor__Reset();

			if (Instability_Event == SC_RIF_PLUGGED_FILTER)
			{
				// The suspension of the Stability Control was caused by a reaction to a  Plugging Event
				PluggingMonitor__Reset();
			}
			else
			{
				// The suspension of the Stability Control wasn't caused by a reaction to a  Plugging Event
				PluggingMonitor__Resume();
			}

			// Inputs reset when coming from suspended state
			ResetInstabilityEvent();

			Task_Suspended = FALSE;
		}

		UpdateInstabilityEvent();

		// Get requested reaction from setting file table depending on Instability_Event
		switch (Instability_Event)
		{
			case SC_INSTABILITY:
				selected_reaction = (STABILITY_CONTROL_REACTIONS_TYPE)Instance_Parameters_Ptr->Reaction_To_Instability;
				break;

			case SC_VERY_LOW_WATER:
				selected_reaction = (STABILITY_CONTROL_REACTIONS_TYPE)Instance_Parameters_Ptr->Reaction_To_Very_Low_Water;
				break;

			case SC_NO_WATER:
				selected_reaction = (STABILITY_CONTROL_REACTIONS_TYPE)Instance_Parameters_Ptr->Reaction_To_No_Water;
				break;

			case SC_RIF_AIR_LOCK:
				selected_reaction = (STABILITY_CONTROL_REACTIONS_TYPE)Instance_Parameters_Ptr->Reaction_To_Air_Lock;
				break;

			case SC_RIF_PLUGGED_FILTER:
				selected_reaction = (STABILITY_CONTROL_REACTIONS_TYPE)Instance_Parameters_Ptr->Reaction_To_Plugged_Filter;
				break;

			case SC_SCL_PRIMARY_REACTION_REQ:
				selected_reaction = (STABILITY_CONTROL_REACTIONS_TYPE)Instance_Parameters_Ptr->Loop_Detection_Primary_Reaction;
				break;

			case SC_SCL_SECONDARY_REACTION_REQ:
				selected_reaction = (STABILITY_CONTROL_REACTIONS_TYPE)Instance_Parameters_Ptr->Loop_Detection_Secondary_Reaction;
				break;

			default:
				selected_reaction = SC_REACTION_NONE;
				break;
		}

		if (selected_reaction != SC_REACTION_NONE)
		{
			// Apply modifications to requested reaction, according to requirements
			StabilityControl__UpdateReaction(&selected_reaction);
		}

		if (selected_reaction != SC_REACTION_NONE)
		{
			// Reset Stability Control Loop counters if any reaction is triggered for any reason.
			StabilityControlLoopMonitor__ResetCounters();
		}

		// Trigger requested reaction
		switch (selected_reaction)
		{
			case SC_REACTION_ADD_WATER: case SC_REACTION_ADD_WATER_THEN_RESTART_PHASE: case SC_REACTION_ADD_WATER_THEN_SKIP_PHASE:
			case SC_REACTION_ADD_WATER_THEN_REDUCE_SPEED:
				if (SC_Subcycle_Execution_Counters[ADD_WATER_INDEX] < (uint8)__UNSIGNED_CHAR_MAX__)
				{
					SC_Subcycle_Execution_Counters[ADD_WATER_INDEX] ++;
				}

				(void)SubCycle__RequestStart(COMPARTMENT_DEFAULT, Common_Parameters_Ptr->Add_Water_Subcycle_Priority);
				// Note that in this case a subcycle is going to be executed, during this subcycle the Stability Control
				// will be "suspended", it means that it will not read any input nor trigger any reaction.

				StatisticsDish__IncreaseWaterAddExecutions();
				BIT_SET(Stability_Control_Flags, SC_WATER_ADDED);
				break;

			case SC_REACTION_RESTART_PHASE:
				if (Interpreter__SetPhase(COMPARTMENT_DEFAULT, Instance_Parameters_Ptr->Phase_Where_To_Restart) == PHASE_STEP_RESULT_PASS)
				{
					sint32 phase_repetitions;
					if (Variable__GetValue(VARIABLE_PHASE_REPETITIONS, 0, &phase_repetitions) == FALSE)
					{
						phase_repetitions = 0;
					}

					if (phase_repetitions < UCHAR_MAX)
					{
						(void)Variable__SetValue (VARIABLE_OPERATION_INCREMET, VARIABLE_PHASE_REPETITIONS, 0, 1);
					}

					if (Instability_Event != SC_RIF_AIR_LOCK)
					{
						AirlockMonitor__Reset();
					}

					ResetInstabilityEvent();

					StatisticsDish__IncreaseInterruptedPhasesNum();
					BIT_SET(Stability_Control_Flags, SC_PHASE_RESTARTED);
				}
				break;

			case SC_REACTION_SKIP_PHASE:
				if (Interpreter__SetPhase(COMPARTMENT_DEFAULT, Instance_Parameters_Ptr->Phase_Where_To_Skip) == PHASE_STEP_RESULT_PASS)
				{
					if (Instability_Event != SC_RIF_AIR_LOCK)
					{
						AirlockMonitor__Reset();
					}

					ResetInstabilityEvent();

					StatisticsDish__IncreaseInterruptedPhasesNum();
					BIT_SET(Stability_Control_Flags, SC_PHASE_SKIPPED);
				}
				break;

			case SC_REACTION_MOTOR_RESTART_SUBCYCLE:
				if (SC_Subcycle_Execution_Counters[MOTOR_RESTART_INDEX] < (uint8)__UNSIGNED_CHAR_MAX__)
				{
					SC_Subcycle_Execution_Counters[MOTOR_RESTART_INDEX] ++;
				}

				(void)SubCycle__RequestStart(COMPARTMENT_DEFAULT, Common_Parameters_Ptr->Motor_Restart_Subcycle_Priority);
				// Note that in this case a subcycle is going to be executed, during this subcycle the Stability Control
				// will be "suspended", it means that it will not read any input nor trigger any reaction.
				break;

			case SC_REACTION_FILTER_PLUGGED_SUBCYCLE:
				if (SC_Subcycle_Execution_Counters[FILTER_PLUGGED_INDEX] < (uint8)__UNSIGNED_CHAR_MAX__)
				{
					SC_Subcycle_Execution_Counters[FILTER_PLUGGED_INDEX] ++;
				}

				(void)SubCycle__RequestStart(COMPARTMENT_DEFAULT, Common_Parameters_Ptr->Filter_Plugged_Subcycle_Priority);
				// Note that in this case a subcycle is going to be executed, during this subcycle the Stability Control
				// will be "suspended", it means that it will not read any input nor trigger any reaction.

				BIT_SET(Stability_Control_Flags, SC_FILTER_CLEANED);
				break;

			case SC_REACTION_ERROR_DETECTED:
				Fault__ConditionDetected(FAULT_ID_VERY_LOW_WATER_OR_SUDS);

				BIT_SET(Stability_Control_Flags, SC_FAULT_DETECTED);
				break;

			case SC_REACTION_REDUCE_MOTOR_SPEED:
				if (Speed_Reduction_Status == SC_NO_SPEED_REDUCTION)
				{
					Speed_Reduction_Status = SC_1ST_SPEED_REDUCTION;
					ResetInstabilityEvent();
					StatisticsDish__IncreaseRPMReductions();
					BIT_SET(Stability_Control_Flags, SC_PUMP_RPM_REDUCED_ONCE);
				}
				else if (Speed_Reduction_Status == SC_1ST_SPEED_REDUCTION)
				{
					Speed_Reduction_Status = SC_2ND_SPEED_REDUCTION;
					ResetInstabilityEvent();
					StatisticsDish__IncreaseRPMReductions();
					BIT_SET(Stability_Control_Flags, SC_PUMP_RPM_REDUCED_TWICE);
				}
				else
				{
					// Nothing to do
				}

				break;

			case SC_REACTION_DEFOAMING_SUBCYCLE:
				if (SC_Subcycle_Execution_Counters[DEFOAMING_INDEX] < (uint8)__UNSIGNED_CHAR_MAX__)
				{
					SC_Subcycle_Execution_Counters[DEFOAMING_INDEX] ++;
				}

				(void)SubCycle__RequestStart(COMPARTMENT_DEFAULT, Common_Parameters_Ptr->Defoaming_Subcycle_Priority);
				// Note that in this case a subcycle is going to be executed, during this subcycle the Stability Control
				// will be "suspended", it means that it will not read any input nor trigger any reaction.
				break;

			case SC_REACTION_FILTER_PLUGGED_2_SUBCYCLE:
				if (SC_Subcycle_Execution_Counters[FILTER_PLUGGED_2_INDEX] < (uint8)__UNSIGNED_CHAR_MAX__)
				{
					SC_Subcycle_Execution_Counters[FILTER_PLUGGED_2_INDEX] ++;
				}

				(void)SubCycle__RequestStart(COMPARTMENT_DEFAULT, Common_Parameters_Ptr->Filter_Plugged_2_Subcycle_Priority);
				// Note that in this case a subcycle is going to be executed, during this subcycle the Stability Control
				// will be "suspended", it means that it will not read any input nor trigger any reaction.

				BIT_SET(Stability_Control_Flags, SC_FILTER_CLEANED);
				break;

			default: // Includes SC_REACTION_NONE
				// Nothing to do
				break;
		}

	}

    return(ACTIVE);
}

/**
 * The function used when the task terminate.
 * @param compartment the compartment that uses the task (unused)
 *
 * @return : None
 */
void StabilityControl__Terminate(uint8 compartment)
{
	Stability_Control_Status = INACTIVE;
	Fault__ConditionRemoved(FAULT_ID_VERY_LOW_WATER_OR_SUDS);
	ResetInstabilityEvent();
	Task_Suspended = FALSE;
	Speed_Reduction_Status = SC_NO_SPEED_REDUCTION;

	// Disable Airlock, Plugging and Heater Calcification algorithms
	AirlockMonitor__Stop();
	PluggingMonitor__Stop();
	HeaterCalcificationDetectionMonitor__Stop();

	// Reset subcycle executions counters
	memset(&SC_Subcycle_Execution_Counters[0], 0, sizeof(SC_Subcycle_Execution_Counters));
}


/**
 * It is called after a reset. It initializes some Stability Control variables even when the task is not active.
 *
 * @return  None
 */
void StabilityControl__VariablesInitialize(void)
{
	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		if (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != (NVDATA_RESTORE_TYPE)NVDATA_RESTORE_OKAY)
		{
			Stability_Control_Status = INACTIVE;
			memset(&SC_Subcycle_Execution_Counters[0], 0, sizeof(SC_Subcycle_Execution_Counters));

			Speed_Reduction_Status = SC_NO_SPEED_REDUCTION;

			Stability_Control_Flags = 0;
		}
	}
}


/**
 * It returns the value of Speed_Reduction_Status.
 *
 * @return Speed_Reduction_Status (SC_NO_SPEED_REDUCTION/SC_1ST_SPEED_REDUCTION/SC_2ND_SPEED_REDUCTION)
 */
SPEED_REDUCTION_STATUS_TYPE StabilityControl__GetSpeedReduction(void)
{
	return Speed_Reduction_Status;
}


/**
 * It calculates the speed reduction, based on the current requested speed, on the diverter position and on the setting file speed
 * reduction data table
 *
 * @param motor_speed 	pointer to the current requested speed
 * @param diverter_position 	the diverter position to be considered to load the correct speed reduction data from setting file
 *
 * @return None
 */
void StabilityControl__ReduceSpeed(uint16 *motor_speed, uint8 diverter_position)
{
    SETTINGFILE_LOADER_TYPE loader;
    uint8 num_items;
    const SPEED_REDUCTION_PARAMS_TYPE *speed_reduction_params_ptr;
    uint16 minimum_speed;

    if (SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS, DISPL_SPEED_REDUCTION, &loader) == PASS)
    {
		num_items = (uint8)(loader.Length/sizeof(SPEED_REDUCTION_PARAMS_TYPE));

		if (diverter_position < num_items)
		{
			speed_reduction_params_ptr = (const SPEED_REDUCTION_PARAMS_TYPE *)(void *)(loader.Data + (diverter_position * sizeof(SPEED_REDUCTION_PARAMS_TYPE)));

			minimum_speed = speed_reduction_params_ptr->Minimum_Speed * (uint16)SETTING_FILE_SPEED_MULTIPLIER;

			if (*motor_speed >= minimum_speed)
			{
				if (Speed_Reduction_Status == SC_1ST_SPEED_REDUCTION)
				{
					sint32 partial_result = (sint32)minimum_speed + ((((sint32)*motor_speed - (sint32)minimum_speed) * (sint32)speed_reduction_params_ptr->Fst_Reduction_Percentage)/100);
					*motor_speed = (uint16)partial_result;
				}
				else if (Speed_Reduction_Status == SC_2ND_SPEED_REDUCTION)
				{
					sint32 partial_result = (sint32)minimum_speed + ((((sint32)*motor_speed - (sint32)minimum_speed) * (sint32)speed_reduction_params_ptr->Snd_Reduction_Percentage)/100);
					*motor_speed = (uint16)partial_result;
				}
			}
			else
			{
				// Minimum speed is greater that the speed requested by setting file, do not apply any change.
			}
		}
		else
		{
			// Not enough items in the speed reduction table
		}
	}
 	else
 	{
 		// Setting file data not present
 	}
}


/**
 * It returns the value of Speed_Reduction_Status.
 *
 * @return Stability_Control_Status (INACTIVE/ACTIVE)
 */
ACTIVE_TYPE StabilityControl__GetStatus(void)
{
	return Stability_Control_Status;
}


/**
 * It returns the value of Loop_Detection_Primary_Reaction for the current instance of Stability Control task
 *
 * @return Instance_Parameters_Ptr->Loop_Detection_Primary_Reaction
 */
STABILITY_CONTROL_REACTIONS_TYPE StabilityControl__GetLDPrimaryReaction(void)
{
	return (STABILITY_CONTROL_REACTIONS_TYPE)Instance_Parameters_Ptr->Loop_Detection_Primary_Reaction;
}


/**
 * It returns the value of Loop_Detection_Secondary_Reaction for the current instance of Stability Control task
 *
 * @return Instance_Parameters_Ptr->Loop_Detection_Secondary_Reaction
 */
STABILITY_CONTROL_REACTIONS_TYPE StabilityControl__GetLDSecondaryReaction(void)
{
	return (STABILITY_CONTROL_REACTIONS_TYPE)Instance_Parameters_Ptr->Loop_Detection_Secondary_Reaction;
}


/**
 * It updates the value of the reaction that will be triggered by the Stability Control task, resulting from the requested reaction
 * and from the cross checks on the max amount of water that can be added, on the max number of speed reductions, on the max number
 * of phase repetitions. The resulting reaction may be different from the originally requested one.
 *
 * @param  reaction_ptr: pointer to the reaction
 *
 * @return none
 */
void StabilityControl__UpdateReaction(STABILITY_CONTROL_REACTIONS_TYPE *reaction_ptr)
{
	sint32 liters_in_tub;
	sint32 phase_repetitions;

	if (Variable__GetValue(VARIABLE_LITERS_IN_TUB, 0, &liters_in_tub) == FALSE)
	{
		liters_in_tub = 0;
	}

	if (Variable__GetValue(VARIABLE_PHASE_REPETITIONS, 0, &phase_repetitions) == FALSE)
	{
		phase_repetitions = 0;
	}

	PartialReactionUpdate(reaction_ptr, liters_in_tub, phase_repetitions);

	if ((*reaction_ptr == SC_REACTION_RESTART_PHASE) && (phase_repetitions >= (sint32)Common_Parameters_Ptr->Max_Phase_Repetitions))
	{
		*reaction_ptr = (STABILITY_CONTROL_REACTIONS_TYPE)Instance_Parameters_Ptr->Reaction_After_Max_Phase_Repeats; // Req 706787

		// Repeat all previous checks, since reaction has been updated
		PartialReactionUpdate(reaction_ptr, liters_in_tub, phase_repetitions);

		if (*reaction_ptr == SC_REACTION_RESTART_PHASE)
		{
			*reaction_ptr = SC_REACTION_NONE; // No recursion allowed
		}
	}
}


/**
 * It sets the flags specified by set_mask in Stability_Control_Flags.
 *
 * @param  set_mask: the mask that specifies the flags to set (bit = 1 -> flag set, bit = 0 flag unchanged)
 *
 * @return none
 */
void StabilityControl__SetFlagsMask(uint8 set_mask)
{
	Stability_Control_Flags |= set_mask;
}


/**
 * It resets the flags specified by reset_mask in Stability_Control_Flags.
 *
 * @param  reset_mask: the mask that specifies the flags to reset (bit = 1 -> flag reset, bit = 0 flag unchanged)
 *
 * @return none
 */
void StabilityControl__ResetFlagsMask(uint8 reset_mask)
{
	Stability_Control_Flags &= (reset_mask ^ (uint8)0xFF);
}


//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================


/**
 * The function
 * @param
 *
 * @return :
 */
static void ResetInstabilityEvent(void)
{
	Instability_Event = SC_NO_INSTABILITY;
	Instability_Counter = 0;
	No_Water_Counter = 0;
	Very_Low_Water_Counter = 0;
	Stable_Water_Counter = 0;
}

/**
 * The function
 * @param
 *
 * @return :
 */
static void UpdateInstabilityEvent(void)
{
	VWI_WATER_SENSE_TYPE vwi_status;

	vwi_status = Vwi__GetWaterStatus();

	// VWI Instability detection
	if ((vwi_status == WS_UNSTABLE_NO_WATER) || (vwi_status == WS_UNSTABLE_WATER))
	{
		if (Instability_Counter < INSTABILITY_DETECTION_TIME_100MS)
		{
			Instability_Counter ++;
		}
		else
		{
			Instability_Event = SC_INSTABILITY;
		}
	}
	else
	{
		if (Instability_Event == SC_INSTABILITY)
		{
			Instability_Event = SC_NO_INSTABILITY;
		}

		Instability_Counter = 0;
	}

	// VWI No Water detection
	if ((vwi_status == WS_UNSTABLE_NO_WATER) || (vwi_status == WS_NO_WATER))
	{
		if (No_Water_Counter < NO_WATER_DETECTION_TIME_100MS)
		{
			No_Water_Counter ++;
		}
		else
		{
			Instability_Event = SC_NO_WATER;
		}
	}
	else
	{
		if (Instability_Event == SC_NO_WATER)
		{
			Instability_Event = SC_NO_INSTABILITY;
		}

		No_Water_Counter = 0;
	}

	// VWI Very Low Water detection
	if ((vwi_status == WS_UNSTABLE_NO_WATER) || (vwi_status == WS_NO_WATER))
	{
		if (Very_Low_Water_Counter < VERY_LOW_WATER_DETECTION_TIME_100MS)
		{
			Very_Low_Water_Counter ++;
		}
		else
		{
			Instability_Event = SC_VERY_LOW_WATER;
		}

		Stable_Water_Counter = 0;
	}
	else
	{
		if (vwi_status == WS_WATER)
		{
			if (Stable_Water_Counter < WATER_PRESENT_TIME_100MS)
			{
				Stable_Water_Counter ++;
			}
			else
			{
				if (Instability_Event == SC_VERY_LOW_WATER)
				{
					Instability_Event = SC_NO_INSTABILITY;
				}

				Very_Low_Water_Counter = 0;
			}
		}
		else
		{
			Stable_Water_Counter = 0;
		}
	}

	// Airlock detection
	if (AirlockMonitor__GetStatus() == ALS_AIRLOCK)
	{
		Instability_Event = SC_RIF_AIR_LOCK;
	}
	else
	{
		if (Instability_Event == SC_RIF_AIR_LOCK)
		{
			Instability_Event = SC_NO_INSTABILITY;
		}
	}

	// Plugging detection
	if (PluggingMonitor__GetStatus() == PL_PLUGGING)
	{
		Instability_Event = SC_RIF_PLUGGED_FILTER;

		if ((STABILITY_CONTROL_REACTIONS_TYPE)Instance_Parameters_Ptr->Reaction_To_Plugged_Filter != (STABILITY_CONTROL_REACTIONS_TYPE)SC_REACTION_NONE)
		{
			Fault__ConditionDetected(FAULT_ID_RIF_FILTER_PLUGGED);
		}
	}
	else
	{
		if (Instability_Event == SC_RIF_PLUGGED_FILTER)
		{
			Instability_Event = SC_NO_INSTABILITY;
		}
	}

	// Stability Control Loop detection
	if (StabilityControlLoopMonitor__GetOutcome() == SCL_PRIMARY_REACTION_REQUESTED)
	{
		Instability_Event = SC_SCL_PRIMARY_REACTION_REQ;
	}
	else if (StabilityControlLoopMonitor__GetOutcome() == SCL_SECONDARY_REACTION_REQUESTED)
	{
		Instability_Event = SC_SCL_SECONDARY_REACTION_REQ;
	}
	else
	{
		if ((Instability_Event == SC_SCL_PRIMARY_REACTION_REQ) || (Instability_Event == SC_SCL_SECONDARY_REACTION_REQ))
		{
			Instability_Event = SC_NO_INSTABILITY;
		}
	}
}


/**
 * The function takes the currently selected reaction and check if it has to be modified according to the specific requirements
 *
 * @param current_reaction_ptr: pointer to the currently selected reaction
 * @param liters_in_tub: the amount of water currently in the tub (used when the reaction requests to add water)
 * @param phase_repetitions: the number of times that the Restart Phase reaction has already been triggered (used when the reaction requests to restart the phase)
 *
 * @return : none
 */
static void PartialReactionUpdate(STABILITY_CONTROL_REACTIONS_TYPE *current_reaction_ptr, sint32 liters_in_tub, sint32 phase_repetitions)
{
	BOOL_TYPE check_subcycle;
	uint8 subcycle_priority;
	uint8 subcycle_execution_counter;
	uint8 subcycle_max_calls;

	if ((*current_reaction_ptr == SC_REACTION_ADD_WATER_THEN_REDUCE_SPEED) && (liters_in_tub >= (sint32)Cliters_Max))
	{
		*current_reaction_ptr = SC_REACTION_REDUCE_MOTOR_SPEED;	// Req 1246164
	}

	if ((*current_reaction_ptr == SC_REACTION_REDUCE_MOTOR_SPEED) && (Speed_Reduction_Status == SC_2ND_SPEED_REDUCTION))
	{
		*current_reaction_ptr = Reaction_After_Max_Speed_Reduct; // Req. 1243484

		if ((*current_reaction_ptr == SC_REACTION_REDUCE_MOTOR_SPEED) || (*current_reaction_ptr == SC_REACTION_ADD_WATER_THEN_REDUCE_SPEED)	// No recursion allowed
			|| (*current_reaction_ptr >= SC_REACTIONS_NUM))	// Default value for backward compatibility with old setting file
		{
			*current_reaction_ptr = SC_REACTION_NONE;
		}
	}

	if (liters_in_tub >= (sint32)Cliters_Max)
	{
		switch (*current_reaction_ptr)
		{
			case SC_REACTION_ADD_WATER:
				*current_reaction_ptr = SC_REACTION_NONE; // Req 307052
				break;

			case SC_REACTION_ADD_WATER_THEN_RESTART_PHASE:
				*current_reaction_ptr = SC_REACTION_RESTART_PHASE; // Req 308251
				break;

			case SC_REACTION_ADD_WATER_THEN_SKIP_PHASE:
				*current_reaction_ptr = SC_REACTION_SKIP_PHASE; // Req 308256
				break;

			default:
				// Nothing to do
				break;
		}
	}

	if (*current_reaction_ptr == SC_REACTION_RESTART_PHASE_THEN_SKIP_PHASE)
	{
		if (phase_repetitions == 0)
		{
			*current_reaction_ptr = SC_REACTION_RESTART_PHASE; // Req 308257
		}
		else
		{
			*current_reaction_ptr = SC_REACTION_SKIP_PHASE; // Req 308258
		}
	}

	// Check the max number of subcycle executions
	check_subcycle = TRUE;

	switch (*current_reaction_ptr)
	{
		case SC_REACTION_ADD_WATER: case SC_REACTION_ADD_WATER_THEN_RESTART_PHASE: case SC_REACTION_ADD_WATER_THEN_SKIP_PHASE:
		case SC_REACTION_ADD_WATER_THEN_REDUCE_SPEED:
			subcycle_priority = Common_Parameters_Ptr->Add_Water_Subcycle_Priority;
			subcycle_execution_counter = SC_Subcycle_Execution_Counters[ADD_WATER_INDEX];
			subcycle_max_calls = SC_Max_Subcycle_Calls.Add_Water;
			break;

		case SC_REACTION_MOTOR_RESTART_SUBCYCLE:
			subcycle_priority = Common_Parameters_Ptr->Motor_Restart_Subcycle_Priority;
			subcycle_execution_counter = SC_Subcycle_Execution_Counters[MOTOR_RESTART_INDEX];
			subcycle_max_calls = SC_Max_Subcycle_Calls.Motor_Restart;
			break;

		case SC_REACTION_FILTER_PLUGGED_SUBCYCLE:
			subcycle_priority = Common_Parameters_Ptr->Filter_Plugged_Subcycle_Priority;
			subcycle_execution_counter = SC_Subcycle_Execution_Counters[FILTER_PLUGGED_INDEX];
			subcycle_max_calls = SC_Max_Subcycle_Calls.Filter_Plugged;
			break;

		case SC_REACTION_DEFOAMING_SUBCYCLE:
			subcycle_priority = Common_Parameters_Ptr->Defoaming_Subcycle_Priority;
			subcycle_execution_counter = SC_Subcycle_Execution_Counters[DEFOAMING_INDEX];
			subcycle_max_calls = SC_Max_Subcycle_Calls.Defoaming;
			break;

		case SC_REACTION_FILTER_PLUGGED_2_SUBCYCLE:
			subcycle_priority = Common_Parameters_Ptr->Filter_Plugged_2_Subcycle_Priority;
			subcycle_execution_counter = SC_Subcycle_Execution_Counters[FILTER_PLUGGED_2_INDEX];
			subcycle_max_calls = SC_Max_Subcycle_Calls.Filter_Plugged_2;
			break;

		default:
			check_subcycle = FALSE;
			// The following initializations are only to silent Lint warning, values are not used since (check_subcycle == FALSE)
			subcycle_priority = 0;
			subcycle_execution_counter = 0;
			subcycle_max_calls = 0;
			break;
	}

	if ((uint8)check_subcycle == (uint8)TRUE)
	{
		if ((subcycle_priority == (uint8)0) ||
			((subcycle_max_calls != (uint8)INVALID_MAX_SUBCYCLE_CALLS) && (subcycle_execution_counter >= subcycle_max_calls)))
		{
			// The requested subcycle is not present in setting file OR the number of subcycle executions has reached its limit
			*current_reaction_ptr = SC_REACTION_NONE;
		}
	}

}


