/**
 * @file
 * @brief       Module that owns the calibration data and applies calibration to input values at run-time.
 *
 * @details     Calibration must be done by external equipment. The external equipment will setup the calibration conditions and then read the LLI through API005 to
 *
 * @copyright   Copyright 2017 Whirlpool Corporation.  All rights reserved - CONFIDENTIAL.
 */

//  --- Include Files -------------------------------------------------------------------------------------------------

// -- This Module --
#include "SystemConfig.h"

#if (CALIBRATION_DATA_FEATURE == ENABLED)

#include "Calibration.h"
#include "Calibration_def.h"
#include "Calibration_prv.h"

// -- Other Modules --
#include "Log.h"
#include "NVData.h"
#include <string.h>


//  --- Private Declarations ------------------------------------------------------------------------------------------


// -- Private Constant Declarations --

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_CALIBRATION


// -- Private Enumerated Constant Declarations --

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_CALIBRATION_LOG_MESSAGE_ID_ENUM
{
    IMPROPER_BUFFER_SIZE = 1                        // Data: Hi=Calibration bytes allocated, Lo=Calibration bytes required.
} MODULE_CALIBRATION_LOG_MESSAGE_ID_TYPE;


// -- Private Structure Type Declarations --


//  --- Private Definitions -------------------------------------------------------------------------------------------


// -- Private Flash-Based Constant Definitions --

#pragma location = "_static_cfg_segment"
//! Array of memory used to hold the calibration data for all the Calibration Items.
static uint8 Calibration_Data[CALIBRATION_DATA_BUFFER_LENGTH];


// -- Private Variable Definitions --


//  --- Private Function Prototypes -----------------------------------------------------------------------------------


//=====================================================================================================================
//  --- Public Functions ----------------------------------------------------------------------------------------------
//=====================================================================================================================


//---------------------------------------------------------------------------------------------------------------------
/**
 * Check if the calibration data stored in non-volatile memory is properly sized.
 */
void Calibration__Initialize(void)
{
    // Check for valid configuration of the module.
    uint16 required = 0;
    for (uint8 i = 0; i < ELEMENTS_IN_ARRAY(CALIBRATION_CONFIG); i++)
    {
        required += CALIBRATION_CONFIG[i].Data_Size;
    }
    if (required != CALIBRATION_DATA_BUFFER_LENGTH)
    {
        LOG_ADD_EXCEPTION(IMPROPER_BUFFER_SIZE, COMBINE_BYTES(CALIBRATION_DATA_BUFFER_LENGTH, required));
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Get the calibrated value of the specified HBL_GENERIC_INPUT_ENUM_TYPE.
 * @param gi = The generic input (GI) associated with the Calibration Item.
 * @param input = The raw measured value before any calibration.
 * @return The calibration value of the specified HBL_GENERIC_INPUT_ENUM_TYPE.
 *         Returns the same value if Calibration Item is not configured.
 */
sint32 Calibration__ApplyByGI(HBL_GENERIC_INPUT_ENUM_TYPE gi, sint32 input)
{
    uint16 offset = 0;
    for (uint8 i = 0; i < ELEMENTS_IN_ARRAY(CALIBRATION_CONFIG); i++)
    {
        if (CALIBRATION_CONFIG[i].Gi == gi)
        {
            CALIBRATION_FUNCTION_TYPE calibration_function = CALIBRATION_CONFIG[i].Function;
            if ((calibration_function != NULL) &&
                (offset < CALIBRATION_DATA_BUFFER_LENGTH))
            {
                void* data = &Calibration_Data[offset];
                return calibration_function(input, data);
            }
        }
        else
        {
            offset += CALIBRATION_CONFIG[i].Data_Size;
        }
    }
    return input;
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Get the calibrated value of the specified CALIBRATION_ITEM_ID_TYPE.
 * @param id = The ID of the requested Calibration Item.
 * @param input = The raw measured value before any calibration.
 * @return The calibration value of the specified CALIBRATION_ITEM_ID_TYPE.
 *         Returns the same value if Calibration Item is not configured.
 */
sint32 Calibration__ApplyByItemID(CALIBRATION_ITEM_ID_TYPE id, sint32 input)
{
    uint16 offset = 0;
    for (uint8 i = 0; i < ELEMENTS_IN_ARRAY(CALIBRATION_CONFIG); i++)
    {
        if (CALIBRATION_CONFIG[i].Item == id)
        {
            CALIBRATION_FUNCTION_TYPE calibration_function = CALIBRATION_CONFIG[i].Function;
            if ((calibration_function != NULL) &&
                (offset < CALIBRATION_DATA_BUFFER_LENGTH))
            {
                void* data = &Calibration_Data[offset];
                return calibration_function(input, data);
            }
        }
        else
        {
            offset += CALIBRATION_CONFIG[i].Data_Size;
        }
    }
    return 0;
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Get the size of the calibration data used by the Calibration Item.
 * @param id = The Calibration Item.
 * @return The size of the calibration data used by the Calibration Item.
 */
uint8 Calibration__GetDataSize(CALIBRATION_ITEM_ID_TYPE id)
{
    for (uint8 i = 0; i < ELEMENTS_IN_ARRAY(CALIBRATION_CONFIG); i++)
    {
        if (CALIBRATION_CONFIG[i].Item == id)
        {
            return CALIBRATION_CONFIG[i].Data_Size;
        }
    }
    return 0;
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Get a pointer to the calibration data for the specified CALIBRATION_ITEM_ID_TYPE.
 * @param id = The requested CALIBRATION_ITEM_ID_TYPE.
 * @return A pointer to the calibration data for the specified CALIBRATION_ITEM_ID_TYPE.
 */
void* Calibration__GetDataPointer(CALIBRATION_ITEM_ID_TYPE id)
{
    uint16 offset = 0;
    for (uint8 i = 0; i < ELEMENTS_IN_ARRAY(CALIBRATION_CONFIG); i++)
    {
        if (CALIBRATION_CONFIG[i].Item == id)
        {
            return &Calibration_Data[offset];
        }
        else
        {
            offset += CALIBRATION_CONFIG[i].Data_Size;
        }
    }
    return NULL;
}


//=====================================================================================================================
//  --- Private Functions ---------------------------------------------------------------------------------------------
//=====================================================================================================================


#endif      // #if (CALIBRATION_DATA_FEATURE == ENABLED)
