/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "C_Extensions.h"
#include "DishAuxVar.h"
#include "DoorMonitor.h"
#include "Hbl.h"
#include "HotHighPotMonitor.h" 
#include "Interpreter.h"
#include "Log.h"
#include "Micro.h"
#include "NVData.h"
#include "SettingFile.h"
#include "SystemTimers.h"
//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

static SYSTEMTIMER_NV_TIMER_TYPE NV_Timer_Handle_Hot_High_Pot;
static uint8 Door_Sequence_ID;
static BOOL_TYPE HotHighPotDone;
static BOOL_TYPE HHP_Can_Start;


#pragma location = "_appliance_segment"
static uint8 HHP_Read_Setting_file_params;
#pragma location = "_appliance_segment"
static uint8 HHP_HotHighPot_Infinity;
#pragma location = "_appliance_segment"
static uint8 HHP_Remaining_Events;
#pragma location = "_appliance_segment"
static uint8 HHP_Time;

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_HOTHIGHPOT_MONITOR

#define OFF_CYCLE	0
#define OFF_PHASE	0
#define HHP_FAIL    1
#define HHP_PASS    0
//! A list of log message IDs that are generated by this module.
typedef enum MODULE_HOTHIGHPOT_MONITOR_LOG_MESSAGE_ID_ENUM
{
	ERROR_LOADING_PARAMETERS       = 1,
} MODULE_HOTHIGHPOT_MONITOR_LOG_MESSAGE_ID_TYPE;


//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the module HotHighPotMonitor and its variables
 *
 */
void HotHighPotMonitor__Initialize(void)
{
	SETTINGFILE_LOADER_TYPE loader;
	Door_Sequence_ID = Hbl__GetGISequenceIDByIndex((HBL_GENERIC_INPUT_ENUM_TYPE)Hbl__GetGIIndexByGIID(HBL_GI_DOOR));

	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		HotHighPotDone = FALSE;
		HHP_Can_Start = FALSE;

		if (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != (NVDATA_RESTORE_TYPE)NVDATA_RESTORE_OKAY)
		{
			HHP_Remaining_Events = 0;
			HHP_Time = 0;
			HHP_Read_Setting_file_params = 0;
			HHP_HotHighPot_Infinity = 0;
			Previous_HHP_Door_Check = HHP_PASS;
			HHP_Door_Check = HHP_PASS;
		}

		if ((HHP_Read_Setting_file_params == 0U)||(HHP_Read_Setting_file_params == 0xFFU))
		{
			// Get the HotHighPotMonitor parameters from the setting file.
			if (SettingFile__BasicLoader(SF_PTR_ACU_PRODUCT_CONFIGURATION_DATA,
										 DSPL_HOTHIGHPOT_PARAMS,
										&loader) == FAIL)
			{
				LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, 0);
			}
			else
			{
				// Read the setting file data into local variables for convenience.
				HHP_Remaining_Events = ((HOTHIGHPOT_MONITOR_INSTANCE_TYPE *)(void *)loader.Data)->Events;
				HHP_Time = ((HOTHIGHPOT_MONITOR_INSTANCE_TYPE *)(void *)loader.Data)->Time;

				HHP_Read_Setting_file_params = 1;

				if (HHP_Remaining_Events == 0U)
				{
					HHP_HotHighPot_Infinity = 1;
				}
			}
		}

		if ((HHP_Remaining_Events == 0U) &&
			(HHP_HotHighPot_Infinity == 0U))
		{
			// monitor not execute
	    	SystemTimers__NVResetTimer(&NV_Timer_Handle_Hot_High_Pot);
		}
		else // monitor can be start
		{
			(void)SystemTimers__NVSetTimerMS(&NV_Timer_Handle_Hot_High_Pot, (uint32)HHP_Time*1000U ,SYSTEMTIMERS_TYPE_DOWN_COUNTER);

			HHP_Can_Start = TRUE;

			if ((HHP_Remaining_Events != 0U) && (HHP_HotHighPot_Infinity == 0U))
			{
				HHP_Remaining_Events --;
			}
		}
	}
}

void HotHighPotMonitor__Execution(void)
{
	DOOR_STATUS_TYPE actual_door_status;
	CYCLE_PHASE_STATEMENT_TYPE cps;
	uint8 value_state;
	HBL_PILOT_ENUM_TYPE heater_pilot_type;

	if ((Door_Sequence_ID != Hbl__GetGISequenceIDByIndex((HBL_GENERIC_INPUT_ENUM_TYPE)Hbl__GetGIIndexByGIID(HBL_GI_DOOR))) &&
		((uint8)HHP_Can_Start == (uint8)TRUE))
	{
		Previous_HHP_Door_Check = HHP_Door_Check;
		if (DoorMonitor__GetDoorStatus() == DOOR_STATUS_CLOSE)
		{
			HHP_Door_Check = HHP_PASS;
		}
		else
		{
			HHP_Door_Check = HHP_FAIL;
		}

		HHP_Can_Start = FALSE;
	}

	if ((Door_Sequence_ID != Hbl__GetGISequenceIDByIndex((HBL_GENERIC_INPUT_ENUM_TYPE)Hbl__GetGIIndexByGIID(HBL_GI_DOOR))) &&
		(SystemTimers__NVCheckTimer(&NV_Timer_Handle_Hot_High_Pot) != SYSTEMTIMERS_STATE_STOPPED))
	{
		actual_door_status = DoorMonitor__GetDoorStatus();
		cps = Interpreter__GetCurrentStatement(COMPARTMENT_DEFAULT);

		if ((SystemTimers__NVCheckTimer(&NV_Timer_Handle_Hot_High_Pot) == SYSTEMTIMERS_STATE_RUNNING) &&
			(actual_door_status == DOOR_STATUS_CLOSE) &&
			((cps.Cycle == (uint8)OFF_CYCLE) && (cps.Phase == (uint8)OFF_PHASE)))
		{
			// Close(ON) Relay Enable and Master Relay
			value_state = (uint8)ON;
			(void)Hbl__SetLoadRequestByLoadID(HBL_LOAD_PILOT_RELAY, HBL_PRIORITY_HOT_HIGH_POT, (uint8 *) &value_state);
			(void)Hbl__SetLoadRequestByLoadID(HBL_LOAD_RELAY_ENABLE, HBL_PRIORITY_HOT_HIGH_POT, (uint8 *) &value_state);
			//////////////////////////////////////
			// Close(ON) Heater L1
			heater_pilot_type = Hbl__GetPilotIDByIndex(Hbl__GetLoadIndexByLoadID(HBL_LOAD_WASHING_HEATER));
			switch (heater_pilot_type)
			{
				case HBL_PILOT_DIGITAL_OUTPUT_MULTI_2_PIN:
				{
					value_state = (uint8)HDOM2_LOAD_STATE_PIN_1;
					(void)Hbl__SetLoadRequestByLoadID(HBL_LOAD_WASHING_HEATER, HBL_PRIORITY_HOT_HIGH_POT, (uint8 *) &value_state);
				}
				break;
				case HBL_PILOT_MULTISEQUENCE_2:
				{
					// TODO
				}
				break;
				default:
				    // nothing to do
                break;
			}

		}
		else
		{
			if ((actual_door_status == DOOR_STATUS_OPEN) && (HHP_Door_Check == (uint8)HHP_PASS))
			{
				HHP_Door_Check = HHP_FAIL;
			}

			if (SystemTimers__NVCheckTimer(&NV_Timer_Handle_Hot_High_Pot) == SYSTEMTIMERS_STATE_DONE)
			{
				SystemTimers__NVResetTimer(&NV_Timer_Handle_Hot_High_Pot);
				HotHighPotDone = TRUE;
			}
		}
	}
}

BOOL_TYPE HotHighPotMonitor__GetHotHighPotDone(void)
{
	return HotHighPotDone;
}
//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================


