/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
// -- This Module --
#include "Fill.h"
#include "ClassAFill.h"
#include "SystemConfig.h"

// -- Other Modules --
#include "DishAuxVar.h"
#include "Fault.h"
#include "Hbl.h"
#include "Interpreter.h"
#include "limits.h"
#include "Log.h"
#include "Micro.h"
#include "Modifier.h"
#include "NormalFill.h"
#include "NVData.h"
#include "Process.h"
#include "Regenerate.h"
#include "TankDrain.h"
#include "TankFill.h"
#include "Selector.h"
#include "SettingFile.h"
#include <string.h>
#include "Variable.h"

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

#pragma location = "_appliance_segment"
uint8 Class_A_Fill_Bitmap;
#pragma location = "_appliance_segment"
uint16  Liters_In_Water_Tank;
#pragma location = "_appliance_segment"
uint16 Liters_In_Tub_Before_Fill;
#pragma location = "_appliance_segment"
uint16 Liters_In_Tank_Before_Fill;
#pragma location = "_appliance_segment"
uint16 Liters_Unchecked;
#pragma location = "_appliance_segment"
TANK_STATE_TYPE Tank_State_Fill;
#pragma location = "_appliance_segment"
TANK_STATE_TYPE Tank_State_Drain;

uint16 Liters_For_Tank_Empty;
uint16 Liters_For_Tank_Full;


//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_FILL

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_FILL_LOG_MESSAGE_ID_ENUM
{
	PROCESS_CONTROL_IS_NULL = 1,
	PROCESS_CONTROL_PARAMS_EXCEED_LIMITS,
	ERROR_INCONSISTENT_AVERAGE_DATA
} MODULE_FILL_LOG_MESSAGE_ID_TYPE;

//!
typedef enum FILL_CYCLE_ENUM
{
    FILL_MAIN_CYCLE = 0,
    FILL_SUB_CYCLE,
    FILL_PAUSE_CYCLE,

	FILL_CYCLE_NUM
} FILL_CYCLE_TYPE;

//! Displacement value that indicates that the feature is not used.
#define UNUSED_FEATURE 0xFF

#define FLOW_RATE_SAMPLES_TO_SAVE		12U

#define FLOW_RATE_SAMPLES_TO_REJECT		2U

// DishAuxVar_AverageWithRejection(), used in Class A Fill and in Tank fill, support a maximum of AVEARAGE_WITH_REJ_MAX_SUPPORTED_SAMPLES_NUM,
// so the number of samples on which calculate Flow Rate Calibrated has to be less than or equal to that limit.
CT_ASSERT(FLOW_RATE_SAMPLES_TO_SAVE <= AVEARAGE_WITH_REJ_MAX_SUPPORTED_SAMPLES_NUM);

// Average with rejection can only be calculated if number of samples to reject is less than total number of samples
CT_ASSERT(FLOW_RATE_SAMPLES_TO_REJECT < FLOW_RATE_SAMPLES_TO_SAVE);


#pragma location = "_appliance_segment"
static uint8 Fill_Sequence_ID;
#pragma location = "_appliance_segment"
static uint8 Fill_Sequence_ID_Reference[FILL_CYCLE_NUM];

#pragma location = "_appliance_segment"
static uint16 Fill_Flow_Rate_Calibrated;
#pragma location = "_appliance_segment"
static uint16 Flow_Rate_Buffer[FLOW_RATE_SAMPLES_TO_SAVE];
#pragma location = "_appliance_segment"
static uint8 Flow_Rate_Samples;

static BOOL_TYPE Class_A_Fill_Project;


//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------

//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------

//---------------------------------------------------------------------------------------------------------------------
/**
 * Initialize the Fill module and its variables.
 */
void Fill__Initialize(void)
{
	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		SETTINGFILE_LOADER_TYPE loader;

		// Discriminate if setting file is using Normal Fill or Class A Fill
		if (SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS, DISPL_CLASS_A_FILL, &loader) == PASS)
		{
			Class_A_Fill_Project = TRUE;

			// Copy parameters into variables to be used in cycle design
			Liters_For_Tank_Empty = (((CLASS_A_FILL_PARAMETER_TYPE *)(void *)loader.Data)->Liters_For_Tank_Empty) * (uint16)5;
			Liters_For_Tank_Full = (((CLASS_A_FILL_PARAMETER_TYPE *)(void *)loader.Data)->Liters_For_Tank_Full) * (uint16)5;
		}
		else
		{
			Class_A_Fill_Project = FALSE;

			Liters_For_Tank_Empty = 0;
			Liters_For_Tank_Full = 0;
		}

		if (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != (NVDATA_RESTORE_TYPE)NVDATA_RESTORE_OKAY)
		{
			Fill_Sequence_ID = 0;
			memset(&Fill_Sequence_ID_Reference[0], 0, sizeof(Fill_Sequence_ID_Reference));

			Class_A_Fill_Bitmap = 0;
			Fill_Flow_Rate_Calibrated = 0; // It means calibration has never been completed

			memset(&Flow_Rate_Buffer[0], 0, sizeof(Flow_Rate_Buffer));

			if ((BOOL_TYPE)Class_A_Fill_Project != (BOOL_TYPE)FALSE)
			{
				Flow_Rate_Buffer[0] = ENDIANU16_STON(((CLASS_A_FILL_PARAMETER_TYPE *)(void *)loader.Data)->Flow_Rate_Nominal); //lint !e927 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
				Flow_Rate_Samples = 1;
			}
			else
			{
				Flow_Rate_Samples = 0;
			}

			Liters_In_Water_Tank = 0;
			Liters_In_Tub_Before_Fill = 0;
			Liters_In_Tank_Before_Fill = 0;
			Liters_Unchecked = 0;
			Tank_State_Fill = TANK_STATE_UNKNOWN;
			Tank_State_Drain = TANK_STATE_UNKNOWN;
		}
	}

	// Call specific processes initialization functions
	NormalFill__Initialize();
	ClassAFill__Initialize();
	TankFill__Initialize();
	TankDrain__Initialize();
}


PROCESS_RESULT_TYPE Fill__Process(PROCESS_CONTROL_TYPE* control)
{
    PROCESS_RESULT_TYPE result = PROCESS_COMPLETE;

    if (control == NULL)
    {
        LOG_ADD_EXCEPTION(PROCESS_CONTROL_IS_NULL, 0);
    }
    else if ((control->Compartment >= APPLIANCE_MAX_COMPARTMENTS) ||
    	/*	 (control->F1_F0_Flags >= (uint8)FILL_OPTION_COUNT) || */ //No need to check F1_F0_Flags since Fill Process support all F1_F0_Flags combinations
			 (control->Process_Instance > 0U))
    {
        LOG_ADD_EXCEPTION(PROCESS_CONTROL_PARAMS_EXCEED_LIMITS, 0);
    }
    else
    {
		FILL_CYCLE_TYPE fill_type;
    	CYCLE_STATE_TYPE cycle_state = Selector__GetCycleState(control->Setting_File_Index,
															   control->Compartment,
															   Interpreter__GetStatus().Main_Cycle[COMPARTMENT_DEFAULT]);

        if (cycle_state == CYCLE_STATE_RUN)
        {
            if (control->Sub_Cycle_Running != (BOOL_TYPE)FALSE)
            {
            	fill_type = FILL_SUB_CYCLE;
            }
            else
            {
            	fill_type = FILL_MAIN_CYCLE;
            }
        }
        else
        {
        	fill_type = FILL_PAUSE_CYCLE;
        }

        if (control->Step_Initializing != (BOOL_TYPE)FALSE)
    	{
    		// Increased each time a new Fill process is started
    		Fill_Sequence_ID ++;

    		Fill_Sequence_ID_Reference[fill_type] = Fill_Sequence_ID;
    	}

    	if (Fill_Sequence_ID_Reference[fill_type] == Fill_Sequence_ID)
    	{
			switch (control->F1_F0_Flags)
			{
				case FILL_OPTION_NORMAL_FILL:
					result = NormalFill__Manager(control);
					break;

				case FILL_OPTION_CLASS_A_FILL:
					result = ClassAFill__Manager(control);
					break;

				case FILL_OPTION_TANK_FILL:
					result = TankFill__Manager(control);
					break;

				case FILL_OPTION_TANK_DRAIN:
					result = TankDrain__Manager(control);
					break;
				default:
					// No other options
					break;
			}
    	}
    	else
    	{
    		// Another Fill Process instance has been started in a different cycle state, in this case the process
    		// execution is skipped because the process data may be no longer meaningful.
    	}
    }

    return result;
}

/**
 * It sets the required bit in Class_A_Fill_Bitmap variable
 *
 * @param  bit_index = the index of the bit to be set
 *
 * @return  None
 */
void Fill__SetBitmapBit(uint8 bit_index)
{
	if (bit_index < (sizeof(Class_A_Fill_Bitmap) * 8U))
	{
        BIT_SET8(Class_A_Fill_Bitmap, bit_index);
	}
}


/**
 * It clears the required bit in Class_A_Fill_Bitmap variable
 *
 * @param  bit_index = the index of the bit to be set
 *
 * @return  None
 */
void Fill__ClearBitmapBit(uint8 bit_index)
{
	if (bit_index < (sizeof(Class_A_Fill_Bitmap) * 8U))
	{
		BIT_CLR(Class_A_Fill_Bitmap, bit_index);
	}
}


/**
 * It returns whether the required bit of Class_A_Fill_Bitmap variable is set or not
 *
 * @param  bit_index = the index of the bit to be set
 *
 * @return  The bit status
 * @retval TRUE/FALSE if the bit is 1/0
 *
 */
BOOL_TYPE Fill__GetBitmapBit(uint8 bit_index)
{
	BOOL_TYPE ret_value = FALSE;

	if (bit_index < (sizeof(Class_A_Fill_Bitmap) * 8U))
	{
		ret_value = (BIT_TEST((uint32)Class_A_Fill_Bitmap, bit_index) != 0U) ? (TRUE) : (FALSE);
	}

	return ret_value;
}


/**
 * It returns whether the project is using Class A Fill or not
 *
 * @return  Class_A_Fill_Project
 * @retval  TRUE/FALSE
 *
 */
BOOL_TYPE Fill__ProjectUsesClassAFill(void)
{
	return Class_A_Fill_Project;
}


/**
 * It reset the H2O_Alarm variable
 *
 * @return  none
 *
 */
void Fill__ClearH2OAlarm(void)
{
	H2O_Alarm = FALSE;
}


/**
 * It implements the initializations required before starting Fill Water phase of Class A Fill and Tank Fill processes.
 *
 * @param  fill_data = pointer to the process volatile data
 * @param  fill_nv_data = pointer to the process non volatile data
 *
 * @return  none
 *
 */
void Fill__ClassAFillCoreInit(CLASS_A_FILL_VOLATILE_DATA_TYPE *fill_data, CLASS_A_FILL_NV_DATA_TYPE *fill_nv_data)
{
	uint16 liters_requested_by_setting;
	uint32 min;

	Liters_In_Tub_Before_Fill =	Liters_In_Tub;
	Liters_In_Tank_Before_Fill = Liters_In_Water_Tank;

	// Calculate Liters_Requested

	liters_requested_by_setting = fill_data->Class_A_Fill_Process_Parameters->Liters_Requested * (uint16)5;

	// Check if modifier is present
	if (fill_data->Class_A_Fill_Process_Parameters->Modifier_Table_Index != (uint8)UNUSED_FEATURE)
	{
		sint32 modified_value;

		modified_value = Modifier__GetValue(liters_requested_by_setting, fill_data->Class_A_Fill_Process_Parameters->Modifier_Table_Index);
		if (modified_value < 0)
		{
			modified_value = 0;
		}
		else if (modified_value > __UNSIGNED_SHORT_MAX__)
		{
			modified_value = __UNSIGNED_SHORT_MAX__;
		}
		else
		{
			// Do nothing, modified_value fits in uint16
		}

		liters_requested_by_setting = (uint16)modified_value;
	}

	if (fill_data->Class_A_Fill_Process_Parameters->Partial_Fill != (BOOL_TYPE)FALSE)
	{
		min = (uint32)liters_requested_by_setting + Liters_In_Tub_Before_Fill;
	}
	else
	{
		min = liters_requested_by_setting;
	}

	if ((fill_data->Class_A_Fill_Parameters->Liters_In_Tub_Max * (uint32)5) < min)
	{
		min = fill_data->Class_A_Fill_Parameters->Liters_In_Tub_Max * (uint32)5;
	}

	fill_nv_data->Liters_Requested = (uint16)min;


	Fill__ClearBitmapBit(DRAIN_CONFIRMED);
	fill_nv_data->Fill_Timer = 0;
	Liters_Current_Fill = 0;
	fill_data->Flow_Rate_Calibration_Enabled = TRUE;
	fill_data->No_Flow_Meter_Pulses_Timer = 0;
}


/**
 * It implements the Fill Water phase of Class A Fill and Tank Fill processes.
 *
 * @param  fill_data = pointer to the process volatile data
 * @param  fill_nv_data = pointer to the process non volatile data
 * @param  fill_option = used to distinguish between Class A Process and Tank Fill process
 *
 * @return  the action type required after this function's call
 * @retval  FILL_CORE_NO_STATE_CHANGE = continue the Fill Water phase;
			FILL_CORE_NO_WATER_DETECTED = activate H2O alarm and go to PAUSE state;
			FILL_CORE_WATER_CHECK_NEEDED = activate Fill Check Water Subcycle;
			FILL_CORE_WATER_FILL_OVER = Fill Water phase completed
 *
 *
 */
FILL_CORE_RET_TYPE Fill__ClassAFillCore(CLASS_A_FILL_VOLATILE_DATA_TYPE *fill_data, CLASS_A_FILL_NV_DATA_TYPE *fill_nv_data, FILL_OPTION_TYPE fill_option)
{
	FILL_CORE_RET_TYPE ret_value = FILL_CORE_NO_STATE_CHANGE;
	uint16 amount_of_water_to_be_filled;

	// Calculate Liters requested
	if (fill_nv_data->Liters_Requested > (fill_data->Class_A_Fill_Parameters->Liters_Offset * (uint16)2))
	{
		amount_of_water_to_be_filled = fill_nv_data->Liters_Requested - (fill_data->Class_A_Fill_Parameters->Liters_Offset * (uint16)2);
	}
	else
	{
		amount_of_water_to_be_filled = 0;
	}

	// Calculate Flow rate current in cl/min
	if (fill_nv_data->Fill_Timer > 0U)
	{
		uint32 flow_rate_current = (Liters_Current_Fill * (uint32)(FILL_CALLS_PER_SECOND  * 60)) / fill_nv_data->Fill_Timer;

		if (flow_rate_current > (uint16)__UNSIGNED_SHORT_MAX__)
		{
			flow_rate_current = __UNSIGNED_SHORT_MAX__;
		}
		fill_data->Flow_Rate_Current = (uint16)flow_rate_current;
	}
	else
	{
		fill_data->Flow_Rate_Current = __UNSIGNED_SHORT_MAX__;
	}

	// Check pulses from flow meter to disable Flow Rate Calibration
	if ((BOOL_TYPE)fill_data->Flow_Rate_Calibration_Enabled != (BOOL_TYPE)FALSE)
	{
		if ((BOOL_TYPE)DishAuxVar__AreFlowMeterPulsesPresent() != (BOOL_TYPE)FALSE)
		{
			// Flow Meter pulses detected, reset timer
			fill_data->No_Flow_Meter_Pulses_Timer = 0;
		}
		else
		{
			if (fill_data->No_Flow_Meter_Pulses_Timer >= (fill_data->Class_A_Fill_Parameters->Flow_Meter_Check_Time * (uint16)FILL_CALLS_PER_SECOND))
			{
				// No pulses for Flow_Meter_Check_Time, disable flow rate calibration
				fill_data->Flow_Rate_Calibration_Enabled = FALSE;
			}
			else
			{
				fill_data->No_Flow_Meter_Pulses_Timer ++;
			}
		}
	}
	else
	{
		// Flow Rate Calibration is already disabled, no need to check Flow Meter pulses
	}

	if (Liters_In_Tub < amount_of_water_to_be_filled)
	{
		if (fill_nv_data->Liters_Requested > Liters_In_Tub_Before_Fill)
		{
			uint16 liters_to_calculate_time = fill_nv_data->Liters_Requested - Liters_In_Tub_Before_Fill;
			uint16 flow_rate_calibrated;

			// Calculate Fill Time Max
			if (ENDIANU16_STON(fill_data->Class_A_Fill_Parameters->Fill_Flow_Rate_Min) > 0U)
			{
				// Calculate Fill Time Max in in process call rate units
				uint32 time = (liters_to_calculate_time * (uint32)(FILL_CALLS_PER_SECOND  * 60)) / ENDIANU16_STON(fill_data->Class_A_Fill_Parameters->Fill_Flow_Rate_Min);

				if (time > (uint16)__UNSIGNED_SHORT_MAX__)
				{
					time = __UNSIGNED_SHORT_MAX__;
				}
				fill_data->Fill_Time_Max = (uint16)time;
			}
			else
			{
				fill_data->Fill_Time_Max = __UNSIGNED_SHORT_MAX__;
			}

			// Check if Flow Rate calibration has ever been completed
			if (Fill_Flow_Rate_Calibrated > 0U)
			{
				flow_rate_calibrated = Fill_Flow_Rate_Calibrated;
			}
			else
			{
				// Flow rate calibration never done, use Flow_Rate_Nominal in place of Fill_Flow_Rate_Calibrated
				flow_rate_calibrated = ENDIANU16_STON(fill_data->Class_A_Fill_Parameters->Flow_Rate_Nominal);
			}

			// Calculate Fill Time Calibrated
			if (flow_rate_calibrated > 0U)
			{
				// Calculate Fill Time Calibrated in process call rate units
				uint32 time = (liters_to_calculate_time * (uint32)(FILL_CALLS_PER_SECOND  * 60)) / flow_rate_calibrated;

				// Convert Fill Time Calibrated in process call rate units
				if (time > (uint16)__UNSIGNED_SHORT_MAX__)
				{
					time = __UNSIGNED_SHORT_MAX__;
				}
				fill_data->Fill_Time_Calibrated = (uint16)time;
			}
			else
			{
				fill_data->Fill_Time_Calibrated = __UNSIGNED_SHORT_MAX__;
			}
		}
		else
		{
			fill_data->Fill_Time_Max = 0;
			fill_data->Fill_Time_Calibrated = 0;
		}

		// Check if Fill Valve has to be switched on
		if ((fill_nv_data->Fill_Timer < fill_data->Fill_Time_Max) &&
			((fill_nv_data->Fill_Timer < fill_data->Fill_Time_Calibrated) || (fill_data->Flow_Rate_Current >= ENDIANU16_STON(fill_data->Class_A_Fill_Parameters->Fill_Flow_Rate_Min))) )
		{
			// Switch on Fill Valve and increase timer for timeout

			ON_OFF_TYPE valve_state;

			fill_nv_data->Fill_Timer ++;

			valve_state = ON;
			(void)Hbl__SetLoadRequestByLoadID(HBL_LOAD_FILL_VALVE, HBL_PRIORITY_APPLICATION_HI, (uint8 *) &valve_state);	//lint !e928 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]

			if (fill_option == FILL_OPTION_TANK_FILL)
			{
				(void)Hbl__SetLoadRequestByLoadID(HBL_LOAD_LOWER_TANK_VALVE, HBL_PRIORITY_APPLICATION_HI, (uint8 *) &valve_state);	//lint !e928 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
				(void)Hbl__SetLoadRequestByLoadID(HBL_LOAD_UPPER_TANK_VALVE, HBL_PRIORITY_APPLICATION_HI, (uint8 *) &valve_state);	//lint !e928 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
			}
		}
		else
		{
			if (fill_option == FILL_OPTION_TANK_FILL)
			{
				sint32 sum;

				sum = (sint32)Liters_In_Water_Tank + (sint32)Liters_Current_Fill;
				if (sum > __UNSIGNED_SHORT_MAX__)
				{
					sum = __UNSIGNED_SHORT_MAX__;
				}
				Liters_In_Water_Tank = (uint16)sum;

				sum = (sint32)Liters_Unchecked + (sint32)fill_nv_data->Liters_Requested - (sint32)Liters_In_Tub_Before_Fill;
				if (sum < 0)
				{
					sum = 0;
				}
				else if (sum > __UNSIGNED_SHORT_MAX__)
				{
					sum = __UNSIGNED_SHORT_MAX__;
				}
				else
				{
					// Do nothing, sum fits in uint16
				}
				Liters_Unchecked = (uint16)sum;
				Tank_State_Fill = TANK_STATE_UNKNOWN;

				// No Water
				ret_value = FILL_CORE_NO_WATER_DETECTED;
			}
			else
			{
				if ((BOOL_TYPE)Regenerate__GetBitmapBit(BACKRINSE_REQUIRED) != (BOOL_TYPE)FALSE)
				{
					// No Water
					ret_value = FILL_CORE_NO_WATER_DETECTED;
				}
				else
				{
					if ((fill_nv_data->Liters_Requested < (fill_data->Class_A_Fill_Parameters->Liters_For_WI_Full_Min * (uint16)5)) ||
						((fill_data->Class_A_Fill_Parameters->Test_Flow_Meter_Fault != (BOOL_TYPE)FALSE) && ((BOOL_TYPE)Fault__IsInFaultState(FAULT_ID_FLOW_METER) != (BOOL_TYPE)FALSE)) ||
						((fill_data->Class_A_Fill_Parameters->Fill_Check_Water_Subcycle_Priority == 0U) || (Interpreter__GetStatus().Sub_Cycle[COMPARTMENT_DEFAULT] != 0U)))
					{
						// It also cover the case in which Fill Check subcycle is not present in setting file, or Fill process
						// is being executed inside a subcycle, so it is not possible to start Fill Check Subcycle.
						if (fill_nv_data->Liters_Requested > Liters_In_Tub_Before_Fill)
						{
							Liters_Current_Fill = fill_nv_data->Liters_Requested - Liters_In_Tub_Before_Fill;
						}
						else
						{
							Liters_Current_Fill = 0;
						}

						Liters_In_Tub = fill_nv_data->Liters_Requested;

						ret_value = FILL_CORE_WATER_FILL_OVER;
					}
					else
					{
						ret_value = FILL_CORE_WATER_CHECK_NEEDED;
					}
				}
			}
		}
	}
	else
	{
		// Water filled

		// Update Flow rate calibrated
		if ((BOOL_TYPE)fill_data->Flow_Rate_Calibration_Enabled != (BOOL_TYPE)FALSE)
		{
			if (fill_nv_data->Fill_Timer >= (fill_data->Class_A_Fill_Parameters->Seconds_To_Calibrate_Min * (uint16)FILL_CALLS_PER_SECOND))
			{
				if (fill_data->Flow_Rate_Current >= ENDIANU16_STON(fill_data->Class_A_Fill_Parameters->Fill_Flow_Rate_Min))
				{
					uint8 i;

					if (fill_data->Flow_Rate_Current < ENDIANU16_STON(fill_data->Class_A_Fill_Parameters->Flow_Rate_Calib_Min))
					{
						fill_data->Flow_Rate_Current = ENDIANU16_STON(fill_data->Class_A_Fill_Parameters->Flow_Rate_Calib_Min);
					}
					else
					{
						if (fill_data->Flow_Rate_Current >= ENDIANU16_STON(fill_data->Class_A_Fill_Parameters->Flow_Rate_Max))
						{
							fill_data->Flow_Rate_Current = ENDIANU16_STON(fill_data->Class_A_Fill_Parameters->Flow_Rate_Max);
						}
					}

					// Shift FIFO array of Flow Rate historical values
					for (i = (ELEMENTS_IN_ARRAY(Flow_Rate_Buffer) - 1U); i > 0U; i --)
					{
						Flow_Rate_Buffer[i] = Flow_Rate_Buffer[i-1U];
					}
					Flow_Rate_Buffer[0] = fill_data->Flow_Rate_Current;

					if (Flow_Rate_Samples < FLOW_RATE_SAMPLES_TO_SAVE)
					{
						// New Flow Rate sample acquired
						Flow_Rate_Samples ++;
					}

					// Calculate average with rejection on Flow_Rate_Buffer elements
					if (DishAuxVar_AverageWithRejection(Flow_Rate_Buffer,
														ELEMENTS_IN_ARRAY(Flow_Rate_Buffer),
														Flow_Rate_Samples,
														(FLOW_RATE_SAMPLES_TO_SAVE - FLOW_RATE_SAMPLES_TO_REJECT),
														&Fill_Flow_Rate_Calibrated) == FAIL)
					{
						LOG_ADD_EXCEPTION(ERROR_INCONSISTENT_AVERAGE_DATA, Flow_Rate_Samples);
					}
				}
			}
		}

		// Clear Fill Valve Failures
		Fault__ConditionRemoved(FAULT_ID_NO_WATER_FILL_VALVE_PROBLEM);
		Fault__ConditionRemoved(FAULT_ID_NO_WATER);

		ret_value = FILL_CORE_WATER_FILL_OVER;
	}

	return ret_value;
}


//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================
