/**
 *  @file		PluggingMonitor.c
 *
 *  @brief      Wrapper for the code generated Plugging_Model
 *
 *  @details    This code has the monitor initialize and execution interfaces, also an enabling/disabling function
 *  			as Start/Stop, a Reset function to clear the model information and a Pause/Resume.
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2018-2019. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "PluggingMonitor.h"

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//! SettingFile Data
static SF_PLUGGING_DATA_TYPE* Plugging__SFData_Ptr;
static SF_PLUGGING_DATA_TYPE Plugging__SFData;

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_PLUGGING_MONITOR

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_PLUGGING_MONITOR_LOG_MESSAGE_ID_ENUM
{
	ERROR_LOADING_PARAMETERS       = 1,
} MODULE_PLUGGING_MONITOR_LOG_MESSAGE_ID_TYPE;

//! Boolean variable to enable and disable Plugging execution.
static BOOL_TYPE Plugging_Enabled = FALSE;
static BOOL_TYPE Plugging_Paused = FALSE;
static BOOL_TYPE Plugging_Reset = FALSE;

//! Plugging Status - Plugged/No Plugged
static PLUGGING_STATUS_TYPE PluggingMonitor_Status;

//! Plugging Model - State Machine current state
static PLUGGING_MONITORSTATE_TYPE PluggingMonitor_AlgorithmState;

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------

//! Model Data
static RT_MODELPLUGGING_MODEL_TYPE PluggingMonitor_ModelData_;
static RT_MODELPLUGGING_MODEL_TYPE *const PluggingMonitor_ModelData = &PluggingMonitor_ModelData_;/* Real-time model */

//! Timer Handle
static uint16 PluggingMonitor_TimerHandle;

//! Recovery Data
#pragma location = "_appliance_segment"
static PLUGGING_MODEL_DATA_TYPE  Plugging_ModelRecoveryData;

//! Check that imported macros have the correct range
#ifdef PLUG_RISK_DELAY_TIMER_MSEC
#if PLUG_RISK_DELAY_TIMER_MSEC > 4294967295U  //uint32 limit
#error The variable for the parameter "PLUG_RISK_DELAY_TIMER_MSEC" is too big
#endif
#endif

#ifdef PLUG_RISK_NOISE_VALUE
#if PLUG_RISK_NOISE_VALUE > 65535  //uint16 limit
#error The variable for the parameter "PLUG_RISK_NOISE_VALUE" is too big
#endif
#endif


//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
//static BOOL_TYPE GetPluggingParameters(SETTINGFILE_OFFSET_TYPE pointer_id, uint16 displacement);


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

SYSTEMTIMERS_STATE_TYPE PluggingMonitor__GetTimerState(void)
{
	return SystemTimers__GetState(PluggingMonitor_TimerHandle);
}

PLUGGING_MODEL_DATA_TYPE PluggingMonitor__GetModelData(void)
{
	return Plugging_ModelRecoveryData;
}

BOOL_TYPE Plugging__GetResetStatus(void)
{
	BOOL_TYPE retval;
	if (Plugging_Reset)
	{
		Plugging_Reset = FALSE;
		retval = TRUE;
	}
	else
	{
		retval = FALSE;
	}

	return retval;
}

void PluggingMonitor__SetRiskDelayTimer(uint32 PluggingTimeout)
{
	(void)SystemTimers__SetMs(PluggingMonitor_TimerHandle, PluggingTimeout);
}

void PluggingMonitor__SetStatus(PLUGGING_STATUS_TYPE PluggingStatus)
{
	PluggingMonitor_Status = PluggingStatus;
}

void PluggingMonitor__SetModelData(PLUGGING_MODEL_DATA_TYPE PluggingData)
{
	Plugging_ModelRecoveryData = PluggingData;
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief		Function to return the Plugging_Status
 *
 */
PLUGGING_STATUS_TYPE PluggingMonitor__GetStatus(void)
{
	return PluggingMonitor_Status;
}

//----------------------------------------------------------------------------
/**
 *  @brief      PluggingMonitor__Initialize
 *  @details    Function used to initialize the Plugging monitor.
 *
 */
void PluggingMonitor__Initialize(void)
{
	Plugging_Model_initialize(PluggingMonitor_ModelData, &PluggingMonitor_AlgorithmState);

	Plugging_ModelRecoveryData.PluggingRisk = 0;
	Plugging_ModelRecoveryData.RiskCounter = 0;
	Plugging_ModelRecoveryData.VwiRiskLastValue = 0;

	//create a new  timer handler
	(void)SystemTimers__ReleaseHandle(PluggingMonitor_TimerHandle);
	PluggingMonitor_TimerHandle = SystemTimers__GetHandle(SYSTEMTIMERS_TYPE_DOWN_COUNTER);

    // Initialize SF data pointer
	Plugging__SFData_Ptr = NULL;

	SETTINGFILE_LOADER_TYPE plugloader;
	if (SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS, DISPL_PLUGGING, &plugloader) == PASS)
	{
		Plugging__SFData.Plugging_VwiVarianceThreshold = ENDIANU16_STON(((SF_PLUGGING_DATA_TYPE*)(void*)(plugloader.Data))->Plugging_VwiVarianceThreshold);
		Plugging__SFData.Plugging_VwiSignalRecoverThreshold = ENDIANU16_STON(((SF_PLUGGING_DATA_TYPE*)(void*)(plugloader.Data))->Plugging_VwiSignalRecoverThreshold);
		Plugging__SFData.Plugging_VwiSignalLowThreshold = ENDIANU16_STON(((SF_PLUGGING_DATA_TYPE*)(void*)(plugloader.Data))->Plugging_VwiSignalLowThreshold);
		Plugging__SFData.Plugging_VwiSignalRiskThreshold = ENDIANU16_STON(((SF_PLUGGING_DATA_TYPE*)(void*)(plugloader.Data))->Plugging_VwiSignalRiskThreshold);
		Plugging__SFData.Plugging_RiskMaxCount = ((SF_PLUGGING_DATA_TYPE*)(void*)(plugloader.Data))->Plugging_RiskMaxCount;

		Plugging__SFData.Plugging_DiverterMovingTimeoutSec = ((SF_PLUGGING_DATA_TYPE*)(void*)(plugloader.Data))->Plugging_DiverterMovingTimeoutSec;

		if(plugloader.Length < sizeof(SF_PLUGGING_DATA_TYPE))
		{
			// Old Setting File, assign default values to this variable
			Plugging__SFData.Plugging_DiverterMovingTimeoutSec = 3;
		}

		Plugging__SFData_Ptr = &Plugging__SFData;
	}
	else
	{
		LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, SF_PTR_ACU_PRODUCT_CONFIGURATION_DATA);
	}
}

//----------------------------------------------------------------------------
/**
 *  @brief      PluggingMonitor__Execution
 *  @details    Function used to perform the Plugging monitor.
 *
 */
void PluggingMonitor__Execution(void)
{
	// Monitor will run only if SF is present
	if (Plugging__SFData_Ptr != NULL)
	{
		// Monitor will run only when not paused
		if (!Plugging_Paused)
		{
			PluggingModel__Execute(PluggingMonitor_ModelData, Plugging__SFData_Ptr,
					Plugging_Enabled, &PluggingMonitor_AlgorithmState);
		}
	}
}



//----------------------------------------------------------------------------
/**
 *  @brief      PluggingMonitor__Start
 *  @details    Function used to enable the Plugging monitor.
 *
 */
void PluggingMonitor__Start(void)
{
	Plugging_Enabled = TRUE;
}

//----------------------------------------------------------------------------
/**
 *  @brief      PluggingMonitor__Stop
 *  @details    Function used to disable the Plugging monitor.
 *
 */
void PluggingMonitor__Stop(void)
{
	Plugging_Enabled = FALSE;
}

//----------------------------------------------------------------------------
/**
 *  @brief      PluggingMonitor__Start
 *  @details    Function used to enable the Plugging monitor.
 *
 */
void PluggingMonitor__Pause(void)
{
	Plugging_Paused = TRUE;
}

//----------------------------------------------------------------------------
/**
 *  @brief      PluggingMonitor__Stop
 *  @details    Function used to disable the Plugging monitor.
 *
 */
void PluggingMonitor__Resume(void)
{
	Plugging_Paused = FALSE;
}

//----------------------------------------------------------------------------
/**
 *  @brief      PluggingMonitor__Reset
 *  @details    Function used to reset the Plugging monitor.
 *
 */
void PluggingMonitor__Reset(void)
{
	PluggingMonitor__Initialize();
	PluggingMonitor_Status = PL_UNDEFINED;
	Plugging_Enabled = TRUE;
	Plugging_Paused = FALSE;
	Plugging_Reset = TRUE;
}

