/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */

/*
@startuml
	title Tridge Detergent State Machine
	'terminate function unused

    [*] --> INITIALIZE

    INITIALIZE: do / CheckTagStatusRead
    INITIALIZE --> PUMP_ON: TagStatusRead / SaveTagSerialNumber \n\t\t     StartDispensingTimer
	INITIALIZE --> TRIDGE_DISPENSE_COMPLETE: NoCartridgeData

	PUMP_ON: do /  CheckCartridge \n\tDispenseDetergent
	PUMP_ON --> PUMP_ON: CartridgeChanged  / UpdateDispensingTimer
	PUMP_ON --> TRIDGE_DISPENSE_COMPLETE: TimerExpired
	PUMP_ON --> TRIDGE_DISPENSE_COMPLETE: NoCartridgeData

	TRIDGE_DISPENSE_COMPLETE:

@enduml
*/

//-------------------------------------- Include Files ----------------------------------------------------------------
// -- This Module --
#include "RinseAidDispense.h"
#include "TridgeDetergent.h"
#include "TridgeDetergent_fsm.h"
#include "C_Extensions.h"

#include "CartridgeDetectionMonitor.h"
#include "Hbl.h"
#include "Log.h"
#include "Micro.h"
#include "Modifier.h"
#include "NVData.h"
#include "SettingFile.h"
#include <string.h>
#include "SystemConfig.h"


//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_TRIDGE_DETERGENT

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_TRIDGE_DETERGENT_LOG_MESSAGE_ID_ENUM
{
    ERROR_LOADING_PARAMETERS			= 1,
} MODULE_TRIDGE_DETERGENT_LOG_MESSAGE_ID_TYPE;

//! Process setting file parameters structure for Tridge Detergent process
typedef PACKED struct TRIDGE_DETERGENT_PROCESS_PARAMETER_STRUCT
{
	DETERGENT_TYPE_TYPE Detergent_Type;
    uint8 Dose_To_Dispense;
    uint8 Modifier_Table_Index;

    uint8 Empty_Dispenser	:1;
    uint8 Unused_B3_b1_7	:7;
} TRIDGE_DETERGENT_PROCESS_PARAMETER_TYPE;

//! Tag_Read_Status values
typedef enum TAG_READ_STATUS_ENUM
{
    TAG_READ_STATUS_WAITING			= 0,
	TAG_READ_STATUS_GOOD,
	TAG_READ_STATUS_KO
} TAG_READ_STATUS_TYPE;

//! Timeout to wait the first tag ststus read (sec x 10)
#define FST_TAG_STATUS_TIMEOUT			100U

//! Volatile data structure for Tridge Detergent processes
typedef PACKED struct TRIDGE_DETERGENT_VOLATILE_DATA_STRUCT
{
	TRIDGE_DETERGENT_PROCESS_PARAMETER_TYPE *Tridge_Detergent_Process_Parameters;
	TRIDGE_DETERGENT_PARAMETER_TYPE *Tridge_Detergent_Parameters;
	uint32 Tag_Serial_Number;
	uint8 Fst_Tag_Status_Timer;
	TAG_READ_STATUS_TYPE Tag_Read_Status;
	TAG_DATA_TYPE Tag_Detergent_Data;
} TRIDGE_DETERGENT_VOLATILE_DATA_TYPE;

//! Volatile data structure for Tridge Detergent processes
typedef struct TRIDGE_DETERGENT_NV_DATA_STRUCT
{
	uint32 Tag_Saved_Serial_Number;
	uint16 Dispensing_Timer;
	TRIDGE_DETERGENT_FSM_STATE_TYPE Process_State; // State machine state for Tridge Detergent process
} TRIDGE_DETERGENT_NV_DATA_TYPE;

//! Array of ordered pumps load id
static const HBL_LOAD_ENUM_TYPE Pumps_Id_Array[DETERGENT_TYPES_NUM] = {HBL_BULK_DISPENSER_1, HBL_BULK_DISPENSER_2, HBL_BULK_DISPENSER_3};

//! Volatile data for Tridge Detergent process
static TRIDGE_DETERGENT_VOLATILE_DATA_TYPE Tridge_Detergent_Data[TRIDGE_DETERGENT_MAX_INSTANCES];
//! Pointer to volatile data for the current instance of Tridge Detergent process
static TRIDGE_DETERGENT_VOLATILE_DATA_TYPE *TD_Process_Data_Ptr;

//! Non volatile data for Tridge Detergent process
#pragma location = "_appliance_segment"
static TRIDGE_DETERGENT_NV_DATA_TYPE Tridge_Detergent_NV_Data[TRIDGE_DETERGENT_MAX_INSTANCES];
//! Pointer to non volatile data for the current instance of Tridge Detergent process
static TRIDGE_DETERGENT_NV_DATA_TYPE *TD_Process_NV_Data_Ptr;

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
static void ReadProcessParameters(PROCESS_CONTROL_TYPE* control);
static uint8 GetReleaseTime(void);
static uint16 GetDispensingTime(uint16 ml_to_dispense_x10);
static uint16 GetAmountToEmptyDispenser(void);


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================
void TridgeDetergent__Initialize(void)
{
	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		if (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != (NVDATA_RESTORE_TYPE)NVDATA_RESTORE_OKAY)
		{
			memset(&Tridge_Detergent_NV_Data[0], 0, sizeof(Tridge_Detergent_NV_Data));

			for (uint8 i = 0; i < ELEMENTS_IN_ARRAY(Tridge_Detergent_NV_Data); i ++)
			{
				Tridge_Detergent_NV_Data[i].Process_State = FSM_STATE_NONE;
			}
		}

		memset(&Tridge_Detergent_Data[0], 0, sizeof(Tridge_Detergent_Data));
	}
}

PROCESS_RESULT_TYPE TridgeDetergent__Manager(PROCESS_CONTROL_TYPE* control)
{
    PROCESS_RESULT_TYPE result = PROCESS_COMPLETE;

    TD_Process_Data_Ptr = &Tridge_Detergent_Data[control->Process_Instance];
    TD_Process_NV_Data_Ptr = &Tridge_Detergent_NV_Data[control->Process_Instance];

    if ((control->Step_Initializing != (BOOL_TYPE)FALSE) ||
		(control->Resume_From_Reset != (BOOL_TYPE)FALSE) ||
		(control->Resume_From_Pause != (BOOL_TYPE)FALSE))
	{
		ReadProcessParameters(control);

		// Setup state machine and timeout to wait for first Tag data read
		TD_Process_Data_Ptr->Fst_Tag_Status_Timer = FST_TAG_STATUS_TIMEOUT;
		TD_Process_Data_Ptr->Tag_Read_Status = TAG_READ_STATUS_WAITING;
	}

	if ((TD_Process_Data_Ptr->Tridge_Detergent_Process_Parameters != NULL) && (TD_Process_Data_Ptr->Tridge_Detergent_Parameters != NULL))
	{
		if (TD_Process_Data_Ptr->Tag_Read_Status == TAG_READ_STATUS_WAITING)
		{
			if (TD_Process_Data_Ptr->Fst_Tag_Status_Timer > 0U)
			{
				TD_Process_Data_Ptr->Fst_Tag_Status_Timer --;

				if (CartridgeDetectionMonitor__GetFstTagStatusReadDone() != FALSE)
				{
					// Tag data received
					TD_Process_Data_Ptr->Tag_Serial_Number = CartridgeDetectionMonitor__GetTagSerialNumber();
					if (CartridgeDetectionMonitor__GetTagData(TD_Process_Data_Ptr->Tridge_Detergent_Process_Parameters->Detergent_Type, &TD_Process_Data_Ptr->Tag_Detergent_Data) != FALSE)
					{
						uint16 local_ml_remaining;
						if (CartridgeDetectionMonitor__GetLocalMLRemaining(TD_Process_Data_Ptr->Tridge_Detergent_Process_Parameters->Detergent_Type, &local_ml_remaining) != FALSE)
						{
							if (local_ml_remaining != 0xFFFFU)
							{
								// Local value of Ml remaining is valid: replace Tag value with local value, since Tag value could not have been updated yet
								TD_Process_Data_Ptr->Tag_Detergent_Data.ML_Remaining = local_ml_remaining;
							}

							TD_Process_Data_Ptr->Tag_Read_Status = TAG_READ_STATUS_GOOD;
						}
						else
						{
							// No data found for selected detergent
						}
					}
					else
					{
						// No data found for selected detergent
					}
				}
			}
			else
			{
				// Timeout expired without receiving valid Tag data
				TD_Process_Data_Ptr->Tag_Read_Status = TAG_READ_STATUS_KO;
			}
		}

		if (control->Step_Initializing != (BOOL_TYPE)FALSE)
		{
			// Initialize this instance of the Tridge Detergent process.
			TridgeDetergentFsmInitialize(&TD_Process_NV_Data_Ptr->Process_State);
		}

		if (control->Resume_From_Reset == (BOOL_TYPE)FALSE)
		{
			// TridgeDetergentFsmExecute() not called in first iteration after a cold reset to avoid a spurious pump turning on in case of
			// long power fail: actually, in this case, Tridge Detergent process would be called for just one iteration before going in PAUSE.
			TridgeDetergentFsmExecute(&TD_Process_NV_Data_Ptr->Process_State);
		}

		result = ((TD_Process_NV_Data_Ptr->Process_State == FSM_STATE_TRIDGE_DISPENSE_COMPLETE) ? PROCESS_COMPLETE : PROCESS_BUSY);
	}
	else
	{
		// No valid setting file parameters, terminate process
	}

	return result;
}


//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

static void ReadProcessParameters(PROCESS_CONTROL_TYPE* control)
{
	SETTINGFILE_LOADER_TYPE loader;

	TD_Process_Data_Ptr->Tridge_Detergent_Process_Parameters = NULL;
	TD_Process_Data_Ptr->Tridge_Detergent_Parameters = NULL;

	// Get the Tridge Detergent process parameters from the setting file.
	if (SettingFile__MSettingBasicLoader(control->Setting_File_Index,
										 SF_PTR_ACU_PROCESS_RINSE_AID_DISPENSE,
										 control->Data_Field_Index,
										 &loader) == FAIL)
	{
		LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, control->Data_Field_Index);
	}
	else
	{
		TD_Process_Data_Ptr->Tridge_Detergent_Process_Parameters = (TRIDGE_DETERGENT_PROCESS_PARAMETER_TYPE *)(void *)loader.Data;

		if ( FAIL == SettingFile__BasicLoader(SF_PTR_ACU_PRODUCT_CONFIGURATION_DATA,
											  DSPL_TRIDGE_SYSTEM_PARAMS,
											  &loader) )
		{
			LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, (uint16)SF_PTR_ACU_PRODUCT_CONFIGURATION_DATA);
		}
		else
		{
			TD_Process_Data_Ptr->Tridge_Detergent_Parameters = (TRIDGE_DETERGENT_PARAMETER_TYPE *)(void *)loader.Data;
		}
	}
}

static uint8 GetReleaseTime(void)
{
	uint8 release_time = 0;

	switch (TD_Process_Data_Ptr->Tridge_Detergent_Process_Parameters->Detergent_Type)
	{
		case DETERGENT_TYPE_ENZIME:
			release_time = TD_Process_Data_Ptr->Tridge_Detergent_Parameters->Release_Time_Enzime;
			break;

		case DETERGENT_TYPE_BLEACH:
			release_time = TD_Process_Data_Ptr->Tridge_Detergent_Parameters->Release_Time_Bleach;
			break;

		case DETERGENT_TYPE_RINSE_AID:
			release_time = TD_Process_Data_Ptr->Tridge_Detergent_Parameters->Release_Time_RinseAid;
			break;

		default:
			// Keep release_time = 0;
			break;
	}

	return release_time;
}

static uint16 GetDispensingTime(uint16 ml_to_dispense_x10)
{
	// // Dispensing time in sec x 10 (rounded)
	uint32 dispensing_time = (((uint32)ml_to_dispense_x10 * GetReleaseTime()) + 5U) / 10U;

	if (dispensing_time > (uint32)__UNSIGNED_SHORT_MAX__)
	{
		dispensing_time = __UNSIGNED_SHORT_MAX__;
	}

	return (uint16)dispensing_time;
}

// Check if dispenser has to be emptied due to remaining detergent under last cycle threshold and return the amount of detergent to empty the dispenser.
static uint16 GetAmountToEmptyDispenser(void)
{
	uint8 last_cycle_threshold = 0;
	uint16 last_cycle_theshold_ml_x10;
	uint16 remaining_ml_x10;
	uint16 ml_to_dispense_x10 = 0;

	// Check if dispenser has to be emptied due to remaining detergent under last cycle threshold.
	switch (TD_Process_Data_Ptr->Tridge_Detergent_Process_Parameters->Detergent_Type)
	{
		case DETERGENT_TYPE_ENZIME:
			last_cycle_threshold = TD_Process_Data_Ptr->Tridge_Detergent_Parameters->Last_Cycle_Threshold_Enzime;
			break;

		case DETERGENT_TYPE_BLEACH:
			last_cycle_threshold = TD_Process_Data_Ptr->Tridge_Detergent_Parameters->Last_Cycle_Threshold_Bleach;
			break;

		case DETERGENT_TYPE_RINSE_AID:
			last_cycle_threshold = TD_Process_Data_Ptr->Tridge_Detergent_Parameters->Last_Cycle_Threshold_RinseAid;
			break;

		default:
			// Keep last_cycle_threshold = 0;
			break;
	}

	// Last Cycle Threshold in ml x 10 (since Last_Cycle_Threshold_X parameter is x 10)
	last_cycle_theshold_ml_x10 = (uint16)last_cycle_threshold * TD_Process_Data_Ptr->Tag_Detergent_Data.DoseAmount_ML;

	if (((uint32)TD_Process_Data_Ptr->Tag_Detergent_Data.ML_Remaining * 10U) < (uint32)__UNSIGNED_SHORT_MAX__)
	{
		remaining_ml_x10 = (uint16)(TD_Process_Data_Ptr->Tag_Detergent_Data.ML_Remaining * 10U);
	}
	else
	{
		remaining_ml_x10 = __UNSIGNED_SHORT_MAX__;
	}

	if (remaining_ml_x10 < last_cycle_theshold_ml_x10)
	{
		// Empty dispenser, dispense all the remaining detergent.
		ml_to_dispense_x10 = remaining_ml_x10;

		// Todo Add extra amount to be sure dispenser is emptied?
	}
	else
	{
		// Do nothing
	}

	return ml_to_dispense_x10;
}

//=====================================================================================================================
// Tridge Detergent State Machine customization functions.
// NOTE: do not modify this header or the StateMachineCodeGenerator will not be able to find it.
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void UpdateDispensingTimer(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	// Dispensing time in sec x 10 (rounded)
	TD_Process_NV_Data_Ptr->Dispensing_Timer = GetDispensingTime(GetAmountToEmptyDispenser());
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void CheckTagStatusRead(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	switch (TD_Process_Data_Ptr->Tag_Read_Status)
	{
		case TAG_READ_STATUS_WAITING:
			// Nothing to do (waiting for first tag status data)
			break;

		case TAG_READ_STATUS_GOOD:
			DISPATCH_FSM_EVENT(FSM_EVENT_TAG_STATUS_READ);
			break;

		case TAG_READ_STATUS_KO:
		default:
			DISPATCH_FSM_EVENT(FSM_EVENT_NO_CARTRIDGE_DATA);
			break;
	}
}

//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void SaveTagSerialNumber(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	TD_Process_NV_Data_Ptr->Tag_Saved_Serial_Number = TD_Process_Data_Ptr->Tag_Serial_Number;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void CheckCartridge(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	switch (TD_Process_Data_Ptr->Tag_Read_Status)
	{
		case TAG_READ_STATUS_WAITING:
			// Nothing to do (coming from Reset or Pause, waiting for first tag status data)
			break;
		case TAG_READ_STATUS_GOOD:
			if (CartridgeDetectionMonitor__GetFstTagStatusReadDone() == FALSE)
			{
				// Cartridge switch opened during process execution: terminate process.
				DISPATCH_FSM_EVENT(FSM_EVENT_NO_CARTRIDGE_DATA);
			}
			else
			{
				if (TD_Process_NV_Data_Ptr->Tag_Saved_Serial_Number != TD_Process_Data_Ptr->Tag_Serial_Number)
				{
					TD_Process_NV_Data_Ptr->Tag_Saved_Serial_Number = TD_Process_Data_Ptr->Tag_Serial_Number;

					if ((uint8)TD_Process_Data_Ptr->Tridge_Detergent_Process_Parameters->Empty_Dispenser != 0U)
					{
						// If cartridge has been changed, we need to check again the emptying conditions
						DISPATCH_FSM_EVENT(FSM_EVENT_CARTRIDGE_CHANGED);
					}
				}
				else
				{
					// Normal operation
				}
			}
			break;

		case TAG_READ_STATUS_KO:
		default:
			DISPATCH_FSM_EVENT(FSM_EVENT_NO_CARTRIDGE_DATA);
			break;
	}
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void StartDispensingTimer(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	uint16 ml_to_dispense_x10;
	if ((uint8)TD_Process_Data_Ptr->Tridge_Detergent_Process_Parameters->Empty_Dispenser == 0U)
	{
		// Normal detergent dispensing
		uint8 dose_to_dispense = TD_Process_Data_Ptr->Tridge_Detergent_Process_Parameters->Dose_To_Dispense;

		if (TD_Process_Data_Ptr->Tridge_Detergent_Process_Parameters->Modifier_Table_Index != (uint8)SF_DISPL_INVALID_VALUE)
		{
			sint32 modified_value;

			modified_value = Modifier__GetValue(TD_Process_Data_Ptr->Tridge_Detergent_Process_Parameters->Dose_To_Dispense,
												TD_Process_Data_Ptr->Tridge_Detergent_Process_Parameters->Modifier_Table_Index);
			if (modified_value < 0)
			{
				modified_value = 0;
			}
			else if (modified_value > __UNSIGNED_CHAR_MAX__)
			{
				modified_value = __UNSIGNED_CHAR_MAX__;
			}
			else
			{
				// Do nothing, modified_value fits in uint8
			}

			dose_to_dispense = (uint8)modified_value;
		}

		// Amount of detergent to dispense in ml x 10 (since Dose_To_Dispense is x 10)
		ml_to_dispense_x10 = (uint16)dose_to_dispense * TD_Process_Data_Ptr->Tag_Detergent_Data.DoseAmount_ML;
	}
	else
	{
		// Check if dispenser has to be emptied due to remaining detergent under last cycle threshold.
		ml_to_dispense_x10 = GetAmountToEmptyDispenser();
	}

	// Dispensing time in sec x 10 (rounded)
	TD_Process_NV_Data_Ptr->Dispensing_Timer = GetDispensingTime(ml_to_dispense_x10);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void DispenseDetergent(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	if (TD_Process_Data_Ptr->Tag_Read_Status == TAG_READ_STATUS_GOOD)
	{
		if (TD_Process_NV_Data_Ptr->Dispensing_Timer > 0U)
		{
			if (TD_Process_Data_Ptr->Tag_Detergent_Data.PumpNumber < ELEMENTS_IN_ARRAY(Pumps_Id_Array))
			{
				uint8 pump_index = Hbl__GetLoadIndexByLoadID(Pumps_Id_Array[TD_Process_Data_Ptr->Tag_Detergent_Data.PumpNumber]);

				if (pump_index != HBL_INDEX_INVALID)
				{
					uint8 pump_state = (uint8)ON;
					(void)Hbl__SetLoadRequestByIndex(pump_index, HBL_PRIORITY_APPLICATION_HI, &pump_state);
				}
			}

			TD_Process_NV_Data_Ptr->Dispensing_Timer --;
		}
		else
		{
			DISPATCH_FSM_EVENT(FSM_EVENT_TIMER_EXPIRED);
		}
	}
	else
	{
		// Nothing to do
	}
}
