/**
 *  @file
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *                    List here all the applicable documents if needed. <tr>
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------

//-------------------------------------- Include Files ----------------------------------------------------------------
// -- This Module --
#include "C_Extensions.h"
#include "SystemConfig.h"

#include "DishAuxVar.h"
#include "Micro.h"
#include "NVData.h"
#include "OWICalibrationProcess.h"
#include "OWIMonitor.h"
#include "Supervisor.h"
#include "Interpreter.h"
#include "Fault.h"

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
#define MODULE_NAME    MODULE_OWI_MONITOR

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_OWIMONITOR_LOG_MESSAGE_ID_ENUM
{
    ERROR_PROCESS_CONTROL       = 1,
    ERROR_LOADING_PARAMETERS
} MODULE_OWI_MONITOR_LOG_MESSAGE_ID_TYPE;

//! The RAM data structure required for each instance of the OWIMonitor process.
//! Pointer to the "Variable" data in the setting file.
static SF_DATA_TYPE* Sf_OWIMonitor_Config;

#pragma location = "_appliance_segment"
static uint16 CycleCounterSinceLastCalibration;

#pragma location = "_appliance_segment"
static uint8 CalibrationCounterSinceLastSuccess;


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================


//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================


//---------------------------------------------------------------------------------------------------------------------

static CYCLE_NAME_TYPE Prev_Cycle_Name;
static BOOL_TYPE OWI_Prev_Calibration_Ongoing;
//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the module HeatMonitor and its variables
 *
 */
void OWIMonitor__Initialize(void)
{
    SETTINGFILE_LOADER_TYPE loader;

    OWI_Prev_Calibration_Ongoing = FALSE;
    Prev_Cycle_Name = CYCLE_NAME_INVALID;
    // Initialize SF data pointer
    Sf_OWIMonitor_Config = NULL;


    // Get the Heat Monitor process parameters from the setting file.
    if (SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS,
                                DISPL_OWI_CALIBRATION,
                                &loader) == FAIL)
    {
        LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, 0);
    }
    else
    {
        Sf_OWIMonitor_Config = (SF_DATA_TYPE*)(void*)(loader.Data);
    }

    if ((Micro__GetResetMode() == MICRO_RESET_MODE_COLD) &&
            (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != (NVDATA_RESTORE_TYPE)NVDATA_RESTORE_OKAY))
    {
        CycleCounterSinceLastCalibration = 0;
        CalibrationCounterSinceLastSuccess = 0;
        OWI_Status = OWI_STATUS_NEEDS_CALIBRATION;
    }

}

void OWIMonitor__Execution(void)
{
    BOOL_TYPE calibration_ongoing;
    CYCLE_PHASE_STATEMENT_TYPE cps;
    CYCLE_STATE_TYPE cycle_state;
    CYCLE_NAME_TYPE cycle_name;

    calibration_ongoing = OWICalibration__GetRunningFlag();
    if (((uint8)OWI_Prev_Calibration_Ongoing == (uint8)TRUE) && (FALSE == calibration_ongoing))    // Calibration finished
    {
        if (PASS == OWICalibration__GetStatus())
        {
            OWI_Status = OWI_STATUS_CALIBRATED;
            CycleCounterSinceLastCalibration = 0;
            CalibrationCounterSinceLastSuccess = 0;
            if ((uint8)Fault__IsInFaultState(FAULT_ID_OWI_CALIBRATION_FAILURE) == (uint8)TRUE)
            {
                // fault clear F3E2
                Fault__ConditionRemoved(FAULT_ID_OWI_CALIBRATION_FAILURE);
            }
        }
        else
        {
            CalibrationCounterSinceLastSuccess++;

            if (CalibrationCounterSinceLastSuccess >= Sf_OWIMonitor_Config->Turbidity_Sensor_Calib_Retry_Count)
            {
                CalibrationCounterSinceLastSuccess = Sf_OWIMonitor_Config->Turbidity_Sensor_Calib_Retry_Count;
                OWI_Status = OWI_STATUS_NON_SENSOR_MODE;
                CycleCounterSinceLastCalibration = 0;
                // fault detect F3E2
                if (Fault__IsInFaultState(FAULT_ID_OWI_CALIBRATION_FAILURE) == FALSE)
                {
                    Fault__ConditionDetected(FAULT_ID_OWI_CALIBRATION_FAILURE);
                }
            }
        }
    }
    OWI_Prev_Calibration_Ongoing = calibration_ongoing;

    cps = Interpreter__GetCurrentStatement(COMPARTMENT_DEFAULT);
    cycle_state = (Selector__GetCycleState(Interpreter__GetCurrentSFIndex(COMPARTMENT_DEFAULT), COMPARTMENT_DEFAULT, cps.Cycle));

    if (cycle_state == CYCLE_STATE_PROGRAMMING)
    {
        cycle_name = Selector__GetCycleNameId(Interpreter__GetCurrentSFIndex(COMPARTMENT_DEFAULT),COMPARTMENT_DEFAULT,cps.Phase);
        if (((CYCLE_NAME_SERVICE_0 == cycle_name) || (CYCLE_NAME_SERVICE_1 == cycle_name))
         && (CYCLE_NAME_SERVICE_0 != Prev_Cycle_Name) && (CYCLE_NAME_SERVICE_1 != Prev_Cycle_Name))
        {
            CalibrationCounterSinceLastSuccess = 0;
            CycleCounterSinceLastCalibration = 0;
            OWI_Status = OWI_STATUS_NEEDS_CALIBRATION;
        }
        Prev_Cycle_Name = cycle_name;
    }
}

void OWIMonitor__CycleStarted(void)
{
    if (Supervisor__IsTestCycleActive())
    {
        CalibrationCounterSinceLastSuccess = 0;
        CycleCounterSinceLastCalibration = 0;
        OWI_Status = OWI_STATUS_NEEDS_CALIBRATION;
    }
}

void OWIMonitor__CycleEndEvent(void)
{
    if (CycleCounterSinceLastCalibration < 0xFFFFU)
    {
        CycleCounterSinceLastCalibration ++;
    }
    if (CycleCounterSinceLastCalibration >= (Sf_OWIMonitor_Config->OWI_Cycles_Between_Calibrations + (uint8)1))
    {
        CalibrationCounterSinceLastSuccess = 0;
        CycleCounterSinceLastCalibration = 0;
        OWI_Status = OWI_STATUS_NEEDS_CALIBRATION;
    }
}

void OWIMonitor__CheckFaultCondition(void)
{
    if (CalibrationCounterSinceLastSuccess >= Sf_OWIMonitor_Config->Turbidity_Sensor_Calib_Retry_Count)
    {
        CalibrationCounterSinceLastSuccess = Sf_OWIMonitor_Config->Turbidity_Sensor_Calib_Retry_Count;
        OWI_Status = OWI_STATUS_NON_SENSOR_MODE;

        // fault detect F3E2
        if (Fault__IsInFaultState(FAULT_ID_OWI_CALIBRATION_FAILURE) == FALSE)
        {
            Fault__ConditionDetected(FAULT_ID_OWI_CALIBRATION_FAILURE);
        }
    }
}
//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================


