/**
 * @file
 * @brief       A cross-category process for determining when to jump to a different step, phase, and/or cycle.
 *
 * @details
 *
 * JumpIf Setting File Parameter Data
 *
 * For a simple jump within the current cycle and phase:
 * <pre>
 *      Word Offset     First Byte              Second Byte
 *      -----------     ---------------         ----------------
 *      +0000h          Condition_Index         Statement_Offset
 * </pre>
 *
 * For a jump to a different cycle and/or phase:
 * <pre>
 *      Word Offset     First Byte              Second Byte
 *      -----------     ---------------         ----------------
 *      +0000h          Condition_Index         Statement_Offset
 *      +0001h          Phase_Offset            Cycle_Offset
 * </pre>
 *
 * For a jump that may return or may have special instructions for estimating:
 * <pre>
 *      Word Offset     First Byte              Second Byte
 *      -----------     ---------------         ----------------
 *      +0000h          Condition_Index         Statement_Offset
 *      +0001h          Phase_Offset            Cycle_Offset
 *      +0002h          Bit 7 = Reerved         0
 *                      Bit 6-5 = Predict
 * </pre>
 *
 * Condition Index: An index to the test condition to evaluate. If the condition evaluates to TRUE,
 * then the jump occurs. If the condition is FALSE, then no jump occurs.
 *
 * Cycle Offset: A signed value [-128, 127] that is added to the current cycle to determine the
 * target cycle. A value of 0 indicates that there is no change in the cycle. A value of -128
 * should be used to set the target cycle to zero.
 *
 * Phase Offset: A signed value [-128, 127] that is added to the current phase to determine the
 * target phase. A value of 0 indicates that there is no change in the phase. A value of -128
 * should be used to set the target phase to zero.
 *
 * Statement Offset: A signed value [-128, 127] that is added to the current statement to determine
 * the new location. A value of -128 should be used to set the target statement to zero.
 *
 * Predict: The prediction field contains instructions on how to interpret the JumpIf behavior
 * during cycle time estimation.
 *      0 = Predict that the Jump will not occur. Do not evaluate the condition and never jump.
 *      1 = Predict that the Jump will occur. Do not evaluate the condition and always jump.
 *      2, 3, or unspecified = Evaluate the condition to determine whether or not to jump.
 *
 *
 * $Header: JumpIf.c 1.6 2015/08/05 17:04:36EDT Nelson Ferragut II (FERRANJ) Exp  $
 *
 * @copyright  Copyright 2014 - $Date: 2015/08/05 17:04:36EDT $  Whirlpool Corporation.  All rights reserved - CONFIDENTIAL.
 */

//  --- Include Files -------------------------------------------------------------------------------------------------

// -- This Module --
#include "C_Extensions.h"
#include "JumpIf.h"

// -- Other Modules --
#include "Condition.h"
#include "Log.h"
#include "Selector.h"
#include "SettingFile.h"


//  --- Private Properties --------------------------------------------------------------------------------------------

// -- Private Constant Declarations --

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_JUMPIF

//! The value passed when the target cycle/phase/statement is zero.
#define TARGET_FIRST_ITEM -128


// -- Private Enumerated Constants Declarations --

//! List of values to compare with the F1_F0_Flags.
typedef enum JUMPIF_OPTION_ENUM
{
    JUMPIF_OPTION_DEFAULT,                          //!< F1=0, F0=0
    JUMPIF_OPTION_PHASE,                            //!< F1=0, F0=1
    JUMPIF_OPTION_COUNT
} JUMPIF_OPTION_TYPE;

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_JUMPIF_LOG_MESSAGE_ID_ENUM
{
    INVALID_PROCESS_CONTROL = 1,
    INVALID_PROCESS_PARAMETERS,
    NO_TARGET_AVAILABLE,
    TARGET_STATEMENT_OUT_OF_RANGE,
    TARGET_PHASE_OUT_OF_RANGE,
    TARGET_CYCLE_OUT_OF_RANGE,
    GESE_SHOULD_USE_NEG_128,
    CPS_NULL_REFERENCE
} MODULE_JUMPIF_LOG_MESSAGE_ID_TYPE;


// -- Private Type Declarations --

//! Types of prediction methods to use when estimating future behavior.
typedef enum JUMPIF_PREDICT_ENUM
{
    PREDICT_NEVER_JUMP          = 0,
    PREDICT_ALWAYS_JUMP         = 1,
    PREDICT_CONDITIONAL_JUMP    = 2
} JUMPIF_PREDICT_TYPE;

//! The data structure found in the setting file.
typedef PACKED struct JUMPIF_PARAMETER_STRUCT
{
    uint8 Condition_Index;
    sint8 Statement_Offset;
    sint8 Phase_Offset;
    sint8 Cycle_Offset;
    uint8 Unused                : 5;
    JUMPIF_PREDICT_TYPE Predict : 2;
    uint8 Reserved              : 1;
} JUMPIF_PARAMETER_TYPE;


// -- Private Variable Definitions --

//! Number of bytes in the JumpIf parameter data structure.
static uint8 Length;

//! Pointer to the JumpIf parameter data structure.
static JUMPIF_PARAMETER_TYPE* Parameter;


//  --- Private Function Prototypes -----------------------------------------------------------------------------------

static BOOL_TYPE GetTarget(JUMPIF_PARAMETER_TYPE* parameter, uint8 length, CYCLE_PHASE_STATEMENT_TYPE* cps);
static void ReadProcessParameters(PROCESS_CONTROL_TYPE* control);


//=====================================================================================================================
//  --- Public Methods ------------------------------------------------------------------------------------------------
//=====================================================================================================================


#if (TIME_ESTIMATION_FEATURE == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief       Predict whether or not the JumpIf statement is expected to jump when executed.
 * @param control = The control parameters provided by the Estimator.
 * @param cps = A pointer to the current cycle, phase, and statement.
 *              It will be updated with the new cycle, phase, and statement if a jump is predicted.
 * @return TRUE if JumpIf statement is predicted to jump.
 */
BOOL_TYPE JumpIf__Estimate(uint8 sf_index, uint16 displacement, CYCLE_PHASE_STATEMENT_TYPE* cps)
{
    BOOL_TYPE predict_jump;
    SETTINGFILE_LOADER_TYPE loader;
    JUMPIF_PARAMETER_TYPE* parameter;

    predict_jump = FALSE;
    if (cps == NULL)
    {
        LOG_ADD_EXCEPTION(CPS_NULL_REFERENCE, 0);
    }
    // Get the JumpIf process parameters from the setting file.
    else if (SettingFile__MSettingBasicLoader(sf_index, SF_PTR_ACU_PROCESS_JUMP_IF, displacement, &loader) == FAIL)
    {
        LOG_ADD_EXCEPTION(INVALID_PROCESS_PARAMETERS, displacement);
    }
    else
    {
        parameter = (JUMPIF_PARAMETER_TYPE*)loader.Data;    //lint !e927 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
        if ((loader.Length >= sizeof(JUMPIF_PARAMETER_TYPE)) &&
            (parameter->Predict < PREDICT_CONDITIONAL_JUMP))
        {
            predict_jump = (BOOL_TYPE)(parameter->Predict);
        }
        else if (CONDITION_LEGACY_EVAL(parameter->Condition_Index) == CONDITION_RESULT_TRUE)
        {
            predict_jump = TRUE;
        }
        else
        {
            // predict_jump stays FALSE as set at the start of the function.
        }

        if (predict_jump == TRUE)
        {
            GetTarget(parameter, loader.Length, cps);
        }
    }

    return predict_jump;
}
#endif                                              // #if (TIME_ESTIMATION_FEATURE == ENABLED)


//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief       Get the target cycle, phase, and statement for the current JumpIf statement.
 *
 * If there is a problem determining the target, then the cycle, phase, and statement are left
 * unchanged. A problem can occur in any of the following cases:
 *      - There is no current JumpIf statement.
 *      - The resulting cycle is out of range.
 *      - The resulting phase is out of range.
 *      - The resulting statement is out of range.
 *
 * @param cps = A pointer to the current cycle, phase, and statement.
 *              It will be updated with the new cycle, phase, and statement.
 *
 * @retval TRUE = Valid target found.
 * @retval FALSE = Valid target not found.
 */
BOOL_TYPE JumpIf__GetTarget(CYCLE_PHASE_STATEMENT_TYPE* cps)
{
    BOOL_TYPE valid_target = FALSE;

    if (Parameter == NULL)
    {
        LOG_ADD_EXCEPTION(NO_TARGET_AVAILABLE, (cps->Phase << 8) + cps->Statement);
    }
    else
    {
        valid_target = GetTarget(Parameter, Length, cps);
    }

    return (valid_target);
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief       The JumpIf process.
 *
 * The JumpIf Process evaluates a condition and determines whether or not a jump should occur.
 *
 * @param control = The control parameters provided by the Interpreter.
 * @retval PROCESS_COMPLETE = The process is ready for the Interpreter to proceed to the next step.
 * @retval PROCESS_BUSY = The process is not ready for the Interpreter to proceed to the next step.
 */
PROCESS_RESULT_TYPE JumpIf__Process(PROCESS_CONTROL_TYPE* control)
{
    PROCESS_RESULT_TYPE result;

    result = PROCESS_BUSY;
    if ((control == NULL) ||
        (control->F1_F0_Flags >= (uint8)JUMPIF_OPTION_COUNT))
    {
        LOG_ADD_EXCEPTION(INVALID_PROCESS_CONTROL, (control != NULL));
    }
    else
    {
        // Read the JumpIf process parameters from the setting file.
        ReadProcessParameters(control);

        // Proceed only if the step was correctly initialized.
        if (Parameter != NULL)
        {
            if (CONDITION_LEGACY_EVAL(Parameter->Condition_Index) == CONDITION_RESULT_TRUE)
            {
                result = PROCESS_COMPLETE;
            }
        }
    }

    return result;
}


//=====================================================================================================================
//  --- Private Methods -----------------------------------------------------------------------------------------------
//=====================================================================================================================


//---------------------------------------------------------------------------------------------------------------------
/**
 * Get the target cycle, phase, and statement for the current JumpIf statement.
 *
 * @param parameter = Pointer to the JumpIf parameter data structure.
 * @param length = Number of bytes in the parameter structure.
 * @param cps = A pointer to the current cycle, phase, and statement.
 *              It will be updated with the new cycle, phase, and statement.
 *
 * @retval TRUE = Valid target found.
 * @retval FALSE = Valid target not found.
 *
 */
static BOOL_TYPE GetTarget(JUMPIF_PARAMETER_TYPE* parameter, uint8 length, CYCLE_PHASE_STATEMENT_TYPE* cps)
{
    BOOL_TYPE valid_target;
    sint16 target_cycle;
    sint16 target_phase;
    sint16 target_statement;

    // Determine the target statement.
    valid_target = TRUE;
    if (parameter->Statement_Offset == TARGET_FIRST_ITEM)
    {
        target_statement = 0;
    }
    else
    {
        target_statement = cps->Statement + parameter->Statement_Offset;
        if ((target_statement < 0) || (MAX_STATEMENTS <= target_statement))
        {
            LOG_ADD_EXCEPTION(TARGET_STATEMENT_OUT_OF_RANGE, (cps->Phase << 8) + cps->Statement);
            valid_target = FALSE;
        }
        else if ((target_statement == 0) && (cps->Statement != 0))
        {
            LOG_ADD_EXCEPTION(GESE_SHOULD_USE_NEG_128, (cps->Phase << 8) + cps->Statement);
        }
    }

    if (length >= (sizeof(parameter->Condition_Index) +
                   sizeof(parameter->Statement_Offset) +
                   sizeof(parameter->Phase_Offset) +
                   sizeof(parameter->Cycle_Offset)))
    {
        // Determine the target phase.
        if (parameter->Phase_Offset == TARGET_FIRST_ITEM)
        {
            target_phase = 0;
        }
        else
        {
            target_phase = cps->Phase + parameter->Phase_Offset;
            if ((target_phase < 0) || (MAX_PHASES <= target_phase))
            {
                LOG_ADD_EXCEPTION(TARGET_PHASE_OUT_OF_RANGE, (cps->Phase << 8) + cps->Statement);
                valid_target = FALSE;
            }
            else if ((target_phase == 0) && (cps->Phase != 0))
            {
                LOG_ADD_EXCEPTION(GESE_SHOULD_USE_NEG_128, (cps->Phase << 8) + cps->Statement);
            }
        }

        // Determine the target cycle.
        target_cycle = cps->Cycle + parameter->Cycle_Offset;
        if ((target_cycle <= 0) || (MAX_CYCLES <= target_cycle))
        {
            LOG_ADD_EXCEPTION(TARGET_CYCLE_OUT_OF_RANGE, (cps->Phase << 8) + cps->Statement);
            valid_target = FALSE;
        }

        // Write the target statement, phase, and cycle.
        if (valid_target == TRUE)
        {
            cps->Statement = target_statement;
            cps->Phase = target_phase;
            cps->Cycle = target_cycle;
        }
    }
    else
    {
        // Write the target statement only.
        // Jump was within the current cycle and phase.
        if (valid_target == TRUE)
        {
            cps->Statement = target_statement;
        }
    }

    return (valid_target);
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief       Read the process parameters and setup the JumpIf process.
 *
 * @param control = The control parameters provided by the Interpreter.
 */
static void ReadProcessParameters(PROCESS_CONTROL_TYPE* control)
{
    SETTINGFILE_LOADER_TYPE loader;

    // Get the JumpIf process parameters from the setting file.
    if (SettingFile__MSettingBasicLoader(control->Setting_File_Index,
                                         SF_PTR_ACU_PROCESS_JUMP_IF,
                                         control->Data_Field_Index,
                                         &loader) == FAIL)
    {
        Parameter = NULL;
        if (control->Step_Initializing == TRUE)
        {
            LOG_ADD_EXCEPTION(INVALID_PROCESS_PARAMETERS, control->Data_Field_Index);
        }
    }
    else
    {
        Parameter = (JUMPIF_PARAMETER_TYPE*)(loader.Data);  //lint !e927 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
        Length = loader.Length;
    }
}

