/**
 *  @file
 *  @brief      Automatically generated private parameters for the Log module.
 *
 *  @details    This file was automatically generated on 11/21/2024 1:40:25 PM by
 *              LogPreprocessor.exe (v1.3.0)  Copyright © 2013-2017 Whirlpool Corporation.
 *
 *              LogPreprocessor.exe attempts to preserve user settings.
 *              The user should test to make sure that changes to this file are handled as expected.
 *
 *  $Header: Program.cs 1.13 2015/10/30 11:22:11EDT Nelson Ferragut II (FERRANJ) Exp  $
 *
 *  @copyright  Copyright 2012 - $Date: 2015/10/30 11:22:11EDT $  Whirlpool Corporation.  All rights reserved - CONFIDENTIAL.
 */
#ifndef LOG_PRV_H_
#define LOG_PRV_H_


// -- Insert custom paramters here, if necessary. --
// -- Private Macro Declarations --

//---------------------------------------------------------------------------------------------------------------------
/**
 * The Log module calls this macro when an invalid Module Identifier is passed as part of a Log
 * Message.
 *
 * @param mod = (LOG_MODULE_ID_TYPE) The Module Identifier that was invalid.
 */
#define DEBUG_MODULE_ID_INVALID(mod)

//---------------------------------------------------------------------------------------------------------------------
/**
 * The Log module calls this macro when an invalid Message Severity is passed as part of a Log
 * Message.
 *
 * @param mod = (LOG_MODULE_ID_TYPE) The Module Identifier associated with the passed Log Message.
 *          This value can be used to find the source of the problem.
 * @param sev = (LOG_SEVERITY_ID_TYPE) The Message Severity that was invalid.
 */
#define DEBUG_SEVERITY_ID_INVALID(mod, sev)


// -- Private Constant Declarations --

//! Define the API number used to report log messages.
#define LOG_REPORT_API          0x04

//! Define the OpCode number used to report log messages.
#define LOG_REPORT_OPCODE       0x0F


//=====================================================================================================================
//  --- Automated Parameters ------------------------------------------------------------------------------------------
//=====================================================================================================================


//---------------------------------------------------------------------------------------------------------------------
/**
 * Automated table of severity filters to enable/disable Log Messages by Message Severity.
 *
 * The LogPreprocessor.exe tool will add entries to this table and remove entries from this table
 * to keep it synchronized with the #LOG_MODULE_ID_TYPE. The tool will attempt to preserve an
 * entry once it is present in the table.
 *
 * The #LOG_MODULE_ID_TYPE is used as an index into this table. Each row in the table represents
 * the filter for a specific application module. The application module's name must be in the
 * comment at the end for the LogPreprocessor.exe tool to know which data belongs with which
 * module.
 *
 * If the #LOG_RUN_TIME_FILTERING is ENABLED, then this table is just the initial setting and
 * these values can be changed at run-time by calling the Log__SetMessageFilter() function.
 */
static const LOG_SEVERITY_FILTER_TYPE LOG_SEVERITY_FILTERS_TABLE[] =
{
//  (LOG_SEVERITY_FILTER_TYPE)(LOG_ALLOW_INFO | LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_NAME
//                            --------------------------------------------------------------------------
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_ABSOLUTE_HUMIDITY_LLI
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_ACCEL_BASELINE
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_ACTIVATE_TASK
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_AIRLOCK_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_ALTERNATE
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_API007APP
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_API007BULKDATA
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_API007NVDATA
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_API010_POLL_VAR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_API011APPCTRL
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_API012EXPANSION
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_API013_REMOTE_FUNCTION
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_API221_MOTION_CTRL
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_APPLIANCE_MANAGER
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_AUTOSTARTFACTORYCYCLE_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_BROWNOUT
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_CALIBRATION
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_CLASS_A_FILL
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_CONDITION
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_CROSSLOADS
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_DC_LOAD_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_DIGITALOUTPUTPILOT
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_DOOR_OPENING_SYSTEM_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_DOOR_OPENING_SYSTEM_PULL
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_DOOR_OPENING_SYSTEM_PUSH
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_EQUATION
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_ERROR_EVENTS
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_ESTIMATOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_EXTERNAL_MOTOR_PILOT
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_FAN_MOTOR_FAULT_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_FAULT
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_FILL
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_FILL_VALVE_FAULT_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_FILTERS
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_FXLS8974
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_HBL
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_HCD_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_HEAT
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_HEAT_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_HEATER_FAULT_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_HEATER_SHADOWING
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_HOTHIGHPOT_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_I2C_INFRARED_LLI
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_I2C_RHT_SENSOR_LLI
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_I2CPRESSURESENSOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_INTERPRETER
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_JUMPIF
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_LISxDH
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_LITT_FAULT_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_LITT_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_LOADS_CONTROL
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_MAGNETRON_PILOT
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_MAGNETRON_PILOT_MAINS_SAMPLER
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_MAGNETRON_PILOT_RELAY_SYNC
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_MAINTAIN
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_MCI
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_MODIFIER
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_MOISTURE_PREVENTION
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_MOTOR_PILOT
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_NORMAL_FILL
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_NVDATA
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_OWI
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_OWI_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_OWI_ONE_SHOT
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_OWI_VRO_READ
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_PARTIALDRAIN
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_PILOT_RELAY_FAULT_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_PLUGGING_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_PRODUCTINFO
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_PUMPCONTROL
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_REGENERATE
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_REGULATIONS
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_RINSE_AID
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_RINSE_AID_DISPENSE
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_RINSE_AID_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_SALT_SENSING_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_SANITIZATION
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_SELECTOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_SENSEDDRAIN
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_SETLOADQUEUE
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_SETTINGFILE
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_SETVARIABLE
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_SFVERSIONCHECK
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_SREXCEPTION
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_SSDRAIN_MOTOR_FAULT_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_STABILITY_CONTROL
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_STATISTICS
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_STATUS
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_STATUSLED
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_SUBCYCLE
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_SUPERVISOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_SYSTEMTIMERS
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_TANK_DRAIN
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_TANK_FILL
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_THERMISTOR_FAULT_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_TRIAC_SHORTED_DRAIN_FAULT_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_TRIACMCI
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_TRIDGE_DETERGENT
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_VARIABLE
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_VOLTAGE_RANGE
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_VSDRAIN_MOTOR_FAULT_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_VWI
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_VWI_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR),   // MODULE_WASH_MOTOR_FAULT_MONITOR
    (LOG_SEVERITY_FILTER_TYPE)(                 LOG_ALLOW_EXCEPTION | LOG_ALLOW_EVENT | LOG_ALLOW_ERROR)    // MODULE_ZEROCROSS
};



#endif  // LOG_PRV_H_


