/**
 *  @file       
 *
 *  @brief      Manages storage and recovery of non-volatile data.
 *

 @startuml{"NVData_SM.png" }
    title NVDATA STATE MACHINE
    [*] --> NVDATA_IDLE
    NVDATA_IDLE --> NVDATA_STORING : EV_BROWNOUT
    NVDATA_STORING --> NVDATA_STORED : EV_STORE_SUCCESS
    NVDATA_STORING --> NVDATA_ERROR : EV_STORE_FAIL
    NVDATA_ERROR --> NVDATA_STORING : EV_RECOVERED


    NVDATA_IDLE:do / check for brownout
    NVDATA_STORING: do / store segments
    NVDATA_STORED: do / check for power
    NVDATA_ERROR: entry / recover


 @enduml

 *
 *  @copyright  Copyright 2015-2017: 2015/08/06 17:02:25EDT $. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "C_Extensions.h"
#include "NVData.h" 
#include "NVData_prv.h"
#include "SRTaskMonitor.h"
#include "Micro.h"
#include "Crc16.h"
#include "Log.h"
#include "Mode.h"
#include <string.h>

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------
//------- Log Module messages ---------------------------------------
//! A list of log message IDs that are generated by this module.
typedef enum
{
    INSUFFICIENT_APPLIENCE_OR_STATISTICS_NONVOLATILE_MEMORY_ALLOCATED = 0,                                   //!< data: the gi index
    INSUFFICIENT_STATIC_NONVOLATILE_MEMORY_ALLOCATED,                                   //!< data: the gi index
} MODULE_NVDATA_LOG_MESSAGE_ID_TYPE;

#define MODULE_NAME MODULE_NVDATA      //!< The name of this module for use by the Log module.

#define NVDATA_READ_BUFFER_SIZE         32
#define NVDATA_INITIAL_CRC              0xFFFF

#ifndef NVDATA_PAGE_FORMAT_SIZE
    #error "NVDATA_PAGE_FORMAT_SIZE not defined"
#endif

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
#if (NVDATA_STORE_APPLIANCE_AND_STATISTICS_FEATURE == ENABLED)

    #ifndef NVDATA_PAGE_SIZE
        #error "NVDATA_PAGE_SIZE not defined"
    #endif

    #if((NVDATA_PAGE_SIZE % NVDATA_PAGE_FORMAT_SIZE) != 0)
    #error "NVDATA_PAGE_SIZE must be a multiple of  NVDATA_PAGE_FORMAT_SIZE"
    #endif

    PACKED typedef struct
    {
        uint32 Signature;
        uint16 Statistics_Crc;
        uint16 Error_Crc;
        uint16 Appliance_Crc;
        uint16 Signature_Counter;
    }NVDATA_HEADER_TYPE;

    static NVDATA_RESTORE_STATUS_TYPE NVData_Status;
    static uint32 Next_Store_Address;
    static BOOL_TYPE NVData_BrownOut;

    // The following definitions will determine how the appliance segment data will be restored after a reset
    // The values are obscure to eliminate any impact from an inadvertent change to the variable.
    #define APPLIANCE_SEGMENT_CORRUPT   0xC3    //!< Indicates the appliance segment should be reported as corrupt
    #define APPLIANCE_SEGMENT_RESTORE   0xE8    //!< Indicates the appliance segment should be restored through the normal process

    //! Indicates whether the appliance segment should be reported as corrupt, ignoring the normal process used to restore the data.
    //! Unique values are used to eliminate an impact from an inadvertent change to the variable.
    //! A value of APPLIANCE_SEGMENT_CORRUPT means the segment should get corrupted on the next reset.
    //! A value of APPLIANCE_SEGMENT_RESTORE means the segment should be restored through the normal process on the next reset.
    #pragma location = "_appliance_segment"
    static uint8 Force_Appliance_Segment_Corruption;

    #define NVDATA_INITIAL_CRC                                  0xFFFF

    #define NVDATA_HEADER_SIGNATURE                             0xA5A55A5A
    #define NVDATA_HEADER_SIGNATURE_INIT                        0x5A5AA5A5
    //=====================================================================================================================
    //=== StateEngineCrank (v2.0) Auto-Generated Definitions for Nvdata State Machine
    //=====================================================================================================================
    // !! StateEngineCrank cannot update this code if you change the header !!


    //! Unique names used to identify states of the Nvdata state machine.
    typedef enum NVDATA_STATE_ENUM
    {
        STATE_NONE           = 0,

        STATE_NVDATA_IDLE    = 1,                       //!< (initial_state)
        STATE_NVDATA_STORING = 2,
        STATE_NVDATA_STORED  = 3,
        STATE_NVDATA_ERROR   = 4,

        STATE_NVDATA_END     = 5
    } NVDATA_STATE_TYPE;

    //! The state variable for the Nvdata state machine.
    //! State machines with a history pseudostate may write to this variable during initialization.
    //! Other state machines must only write to this variable through auto-generated functions.
    static NVDATA_STATE_TYPE Nvdata_State;

    // -- Private Function Prototypes used by the state machine for customization functions --
    static void CheckForBrownout(void);
    static void CheckForPower(void);
    static void Recover(void);
    static void StoreSegments(void);

    // -- Private Function Prototypes used by the state machine for standard state machine functions --
    static void EventBrownout(void);
    static void EventRecovered(void);
    static void EventStoreFail(void);
    static void EventStoreSuccess(void);
    static void NvdataExecute(void);
    static void NvdataInitialize(void);

    // !! StateEngineCrank cannot update this code if you change the footer !!
    // End of StateEngineCrank Auto-Generated Code.




    //=====================================================================================================================
    /**
     * Header Segment
     */
    //=====================================================================================================================
    #pragma location = "_header_segment"
    static volatile NVDATA_HEADER_TYPE NVData_Header;


    //=====================================================================================================================
     /**
      * Appliance Segments
      */
    //=====================================================================================================================
    #pragma location = "_appliance_segment"
    static volatile uint32 DataFlash_Appliance_Filler;

    #pragma section = "_appliance_segment"
    extern uint32 NVDATA_SECTION_APPLIANCE$$Base;
    extern uint32 NVDATA_SECTION_APPLIANCE$$Limit;
    static uint8 * const  DATAFLASH_APPLIANCE_START =               (uint8 * )(&NVDATA_SECTION_APPLIANCE$$Base);
    static const uint32   DATAFLASH_APPLIANCE_LIMIT =               (uint32)(&NVDATA_SECTION_APPLIANCE$$Limit);

    //=====================================================================================================================
     /**
      * Statistics Segments
      */
    //=====================================================================================================================
    #pragma location = "_statistics_segment"
    static volatile uint32 DataFlash_Statistics_Filler;


    #pragma section = "NVDATA_SECTION_STATISTICS"
    extern uint32 NVDATA_SECTION_STATISTICS$$Base;
    extern uint32 NVDATA_SECTION_STATISTICS$$Limit;
    static uint8 * const  DATAFLASH_STATISTICS_START =               (uint8 * )(&NVDATA_SECTION_STATISTICS$$Base);
    static const uint32   DATAFLASH_STATISTICS_LIMIT =               (uint32)(&NVDATA_SECTION_STATISTICS$$Limit);
    //-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
    static uint32 UpdatePosition(uint32 currentposition, uint32 size);
    static void Restore(uint32 address, uint32 address2);


    //=====================================================================================================================
     /**
      * Firmware and Setting File validation
      */
    //=====================================================================================================================
    extern uint32 __SetingFile_Start;
    extern uint32 __SetingFile_Size;

	#define SF_CRC                        ( (uint16) (*(uint16 *) (((uint32)(&__SetingFile_Start)) + ((uint32)(&__SetingFile_Size)) - 4U) ) )

    // symbol MICRO_FLASH_CRC created by the IELF tool, this holds the calculated CRC value on the flash memory.
    extern uint32  MICRO_FLASH_CRC;		//lint !e18 Lint: 18 Symbol 'MICRO_FLASH_CRC' redeclared

    #pragma location = "_appliance_segment"
    static uint16 NVData_FirmwareCrc;

    #pragma location = "_appliance_segment"
    static uint16 NVData_SettingFileCrc;

    static BOOL_TYPE IsThisNewFirmwareOrSettingFile(void);
    static void StoreNewFirmwareAndSettingFile(void);
#endif
//=====================================================================================================================
 /**
  * Board Data
  */
//=====================================================================================================================
#if (NVDATA_STORE_STATIC_FEATURE == ENABLED)
    #ifndef NVDATA_STATIC_PAGE_SIZE
        #define NVDATA_STATIC_PAGE_SIZE         NVDATA_PAGE_SIZE
    #endif

    #if((NVDATA_STATIC_PAGE_SIZE % NVDATA_PAGE_FORMAT_SIZE) != 0)
    #error "NVDATA_STATIC_PAGE_SIZE must be a multiple of  NVDATA_PAGE_FORMAT_SIZE"
    #endif

    #pragma section = "NVDATA_SECTION_STATIC_CFG"
    extern uint32 NVDATA_SECTION_STATIC_CFG$$Base;
    extern uint32 NVDATA_SECTION_STATIC_CFG$$Limit;
    static uint8 * const  DATAFLASH_STATICDATA_START =               (uint8 * )(&NVDATA_SECTION_STATIC_CFG$$Base);
    static const uint32   DATAFLASH_STATICDATA_LIMIT =               (uint32)(&NVDATA_SECTION_STATIC_CFG$$Limit);

    static PASS_FAIL_TYPE RestoreStaticData(void);
#endif

static PASS_FAIL_TYPE FlushPage(uint32 address);

//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief It Initializes the module NVData and its variables
 *
 */
void NVData__Initialize(void)
{
	MICRO_DECLARE_INTERRUPT_CONTEXT_LOCAL();
    uint32 segment_total_size;
    NVDATA__INITIALIZEDEVICE();

    #if (NVDATA_STORE_STATIC_FEATURE == ENABLED)
        segment_total_size = (DATAFLASH_STATICDATA_LIMIT - (uint32)DATAFLASH_STATICDATA_START);     //lint !e923 Lint: 923 cast from pointer to unsigned long [Encompasses MISRA 2004 Rule 11.1], [MISRA 2004 Rule 11.3]

        //Check if the allocated non volatile memory is sufficient to store the data
        if (NVDATA_STATIC_PAGE_SIZE < segment_total_size)
        {
            LOG_ADD_ERROR(INSUFFICIENT_STATIC_NONVOLATILE_MEMORY_ALLOCATED, segment_total_size);
            Mode__SetModeExtended(MODE_NORMAL, SUBMODE_NORMAL_ERROR);
        }
    #endif

    #if (NVDATA_STORE_APPLIANCE_AND_STATISTICS_FEATURE == ENABLED)
        NVDATA_HEADER_TYPE header1;
        NVDATA_HEADER_TYPE header2;

        segment_total_size = (DATAFLASH_APPLIANCE_LIMIT - (uint32)DATAFLASH_APPLIANCE_START) + (uint16)(DATAFLASH_STATISTICS_LIMIT - (uint32)DATAFLASH_STATISTICS_START); //lint !e923 Lint: 923 cast from pointer to unsigned long [Encompasses MISRA 2004 Rule 11.1], [MISRA 2004 Rule 11.3]

        //Check if the allocated non volatile memory is sufficient to store the data
        if (NVDATA_PAGE_SIZE < segment_total_size)
        {
            LOG_ADD_ERROR(INSUFFICIENT_APPLIENCE_OR_STATISTICS_NONVOLATILE_MEMORY_ALLOCATED, segment_total_size);
            Mode__SetModeExtended(MODE_NORMAL, SUBMODE_NORMAL_ERROR);
        }

    #endif

	// Disable all interrupts -------------------------------------------------------
	MICRO_SAVE_INTERRUPT_CONTEXT_LOCAL();

	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
    {

        #if (NVDATA_STORE_APPLIANCE_AND_STATISTICS_FEATURE == ENABLED)
			Micro__ServiceWatchdog();
            Next_Store_Address = 0xFFFFFFFF;

            DataFlash_Appliance_Filler = 0;
            DataFlash_Statistics_Filler = 0;
            NVData_Header.Signature = NVDATA_HEADER_SIGNATURE;

            header1.Signature = 0xFFFFFFFF;
            header2.Signature = 0xFFFFFFFF;

            NVData_Status.Byte = 0;
            NVDATA__READ((uint8 *)&header1, 0, sizeof(header1)); //lint !e928 Lint: 928 cast from pointer to pointer [MISRA 2004 Rule 11.4]
            NVDATA__READ((uint8 *)&header2, NVDATA_PAGE_SIZE, sizeof(header2)); //lint !e928 Lint: 928 cast from pointer to pointer [MISRA 2004 Rule 11.4]

            NVData_Status.Bit.Appliance_Data_Recovered = NVDATA_RESTORE_CORRUPTED;
            NVData_Status.Bit.Statistics_Data_Recovered = NVDATA_RESTORE_CORRUPTED;

            // Header 1 is good
            if (header1.Signature == NVDATA_HEADER_SIGNATURE)
            {
                if (header2.Signature == NVDATA_HEADER_SIGNATURE)
                {
                    /////////
                    if ((header2.Signature_Counter > header1.Signature_Counter) &&
                        (header2.Signature_Counter > 0))
                    {
                        // Restore from 2
                        Restore(NVDATA_PAGE_SIZE,0);
                        Next_Store_Address = 0;

                    }
                    else
                    {
                        // Restore from 1
                        Restore(0,NVDATA_PAGE_SIZE);
                        Next_Store_Address = NVDATA_PAGE_SIZE;
                    }
                }
                else if (header2.Signature == NVDATA_HEADER_SIGNATURE_INIT)
                {
                    ////////
                    // header 1 good, header 2 initialized
                    // Restore from 1
                    Restore(0,0xFFFFFFFF);
                    Next_Store_Address = NVDATA_PAGE_SIZE;
                }
                else
                {
                    ////////
                    // header 1 good, header 2  corrupted
                    Restore(0,0xFFFFFFFF);
                    Next_Store_Address = NVDATA_PAGE_SIZE;

                    // consider restored data as restored from backup
                    if (NVData_Status.Bit.Appliance_Data_Recovered  == NVDATA_RESTORE_OKAY)
                    {
                        NVData_Status.Bit.Appliance_Data_Recovered = NVDATA_RESTORE_OKAY_BACKUP;
                    }

                    if (NVData_Status.Bit.Statistics_Data_Recovered  == NVDATA_RESTORE_OKAY)
                    {
                        NVData_Status.Bit.Statistics_Data_Recovered = NVDATA_RESTORE_OKAY_BACKUP;
                    }

                }
            }
            else
            {
                // Header 1 is corrupted
                if (header2.Signature == NVDATA_HEADER_SIGNATURE)
                {
                    ////////
                    // header 1 bad, header 2 good
                    // Restore from 2
                    Restore(NVDATA_PAGE_SIZE,0xFFFFFFFF);
                    Next_Store_Address = 0;

                    // consider restored data as restored from backup
                    if (NVData_Status.Bit.Appliance_Data_Recovered  == NVDATA_RESTORE_OKAY)
                    {
                        NVData_Status.Bit.Appliance_Data_Recovered = NVDATA_RESTORE_OKAY_BACKUP;
                    }

                    if (NVData_Status.Bit.Statistics_Data_Recovered  == NVDATA_RESTORE_OKAY)
                    {
                        NVData_Status.Bit.Statistics_Data_Recovered = NVDATA_RESTORE_OKAY_BACKUP;
                    }
                }
                else
                {
                	// Blank NVData: get current Firmware and Setting file CRC for future reference
                	StoreNewFirmwareAndSettingFile();
                }
            }
        #endif

        #if (NVDATA_STORE_STATIC_FEATURE == ENABLED)
            // Static Board Data -----------------------------------------------------------
            RestoreStaticData();
        #endif

    }
	#if (NVDATA_STORE_APPLIANCE_AND_STATISTICS_FEATURE == ENABLED)

        NvdataInitialize();
        NVData_BrownOut = FALSE;

        if (Next_Store_Address == 0xFFFFFFFF)
        {
            FlushPage(NVDATA_PAGE_SIZE);
            header1.Signature =NVDATA_HEADER_SIGNATURE_INIT;
            NVDATA__WRITE(NVDATA_PAGE_SIZE,(uint8 *)&header1,sizeof(header1)); //lint !e928 Lint: 928 cast from pointer to pointer [MISRA 2004 Rule 11.4]

            // Not Consistent
            FlushPage(0);
            Next_Store_Address = 0;
            NVData_Header.Signature_Counter = 0;
        }
        else
        {
            // Consistent
            if (Next_Store_Address == 0)
            {
                // Make page 0 ready
                FlushPage(0);
            }
            else
            {
                // Make page 1 ready
                FlushPage(NVDATA_PAGE_SIZE);
            }
        }
		Micro__ServiceWatchdog();
    #endif
	MICRO_RESTORE_INTERRUPT_CONTEXT_LOCAL();
}

#if (NVDATA_STORE_APPLIANCE_AND_STATISTICS_FEATURE == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This method handles the NVData in terms of keep in idle, perform a writing, etc.
 */
void NVData__Handler(void)
{
    NvdataExecute();
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This method trig the process to store all the data,
 * @return
 */
void NVData__BronwOut(BOOL_TYPE bout)
{
    NVData_BrownOut = bout;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This method Retrieves the status of the last data restore.
 * @return
 */
NVDATA_RESTORE_STATUS_TYPE * NVData__GetLastRestoreStatus(void)
{
    return (&NVData_Status);
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   Force the appliance segment of data to be corrupt. The next time the system resets the appliance segment
 *          data will not be restored. This does not affect any other segment.
 *
 * @return PASS_FAIL_TYPE
 *  @retval PASS(1) - Successfully able to Set appliance Segment corrupt
 *  @retval FAIL(0) - Failed to Set appliance Segment corrupt
 */
PASS_FAIL_TYPE NVData__SetApplianceSegmentCorrupt(void)
{
    PASS_FAIL_TYPE status = FAIL;

    // Prevent StoreSegments() call if NVData__Initialize has not been called
    // e.g. firmware with no setting file valid.
    if (NVData_Header.Signature == NVDATA_HEADER_SIGNATURE)
    {
        // If not in Normal Mode NVData could not be initialized
        if (Mode__GetMode() != MODE_NORMAL)
        {
            NVDATA__INITIALIZEDEVICE();
        }
        Force_Appliance_Segment_Corruption = APPLIANCE_SEGMENT_CORRUPT;
        status = NVData__Store();
    }

    return (status);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This method stores the NVData variables in a blocking way without reseting.
 *
 * @return PASS_FAIL_TYPE
 *  @retval PASS(1) - Successfully able to store the data
 *  @retval FAIL(0) - Failed to store the data
 */
PASS_FAIL_TYPE NVData__ForceBlockingStore(void)
{
    PASS_FAIL_TYPE status = FAIL;
    uint32 starting;
    uint32 size;
    MICRO_DECLARE_INTERRUPT_CONTEXT_LOCAL();

    // If called when in Low Power Mode NVData could not be initialized
    if (Mode__GetMode() != MODE_NORMAL)
    {
        NVDATA__INITIALIZEDEVICE();
    }

    if ((Next_Store_Address == 0) ||
        (Next_Store_Address == NVDATA_PAGE_SIZE))
    {
        NVData_Header.Signature_Counter++;


        // Interrupts shall be DISABLED while in the process of storing the non volatile data
        // As we calculate the crc of data before storing on the data flash memory so once the crc is caculated disabling interrupt would avoid data changes caused by the interrupt
        MICRO_SAVE_INTERRUPT_CONTEXT_LOCAL();
        SRTaskMonitor__Suspend();

        // Update Crc Data;
        NVData_Header.Appliance_Crc = Crc16__RangeProcess((uint8 *)DATAFLASH_APPLIANCE_START,0xFFFF, (uint16)(DATAFLASH_APPLIANCE_LIMIT - (uint32)DATAFLASH_APPLIANCE_START)); //lint !e926 !e923 Lint: 926 cast from pointer to pointer [MISRA 2004 Rule 11.4]
        NVData_Header.Statistics_Crc = Crc16__RangeProcess((uint8 *)DATAFLASH_STATISTICS_START,0xFFFF, (uint16)(DATAFLASH_STATISTICS_LIMIT - (uint32)DATAFLASH_STATISTICS_START)); //lint !e926 !e923 Lint: 926 cast from pointer to pointer [MISRA 2004 Rule 11.4]

        // To ensure Watchdog ha time to store the data.
        Micro__ServiceWatchdog();

        // Start to store Data
        starting =  Next_Store_Address;
        if (NVDATA__WRITE(starting,(uint8 *)&NVData_Header,sizeof(NVData_Header)) == NVDATA_PROCESS_OKAY) //lint !e928 Lint: 928 cast from pointer to pointer [MISRA 2004 Rule 11.4]
        {
            starting = UpdatePosition(starting,sizeof(NVData_Header));
            size  = DATAFLASH_APPLIANCE_LIMIT - (uint32)DATAFLASH_APPLIANCE_START; //lint !e923 Lint: 923 cast from pointer to unsigned long [Encompasses MISRA 2004 Rule 11.1], [MISRA 2004 Rule 11.3]
            if (NVDATA__WRITE(starting,DATAFLASH_APPLIANCE_START,size) == NVDATA_PROCESS_OKAY)
            {
                starting = UpdatePosition(starting,size);

                size  = DATAFLASH_STATISTICS_LIMIT - (uint32)DATAFLASH_STATISTICS_START; //lint !e923 Lint: 923 cast from pointer to unsigned long [Encompasses MISRA 2004 Rule 11.1], [MISRA 2004 Rule 11.3]
                if (NVDATA__WRITE(starting,DATAFLASH_STATISTICS_START,size) == NVDATA_PROCESS_OKAY)
                {
                    status = PASS;
                }
            }
        }

        Micro__ServiceWatchdog();

        // flip the page
        if (Next_Store_Address == 0)
        {
            Next_Store_Address = NVDATA_PAGE_SIZE;
        }
        else
        {
            Next_Store_Address = 0;
        }

        if (FlushPage(Next_Store_Address) != PASS)
        {
            status = FAIL;
        }

        Micro__ServiceWatchdog();

        // Enable interrupts -------------------------------------------------------
        SRTaskMonitor__Resume();
        MICRO_RESTORE_INTERRUPT_CONTEXT_LOCAL();
    }

    return (status);
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *	@brief 		This function stores all the segments into the Data Flash memory
 *	@details 	this function is been called automatically in the event of Brown Out condition or if the IAP is engagement is requested
 *				The application shall not call this function explicitly from their algorithm
 *
 *	@return
 *		@retval PASS(1)  - Stored successful
 *		@retval FAIL(0) - Failed to store
 */
PASS_FAIL_TYPE NVData__Store(void)
{
    MICRO_DECLARE_INTERRUPT_CONTEXT_LOCAL();
    uint32 starting;
    uint32 size;
    PASS_FAIL_TYPE success = FAIL;

    // If called when in Low Power Mode NVData could not be initialized
    if (Mode__GetMode() != MODE_NORMAL)
    {
        NVDATA__INITIALIZEDEVICE();
    }

    if ((Next_Store_Address == 0) ||
        (Next_Store_Address == NVDATA_PAGE_SIZE))
    {
        // Interrupts shall be DISABLED while in the process of storing the non volatile data
        // As we calculate the crc of data before storing on the data flash memory so once the crc is caculated disabling interrupt would avoid data changes caused by the interrupt
        MICRO_SAVE_INTERRUPT_CONTEXT_LOCAL();
        SRTaskMonitor__Suspend();

        // Update Crc Data;
        NVData_Header.Signature_Counter++;
        NVData_Header.Appliance_Crc = Crc16__RangeProcess((uint8 *)DATAFLASH_APPLIANCE_START,0xFFFF, (uint16)(DATAFLASH_APPLIANCE_LIMIT - (uint32)DATAFLASH_APPLIANCE_START));  //lint !e926 !e923 Lint: 926 cast from pointer to pointer [MISRA 2004 Rule 11.4]
        NVData_Header.Statistics_Crc = Crc16__RangeProcess((uint8 *)DATAFLASH_STATISTICS_START,0xFFFF, (uint16)(DATAFLASH_STATISTICS_LIMIT - (uint32)DATAFLASH_STATISTICS_START));  //lint !e926 !e923 Lint: 926 cast from pointer to pointer [MISRA 2004 Rule 11.4]

        // To ensure Watchdog has time to store the data.
        Micro__ServiceWatchdog();

        // Start to tore Data
        starting =  Next_Store_Address;
        if (NVDATA__WRITE(starting,(uint8 *)&NVData_Header,sizeof(NVData_Header)) == NVDATA_PROCESS_OKAY) //lint !e928 Lint: 928 cast from pointer to pointer [MISRA 2004 Rule 11.4]
        {
            starting = UpdatePosition(starting,sizeof(NVData_Header));
            size  = DATAFLASH_APPLIANCE_LIMIT - (uint32)DATAFLASH_APPLIANCE_START; //lint !e923 Lint: 923 cast from pointer to unsigned long [Encompasses MISRA 2004 Rule 11.1], [MISRA 2004 Rule 11.3]
            if (NVDATA__WRITE(starting,DATAFLASH_APPLIANCE_START,size) == NVDATA_PROCESS_OKAY)
            {
                starting = UpdatePosition(starting,size);

                size  = DATAFLASH_STATISTICS_LIMIT - (uint32)DATAFLASH_STATISTICS_START; //lint !e923 Lint: 923 cast from pointer to unsigned long [Encompasses MISRA 2004 Rule 11.1], [MISRA 2004 Rule 11.3]
                if (NVDATA__WRITE(starting,DATAFLASH_STATISTICS_START,size) == NVDATA_PROCESS_OKAY)
                {
                    success = PASS;
                }
            }
        }
        Micro__ServiceWatchdog();

        // flip the page
        if (Next_Store_Address == 0)
        {
            Next_Store_Address = NVDATA_PAGE_SIZE;
        }
        else
        {
            Next_Store_Address = 0;
        }

        // Enable interrupts -------------------------------------------------------
        SRTaskMonitor__Resume();
        MICRO_RESTORE_INTERRUPT_CONTEXT_LOCAL();
    }

    if (success == PASS)
    {
        NVData_Status.Bit.Appliance_Data_Recovered = NVDATA_RESTORE_OKAY;
        NVData_Status.Bit.Statistics_Data_Recovered = NVDATA_RESTORE_OKAY;

        EventStoreSuccess();
    }
    else
    {
        EventStoreFail();
    }

    return success;
}

#endif

#if (NVDATA_STORE_STATIC_FEATURE == ENABLED)

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This method stores the Static Data on DataFlash Page
 *
 * @return PASS_FAIL_TYPE
 *  @retval PASS(1) - Successfully able to store the static data on the DataFlash memory
 *  @retval FAIL(0) - Fail to store the static data on the DataFlash memory
 */
PASS_FAIL_TYPE NVData__StoreStaticData(void)
{
	MICRO_DECLARE_INTERRUPT_CONTEXT_LOCAL();
    uint16 size;
    PASS_FAIL_TYPE status= FAIL;

    if (FlushPage(NVDATA_STATIC_DATA_LOCATION) == PASS)
    {
        size = (uint16)(DATAFLASH_STATICDATA_LIMIT - (uint32)(&NVDATA_SECTION_STATIC_CFG$$Base));

        MICRO_SAVE_INTERRUPT_CONTEXT_LOCAL();
        SRTaskMonitor__Suspend();
        if (NVDATA__WRITE(NVDATA_STATIC_DATA_LOCATION,DATAFLASH_STATICDATA_START,size) == NVDATA_PROCESS_OKAY)
        {
            // Read back the stored data from DataFlash memory to the RAM memory
            // This read is mandatory as the external tool wants to read back the stored data to check the data integrity
            status = RestoreStaticData();
        }
        SRTaskMonitor__Resume();
        MICRO_RESTORE_INTERRUPT_CONTEXT_LOCAL();
    }

    return (status);
}
#endif

//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------
/**
 * @details This function does erasing the Data Flash memory
 * @param address
 *
 * @return PASS_FAIL_TYPE
 *  @retval PASS(1) - Successfully able to erase the Data Flash memory
 *  @retval FAIL(0) - Failed to erase the Data Flash memory
 */
static PASS_FAIL_TYPE FlushPage(uint32 address)
{
    PASS_FAIL_TYPE status = FAIL;
    uint8 operations = (uint8)(NVDATA_PAGE_SIZE/NVDATA_PAGE_FORMAT_SIZE);

    #if(NVDATA_STATIC_PAGE_SIZE != NVDATA_PAGE_SIZE)
        if (address >= NVDATA_STATIC_DATA_LOCATION)
        {
            operations = (uint8)(NVDATA_STATIC_PAGE_SIZE/NVDATA_PAGE_FORMAT_SIZE);
        }
    #endif

    while (operations > 0)
    {
        status = PASS;
        Micro__ServiceWatchdog();
        if (NVDATA__PAGEERASE(address) != NVDATA_PROCESS_OKAY)
        {
            status = FAIL;
            break;
        }
        operations--;
        address += NVDATA_PAGE_FORMAT_SIZE;
    }

    return (status);
}


#if (NVDATA_STORE_STATIC_FEATURE == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief - Restores the static Data from Data Flash memory to RAM memory
 *
 * @return PASS_FAIL_TYPE
 *  @retval PASS(1) - Successfully able to restored the static data
 *  @retval FAIL(0) - Failed to restored the static data
 */
static PASS_FAIL_TYPE RestoreStaticData(void)
{
    PASS_FAIL_TYPE status = FAIL;
    uint16 size = (uint16)(DATAFLASH_STATICDATA_LIMIT - (uint32)(&NVDATA_SECTION_STATIC_CFG$$Base));

    if (size != 0)
    {
        Micro__ServiceWatchdog();

        if (NVDATA__READ((uint8 *)DATAFLASH_STATICDATA_START, NVDATA_STATIC_DATA_LOCATION, size) == NVDATA_PROCESS_OKAY) //lint !e926 Lint: 926 cast from pointer to pointer [MISRA 2004 Rule 11.4]
        {
            status = PASS;
        }
    }

    return (status);
}
#endif


#if (NVDATA_STORE_APPLIANCE_AND_STATISTICS_FEATURE == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This function restores the Appliance segment and Statistics segment
 * @details While restoring the Appliance segment it also verifies
 *          if the same Firmware and SettingFile versions are used to restore the data or not
 *
 * @param address
 * @param address2
 */
static void Restore(uint32 address, uint32 address2)
{
    NVDATA_HEADER_TYPE header2;
    uint32 starting;
    uint32 starting2;
    uint32 size;
    uint16 crc;

    if ((address == 0) ||
        (address == NVDATA_PAGE_SIZE))
    {

        starting =  address;
        starting2 = address2;
        NVDATA__READ((uint8 *)&NVData_Header, starting, sizeof(NVData_Header)); //lint !e928 Lint: 928 cast from pointer to pointer [MISRA 2004 Rule 11.4]
        if (address2 != 0xFFFFFFFF)
        {
            NVDATA__READ((uint8 *)&header2, starting2, sizeof(NVData_Header)); //lint !e928 Lint: 928 cast from pointer to pointer [MISRA 2004 Rule 11.4]
        }

        /**
         * Restoring the Appliance segment
         */
        starting = UpdatePosition(starting,sizeof(NVData_Header));
        starting2 = UpdatePosition(starting2,sizeof(NVData_Header));

        size  = DATAFLASH_APPLIANCE_LIMIT - (uint32)DATAFLASH_APPLIANCE_START; //lint !e923 Lint: 923 cast from pointer to unsigned long [Encompasses MISRA 2004 Rule 11.1], [MISRA 2004 Rule 11.3]
        NVDATA__READ(DATAFLASH_APPLIANCE_START, starting, size);
        crc = Crc16__RangeProcess((uint8 *)DATAFLASH_APPLIANCE_START,0xFFFF, (uint16)(DATAFLASH_APPLIANCE_LIMIT - (uint32)DATAFLASH_APPLIANCE_START)); //lint !e926 !e923 Lint: 926 cast from pointer to pointer [MISRA 2004 Rule 11.4]

        if (crc == NVData_Header.Appliance_Crc)
        {
            // restored
            NVData_Status.Bit.Appliance_Data_Recovered = NVDATA_RESTORE_OKAY;
        }
        else
        {
            if (address2 != 0xFFFFFFFF)
            {
                NVDATA__READ(DATAFLASH_APPLIANCE_START, starting2, size);
                crc = Crc16__RangeProcess((uint8 *)DATAFLASH_APPLIANCE_START,0xFFFF, (uint16)(DATAFLASH_APPLIANCE_LIMIT - (uint32)DATAFLASH_APPLIANCE_START)); //lint !e926 !e923 Lint: 926 cast from pointer to pointer [MISRA 2004 Rule 11.4]

                if (crc == header2.Appliance_Crc)       //lint !e644 Lint: 644 Variable 'header2' (line 580) may not have been initialized
                {
                    // restored from backup
                    NVData_Status.Bit.Appliance_Data_Recovered = NVDATA_RESTORE_OKAY_BACKUP;
                    NVData_Header.Appliance_Crc = crc;
                }
            }
        }

        if (Force_Appliance_Segment_Corruption == APPLIANCE_SEGMENT_CORRUPT)
        {
            Force_Appliance_Segment_Corruption = APPLIANCE_SEGMENT_RESTORE;             // Immediately reset variable so appliance segment data is restored on next reset
            NVData_Status.Bit.Appliance_Data_Recovered = NVDATA_RESTORE_CORRUPTED;

            //Discard the restored data on the Ram memory
            memset(DATAFLASH_APPLIANCE_START, 0, size);
        }

        // Make sure that the stored appliance segment match with the Setting file and Firmware version used to store the data previously
        if (IsThisNewFirmwareOrSettingFile() != FALSE)
        {
            NVData_Status.Bit.Appliance_Data_Recovered = NVDATA_RESTORE_CORRUPTED;

            //Discard the restored data on the Ram memory
            memset(DATAFLASH_APPLIANCE_START, 0, size);

            //Store Setting file and Firmware version
            StoreNewFirmwareAndSettingFile();

        }


        /**
         * Restoring the Statistics segment
         */
        starting = UpdatePosition(starting,size);
        starting2 = UpdatePosition(starting2,size);

        size  = DATAFLASH_STATISTICS_LIMIT - (uint32)DATAFLASH_STATISTICS_START; //lint !e923 Lint: 923 cast from pointer to unsigned long [Encompasses MISRA 2004 Rule 11.1], [MISRA 2004 Rule 11.3]

        NVDATA__READ(DATAFLASH_STATISTICS_START, starting, size);
        crc = Crc16__RangeProcess((uint8 *)DATAFLASH_STATISTICS_START,0xFFFF, (uint16)(DATAFLASH_STATISTICS_LIMIT - (uint32)DATAFLASH_STATISTICS_START));  //lint !e926 !e923 Lint: 926 cast from pointer to pointer [MISRA 2004 Rule 11.4]

        if (crc == NVData_Header.Statistics_Crc)
        {
            // restored
            NVData_Status.Bit.Statistics_Data_Recovered = NVDATA_RESTORE_OKAY;
        }
        else
        {
            if (address2 != 0xFFFFFFFF)
            {
                NVDATA__READ(DATAFLASH_STATISTICS_START, starting2, size);
                crc = Crc16__RangeProcess((uint8 *)DATAFLASH_STATISTICS_START,0xFFFF, (uint16)(DATAFLASH_STATISTICS_LIMIT - (uint32)DATAFLASH_STATISTICS_START)); //lint !e926 !e923 Lint: 926 cast from pointer to pointer [MISRA 2004 Rule 11.4]

                if (crc == NVData_Header.Statistics_Crc)
                {
                    // restore from backup
                    NVData_Status.Bit.Statistics_Data_Recovered = NVDATA_RESTORE_OKAY_BACKUP;
                }
            }
        }
    }
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *
 * @param currentposition
 * @param size
 * @return
 */
static uint32 UpdatePosition(uint32 currentposition, uint32 size)
{
    uint32 position;
    uint32 aux;

    position = currentposition + size;

    aux = position / NVDATA_MEMORY_ALIGMENT;
    aux *= NVDATA_MEMORY_ALIGMENT;

    if (position > aux)
    {
        position = (aux + NVDATA_MEMORY_ALIGMENT);
    }
    return (position);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief - This function validates the stored appliance segment match with the Setting file and Firmware version
 *          used to store the data previously
 *
 * @return
 *  @retval TRUE(1) If the Firmware and setting file changed from the last reset
 *  @retval FALSE(0) If the Firmware and setting file did not changed from the last reset
 */
static BOOL_TYPE IsThisNewFirmwareOrSettingFile(void)
{
    BOOL_TYPE newfile = FALSE;

    //Validate the Firmware version
    if ((uint16)MICRO_FLASH_CRC !=  NVData_FirmwareCrc)
    {
        newfile = TRUE;
    }

    //Validate the Setting File version
    if (SF_CRC != NVData_SettingFileCrc)      //lint !e923  Lint: 923 cast from unsigned long to pointer [Encompasses MISRA 2004 Rule 11.1], [MISRA 2004 Rule 11.3]
    {
        newfile = TRUE;
    }

    return newfile;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief - This function stores the firmware and setting file version in the non volatile memory
 *
 */
static void StoreNewFirmwareAndSettingFile(void)
{
    NVData_FirmwareCrc = (uint16)MICRO_FLASH_CRC;
    NVData_SettingFileCrc = SF_CRC;        //lint !e923  Lint: 923 cast from unsigned long to pointer [Encompasses MISRA 2004 Rule 11.1], [MISRA 2004 Rule 11.3]
}

//=====================================================================================================================
//  --- Private State Machine Customization Functions -----------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This method is called during IDLE state to check if there is a brownout condition.
 */
static void CheckForBrownout(void)
{
    if (NVData_BrownOut == TRUE)
    {
        EventBrownout();
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This method is called from the STORED state to check if the power was restored.
 */
static void CheckForPower(void)
{
    if (NVData_BrownOut == FALSE)
    {
        // Force Reset
        Micro__ForceReset(MICRO_RESET_MODE_WARM);
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This method is called when the storing process fail in order to try to recover the flash by erasing both pages
 * and restart the string process.
 */
static void Recover(void)
{
    // Not Consistent
    FlushPage(0);
    // To ensure Watchdog ha time to store the data.
    Micro__ServiceWatchdog();
    FlushPage(Next_Store_Address);
    // To ensure Watchdog ha time to store the data.
    Micro__ServiceWatchdog();
    Next_Store_Address = 0;
    EventRecovered();
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This method is called to perform the store process, where it calculates CRC and store the data.
 *
 * @return PASS_FAIL_TYPE
 *  @retval PASS(1) - Successfully able to store the data
 *  @retval FAIL(0) - Failed to store the data
 */
static void StoreSegments(void)
{
	NVData__Store();
}

//=====================================================================================================================
//=== StateEngineCrank (v2.0) Auto-Generated Functions for Nvdata State Machine
//=====================================================================================================================
// !! StateEngineCrank cannot update this code if you change the header !!


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Ev Brownout Event for the Nvdata state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventBrownout(void)
{
    switch (Nvdata_State)
    {
        case STATE_NVDATA_IDLE:
            Nvdata_State = STATE_NVDATA_STORING;
            break;

        default:
            // Event is ignored for all other values of Nvdata_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Ev Recovered Event for the Nvdata state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventRecovered(void)
{
    switch (Nvdata_State)
    {
        case STATE_NVDATA_ERROR:
            Nvdata_State = STATE_NVDATA_STORING;
            break;

        default:
            // Event is ignored for all other values of Nvdata_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Ev Store Fail Event for the Nvdata state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventStoreFail(void)
{
    switch (Nvdata_State)
    {
        case STATE_NVDATA_STORING:
            Nvdata_State = STATE_NVDATA_ERROR;
            Recover();                              // STATE_NVDATA_ERROR entry function.
            break;

        default:
            // Event is ignored for all other values of Nvdata_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Ev Store Success Event for the Nvdata state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventStoreSuccess(void)
{
    switch (Nvdata_State)
    {
        case STATE_NVDATA_STORING:
            Nvdata_State = STATE_NVDATA_STORED;
            break;

        default:
            // Event is ignored for all other values of Nvdata_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * The main execution function for the Nvdata state machine.
 * This function should be called periodically while the state machine is running.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void NvdataExecute(void)
{
    switch (Nvdata_State)
    {
        case STATE_NVDATA_IDLE:
            CheckForBrownout();                     // STATE_NVDATA_IDLE do function.
            break;

        case STATE_NVDATA_STORING:
            StoreSegments();                        // STATE_NVDATA_STORING do function.
            break;

        case STATE_NVDATA_STORED:
            CheckForPower();                        // STATE_NVDATA_STORED do function.
            break;

        default:
            // There is nothing to do for all other values of Nvdata_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * The initialization function for the Nvdata state machine.
 * This function resets the state machine to the initial state.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void NvdataInitialize(void)
{
    Nvdata_State = STATE_NVDATA_IDLE;
}


// !! StateEngineCrank cannot update this code if you change the footer !!
// End of StateEngineCrank Auto-Generated Code.

#endif



