/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
/*
@startuml
        Title OWIOneShot State Machine

        [*] --> INITIALIZE

        INITIALIZE : entry / ReadProcessParameters()
        INITIALIZE --> WAIT_TIMEOT : OWI_OneShot

        WAIT_TIMEOT : do / CheckTimeout()
        WAIT_TIMEOT --> SAVE_OWI_VALUES : TimeoutExpired

		SAVE_OWI_VALUES : do / SaveOWIValues()
		SAVE_OWI_VALUES --> EXIT : CheckConditionsToExitTrue

        EXIT: do / returnTRUE()
@enduml
*/
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "C_Extensions.h"

#include "DishAuxVar.h"
#include "Hbl.h"
#include "Micro.h"
#include "OWICalibrationProcess.h"
#include "OWIOneShot.h" 
#include "Selector.h"
#include "Variable.h"

//=====================================================================================================================
//=== StateEngineCrank (v2.8) Auto-Generated Definitions for OWI One Shot State Machine
//=====================================================================================================================
// !! StateEngineCrank cannot update this code if you change the header !!


//! Unique names used to identify states of the OWI One Shot state machine.
typedef enum OWI_ONE_SHOT_STATE_ENUM
{
    STATE_OWI_ONE_SHOT_NONE            = 0,

    STATE_OWI_ONE_SHOT_INITIALIZE      = 1,         //!< (initial_state)
    STATE_OWI_ONE_SHOT_WAIT_TIMEOT     = 2,
    STATE_OWI_ONE_SHOT_SAVE_OWI_VALUES = 3,
    STATE_OWI_ONE_SHOT_EXIT            = 4,

    STATE_OWI_ONE_SHOT_END             = 5
} OWI_ONE_SHOT_STATE_TYPE;

//! The state variable for the OWI One Shot state machine.
//! State machines with a history pseudostate may write to this variable during initialization.
//! Other state machines must only write to this variable through auto-generated functions.
static OWI_ONE_SHOT_STATE_TYPE OWI_One_Shot_State;

// -- Private Function Prototypes used by the state machine for customization functions --
static void CheckTimeout(void);
static void ReadProcessParameters(void);
static void ReturnTRUE(void);
static void SaveOWIValues(void);

// -- Private Function Prototypes used by the state machine for standard state machine functions --
static void EventCheckConditionsToExitTrue(void);
static void EventOWIOneShot(void);
static void EventTimeoutExpired(void);
static void OWIOneShotExecute(void);
static void OWIOneShotInitialize(void);
static void OWIOneShotTerminate(void);

// !! StateEngineCrank cannot update this code if you change the footer !!
// End of StateEngineCrank Auto-Generated Code.


//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------


//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
static BOOL_TYPE OWIOneShot_Ready_To_Exit;
static PROCESS_CONTROL_TYPE* Control;
static SYSTEMTIMER_NV_TIMER_TYPE NV_Timer_Handle_OWI_One_Shot_Save_Timeout;
static BOOL_TYPE OWIOneShot_Process_Initialized;

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_OWI_ONE_SHOT

//! The types of OWI variations that are available.
typedef enum OWI_OPTION_ENUM
{
	OWI_CALIBRATION,                          //!< F1=0, F0=0
	OWI_ONE_SHOT_READING,        		//!< F1=0, F0=1
	OWI_OPTION_COUNT
} OWI_OPTION_TYPE;

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_OWI_ONE_SHOT_LOG_MESSAGE_ID_ENUM
{
    ERROR_PROCESS_CONTROL       = 1,
    ERROR_LOADING_PARAMETERS
} MODULE_OWI_ONE_SHOT_LOG_MESSAGE_ID_TYPE;

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
static void ActivateOWI(void);

//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

PROCESS_RESULT_TYPE OWIOneShot__Process(PROCESS_CONTROL_TYPE* control)
{
    PROCESS_RESULT_TYPE result;
    OWI_OPTION_TYPE option = (OWI_OPTION_TYPE)control->F1_F0_Flags;
    if ((control == NULL ) ||
        (control->Compartment >= APPLIANCE_MAX_COMPARTMENTS) ||
        (option >= OWI_OPTION_COUNT))
    {
        LOG_ADD_EXCEPTION(ERROR_PROCESS_CONTROL, (control != NULL));
    }
    else
    {
       Control = control;
        if (((uint8)control->Step_Initializing == (uint8)TRUE) || ((uint8)control->Resume_From_Reset == (uint8)TRUE) ||
        	(((uint8)control->Resume_From_Pause == (uint8)TRUE) && (OWIOneShot_Process_Initialized == FALSE)))
        {
            // Initialize this instance of the OWI ONe SHOT process.
    		OWIOneShot_Ready_To_Exit = FALSE;
        	OWIOneShotInitialize();
        }
        else
        {
        	OWIOneShotExecute();
        }

    }//*/

    result = ((uint8)OWIOneShot_Ready_To_Exit == (uint8)TRUE)? PROCESS_COMPLETE : PROCESS_BUSY;
    return result;
}


void OWIOneShot__Initialize(void)
{
	OWIOneShot_Process_Initialized = FALSE;

	SystemTimers__NVResetTimer(&NV_Timer_Handle_OWI_One_Shot_Save_Timeout);
}


void OWIOneShot__PauseTimer(void)
{
	(void)SystemTimers__NVPauseTimer(&NV_Timer_Handle_OWI_One_Shot_Save_Timeout);
}


void OWIOneShot__ResumeTimer(void)
{
	(void)SystemTimers__NVResumeTimer(&NV_Timer_Handle_OWI_One_Shot_Save_Timeout);
}


void OWIOneShot__CycleResumeStart(uint8 compartment,uint8 subcycle_id)
{
	if (Selector__GetCycleNameId(0, compartment , subcycle_id) == CYCLE_NAME_SPECIFIC_CYCLE_RESUME)
	{
		(void)SystemTimers__NVPauseTimer(&NV_Timer_Handle_OWI_One_Shot_Save_Timeout);
	}

}


void OWIOneShot__CycleResumeEnd(uint8 compartment,uint8 subcycle_id)
{
	if (Selector__GetCycleNameId(0, compartment , subcycle_id) == CYCLE_NAME_SPECIFIC_CYCLE_RESUME)
	{
		(void)SystemTimers__NVResumeTimer(&NV_Timer_Handle_OWI_One_Shot_Save_Timeout);
	}
}




//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void ActivateOWI(void)
{
	sint32 duty_cycle;

	(void)Variable__GetValue(VARIABLE_OWI_CALIBRATION_DRIVE_DUTY_CYCLE,0,(sint32*)((void*)(&duty_cycle)));

	(void)Hbl__SetLoadRequestByLoadID(HBL_LOAD_OWI, HBL_PRIORITY_APPLICATION_HI, (uint8 *) &duty_cycle);
}


//=====================================================================================================================
//  --- Private State Machine Customization Functions -----------------------------------------------------------------
//=====================================================================================================================


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void CheckTimeout(void)
{
	ActivateOWI();

	if (SystemTimers__NVCheckTimer(&NV_Timer_Handle_OWI_One_Shot_Save_Timeout) == SYSTEMTIMERS_STATE_DONE)
	{
		EventTimeoutExpired();
	}
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void ReadProcessParameters(void)
{
	SETTINGFILE_LOADER_TYPE loader;
	SF_DATA_TYPE* OWI_Parameters;
	uint8 save_timeout;

	save_timeout =  0;

	// Get the OWI parameters from the setting file machine structure.
	if ( FAIL == SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS,
										  DISPL_OWI_CALIBRATION,
										  &loader) )
	{
		LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, Control->Data_Field_Index);
	}
	else
	{
		// Read the setting file data into local variables for convenience.
		OWI_Parameters = (SF_DATA_TYPE*)(void*)loader.Data;
		save_timeout = OWI_Parameters->OWI_One_Shot_Read_Timeout;

		OWIOneShot_Process_Initialized = TRUE;
	}

	if (save_timeout == 0U)
	{
		// if the parameter in the file setting is 0, I still expect 100ms to read
		(void)SystemTimers__NVSetTimerMS(&NV_Timer_Handle_OWI_One_Shot_Save_Timeout, 100 ,SYSTEMTIMERS_TYPE_DOWN_COUNTER);
	}
	else
	{
		(void)SystemTimers__NVSetTimerMS(&NV_Timer_Handle_OWI_One_Shot_Save_Timeout, (uint32)save_timeout*(uint32)1000 ,SYSTEMTIMERS_TYPE_DOWN_COUNTER);
	}

	EventOWIOneShot();
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void ReturnTRUE(void)
{
	OWIOneShot_Ready_To_Exit = TRUE;
	OWIOneShotTerminate();
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void SaveOWIValues(void)
{
	// OWI_Analog
	OWI_Analog = *(uint16 PACKED *)Hbl__GetGIDataByIndex(Hbl__GetGIIndexByGIID(HBL_GI_TURBIDITY_SENSOR_OWI));

	Soil_Measure_6 = Soil_Measure_5;
	Soil_Measure_5 = Soil_Measure_4;
	Soil_Measure_4 = Soil_Measure_3;
	Soil_Measure_3 = Soil_Measure_2;
	Soil_Measure_2 = Soil_Measure_Recent;
	Soil_Measure_Recent = OWI_Analog;

	EventCheckConditionsToExitTrue();
}


//=====================================================================================================================
//=== StateEngineCrank (v2.8) Auto-Generated Functions for OWI One Shot State Machine
//=====================================================================================================================
// !! StateEngineCrank cannot update this code if you change the header !!


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Check Conditions To Exit True Event for the OWI One Shot state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventCheckConditionsToExitTrue(void)
{
    switch (OWI_One_Shot_State)
    {
        case STATE_OWI_ONE_SHOT_SAVE_OWI_VALUES:
            OWI_One_Shot_State = STATE_OWI_ONE_SHOT_EXIT;
            break;

        default:
            // Event is ignored for all other values of OWI_One_Shot_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the OWI One Shot Event for the OWI One Shot state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventOWIOneShot(void)
{
    switch (OWI_One_Shot_State)
    {
        case STATE_OWI_ONE_SHOT_INITIALIZE:
            OWI_One_Shot_State = STATE_OWI_ONE_SHOT_WAIT_TIMEOT;
            break;

        default:
            // Event is ignored for all other values of OWI_One_Shot_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Timeout Expired Event for the OWI One Shot state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventTimeoutExpired(void)
{
    switch (OWI_One_Shot_State)
    {
        case STATE_OWI_ONE_SHOT_WAIT_TIMEOT:
            OWI_One_Shot_State = STATE_OWI_ONE_SHOT_SAVE_OWI_VALUES;
            break;

        default:
            // Event is ignored for all other values of OWI_One_Shot_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * The main execution function for the OWI One Shot state machine.
 * This function should be called periodically while the state machine is running.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void OWIOneShotExecute(void)
{
    switch(OWI_One_Shot_State)
    {
        case STATE_OWI_ONE_SHOT_WAIT_TIMEOT:
            CheckTimeout();                         // Do function.
            break;

        case STATE_OWI_ONE_SHOT_SAVE_OWI_VALUES:
            SaveOWIValues();                        // Do function.
            break;

        case STATE_OWI_ONE_SHOT_EXIT:
            ReturnTRUE();                           // Do function.
            break;

        default:
            // There is nothing to do for all other values of OWI_One_Shot_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * The initialization function for the OWI One Shot state machine.
 * This function resets the state machine to the initial state and executes the initial state's
 * entry function.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void OWIOneShotInitialize(void)
{
    OWI_One_Shot_State = STATE_OWI_ONE_SHOT_INITIALIZE;
    ReadProcessParameters();                        // Entry Function.
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * The termination function for the OWI One Shot state machine.
 * This function disables the state machine. Calls to StateMachineExecute() will have no effect.
 * The StateMachineInitialize() function must be called again to restart the state machine.
 * If the current state has an exit function, it will be called.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void OWIOneShotTerminate(void)
{
    // None of the states have an Exit function.
    OWI_One_Shot_State = STATE_OWI_ONE_SHOT_NONE;
}


// !! StateEngineCrank cannot update this code if you change the footer !!
// End of StateEngineCrank Auto-Generated Code.
