/*
 * DiverterFaultMonitor.h
 *
 *  Created on: 28.08.2018
 *      Author: WAZNYP
 */

#ifndef SOURCE_CATEGORY_APPLICATION_APPLICATIONDISH_MONITORS_DIVERTERFAULTMONITOR_DIVERTERFAULTMONITOR_H_
#define SOURCE_CATEGORY_APPLICATION_APPLICATIONDISH_MONITORS_DIVERTERFAULTMONITOR_DIVERTERFAULTMONITOR_H_

void DiverterFaultMonitor__Initialize(void);
void DiverterFaultMonitor__Execution(void);

#endif /* SOURCE_CATEGORY_APPLICATION_APPLICATIONDISH_MONITORS_DIVERTERFAULTMONITOR_DIVERTERFAULTMONITOR_H_ */
