/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------

//-------------------------------------- Include Files ----------------------------------------------------------------
// -- This Module --
#include "RinseAidDispense.h"
#include "RinseAid.h"
#include "TridgeDetergent.h"
#include "C_Extensions.h"

#include "Hbl.h"
#include "Log.h"
#include "Micro.h"
#include "NVData.h"
#include "SettingFile.h"
#include <string.h>
#include "SystemConfig.h"


//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_RINSE_AID_DISPENSE


//! The types of RINSE_AID_DISPENSE variations that are available.
typedef enum RINSE_AID_DISPENSE_OPTION_ENUM
{
	RINSE_AID_DISPENSE,                          //!< F1=0, F0=0
	TRIDGE_DETERGENT_DISPENSE,
	RINSE_AID_DISPENSE_OPTION_COUNT
} RINSE_AID_DISPENSE_OPTION_TYPE;

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_RINSE_AID_DISPENSE_LOG_MESSAGE_ID_ENUM
{
	PROCESS_CONTROL_IS_NULL = 1,
	PROCESS_CONTROL_PARAMS_EXCEED_LIMITS,
} MODULE_RINSE_AID_DISPENSE_LOG_MESSAGE_ID_TYPE;


//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================
void RinseAidDispense__Initialize(void)
{
	RinseAid__Initialize();
	TridgeDetergent__Initialize();
}

PROCESS_RESULT_TYPE RinseAidDispense__Process(PROCESS_CONTROL_TYPE* control)
{
    PROCESS_RESULT_TYPE result = PROCESS_COMPLETE;

    if (control == NULL)
    {
        LOG_ADD_EXCEPTION(PROCESS_CONTROL_IS_NULL, 0);
    }
    else if ((control->Compartment >= APPLIANCE_MAX_COMPARTMENTS) ||
    		 (control->F1_F0_Flags >= (uint8)RINSE_AID_DISPENSE_OPTION_COUNT))
    {
        LOG_ADD_EXCEPTION(PROCESS_CONTROL_PARAMS_EXCEED_LIMITS, 0);
    }
    else
    {
		switch (control->F1_F0_Flags)
		{
			case RINSE_AID_DISPENSE:
			 	if (control->Process_Instance < RINSE_AID_MAX_INSTANCES)
			 	{
			 		result = RinseAid__Manager(control);
			 	}
			 	else
			 	{
			        LOG_ADD_EXCEPTION(PROCESS_CONTROL_PARAMS_EXCEED_LIMITS, 1);
			 	}
				break;

			case TRIDGE_DETERGENT_DISPENSE:
			 	if (control->Process_Instance < TRIDGE_DETERGENT_MAX_INSTANCES)
			 	{
			 		result = TridgeDetergent__Manager(control);
			 	}
			 	else
			 	{
			        LOG_ADD_EXCEPTION(PROCESS_CONTROL_PARAMS_EXCEED_LIMITS, 2);
			 	}
				break;

			default:
				// No other valid options
				break;
		}

    }

    return result;
}


//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

