/**
 *  @file       CrossLoads.c
 *
 *  @brief      Hbl sub module to handle CrossLoads feature
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2018-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "C_Extensions.h"
#include "CrossLoads.h"
#include "SRException.h"
#include "SRData.h"
#include "Crc8.h"
#include "Mode.h"
#include "SettingFile.h"
#include "Log.h"
#include "string.h"

// This module is a Hbl sub-module, and including Hbl_prv.h makes transition easier and backward compatible
#include "Hbl_prv.h"

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------

#define CRC8_INITIAL_SEED                               0xFF

//------- Log Module messages ---------------------------------------
//! A list of log message IDs that are generated by this module.
typedef enum
{
    NUM_OF_SETTING_CROSSLOADS_EXCEEDEDS_MAX_NUM,                    //!< data: the number of Cross Load defined in the GESE setting
    INVALID_CROSSLOAD_HANDLER,                                      //!< data: the number of Cross Load defined in the GESE setting
} MODULE_CROSSLOADS_LOG_MESSAGE_ID_TYPE;

#define MODULE_NAME MODULE_CROSSLOADS      //!< The name of this module for use by the Log module.


//------- Crossload Management ---------------------------------------
typedef enum
{
    CROSSLOAD_TYPE_MASTER_RELAY,        //!< CROSSLOAD_TYPE_MASTER_RELAY
    CROSSLOAD_TYPE_SWITCH_RELAY,        //!< CROSSLOAD_TYPE_SWITCH_RELAY
    CROSSLOAD_TYPE_REVERSE_SWITCH_RELAY,//!< CROSSLOAD_TYPE_REVERSE_SWITCH_RELAY
    CROSSLOAD_TYPE_TRANSITION_RELAY,    //!< CROSSLOAD_TYPE_TRANSITION_RELAY
} CROSSLOAD_STATE_MACHINE_SELECTOR_TYPE;

typedef enum
{
    CROSSLOAD_STEADY_STATE,
    CROSSLOAD_ON_TRANSITION,
    CROSSLOAD_OFF_TRANSITION,
    CROSSLOAD_FORCED_STATE
} CROSSLOAD_STATE_TYPE;

typedef struct {
    uint8 On;
    uint8 Off;
} CROSSLOAD_LOAD_POSITION_TYPE;

/**
 * Struct to cast the parameters for the Cross Load.
 */
PACKED typedef struct
{
    uint8                                   On_Delay     : 6;
    CROSSLOAD_STATE_MACHINE_SELECTOR_TYPE   Type         : 2;
    uint8                                   Off_Delay    : 6;
    uint8                                   Unused       : 2;
    CROSSLOAD_LOAD_POSITION_TYPE            Load_Position [];
} CROSSLOAD_PARAMETERS_TYPE;

/**
 * HBL Cross Load Config Struct
 */
PACKED typedef struct
{
    CROSSLOAD_PARAMETERS_TYPE   *Parameter_Ptr;
    uint8                       Crossload_Position;
    uint8                       Number_Of_Couples;
} HBL_CROSS_LOAD_TYPE;

PACKED typedef struct
{
    uint8                                   Requested;
    uint8                                   Processed;
    uint8                                   Timer;
    CROSSLOAD_STATE_TYPE                    Generic_State;
    CROSSLOAD_STATE_TYPE                    Previous_State;
} CROSSLOAD_DATA_TYPE;

typedef void (* CROSSLOAD_STATE_MACHINE_FUNCTION_POINTER_TYPE)(HBL_CROSS_LOAD_TYPE *, CROSSLOAD_DATA_TYPE*, uint8 *);

#if (HBL_CROSS_LOADS_FEATURE == ENABLED)

static uint8 Crossloads_Num;
static HBL_CROSS_LOAD_TYPE Crossload_Cfg[HBL_XLOAD_NUM_CROSSLOAD];
static CROSSLOAD_DATA_TYPE Crossload_Data[HBL_XLOAD_NUM_CROSSLOAD];
static uint8 Crossload_Crc[HBL_XLOAD_NUM_CROSSLOAD];
static uint8 N_Crossloads_Num;

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------

static BOOL_TYPE IsLoadStatusOnTransition(uint8 load_index);
static uint8 GetCrossLoadIndex(uint8 load_index);
static BOOL_TYPE IsCrossLoadTransition(uint8 load_index, BOOL_TYPE check_previous);
static void ResetCrossLoadTransition(uint8 cross_load_index);
static uint8 GetLoadPriority(uint8 load_index, uint8 *hbl_prio_ptr);
#if (HBL_XLOAD_MASTER_RELAY_SUPPORT == ENABLED)
static void MasterLoadHandler(HBL_CROSS_LOAD_TYPE *cfg_ptr, CROSSLOAD_DATA_TYPE * data_ptr, uint8 *hbl_prio_ptr);
#endif
#if (HBL_XLOAD_SWITCH_RELAY_SUPPORT == ENABLED)
static void SwitchLoadHandler(HBL_CROSS_LOAD_TYPE *cfg_ptr, CROSSLOAD_DATA_TYPE * data_ptr, uint8 *hbl_prio_ptr);
#endif
#if (HBL_XLOAD_REVERSE_SWITCH_RELAY_SUPPORT == ENABLED)
static void ReverseLoadRelayHandler(HBL_CROSS_LOAD_TYPE *cfg_ptr, CROSSLOAD_DATA_TYPE * data_ptr, uint8 *hbl_prio_ptr);
#endif
#if (HBL_XLOAD_TRANSITION_RELAY_SUPPORT == ENABLED)
static void TransitionLoadHandler(HBL_CROSS_LOAD_TYPE *cfg_ptr, CROSSLOAD_DATA_TYPE * data_ptr, uint8 *hbl_prio_ptr);
#endif

static CROSSLOAD_STATE_MACHINE_FUNCTION_POINTER_TYPE const CrossloadHandlers[4] =
{
    #if (HBL_XLOAD_MASTER_RELAY_SUPPORT == ENABLED)
        &MasterLoadHandler,
    #else
        (CROSSLOAD_STATE_MACHINE_FUNCTION_POINTER_TYPE) NULL,
    #endif
    #if (HBL_XLOAD_SWITCH_RELAY_SUPPORT == ENABLED)
        &SwitchLoadHandler,
    #else
        (CROSSLOAD_STATE_MACHINE_FUNCTION_POINTER_TYPE) NULL,
    #endif
    #if (HBL_XLOAD_REVERSE_SWITCH_RELAY_SUPPORT == ENABLED)
        &ReverseLoadRelayHandler,
    #else
        (CROSSLOAD_STATE_MACHINE_FUNCTION_POINTER_TYPE) NULL,
    #endif
    #if (HBL_XLOAD_TRANSITION_RELAY_SUPPORT == ENABLED)
        &TransitionLoadHandler,
    #else
        (CROSSLOAD_STATE_MACHINE_FUNCTION_POINTER_TYPE) NULL,
    #endif
};

#endif


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This method loads the Hbl Configuration for Cross Loads from the Setting File.
 */
void CrossLoads__Initialize(void)
{
#if (HBL_CROSS_LOADS_FEATURE == ENABLED)
    uint8 index;
    uint8 *ptr;
    SETTINGFILE_LOADER_TYPE cross_load_table;
    HBL_CROSS_LOAD_TYPE *cfg_ptr;

    memset(Crossload_Data , 0 , sizeof(Crossload_Data));

    SettingFile__BasicLoader(SF_PTR_ACU_IO_CONFIG, SF_DISPL_CROSS_LOADS, &cross_load_table);

    index = (cross_load_table.Length / 2);

    if (index > HBL_XLOAD_NUM_CROSSLOAD)
    {
        LOG_ADD_EXCEPTION(NUM_OF_SETTING_CROSSLOADS_EXCEEDEDS_MAX_NUM, Crossloads_Num);
        Mode__SetModeExtended(MODE_NORMAL, SUBMODE_NORMAL_ERROR);
        index = HBL_XLOAD_NUM_CROSSLOAD;
    }
    SRData__UpdateByte(&Crossloads_Num, &N_Crossloads_Num, index);

    for (index = 0 ; index < HBL_XLOAD_NUM_CROSSLOAD ; index++)
    {
        SETTINGFILE_LOADER_TYPE param_table;
        cfg_ptr = &Crossload_Cfg[index];
        ptr = &cross_load_table.Data[2*index];

        cfg_ptr->Crossload_Position = HBL_LOAD_INVALID;
        cfg_ptr->Parameter_Ptr = NULL;
        cfg_ptr->Number_Of_Couples = 0;

        if (index < Crossloads_Num)
        {
            //Getting the CROSS LOAD parameters from the Settings File.
            if ((ptr[0] < Hbl__GetNumLoads()) &&
                (SettingFile__BasicLoader(SF_PTR_ACU_IO_DEVICE, ptr[1], &param_table) == PASS))
            {
                CROSSLOAD_PARAMETERS_TYPE *new_param_ptr = ((CROSSLOAD_PARAMETERS_TYPE*)(param_table.Data)); //lint !e927 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4];
                if (CrossloadHandlers[new_param_ptr->Type] != (CROSSLOAD_STATE_MACHINE_FUNCTION_POINTER_TYPE) NULL)
                {
                    cfg_ptr->Crossload_Position = ptr[0];
                    cfg_ptr->Parameter_Ptr = new_param_ptr;
                    cfg_ptr->Number_Of_Couples = (param_table.Length - 2) / 2;
                }
            }
            if (cfg_ptr->Crossload_Position == HBL_LOAD_INVALID)
            {
                LOG_ADD_EXCEPTION(INVALID_CROSSLOAD_HANDLER, index);
                Mode__SetModeExtended(MODE_NORMAL, SUBMODE_NORMAL_ERROR);
            }
        }

        Crossload_Crc[index] = Crc8(CRC8_INITIAL_SEED,(uint8 *)&Crossload_Cfg[index],sizeof(HBL_CROSS_LOAD_TYPE)); //lint !e928 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
    }
#endif
}


//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief - This function is the core handler of the Crossload and it should be called every 100ms
 * @param load
 * @return
 */
void CrossLoads__Process(uint8 *hbl_prio_ptr)
{
#if (HBL_CROSS_LOADS_FEATURE == ENABLED)
    CROSSLOAD_STATE_MACHINE_FUNCTION_POINTER_TYPE handler_ptr;
    HBL_CROSS_LOAD_TYPE *cfg_ptr;
    CROSSLOAD_DATA_TYPE *data_ptr;
    uint8 index;
    uint8 cur_prio;

    if (SRDATA_OK == (SRData__CheckByte(&Crossloads_Num, &N_Crossloads_Num)))
    {
        for (index = 0 ; index < Crossloads_Num ; index++)
        {
            cfg_ptr = &Crossload_Cfg[index];

            if (Crossload_Crc[index] == Crc8(CRC8_INITIAL_SEED,(uint8 *) cfg_ptr, sizeof(Crossload_Cfg[0]))) //lint !e928 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
            {
                data_ptr = &Crossload_Data[index];
                handler_ptr = CrossloadHandlers[cfg_ptr->Parameter_Ptr->Type];

                if ((cfg_ptr->Crossload_Position < Hbl__GetNumLoads()) &&
                    (handler_ptr != (CROSSLOAD_STATE_MACHINE_FUNCTION_POINTER_TYPE) NULL))
                {
                    data_ptr->Requested = *(uint8*)Hbl__GetRequestedLoad(cfg_ptr->Crossload_Position);
                    data_ptr->Processed = *(uint8*)Hbl__GetProcessedLoad(cfg_ptr->Crossload_Position);

                    // Call Cross Load Handler defined
                    (*handler_ptr)(cfg_ptr, data_ptr, hbl_prio_ptr);

                    cur_prio = GetLoadPriority(cfg_ptr->Crossload_Position, hbl_prio_ptr);
                    Hbl__SetLoadRequestByIndex(cfg_ptr->Crossload_Position,
                        (HBL_PRIORITY_TYPE)cur_prio,
                        &Crossload_Data[index].Processed);
                }
            }
            else
            {
                SRException__Queue(SREXCEPTION_HBL_DATA_NOT_CONSISTENT,0xFE,index);
            }
        }

        for (index = 0 ; index < Crossloads_Num ; index++)
        {
            cfg_ptr = &Crossload_Cfg[index];
            if (cfg_ptr->Crossload_Position < Hbl__GetNumLoads())
            {
                data_ptr = &Crossload_Data[index];
                data_ptr->Previous_State = data_ptr->Generic_State;
            }
        }

    }
#endif
}

//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

#if (HBL_CROSS_LOADS_FEATURE == ENABLED)

#if (HBL_XLOAD_MASTER_RELAY_SUPPORT == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief - This function manages the Crossloads of type Master Load
 *
 * @param CROSSLOAD_DATA_TYPE * , CROSSLOAD_PARAMETERS_TYPE *
 */
static void MasterLoadHandler(HBL_CROSS_LOAD_TYPE *cfg_ptr, CROSSLOAD_DATA_TYPE * data_ptr, uint8 *hbl_prio_ptr)
{
    CROSSLOAD_PARAMETERS_TYPE *param_ptr = cfg_ptr->Parameter_Ptr;
    uint8 my_prio = GetLoadPriority(cfg_ptr->Crossload_Position, hbl_prio_ptr);
    uint8 load_check_index;
    uint8 load_clear_index;
    uint8 new_processed;
    uint8 position_index;

    switch (data_ptr->Generic_State)
    {
        case CROSSLOAD_STEADY_STATE:
        {
            uint8 *load_process_ptr;
            uint8 load_request_len;
            uint8 load_check_prio;
            uint8 max_check_prio = 0;
            BOOL_TYPE full_delay = FALSE;

            for(position_index = 0 ; position_index < cfg_ptr->Number_Of_Couples ; position_index++)
            {
                if (data_ptr->Processed == OFF)
                {
                    load_clear_index = param_ptr->Load_Position[position_index].On;
                    load_check_index = param_ptr->Load_Position[position_index].Off;
                }
                else
                {
                    load_clear_index = param_ptr->Load_Position[position_index].Off;
                    load_check_index = param_ptr->Load_Position[position_index].On;
                }

                // Perform clear only if Master load priority is higher than load to clear
                // otherwise load should override that behavior
                // Clear here only when no transition occur
                if ((data_ptr->Processed == data_ptr->Requested) &&
                    (PASS == Hbl__SetLoadRequestByIndex(load_clear_index, (HBL_PRIORITY_TYPE)my_prio,
                    (uint8 *)Hbl__GetFlushBuffer())))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                {
                    ResetCrossLoadTransition(load_clear_index);
                }

                load_check_prio = GetLoadPriority(load_check_index, hbl_prio_ptr);

                if (my_prio >= load_check_prio)
                {
                    load_process_ptr = Hbl__GetProcessedLoad(load_check_index);
                    if (load_process_ptr != NULL)
                    {
                        load_request_len = Hbl__GetLoadDataSize(load_check_index);
                        if (memcmp(load_process_ptr, Hbl__GetFlushBuffer(), load_request_len) != 0)
                        {
                            full_delay = TRUE;
                        }

                        if (load_check_prio > max_check_prio)
                        {
                            max_check_prio = load_check_prio;
                        }
                    }
                }
            }

            // Perform Master load transition only if priorty is higher than maximum of other loads *
            if ((my_prio >= max_check_prio) &&
                (data_ptr->Processed != data_ptr->Requested))
            {
                new_processed = data_ptr->Processed;
                data_ptr->Generic_State = (data_ptr->Requested == OFF) ? CROSSLOAD_OFF_TRANSITION :
                    CROSSLOAD_ON_TRANSITION;

                if (full_delay)
                {
                    data_ptr->Timer = param_ptr->On_Delay + param_ptr->Off_Delay;
                    if(data_ptr->Timer == 0)
                    {
                        new_processed = data_ptr->Requested;
                    }
                }
                else
                {
                    data_ptr->Timer = param_ptr->On_Delay;
                    new_processed = data_ptr->Requested;
                }

                for(position_index = 0 ; position_index < cfg_ptr->Number_Of_Couples ; position_index++)
                {
                    if (data_ptr->Processed == OFF)
                    {
                        load_clear_index = param_ptr->Load_Position[position_index].Off;
                        load_check_index = param_ptr->Load_Position[position_index].On;
                    }
                    else
                    {
                        load_clear_index = param_ptr->Load_Position[position_index].On;
                        load_check_index = param_ptr->Load_Position[position_index].Off;
                    }
                    // Perform clear only if Master load priorty is higher than load to clear
                    // otherwise load should override that behavior
                    if (PASS == Hbl__SetLoadRequestByIndex(load_clear_index, (HBL_PRIORITY_TYPE)my_prio,
                        (uint8 *)Hbl__GetFlushBuffer()))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                    {
                        ResetCrossLoadTransition(load_clear_index);
                    }

                    // Perform clear only if Delay Timer > 0 and Master load priorty is higher than load to clear
                    // otherwise load should override that behavior
                    if ((data_ptr->Timer > 0) &&
                        (PASS == Hbl__SetLoadRequestByIndex(load_check_index, (HBL_PRIORITY_TYPE)my_prio,
                        (uint8 *)Hbl__GetFlushBuffer())))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                    {
                        ResetCrossLoadTransition(load_check_index);
                    }

                }

                data_ptr->Processed = new_processed;
                if(data_ptr->Timer == 0)
                {
                    data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
                }
            }

        }
        break;

        case CROSSLOAD_ON_TRANSITION:
        case CROSSLOAD_OFF_TRANSITION:
        {
            BOOL_TYPE timer_wait = IsLoadStatusOnTransition(cfg_ptr->Crossload_Position);
            uint8 new_requested = (data_ptr->Generic_State == CROSSLOAD_ON_TRANSITION) ? ON : OFF;
            new_processed = new_requested;

            //------------------------------------------------------------
            if(data_ptr->Timer > param_ptr->On_Delay)
            {
                new_processed = (new_processed == OFF) ? ON : OFF;
            }

            //------------------------------------------------------------
            if (data_ptr->Timer > 0)
            {
                //----------- Load-Off & Load-On Keep Off Process ------------
                for(position_index = 0 ; position_index < cfg_ptr->Number_Of_Couples ; position_index++)
                {
                    timer_wait |= IsLoadStatusOnTransition(param_ptr->Load_Position[position_index].Off);
                    timer_wait |= IsLoadStatusOnTransition(param_ptr->Load_Position[position_index].On);
                }

                /* Request changed during transition: it resets transition if turning OFF loads before CrossLoad switch
                 * and updates ON/OFF transition according to the new request.
                 */
                if(data_ptr->Requested != new_requested)
                {
                    if(data_ptr->Timer > param_ptr->On_Delay)
                    {
                        data_ptr->Timer = 0;
                        timer_wait = TRUE;
                    }
                    new_processed = data_ptr->Requested;
                    data_ptr->Generic_State = (new_processed == OFF) ?
                        CROSSLOAD_OFF_TRANSITION : CROSSLOAD_ON_TRANSITION;
                }
                /* No request changes, but Processed is not the expected value: an Override has been performed after processing it.
                 * If this override happens before CrossLoad switch (Timer higher than On_Delay) it shorten time to On_Delay to prevent glitches
                 * If this override happens when turning OFF loads after CrossLoad switch it waits until the action stops
                 */
                else if(data_ptr->Processed != new_processed)
                {
                    if(data_ptr->Timer > param_ptr->On_Delay)
                    {
                        data_ptr->Timer = param_ptr->On_Delay;
                        new_processed = data_ptr->Processed;
                    }
                    timer_wait = TRUE;
                }

                if (timer_wait == FALSE)
                {
                    data_ptr->Timer--;
                    if(data_ptr->Timer == param_ptr->On_Delay)
                    {
                        new_processed = (new_processed == OFF) ? ON : OFF;
                    }
                }

                //----------- Load-Off & Load-On Keep Off Process ------------
                for(position_index = 0 ; position_index < cfg_ptr->Number_Of_Couples ; position_index++)
                {
                    // Clear OFF load index except on last iteration going to OFF
                    if((data_ptr->Generic_State == CROSSLOAD_ON_TRANSITION) ||
                        (data_ptr->Timer > 0))
                    {
                        load_clear_index = param_ptr->Load_Position[position_index].Off;
                        if (PASS == Hbl__SetLoadRequestByIndex(load_clear_index, (HBL_PRIORITY_TYPE)my_prio, (uint8 *)Hbl__GetFlushBuffer()))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                        {
                            ResetCrossLoadTransition(load_clear_index);
                        }

                    }

                    // Clear ON load index except on last iteration going to ON
                    if((data_ptr->Generic_State == CROSSLOAD_OFF_TRANSITION) ||
                        (data_ptr->Timer > 0))
                    {
                        load_clear_index = param_ptr->Load_Position[position_index].On;
                        if (PASS == Hbl__SetLoadRequestByIndex(load_clear_index, (HBL_PRIORITY_TYPE)my_prio, (uint8 *)Hbl__GetFlushBuffer()))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                        {
                            ResetCrossLoadTransition(load_clear_index);
                        }
                    }
                }
            }

            if (data_ptr->Timer == 0)
            {
                data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
            }
            data_ptr->Processed = new_processed;
        }
        break;

        default:
            data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
            break;
    }
}
#endif //(HBL_XLOAD_MASTER_RELAY_SUPPORT == ENABLED)
#if (HBL_XLOAD_SWITCH_RELAY_SUPPORT == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief - This function manages the Crossloads of type Switch Load
 *
 * @param CROSSLOAD_DATA_TYPE * , CROSSLOAD_PARAMETERS_TYPE *
 */
static void SwitchLoadHandler(HBL_CROSS_LOAD_TYPE *cfg_ptr, CROSSLOAD_DATA_TYPE * data_ptr, uint8 *hbl_prio_ptr)
{
    CROSSLOAD_PARAMETERS_TYPE *param_ptr = cfg_ptr->Parameter_Ptr;
    uint8 my_prio = GetLoadPriority(cfg_ptr->Crossload_Position, hbl_prio_ptr);
    uint8 position_index;
    uint8 *load_request_ptr;
    uint8 *load_process_ptr;
    uint8 load_request_len;
    BOOL_TYPE do_switch = FALSE;
    BOOL_TYPE keep_status = FALSE;

    switch (data_ptr->Generic_State)
    {
        case CROSSLOAD_STEADY_STATE:
        case CROSSLOAD_FORCED_STATE:
        {
            uint8 load_check_index; // Load index to check if switch has to be executed
            uint8 load_keep_index;  // Load index to check if switch position should be kept
            uint8 load_check_prio;

            for(position_index = 0 ; position_index < cfg_ptr->Number_Of_Couples ; position_index++)
            {
                // Place check and keep positions according to Switch status
                if (data_ptr->Processed == OFF)
                {
                    load_check_index = param_ptr->Load_Position[position_index].On;
                    load_keep_index = param_ptr->Load_Position[position_index].Off;
                }
                else
                {
                    load_check_index = param_ptr->Load_Position[position_index].Off;
                    load_keep_index = param_ptr->Load_Position[position_index].On;
                }


                // If keep position is ON: keep actual status
                load_check_prio = GetLoadPriority(load_check_index, hbl_prio_ptr);
                load_request_ptr = Hbl__GetRequestedLoad(load_keep_index);
                if (load_request_ptr != NULL)
                {
                    load_request_len = Hbl__GetLoadDataSize(load_keep_index);

                    // Perform clear only if Switch load priority is lower than load to keep
                    // otherwise load status is kept as is
                    if ((memcmp(load_request_ptr, Hbl__GetFlushBuffer(), load_request_len) != 0) ||
                        (keep_status != FALSE))
                    {
                        keep_status = TRUE;
                        if (PASS == Hbl__SetLoadRequestByIndex(load_check_index, (HBL_PRIORITY_TYPE)load_check_prio,
                        (uint8 *)Hbl__GetFlushBuffer()))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                        {
                            ResetCrossLoadTransition(load_check_index);
                        }
                    }
                }

                if ((keep_status == FALSE) &&
                    (load_check_prio >= my_prio))
                {
                    // If check position is ON: keep actual status
                    load_request_ptr = Hbl__GetRequestedLoad(load_check_index);
                    load_request_len = Hbl__GetLoadDataSize(load_check_index);
                    // Perform Switch load transition only if priorty is higher than maximum of other loads *
                    if ((load_request_ptr != NULL) &&
                        (memcmp(load_request_ptr, Hbl__GetFlushBuffer(), load_request_len) != 0))
                    {
                        load_process_ptr = Hbl__GetProcessedLoad(load_check_index);
                        if ((!IsLoadStatusOnTransition(load_check_index)) &&
                            (!IsCrossLoadTransition(load_check_index, TRUE)) &&
                            (memcmp(load_request_ptr, load_process_ptr, load_request_len) != 0))
                        {
                            do_switch = TRUE;
                        }
                        else
                        {
                            data_ptr->Processed = (data_ptr->Processed == OFF) ? ON : OFF;
                            keep_status = TRUE;
                        }
                    }
                }
            }

            if (keep_status == FALSE)
            {
                // No keep status required: check if Switch Load request changed by
                // direct request or via other load
                if (do_switch == FALSE)
                {
                    if (data_ptr->Processed != OFF)
                    {
                        if ((data_ptr->Requested != OFF) && (my_prio > SRHBL_PRIORITY_MINIMUM))
                        {
                            data_ptr->Generic_State = CROSSLOAD_FORCED_STATE;
                        }
                        else if (data_ptr->Generic_State == CROSSLOAD_FORCED_STATE)
                        {
                            data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
                            data_ptr->Processed = OFF;
                        }
                        else
                        {
                            do_switch = TRUE;
                        }
                    }
                    else if (data_ptr->Requested != OFF)
                    {
                        data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
                        data_ptr->Processed = ON;
                    }
                }

                if (do_switch != FALSE)
                {
                    if (data_ptr->Processed == OFF)
                    {
                        data_ptr->Generic_State = CROSSLOAD_ON_TRANSITION;
                        data_ptr->Processed = ON;
                        data_ptr->Timer = param_ptr->On_Delay;
                    }
                    else
                    {
                        data_ptr->Generic_State = CROSSLOAD_OFF_TRANSITION;
                        if(data_ptr->Timer == 0)
                        {
                            data_ptr->Timer = param_ptr->On_Delay + param_ptr->Off_Delay;
                        }
                    }

                    if(data_ptr->Timer > 0)
                    {
                        for(position_index = 0 ; position_index < cfg_ptr->Number_Of_Couples ; position_index++)
                        {
                            uint8 load_off_pos = param_ptr->Load_Position[position_index].Off;
                            uint8 load_on_pos = param_ptr->Load_Position[position_index].On;
                            uint8 load_off_prio = GetLoadPriority(load_off_pos, hbl_prio_ptr);
                            uint8 load_on_prio = GetLoadPriority(load_on_pos, hbl_prio_ptr);

                            if (PASS == Hbl__SetLoadRequestByIndex(load_off_pos, (HBL_PRIORITY_TYPE)load_off_prio,
                                    (uint8 *)Hbl__GetFlushBuffer()))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                            {
                                ResetCrossLoadTransition(load_off_pos);
                            }
                            if (PASS == Hbl__SetLoadRequestByIndex(load_on_pos, (HBL_PRIORITY_TYPE)load_on_prio,
                                    (uint8 *)Hbl__GetFlushBuffer()))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                            {
                                ResetCrossLoadTransition(load_on_pos);
                            }
                        }
                    }
                    else
                    {
                        data_ptr->Processed = (data_ptr->Generic_State == CROSSLOAD_OFF_TRANSITION) ? OFF : ON;
                        data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
                    }
                }
            }
            else
            {
                data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
            }
            break;
        }

        case CROSSLOAD_OFF_TRANSITION:
        case CROSSLOAD_ON_TRANSITION:
        {
            uint8 load_off_pos;
            uint8 load_on_pos;
            uint8 load_off_prio;
            uint8 load_on_prio;
            uint8 new_processed;
            BOOL_TYPE timer_wait = IsLoadStatusOnTransition(cfg_ptr->Crossload_Position);

            //------------------------------------------------------------
            new_processed = (data_ptr->Generic_State == CROSSLOAD_OFF_TRANSITION) ? OFF : ON;
            if (data_ptr->Timer > param_ptr->On_Delay)
            {
                new_processed = (new_processed == OFF) ? ON : OFF;
            }

            if (new_processed != data_ptr->Processed)
            {
                if(data_ptr->Timer <= param_ptr->On_Delay)
                {
                    timer_wait = TRUE;
                }
                else
                {
                    data_ptr->Timer = 0;
                }
            }

            if (data_ptr->Timer > 0)
            {
                //----------- Load-Off & Load-On Keep Off Process ------------
                for(position_index = 0 ; position_index < cfg_ptr->Number_Of_Couples ; position_index++)
                {
                    load_off_pos = param_ptr->Load_Position[position_index].Off;
                    load_on_pos = param_ptr->Load_Position[position_index].On;
                    if(new_processed == OFF)
                    {
                        timer_wait |= IsLoadStatusOnTransition(load_off_pos);
                        timer_wait |= IsCrossLoadTransition(load_off_pos, TRUE);
                    }
                    else
                    {
                        timer_wait |= IsLoadStatusOnTransition(load_on_pos);
                        timer_wait |= IsCrossLoadTransition(load_on_pos, TRUE);
                    }

                    if (data_ptr->Timer > param_ptr->On_Delay)
                    {
                        uint8 load_keep_index = (data_ptr->Generic_State == CROSSLOAD_OFF_TRANSITION) ? load_on_pos : load_off_pos;

                        load_process_ptr = Hbl__GetRequestedLoad(load_keep_index);
                        load_request_len = Hbl__GetLoadDataSize(load_keep_index);
                        if (load_process_ptr != NULL)
                        {
                            if(memcmp(load_process_ptr, Hbl__GetFlushBuffer(), load_request_len) != 0)
                            {
                                timer_wait = TRUE;
                                data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
                                data_ptr->Timer = 0;
                            }
                        }
                    }
                }

                if (timer_wait == FALSE)
                {
                    data_ptr->Timer--;
                    if(data_ptr->Timer == param_ptr->On_Delay)
                    {
                        new_processed =  (new_processed == OFF) ? ON : OFF;
                    }
                }
            }

            if(data_ptr->Timer > 0)
            {
                for(position_index = 0 ; position_index < cfg_ptr->Number_Of_Couples ; position_index++)
                {
                    load_off_pos = param_ptr->Load_Position[position_index].Off;
                    load_on_pos = param_ptr->Load_Position[position_index].On;
                    load_off_prio = GetLoadPriority(load_off_pos, hbl_prio_ptr);
                    load_on_prio = GetLoadPriority(load_on_pos, hbl_prio_ptr);

                    if (PASS == Hbl__SetLoadRequestByIndex(load_off_pos, (HBL_PRIORITY_TYPE)load_off_prio,
                            (uint8 *)Hbl__GetFlushBuffer()))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                    {
                        ResetCrossLoadTransition(load_off_pos);
                    }
                    if (PASS == Hbl__SetLoadRequestByIndex(load_on_pos, (HBL_PRIORITY_TYPE)load_on_prio,
                            (uint8 *)Hbl__GetFlushBuffer()))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                    {
                        ResetCrossLoadTransition(load_on_pos);
                    }
                }
                data_ptr->Processed = new_processed;
            }
            else
            {
                data_ptr->Processed = new_processed;
                data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
            }
            break;
        }

        default:
            data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
            break;
    }
}
#endif //(HBL_XLOAD_SWITCH_RELAY_SUPPORT == ENABLED)
#if (HBL_XLOAD_REVERSE_SWITCH_RELAY_SUPPORT == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief - This function manages the Crossloads of type Reverse Switch Load
 *
 * @param CROSSLOAD_DATA_TYPE * , CROSSLOAD_PARAMETERS_TYPE *
 */
static void ReverseLoadRelayHandler(HBL_CROSS_LOAD_TYPE *cfg_ptr, CROSSLOAD_DATA_TYPE * data_ptr, uint8 *hbl_prio_ptr)
{
    CROSSLOAD_PARAMETERS_TYPE *param_ptr = cfg_ptr->Parameter_Ptr;
    uint8 my_prio = GetLoadPriority(cfg_ptr->Crossload_Position, hbl_prio_ptr);
    uint8 position_index;
    uint8 load_check_index; // Load index to check if switch has to be executed
    uint8 load_keep_index;  // Load index to check if swict position should be kept
    uint8 load_check_prio;
    uint8 load_keep_prio;
    uint8 *load_request_ptr;
    uint8 load_request_len;
    BOOL_TYPE do_switch = FALSE;
    BOOL_TYPE keep_status = FALSE;

    for(position_index = 0 ; position_index < cfg_ptr->Number_Of_Couples ; position_index++)
    {
        // Place check and keep positions according to Reverse Switch status
        if (data_ptr->Processed == OFF)
        {
            load_check_index = param_ptr->Load_Position[position_index].On;
            load_keep_index = param_ptr->Load_Position[position_index].Off;
        }
        else
        {
            load_check_index = param_ptr->Load_Position[position_index].Off;
            load_keep_index = param_ptr->Load_Position[position_index].On;
        }

        load_keep_prio = GetLoadPriority(load_keep_index, hbl_prio_ptr);
        load_check_prio = GetLoadPriority(load_check_index, hbl_prio_ptr);

        if (load_keep_prio >= my_prio)
        {
            // If keep position is ON: keep actual status
            load_request_ptr = Hbl__GetRequestedLoad(load_keep_index);
            if (load_request_ptr != NULL)
            {
                load_request_len = Hbl__GetLoadDataSize(load_keep_index);

                // Perform clear only if Switch load priorty is lower than load to keep
                // otherwise load status is kept as is
                if (memcmp(load_request_ptr, Hbl__GetFlushBuffer(), load_request_len) != 0)
                {
                    keep_status = TRUE;
                    do_switch = FALSE;
                    if(PASS == Hbl__SetLoadRequestByIndex(load_check_index,
                        (HBL_PRIORITY_TYPE)load_check_prio, (uint8 *)Hbl__GetFlushBuffer()))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                    {
                        ResetCrossLoadTransition(load_check_index);
                    }
                }
            }
        }

        if ((keep_status == FALSE) &&
            (load_check_prio >= my_prio))
        {
            load_request_ptr = Hbl__GetRequestedLoad(load_check_index);
            if (load_request_ptr != NULL)
            {
                load_request_len = Hbl__GetLoadDataSize(load_check_index);

                // Perform Reverse Switch load transition only if priorty is higher than maximum of other loads *
                if(memcmp(load_request_ptr, (uint8 *)Hbl__GetFlushBuffer(), load_request_len) != 0)
                {
                    do_switch = TRUE;
                }
            }
        }
    }

    switch (data_ptr->Generic_State)
    {
        case CROSSLOAD_STEADY_STATE:
        case CROSSLOAD_FORCED_STATE:
        {

            if (keep_status == FALSE)
            {
                // No keep status required: check if Switch Load request changed by
                // direct request or via other load
                if (do_switch == FALSE)
                {
                    if (data_ptr->Processed != OFF)
                    {
                        if ((data_ptr->Requested != OFF) && (my_prio > SRHBL_PRIORITY_MINIMUM))
                        {
                            data_ptr->Generic_State = CROSSLOAD_FORCED_STATE;
                        }
                        else if (data_ptr->Generic_State == CROSSLOAD_FORCED_STATE)
                        {
                            data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
                            data_ptr->Processed = OFF;
                        }
                        else
                        {
                            do_switch = TRUE;
                        }
                    }
                    else if (data_ptr->Requested != OFF)
                    {
                        data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
                        data_ptr->Processed = ON;
                    }
                }

                if (do_switch != FALSE)
                {
                    if (data_ptr->Processed == OFF)
                    {
                        data_ptr->Timer = param_ptr->On_Delay;
                        data_ptr->Generic_State = CROSSLOAD_ON_TRANSITION;
                        if(param_ptr->On_Delay == 0)
                        {
                            data_ptr->Processed = ON;
                        }
                    }
                    else
                    {
                        data_ptr->Processed = OFF;
                        data_ptr->Timer = param_ptr->Off_Delay;
                        if(param_ptr->Off_Delay > 0)
                        {
                            data_ptr->Generic_State = CROSSLOAD_OFF_TRANSITION;
                            for(position_index = 0 ; position_index < cfg_ptr->Number_Of_Couples ; position_index++)
                            {
                                load_check_index = param_ptr->Load_Position[position_index].On;
                                load_check_prio = GetLoadPriority(load_check_index, hbl_prio_ptr);
                                load_request_ptr = Hbl__GetProcessedLoad(load_check_index);
                                if (load_request_ptr != NULL)
                                {
                                    load_request_len = Hbl__GetLoadDataSize(load_check_index);
                                    if (PASS == Hbl__SetLoadRequestByIndex(load_check_index,
                                       (HBL_PRIORITY_TYPE)load_check_prio, (uint8 *)load_request_ptr))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                                    {
                                        ResetCrossLoadTransition(load_check_index);
                                    }
                                }
                            }
                        }
                        else
                        {
                            data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
                        }
                    }
                }
            }
            else
            {
                data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
            }
            break;
        }

        case CROSSLOAD_OFF_TRANSITION:
        case CROSSLOAD_ON_TRANSITION:
        {
            uint8 new_processed = OFF;

            if (data_ptr->Timer > 0)
            {
                data_ptr->Timer--;
            }

            //----------- OFF Transition: keep ON load requests and clear OFF load requests ------------
            if (data_ptr->Generic_State == CROSSLOAD_OFF_TRANSITION)
            {
                // Back to Steady state ON if one of On loads are ON:
                if( ((data_ptr->Processed == OFF) && do_switch) ||
                    ((data_ptr->Processed != OFF) && keep_status))
                {
                    data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
                    data_ptr->Timer = 0;
                    new_processed = ON;
                }
                else if(data_ptr->Processed != OFF)
                {
                    data_ptr->Timer++;
                }

                if(data_ptr->Timer > 0)
                {
                    for(position_index = 0 ; position_index < cfg_ptr->Number_Of_Couples ; position_index++)
                    {
                        // Keep previous state of On load on previous CrossLoad state
                        load_keep_index = param_ptr->Load_Position[position_index].On;
                        load_keep_prio = GetLoadPriority(load_keep_index, hbl_prio_ptr);
                        load_request_ptr = Hbl__GetProcessedLoad(load_keep_index);
                        if ((load_request_ptr != NULL) &&
                            (PASS == Hbl__SetLoadRequestByIndex(load_keep_index, (HBL_PRIORITY_TYPE)load_keep_prio,
                            (uint8 *)load_request_ptr)))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                        {
                            ResetCrossLoadTransition(load_keep_index);
                        }

                        // Clear state of Off load on next CrossLoad state
                        load_check_index = param_ptr->Load_Position[position_index].Off;
                        load_check_prio = GetLoadPriority(load_check_index, hbl_prio_ptr);
                        if((PASS == Hbl__SetLoadRequestByIndex(load_check_index, (HBL_PRIORITY_TYPE)load_check_prio,
                            (uint8 *)Hbl__GetFlushBuffer())))   //lint !e926 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
                        {
                            ResetCrossLoadTransition(load_check_index);
                        }
                    }
                }
                else
                {
                    data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
                }
            }
            else
            {
                if(data_ptr->Timer == 0)
                {
                    new_processed = ON;
                }

                if(do_switch == FALSE)
                {
                    data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
                    data_ptr->Timer = 0;
                }
            }

            data_ptr->Processed = new_processed;
            break;
        }

        default:
            data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
            break;
    }
}
#endif //(HBL_XLOAD_REVERSE_SWITCH_RELAY_SUPPORT == ENABLED)
#if (HBL_XLOAD_TRANSITION_RELAY_SUPPORT == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief - This function manages the Crossloads of type Transition Load
 *
 * @param CROSSLOAD_DATA_TYPE * , CROSSLOAD_PARAMETERS_TYPE *
 */
static void TransitionLoadHandler(HBL_CROSS_LOAD_TYPE *cfg_ptr, CROSSLOAD_DATA_TYPE * data_ptr, uint8 *hbl_prio_ptr)
{
    CROSSLOAD_PARAMETERS_TYPE *param_ptr = cfg_ptr->Parameter_Ptr;
    uint8 my_prio = GetLoadPriority(cfg_ptr->Crossload_Position, hbl_prio_ptr);
    uint8 *load_request_ptr;
    uint8 *load_process_ptr;
    uint8 load_index;
    uint8 position_index;
    uint8 load_request_len;
    uint8 load_prio;

    switch (data_ptr->Generic_State)
    {
        case CROSSLOAD_STEADY_STATE:
        {
            BOOL_TYPE do_switch = FALSE;
            //------- Load-On Transition Monitor and Relay Trigger Process ---------------
            if ((data_ptr->Requested == OFF) &&
            		((param_ptr->Off_Delay + param_ptr->On_Delay) > 0))
            {
                for(position_index = 0 ; position_index < cfg_ptr->Number_Of_Couples ; position_index++)
                {
                    load_index = param_ptr->Load_Position[position_index].On;
                    load_request_ptr = Hbl__GetRequestedLoad(load_index);
                    load_process_ptr = Hbl__GetProcessedLoad(load_index);
                    load_request_len = Hbl__GetLoadDataSize(load_index);
                    load_prio = GetLoadPriority(load_index, hbl_prio_ptr);

                    if ((load_request_ptr != NULL) &&
                        (load_prio >= my_prio) &&
                        (!IsLoadStatusOnTransition(load_index)) &&
                        (memcmp(load_request_ptr, load_process_ptr, load_request_len) != 0))
                    {
                        do_switch = TRUE;
                        if(param_ptr->On_Delay > 0)
                        {
                            Hbl__SetLoadRequestByIndex(load_index, (HBL_PRIORITY_TYPE)load_prio, load_process_ptr);
                        }
                    }
                }
            }

            if (do_switch != FALSE)
            {
                data_ptr->Timer = param_ptr->On_Delay + param_ptr->Off_Delay;
                data_ptr->Generic_State = CROSSLOAD_ON_TRANSITION;
                data_ptr->Processed = ON;
            }
            else
            {
                data_ptr->Processed = data_ptr->Requested;
            }
        }
        //----------------------------------------------------------------------------
        break;

        case CROSSLOAD_ON_TRANSITION:
        {
            BOOL_TYPE timer_wait = IsLoadStatusOnTransition(cfg_ptr->Crossload_Position);
            uint8 new_timer = data_ptr->Timer;

            if (data_ptr->Processed == OFF)
            {
                if(new_timer > param_ptr->Off_Delay)
                {
                    timer_wait = TRUE;
                }
                else
                {
                    new_timer = 0;
                }
            }
            else if ((data_ptr->Requested != OFF) && (my_prio > SRHBL_PRIORITY_MINIMUM))
            {
                new_timer = 0;
            }

            if (new_timer > 0)
            {
                new_timer--;

                for(position_index = 0; position_index < cfg_ptr->Number_Of_Couples; position_index++)
                {
                    load_index = param_ptr->Load_Position[position_index].On;
                    load_prio = GetLoadPriority(load_index, hbl_prio_ptr);
                    load_request_ptr = Hbl__GetRequestedLoad(load_index);
                    load_process_ptr = Hbl__GetProcessedLoad(load_index);
                    load_request_len = Hbl__GetLoadDataSize(load_index);
                    timer_wait |= IsLoadStatusOnTransition(load_index);
                    timer_wait |= IsCrossLoadTransition(load_index, FALSE);

                    if ((load_request_ptr != NULL) &&
                        (load_process_ptr != NULL) &&
                        (memcmp(load_request_ptr, load_process_ptr, load_request_len) != 0))
                    {
                        //------- Load-On Keep State Process ---------------
                        if (new_timer > param_ptr->Off_Delay)
                        {
                            Hbl__SetLoadRequestByIndex(load_index, (HBL_PRIORITY_TYPE)load_prio, load_process_ptr);
                        }
                        else
                        {
                            new_timer = param_ptr->Off_Delay;
                            timer_wait = FALSE;
                        }
                    }
                }
                if (timer_wait == FALSE)
                {
                    data_ptr->Timer = new_timer;
                }
            }

            if(new_timer == 0)
            {
                data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
                data_ptr->Processed = OFF;
            }
            else
            {
                data_ptr->Processed = ON;
            }
        }
        break;

        default:
            data_ptr->Generic_State = CROSSLOAD_STEADY_STATE;
            break;
    }
}
#endif  //(HBL_XLOAD_TRANSITION_RELAY_SUPPORT == ENABLED)

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   This method checks if a load status is on a transition state or not
 * @param   load_index  Load index to check
 * @return  TRUE if Load status is not on target, FALSE if load status is on target or load is not preset
 */
static BOOL_TYPE IsLoadStatusOnTransition(uint8 load_index)
{
    BOOL_TYPE ret_val = FALSE;
    HBL_LOAD_STATUS_TYPE *load_status = Hbl__GetLoadStatusByIndex(load_index);

    if (load_status != NULL)
    {
        ret_val = (BOOL_TYPE) ((load_status->Load.Status != HBL_LOAD_STATUS_TARGET_COMPLETED) &&
                (load_status->Load.Status != HBL_LOAD_STATUS_TARGET_ALT_TABLE));
    }

    return(ret_val);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   This method checks if a Cross Load (referred by its load_index) is on a transition state or not
 * @param   load_index      Load index to check
 *          check_previous  if ENABLED it checks also if previous state is on a transition state or not
 * @return  TRUE if Cross Load status is not on a steady state, FALSE if on a a steady state or it's not a Cross Load
 */
static BOOL_TYPE IsCrossLoadTransition(uint8 load_index, BOOL_TYPE check_previous)
{
    BOOL_TYPE ret_val = FALSE;
    uint8 cross_load_index = GetCrossLoadIndex(load_index);

    if(cross_load_index < Crossloads_Num)
    {
        CROSSLOAD_DATA_TYPE *data_ptr = &Crossload_Data[cross_load_index];
        if((data_ptr->Generic_State != CROSSLOAD_STEADY_STATE) && (data_ptr->Generic_State != CROSSLOAD_FORCED_STATE) &&
            ((check_previous == FALSE) ||
                ((data_ptr->Previous_State != CROSSLOAD_STEADY_STATE) && (data_ptr->Previous_State != CROSSLOAD_FORCED_STATE))))
        {
            ret_val = TRUE;
        }
    }
    return(ret_val);
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   This method reset a Cross Load transition if it started its transition state
 * @param   load_index  Load index to check
 */
static void ResetCrossLoadTransition(uint8 load_index)
{
    uint8 cross_load_index = GetCrossLoadIndex(load_index);

    if(cross_load_index < Crossloads_Num)
    {
        CROSSLOAD_DATA_TYPE *data_ptr = &Crossload_Data[cross_load_index];
        if(((data_ptr->Generic_State != CROSSLOAD_STEADY_STATE) && (data_ptr->Generic_State != CROSSLOAD_FORCED_STATE)) &&
            ((data_ptr->Previous_State == CROSSLOAD_STEADY_STATE) || (data_ptr->Previous_State == CROSSLOAD_FORCED_STATE)))
        {
            HBL_CROSS_LOAD_TYPE *cfg_ptr = &Crossload_Cfg[cross_load_index];
            data_ptr->Processed = *(uint8*)Hbl__GetProcessedLoad(cfg_ptr->Crossload_Position);
            data_ptr->Generic_State = data_ptr->Previous_State;
            data_ptr->Timer = 0;
        }
    }
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   This method looks if a load is configured as a Cross Load and returns Cross Load index
 * @param   load_index  Load index to check
 * @return  CrossLoad index if found,  HBL_LOAD_INDEX_INVALID otherwise
 */
static uint8 GetCrossLoadIndex(uint8 load_index)
{
    uint8 cross_load_index = HBL_LOAD_INDEX_INVALID;

    for (uint8 index = 0 ; index < Crossloads_Num ; index++)
    {
        HBL_CROSS_LOAD_TYPE *cfg_ptr = &Crossload_Cfg[index];
        if(cfg_ptr->Crossload_Position == load_index)
        {
            cross_load_index = index;
            break;
        }
    }
    return(cross_load_index);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   This method gets current load priority
 * @param   load_index  Load index to check
 * @return  current priority value, 0 if load_index is out of range
 */
static uint8 GetLoadPriority(uint8 load_index, uint8 *hbl_prio_ptr)
{
    uint8 cur_prio = 0;

    if (load_index < Hbl__GetNumLoads())
    {
        cur_prio = hbl_prio_ptr[load_index];
    }

    return(cur_prio);
}

#endif
