/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2018-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "C_Extensions.h"
#include "VwiMonitor.h" 
#include "Vwi.h"
#include "Vwi_prv.h"


#if(VWI_CLIENT_FEATURE == ENABLED)
#include "API221MotionCtrl.h"
#include "Selector.h"
#include "Interpreter.h"
#include "Log.h"
#include "Micro.h"

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//! The data structure of the Heat process parameters as they are found in the setting file.
typedef PACKED struct VWI_PARAMETER_STRUCT
{
    uint8 VWI_Calibration_Time;
    uint8 VWI_Present;
    uint8 VWI_Sig_Water_Threshold;
    uint8 VWI_Sig_Variance_Threshold;
    uint8 VWI_Signal_Low_Water_Threshold;
    uint8 VWI_Signal_Calibration_Target;
    uint8 VWI_Wash_Motor_Type;
    uint8 VWI_Data_Channel_Period;
    uint16 Speed_Comp_Zero_Level;
    uint16 Min_Comp_Speed;
    uint16 Max_Comp_Speed;
    uint16 Speed_Comp_Step;
    uint16 Sig_Speed_Comp[20];
} VWI_PARAMETER_TYPE;

static BOOL_TYPE VwiMonitor_Callback_Active;

//! The name of this module for use by the Log module.
#define MODULE_NAME 	MODULE_VWI_MONITOR

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_VWI_MONITOR_LOG_MESSAGE_ID_ENUM
{
	ERROR_LOADING_VWI_PARAMETERS       = 1,
} MODULE_VWI_MONITOR_LOG_MESSAGE_ID_TYPE;

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
static void ReadSfData(void);
static void API221HandleMotorEvent(API221_EVENT_TYPE event);
#endif // (VWI_CLIENT_FEATURE == ENABLED)
//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the module VwiMonitor and its variables
 *
 */
void VwiMonitor__Initialize(void)
{
#if(VWI_CLIENT_FEATURE == ENABLED)

	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		VwiMonitor_Callback_Active = FALSE;
		ReadSfData();
	}

#endif // (VWI_CLIENT_FEATURE == ENABLED)
}

/**
 * 	@brief 		Main handler for VwiMonitor
 */
void VwiMonitor__Execute(void)
{
#if(VWI_CLIENT_FEATURE == ENABLED)
	uint8 label = (Selector__GetCycleState(0, 0, (Interpreter__GetCurrentStatement(0)).Cycle));

	//In case of cycle is running or we have some fault and we will need VWI information
	if((label == CYCLE_STATE_RUN) || (label == CYCLE_STATE_FAULT))
	{
		if(VwiMonitor_Callback_Active == FALSE)
		{
			API221MotionCtrl__RegisterForEvents(API221HandleMotorEvent);
			VwiMonitor_Callback_Active = TRUE;
		}
	}
	else
	{
		//Unsubscribe Motor state and also turn off remote data
		if(VwiMonitor_Callback_Active == TRUE)
		{
			API221MotionCtrl__UnregisterForEvents(API221HandleMotorEvent);
			VwiMonitor_Callback_Active = FALSE;

			Vwi__RemoteChannelEnable(MOTOR_0, MCISENSORSDW_AI_VWI_CHANNEL_0, FALSE);
			Vwi__RemoteChannelEnable(MOTOR_0, MCISENSORSDW_AI_VWI_CHANNEL_1, FALSE);
			Vwi__RemoteChannelEnable(MOTOR_1, MCISENSORSDW_AI_VWI_CHANNEL_0, FALSE);
			Vwi__RemoteChannelEnable(MOTOR_1, MCISENSORSDW_AI_VWI_CHANNEL_1, FALSE);
		}
	}
#endif // (VWI_CLIENT_FEATURE == ENABLED)
}


//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================
#if(VWI_CLIENT_FEATURE == ENABLED)

/**
 * @brief Function read VWI Data period value from SettingFile and set
 *
 */
static void ReadSfData()
{
	SETTINGFILE_LOADER_TYPE loader;
	uint16 Data_Period;

	if (SettingFile__BasicLoader(VWI_SETTING_FILE_PTR, VWI_SETTING_FILE_DISPL_DEFAULT, &loader) == PASS)
	{
		uint8 sf_data;
		sf_data = ((VWI_PARAMETER_TYPE*)(loader.Data))->VWI_Data_Channel_Period; //lint !e927 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]

		//Multiply SettingFile parameter x100
		Data_Period = (sf_data*100);
	}
	else
	{
		Data_Period = 1000;
		LOG_ADD_EXCEPTION(ERROR_LOADING_VWI_PARAMETERS, 0);
	}
	
	Vwi__RemoteChannelPeriod(0xFF, Data_Period);
}


/**
 * Handle events published through API221.
 * This function is called by the communication thread.
 * @param event = The event that was published through API221.
 */
static void API221HandleMotorEvent(API221_EVENT_TYPE event)
{
	switch (event.Event)
	{
		case API221_EVENT_ERROR:
		case API221_EVENT_STOPPED:
			Vwi__RemoteChannelEnable(event.Motor, MCISENSORSDW_AI_VWI_CHANNEL_0, FALSE);
			Vwi__RemoteChannelEnable(event.Motor, MCISENSORSDW_AI_VWI_CHANNEL_1, FALSE);
			break;

		case API221_EVENT_RAMP_STARTED:
		case API221_EVENT_REACHED_TARGET:
			Vwi__RemoteChannelEnable(event.Motor, MCISENSORSDW_AI_VWI_CHANNEL_0, TRUE);
			Vwi__RemoteChannelEnable(event.Motor, MCISENSORSDW_AI_VWI_CHANNEL_1, TRUE);
			break;

		default:
			// Ignore all other events
			break;
	}
}

#endif // (VWI_CLIENT_FEATURE == ENABLED)
