/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "C_Extensions.h"
#include "Micro.h"
#include "OWI.h" 
#include "OWIOneShot.h"
#include "OWICalibrationProcess.h"
//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_OWI

//! The types of OWI variations that are available.
typedef enum OWI_OPTION_ENUM
{
	OWI_CALIBRATION,                          //!< F1=0, F0=0
	OWI_ONE_SHOT_READING,        		//!< F1=0, F0=1
	OWI_OPTION_COUNT
} OWI_OPTION_TYPE;

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_OWI_LOG_MESSAGE_ID_ENUM
{
	PROCESS_CONTROL_IS_NULL = 1,
	PROCESS_CONTROL_PARAMS_EXCEED_LIMITS
} MODULE_OWI_LOG_MESSAGE_ID_TYPE;
//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 * It Initializes the module OWI and its variables
 * Called after reset.
 */
void OWI__Initialize(void)
{
	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		// OWI One Shot
		OWIOneShot__Initialize();

		// OWI Calibration
		OWICalibration__Initialize();
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the module OWI and its variables
 *
 */

PROCESS_RESULT_TYPE OWI__Process(PROCESS_CONTROL_TYPE* control)
{
    PROCESS_RESULT_TYPE result = PROCESS_COMPLETE;

    if (control == NULL)
	{
    	LOG_ADD_EXCEPTION(PROCESS_CONTROL_IS_NULL, 0);
	}
    else if ((control->Compartment >= (uint8)APPLIANCE_MAX_COMPARTMENTS) ||
    		 (control->F1_F0_Flags >= (uint8)OWI_OPTION_COUNT)||
             (control->Process_Instance > (uint8)0))
    {
    	LOG_ADD_EXCEPTION(PROCESS_CONTROL_PARAMS_EXCEED_LIMITS, 0);
    }
    else
    {
    	OWI_OPTION_TYPE owi_options = (OWI_OPTION_TYPE)control->F1_F0_Flags;
        if (owi_options == OWI_CALIBRATION)
        {
        	result = OWICalibration__Process(control);
        }
        else if (owi_options == OWI_ONE_SHOT_READING)
        {
        	result = OWIOneShot__Process(control);
        }

    }//*/

    return result;
}

//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================


