/*
 * DCLoadCurrentMonitor_prv.h
 *
 *  Created on: Jul 7, 2023
 *      Author: WAZNYP
 */

#ifndef SOURCE_PROJECTSPECIFIC_APPLICATION_ACU_CONFIG_DCLOADCURRENTMONITOR_PRV_H_
#define SOURCE_PROJECTSPECIFIC_APPLICATION_ACU_CONFIG_DCLOADCURRENTMONITOR_PRV_H_

#define DCLOAD_CURRENT_MONITOR_DOS_FAULT_FEATURE	ENABLED

#endif /* SOURCE_PROJECTSPECIFIC_APPLICATION_ACU_CONFIG_DCLOADCURRENTMONITOR_PRV_H_ */
