/**
 *  @file		DoorOpeningSystemPull.c
 *
 *  @brief		A task that triggers the start of the sequence to pull in the DOS pin
 *
 *  @details    Door Opening System (briefly DOS) is a device used to assist with the drying by opening the door of the dishwasher
 *  			releasing the moisture out of the tub at selected moment given by the cycle design.
 *  			Door Opening System Pull Task shall be activated in the point of the cycle when the DOS pin has to be retracted.
 *  			Once started, the Pull sequence is managed by the Door Open System Monitor, so that it is completed even if the task
 *  			is terminated. Moreover, the Pull sequence can be started also outside the DOS Pull task.
 *  			No Deactivate Task call is needed, the task automatically deactivate itself when it is completed.
 *
 */

//  --- Include Files -------------------------------------------------------------------------------------------------

// -- This Module --
#include "C_Extensions.h"
#include "DoorOpeningSystemPull.h"

// -- Other Modules --
#include "DoorOpeningSystemMonitor.h"
#include "Log.h"
#include "Hbl.h"
#include "SettingFile.h"


//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
//! The name of this module to be used by the Log module.
#define MODULE_NAME MODULE_DOOR_OPENING_SYSTEM_PULL

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_DOOR_OPENING_SYSTEM_PULL_LOG_MESSAGE_ID_ENUM
{
	ERROR_MISSING_PARAMETERS  = 1,
} MODULE_DOOR_OPENING_SYSTEM_PULL_LOG_MESSAGE_ID_TYPE;


//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//----------------------------------------------------------------------------
/**
 * It initializes the Door Opening System Pull task and its data.
 *
 * @param  compartment = compartment inside which the task is running
 * @param  sf_index = the index of the setting file from which to load the task data
 * @param  displacement = the displacement for the task data in the setting file (unused, since all the instances
 * 		   of the Door Opening System Pull Task use the same data table).
 * @return the status of the task (ACTIVE or INACTIVE)
 *
 */
ACTIVE_TYPE DoorOpeningSystemPull__Initialize(uint8 compartment, uint8 sf_index, uint8 displacement)
{
    SETTINGFILE_LOADER_TYPE loader;
	ACTIVE_TYPE ret_value = INACTIVE;

	if (Hbl__GetLoadIndexByLoadID(HBL_LOAD_DOOR_OPENING_SYSTEM) != (uint8)HBL_INDEX_INVALID)
	{
		// Get the DOS Push parameters from the setting file.
		if (SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS, DSPL_DOOR_OPENING_SYSTEM, &loader) == PASS)
		{
			DoorOpeningSystemMonitor__StartPull(((DOOR_OPENING_SYSTEM_SF_PARAMS_TYPE *)(void*)loader.Data)->Pull_Off_Time); //lint !e927 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
			ret_value = ACTIVE;
		}
		else
		{
			// Algorithm parameters missing, allow step advancement
			LOG_ADD_EXCEPTION(ERROR_MISSING_PARAMETERS, DSPL_DOOR_OPENING_SYSTEM);
		}
	}
	else
	{
		// Door Opening System not present, allow step advancement
	}

	return ret_value;
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Function called during the execution of the Door Opening System Pull task.
 *
 * @param  compartment = compartment inside which the task is running
 * @return the status of the task (ACTIVE or INACTIVE)
 */
ACTIVE_TYPE DoorOpeningSystemPull__Task(uint8 compartment)
{
	ACTIVE_TYPE ret_value;

	if (DoorOpeningSystemMonitor__GetDOSPullState() != DOS_PULL_COMPLETE )
	{
		// PULL procedure is not complete, the task doesn't allow step advancement.
		ret_value = ACTIVE;
	}
	else
	{
		// PULL procedure is complete, the microprogram allows step advancement.
		ret_value = INACTIVE;
	}

	return ret_value;
}


/**
 * It is called at the initialization of the task after NVdata restore.
 *
 * @param  compartment = compartment inside which the task is running
 *
 * @return  None
 */
void DoorOpeningSystemPull__NVDataRestore(uint8 compartment)
{

}


/**
 * It is called when the task ends
 *
 * @param  compartment = compartment inside which the task is running
 *
 * @return  None
 */
void DoorOpeningSystemPull__Terminate(uint8 compartment)
{

}


//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

