/**
 *  @file
 *  @brief      Motor Control Interface
 *
 *  @details    One interface for any motor present in system
 *
 *  @Module_Owner Leonardo Ricupero / Eduardo H Couto
 *  $Header: Mci.c 1.00 - July/2020
 *
 *  @copyright  Copyright 2020 - Whirlpool Corporation.  All rights reserved - CONFIDENTIAL.
 */

//  --- Include Files -------------------------------------------------------------------------------------------------

// -- This Module --
#include "C_Extensions.h"
#include "Mci.h"

#include "Mcl.h"
#include "MotorTypeDefs.h"
#include "TimerInterruptExt.h"

// -- ANSI/ISO --

// -- Project --
#include "Micro.h"

#include "Mci_prv.h"
#include "SettingFile.h"

//  --- Public Variables ----------------------------------------------------------------------------------------------

#include "Log.h"

// --- LOG MODULE SETTINGS ---------------------------
//! A list of log message IDs that are generated by this module.
typedef enum MODULE_MCI_LOG_MESSAGE_ID_ENUM
{
	//Event
	MCI_EVENT_GWS_INITIALIZED                        = 1,    //!< GWS Initialized and Parameters loaded!
	MCI_EVENT_RIF_INITIALIZED                        = 2,    //!< RIF pump initialized (Active Power Module)
	/* ---- */
	MCI_EVENT_FAULT_CLEARED                          = 5,    //!< MCI Fault has been cleared.

	//Exception
	MCI_EXCEPTION_PARAMETERS_NOT_LOADED              = 10,   //!< Error to load MCI parameters.

} MODULE_MCI_LOG_MESSAGE_ID_TYPE;

//! The name of this module for use by the Log module.
#define MODULE_NAME  MODULE_MCI

//  --- Private Properties --------------------------------------------------------------------------------------------
static APL_WASH_MOTOR_TYPE Mci_Wash_Motor_Type;
static BOOL_TYPE Mci_Params_Loaded;
//  --- Private Function Prototypes -----------------------------------------------------------------------------------
static void Mci__ParameterLoading(void);


#ifdef ENABLE_API220_CALLBACKS

    #include "APIMotorControl.h"

    #define API220_PUBLISHDIGITAL_CALLBACK(motor, write_data, value, ret_val)   APIMotorControl__PublishSetDigital((motor), (write_data), (value), (ret_val))
    #define API220_PUBLISHANALOG_CALLBACK(motor, write_data, value, ret_val)    APIMotorControl__PublishSetAnalog((motor), (write_data), (value), (ret_val))
    #define API220_RUN_CALLBACK(motor, speed_rpm, ramp_rpm_per_s, response)     APIMotorControl__PublishRun((motor), (speed_rpm), (ramp_rpm_per_s), (response))
	#define API220_MANUAL_INJECTION_CALLBACK(motor, 			\
											method, 			\
											level_x32, 			\
											level_rate_x32, 	\
											param_x32, 			\
											param_rate_x32, 	\
											response)							// todo Luigi needs to implement the API220 call back of manual injection
    #define API220_STOP_CALLBACK(motor, ramp_rpm_per_s, response)               APIMotorControl__PublishStop((motor), (ramp_rpm_per_s), (response))

#else

    #define API220_PUBLISHDIGITAL_CALLBACK(motor, write_data, value, ret_val)
    #define API220_PUBLISHANALOG_CALLBACK(motor, write_data, value, ret_val)
    #define API220_RUN_CALLBACK(motor, speed_rpm, ramp_rpm_per_s, response)
	#define API220_MANUAL_INJECTION_CALLBACK(motor, 			\
											method, 			\
											level_x32, 			\
											level_rate_x32, 	\
											param_x32, 			\
											param_rate_x32, 	\
											response)
	#define API220_STOP_CALLBACK(motor, ramp_rpm_per_s, response)

#endif


#ifndef MCISLFAC__DEBUG_INITIALIZE
	#define MCISLFAC__DEBUG_INITIALIZE()
#endif

#ifndef MCISLFAC__DEBUG_FASTHANDLER
	#define MCISLFAC__DEBUG_FASTHANDLER()
#endif

#ifndef MCISLFAC__DEBUG_SLOWHANDLER
	#define MCISLFAC__DEBUG_SLOWHANDLER()
#endif

#ifndef MCISLFAC__DEBUG_250USHANDLER
	#define MCISLFAC__DEBUG_250USHANDLER()
#endif

#ifndef MCISLFAC__DEBUG_ZEROCROSSHANDLER
	#define MCISLFAC__DEBUG_ZEROCROSSHANDLER()
#endif

#ifndef MCISLFAC__DEBUG_TRIACHANDLER
	#define MCISLFAC__DEBUG_TRIACHANDLER()
#endif

#ifndef MCISLFAC__DEBUG_1MSHANDLER
	#define MCISLFAC__DEBUG_1MSHANDLER()
#endif

#ifndef MCISLFAC__DEBUG_5MSHANDLER
	#define MCISLFAC__DEBUG_5MSHANDLER()
#endif

#ifndef MCISLFAC__FASTHANDLER_ENTRY
	#define MCISLFAC__FASTHANDLER_ENTRY()
#endif

//=====================================================================================================================
//  --- Public Functions ----------------------------------------------------------------------------------------------
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------
/**
 * Initialize the Mci module.
 * Set initial values for all module variables.
 */
void Mci__Initialize(void)
{
	Mci_Params_Loaded = FALSE;
    MCISLFAC__DEBUG_INITIALIZE();
}





//---------------------------------------------------------------------------------------------------------------------
/**
 * This function is called every 250 us
 *
 */
void Mci__250usHandler(void)
{
    MCISLFAC__DEBUG_250USHANDLER();
}





//---------------------------------------------------------------------------------------------------------------------
/**
 * This function is called every 25 ms
 *
 */
void Mci__SlowHandler(void)
{
	if(Mci_Params_Loaded == TRUE)
    {
    	Mcl__SlowHandler();
    }
    MCISLFAC__DEBUG_SLOWHANDLER();
}




//---------------------------------------------------------------------------------------------------------------------
/**
 * This function is called every 1 ms
 *
 */
void Mci__1msHandler(void)
{
    MCISLFAC__DEBUG_1MSHANDLER();
}



//---------------------------------------------------------------------------------------------------------------------
/**
 * This function is called every 5 ms
 *
 */
void Mci__5msHandler(void)
{
    MCISLFAC__DEBUG_5MSHANDLER();
}



//---------------------------------------------------------------------------------------------------------------------
/**
 * This routine will run the motor with speed_rpm speed and ramp_rpm_per_s acceleration
 *
 * And also, is the acceleration to the next speed. This parameter is POSITIVE the MciHsfac will take care of its
 *           sign if a negative speed or deceleration is needed.
 * @return  MCI_CMD_ACCEPTED - command accepted
 *          MCI_CMD_DENIED - command denied.
 *          MCI_CMD_SPEED_OUT_OF_RANGE - the speed is bigger or smaller than the supported limits.
 *          MCI_CMD_RAMP_OUT_OF_RANGE - the ramp is faster or slower than the supported limits.
 */
MCI_CMD_RESPONSE_TYPE Mci__Run(MOTOR_ENUM_TYPE motor, sint16 speed_rpm, sint16 ramp_rpm_per_s)
{
    MCI_CMD_RESPONSE_TYPE ret_val = MCI_CMD_PARAM_NOT_LOADED;

    if(Mci_Params_Loaded == TRUE)
    {
    	ret_val = Mcl__Run(motor, speed_rpm, 0);
    }

	API220_RUN_CALLBACK(motor, speed_rpm, ramp_rpm_per_s, ret_val);
    return ret_val;
}





//---------------------------------------------------------------------------------------------------------------------
/**
 * Stop the motor regardless its speed with a desired rate. This commands always accepted.
 *
 * @param   ramp_rpm_per_s
 * @return  MCIHSFAC_CMD_ACCEPTED - command accepted
 *          MCIHSFAC_CMD_DENIED - command denied.
 */
MCI_CMD_RESPONSE_TYPE Mci__Stop(MOTOR_ENUM_TYPE motor, sint16 ramp_rpm_per_s)
{
    MCI_CMD_RESPONSE_TYPE ret_val = MCI_CMD_PARAM_NOT_LOADED;

    if(Mci_Params_Loaded == TRUE)
    {
    	ret_val = Mcl__Stop(motor, ramp_rpm_per_s);
    }

    API220_STOP_CALLBACK(motor, ramp_rpm_per_s, ret_val);
    return ret_val;
}





//---------------------------------------------------------------------------------------------------------------------
/**
 * Get the error structure
 * @param motor =  index to the motor. See the Mci.h file
 * @return ret_val = MciSlfac_Last_Failure variable value.
 */
uint32 Mci__GetErrorList(MOTOR_ENUM_TYPE motor)
{
    uint32 ret_val = 0;
    if(Mci_Params_Loaded == TRUE)
    {
    	ret_val = Mcl__GetErrorList();
    }

    return(ret_val);
}




//---------------------------------------------------------------------------------------------------------------------
/**
 * Get the digital structure
 * @param motor =  index to the motor. See the Mci.h file
 * @return ret_val = Mci status control variable value.
 */
uint32 Mci__GetDigitalList(MOTOR_ENUM_TYPE motor)
{
    uint32 ret_val;
    ret_val = 0;

    if(Mci_Params_Loaded == TRUE)
    {
    	ret_val = (uint32)Mcl__GetDigital(MCI_DI_REACHED_TARGET_SPEED);
    }

    return(ret_val);
}




//---------------------------------------------------------------------------------------------------------------------
/**
 * Read any digital data from the Mci
 *
 * @param   read_data is index of the parameter. See the Mci.h file
 * @return  TRUE/FALSE according to the type of the passed parameter. The default return is FALSE.
 */
uint8 Mci__GetDigital(MOTOR_ENUM_TYPE motor, MCI_DI_TYPE read_data)
{
    uint8  ret_val = 255; //Default response

    if(Mci_Params_Loaded == TRUE)
    {
    	ret_val = Mcl__GetDigital(read_data);
    }

    return ret_val;
}





//---------------------------------------------------------------------------------------------------------------------
/**
 * Write a digital data to the Mci.
 *
 * @param   write_data is the index to the data. See the Mci.h file.
 * @param   value TRUE/FALSE according to the selected data
 * @return  TRUE - value accepted
 *          FALSE - value denied - default answer.
 */
uint8 Mci__SetDigital(MOTOR_ENUM_TYPE motor, MCI_DO_TYPE write_data, unsigned char value)
{
	uint8  ret_val;
    ret_val = 0;

    return ret_val;
}





//---------------------------------------------------------------------------------------------------------------------
/**
 * Read analog data from the Mci.
 *
 * @param  read_data index to the parameter. See the Mci.h file
 * @return the parameter value. The default return is zero.
 */
sint32 Mci__GetAnalog(MOTOR_ENUM_TYPE motor, MCI_AI_TYPE read_data)
{
	sint32 ret_val;
	ret_val = 0;

	if(Mci_Params_Loaded == TRUE)
	{
		ret_val = Mcl__GetAnalog(read_data);
	}
	else if(Mci_Wash_Motor_Type == WM_SINGLE_SPEED_ASYNCH_SPH_PSC)
	{
		ret_val = MCI_GET_ANALOG_ALT_MOTOR(read_data);
	}

	return ret_val;
}




//---------------------------------------------------------------------------------------------------------------------
/**
 * Set analog data from the Mci.
 *
 * @param  Motor, index and data
 * @return FALSE/TRUE
 */
uint8 Mci__SetAnalog(MOTOR_ENUM_TYPE motor, MCI_AO_TYPE write_data, sint32 value)
{
    uint8 ret_val = FALSE;


    //API220_PUBLISHANALOG_CALLBACK(motor, write_data, value, ret_val);
    return(ret_val);
}




//---------------------------------------------------------------------------------------------------------------------
/**
 * Clear Error
 *
 */
uint8 Mci__ClearError(MOTOR_ENUM_TYPE motor)
{
    uint8 ret_val = (uint8)TRUE;

    if(Mci_Params_Loaded == TRUE)
    {
    	ret_val = Mcl__ClearError();
    	LOG_ADD_EVENT(MCI_EVENT_FAULT_CLEARED, (uint16)ret_val);
    }

    return(ret_val);
}




//---------------------------------------------------------------------------------------------------------------------
/**
 * Get Error Flag
 *
 */
uint8 Mci__GetError(MOTOR_ENUM_TYPE motor)
{
    uint8 ret_val = 0;

    if(Mci_Params_Loaded == TRUE)
    {
    	ret_val = Mcl__GetError(motor);
    }

    return ret_val;
}




//---------------------------------------------------------------------------------------------------------------------
/**
 * Set wash motor type. Call it after Mci__SetModuleType
 *
 */
void Mci__SetWashMotorType(APL_WASH_MOTOR_TYPE wash_type)
{
	Mci_Wash_Motor_Type = wash_type; /* Set Mci Wash Pump */

	if((wash_type == WM_SINGLE_SPEED_SYNCH_SPH_AW)  ||
	   (wash_type == WM_SINGLE_SPEED_SYNCH_SPH_PW))
	{
		if(Mci_Params_Loaded == FALSE)
		{
			Mci__ParameterLoading();
			if(Mci_Params_Loaded == TRUE)
			{
				Mcl__Initialize();
				Mcl__SetWashMotorType(wash_type);
				LOG_ADD_EVENT(MCI_EVENT_GWS_INITIALIZED, Mcl__GetParamsID());
			}
		}
	}
	else if(wash_type == WM_SINGLE_SPEED_ASYNCH_SPH_PSC)
	{
		MCI_INITIALIZE_ALT_MOTOR(wash_type); //Initialize Active Power for RIF Motor
		LOG_ADD_EVENT(MCI_EVENT_RIF_INITIALIZED, Mci_Wash_Motor_Type);
	}
}




//---------------------------------------------------------------------------------------------------------------------
/**
 *
 *
 */
void Mci__MotorControlHandler(void)
{
	MCISLFAC__FASTHANDLER_ENTRY();

    if(Mci_Params_Loaded == TRUE)
    {
		Mcl__RunningHandler();
	}
	else if(Mci_Wash_Motor_Type == WM_SINGLE_SPEED_ASYNCH_SPH_PSC)
	{
		MCI_RUNNING_ALT_MOTOR(); //Run alternative motor (RIF, for instance).
	}

	MCISLFAC__DEBUG_FASTHANDLER();
}




//---------------------------------------------------------------------------------------------------------------------
/**
 * VZC event handler
 *
 */
void Mci__ZeroCrossHandler(TC_EVENT_TYPE event, uint16 ccr_value)
{
    if(Mci_Params_Loaded == TRUE)
    {
		Mcl__ZeroCrossHandler(event, ccr_value);
	}
    MCISLFAC__DEBUG_ZEROCROSSHANDLER();
}




//---------------------------------------------------------------------------------------------------------------------
/**
 * Triac fire event handler
 *
 */
void Mci__TriacFireHandler(void)
{
    if(Mci_Params_Loaded == TRUE)
    {
		Mcl__TriacFireHandler(TC_UNKNOWN_EVENT);
	}
    MCISLFAC__DEBUG_TRIACHANDLER();
}





//=====================================================================================================================
//  --- Private Functions ---------------------------------------------------------------------------------------------
//=====================================================================================================================

#ifdef MCI_INTERNAL_PARAMETERS
#include "Mci_GWS_Params_prm.h"
#endif
//---------------------------------------------------------------------------------------------------------------------
/**
 * Function for loading parameters from setting file
 *
 */
void Mci__ParameterLoading(void)
{
    MCL_PARAMS_TYPE* mcl_params;
#ifndef MCI_INTERNAL_PARAMETERS
    SETTINGFILE_LOADER_TYPE params;

    //Initializing default variables
    Mci_Params_Loaded = FALSE;

    //Load parameters
    if (SettingFile__BasicLoader(SF_PTR_MCU_CLASS_A_MCI, SF_DISPL_MOTOR_PARAMS_GLOBAL_WASH_SYSTEM, &params) == PASS)
    {
        mcl_params = (MCL_PARAMS_TYPE*)(params.Data); //copying data into stack.
        if(Mcl__SetParams(mcl_params) == TRUE)
        {
            //If parameters properly loaded into Motor Control Module...
            Mci_Params_Loaded = TRUE;
        }
    }
    else
    {
    	LOG_ADD_EXCEPTION(MCI_EXCEPTION_PARAMETERS_NOT_LOADED, (uint16)Mci_Params_Loaded);
    }

#else
    //copying data into stack...
    mcl_params = (MCL_PARAMS_TYPE*)Mci_GWS_Params_SF; //lint !e927 Lint: 927 cast from pointer to pointer [MISRA 2004 Rule 11.4]
    if(Mcl__SetParams(mcl_params) == TRUE)
    {
        //If parameters properly loaded into Motor Control Module...
        Mci_Params_Loaded = TRUE;
    }
#endif
}
