/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */

/*
@startuml
	title Tank Fill State Machine
	'terminate function unused

	[*] --> INITIALIZE

	INITIALIZE --> FILL_WATER: StartTankFill
	INITIALIZE --> FILL_COMPLETE: FillCompleted

	INITIALIZE: entry / InitializeTankFillVariables

	FILL_WATER --> NO_WATER: NoWaterDetected
	FILL_WATER --> TANK_FILL_DELAY: WaterFillOver

	FILL_WATER: entry / FillWaterInitialCheck
	FILL_WATER: do / FillWater

	TANK_FILL_DELAY: entry / StartDelayTimer
	TANK_FILL_DELAY: do / WaitForTankFillDelay

	TANK_FILL_DELAY --> AFTER_FILL_CHECK_SUBCYCLE: AfterFillWaterCheckNeeded
	TANK_FILL_DELAY --> FILL_COMPLETE: FillCompleted / UpdateStatistics

	AFTER_FILL_CHECK_SUBCYCLE --> FILL_COMPLETE: FillCompleted / UpdateStatistics
	AFTER_FILL_CHECK_SUBCYCLE: entry / ResetAFSubcycleExecution

	AFTER_FILL_CHECK_SUBCYCLE: do / WaitAFSubcycleExecution

	NO_WATER --> FILL_WATER: RestartFill
	NO_WATER: entry / SetH2OAlarm
	NO_WATER: do / WaitForPauseEnd

@enduml
*/

//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
// -- This Module --
#include "TankFill.h"
#include "TankFill_fsm.h"
#include "Fill.h"
#include "SystemConfig.h"

// -- Other Modules --
#include "DishAuxVar.h"
#include "Fault.h"
#include "Log.h"
#include "Micro.h"
#include "NVData.h"
#include "Selector.h"
#include "SettingFile.h"
#include "Statistics.h"
#include <string.h>
#include "SubCycle.h"
#include "Supervisor.h"
#include "Vwi.h"


//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_TANK_FILL

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_TANK_FILL_LOG_MESSAGE_ID_ENUM
{
    ERROR_LOADING_PARAMETERS	= 1,
} MODULE_TANK_FILL_LOG_MESSAGE_ID_TYPE;


//! Volatile data for Tank Fill process
static CLASS_A_FILL_VOLATILE_DATA_TYPE Tank_Fill_Data;

//! Non volatile data for Tank Fill process
#pragma location = "_appliance_segment"
static CLASS_A_FILL_NV_DATA_TYPE Tank_Fill_NV_Data;

//! State machine state for Tank Fill process
#pragma location = "_appliance_segment"
static TANKFILL_FSM_STATE_TYPE Tank_Fill_State;


//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
static PASS_FAIL_TYPE ReadProcessParameters(PROCESS_CONTROL_TYPE* control);
static void NoWaterFoundInAfterFillChecks(void);


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------

//---------------------------------------------------------------------------------------------------------------------


/**
 * Initialize the TankFill module's variables.
 */
void TankFill__Initialize(void)
{
	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		if (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != (NVDATA_RESTORE_TYPE)NVDATA_RESTORE_OKAY)
		{
			Tank_Fill_State = FSM_STATE_NONE;
			Tank_Fill_NV_Data.Liters_Requested = 0;
			Tank_Fill_NV_Data.Fill_Timer = 0;
			Tank_Fill_NV_Data.H2O_Pause_Executed = FALSE;
		}

		memset(&Tank_Fill_Data, 0, sizeof(Tank_Fill_Data));

		Tank_Fill_Data.Process_Parameters_Loading = FAIL;
		Tank_Fill_Data.Subcycle_Executed = FALSE;
		Tank_Fill_Data.Flow_Rate_Calibration_Enabled = FALSE;
	}
}


/**
 * It implements the Tank Fill process
 */
PROCESS_RESULT_TYPE TankFill__Manager(PROCESS_CONTROL_TYPE* control)
{
	PROCESS_RESULT_TYPE result = PROCESS_COMPLETE;

	if ((control->Step_Initializing != (BOOL_TYPE)FALSE) ||
		(control->Resume_From_Reset != (BOOL_TYPE)FALSE) ||
		(control->Resume_From_Pause != (BOOL_TYPE)FALSE))
	{
		Tank_Fill_Data.Process_Parameters_Loading = ReadProcessParameters(control);
	}

	if (Tank_Fill_Data.Process_Parameters_Loading == PASS)
	{
		if (control->Step_Initializing != (BOOL_TYPE)FALSE)
		{
			// Initialize this instance of the TankFill process.
			TankFillFsmInitialize(&Tank_Fill_State);
		}

		if (control->Resume_From_Reset == (BOOL_TYPE)FALSE)
		{
			// TankFillFsmExecute() not called in first iteration after a cold reset to avoid a spurious Fill Valve turning on in case of
			// long power fail: actually, in this case, Fill process would be called for just one iteration before going in PAUSE.
			TankFillFsmExecute(&Tank_Fill_State);
		}

		result = ((Tank_Fill_State == FSM_STATE_FILL_COMPLETE) ? PROCESS_COMPLETE : PROCESS_BUSY);
	}

	return result;
}


/**
 * Called in SUB_CYCLE_END(), it checks if the ended subcycle is the Fill Check Water subcycle and,
 * if it is, it marks it as executed.
 */
void TankFill__SetSubcycleExecuted(uint8 compartment, uint8 subcycle_id, SUB_CYCLE_END_TYPE subcycle_end_code)
{
	if (Selector__GetCycleNameId(0, compartment , subcycle_id) == CYCLE_NAME_SPECIFIC_FILL_CHECK_WATER)
	{
		if ((subcycle_end_code == SUB_CYCLE_END_COMPLETED) || (subcycle_end_code == SUB_CYCLE_END_SET_STATE_PROCESS))
		{
			Tank_Fill_Data.Subcycle_Executed = TRUE;
		}
	}
}


/**
 * Called in PAUSE_EXIT(), it informs the process that the cycle has exited from PAUSE state.
 */
void TankFill__SetH2OPauseExecuted(void)
{
	Tank_Fill_NV_Data.H2O_Pause_Executed = TRUE;
}


/**
 * Called in SUB_CYCLE_START() and in PAUSE_ENTRY(), it disables the Flow Rate calibration
 */
void TankFill__DisableFlowRateCalibration(void)
{
	Tank_Fill_Data.Flow_Rate_Calibration_Enabled = FALSE;
}

//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

static PASS_FAIL_TYPE ReadProcessParameters(PROCESS_CONTROL_TYPE* control)
{
	PASS_FAIL_TYPE result = FAIL;
	SETTINGFILE_LOADER_TYPE loader;

	// Get the Fill process parameters from the setting file.
	if (SettingFile__MSettingBasicLoader(control->Setting_File_Index,
										 SF_PTR_ACU_PROCESS_FILL,
										 control->Data_Field_Index,
										 &loader) == FAIL)
	{
		LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, control->Data_Field_Index);
	}
	else
	{
		Tank_Fill_Data.Class_A_Fill_Process_Parameters = (CLASS_A_FILL_PROCESS_PARAMETER_TYPE *)(void *)loader.Data;

		if ( FAIL == SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS,
											  DISPL_CLASS_A_FILL,
											  &loader) )
		{
			LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, (uint16)SF_PTR_ACU_ALGORITHM_PARAMETERS);
		}
		else
		{
			Tank_Fill_Data.Class_A_Fill_Parameters = (CLASS_A_FILL_PARAMETER_TYPE *)(void *)loader.Data;

			result = PASS;
		}
	}

	return result;
}


static void NoWaterFoundInAfterFillChecks(void)
{
	if (Liters_In_Tub > Liters_In_Tub_Before_Fill)
	{
		Liters_In_Water_Tank = Liters_In_Tub - Liters_In_Tub_Before_Fill;
	}
	else
	{
		Liters_In_Water_Tank = 0;
	}
	Liters_In_Tub = Liters_In_Tub_Before_Fill;

	Tank_State_Fill = TANK_STATE_PASSED;
	Fill__SetBitmapBit(TANK_STATE_CLEAN);
}


//=====================================================================================================================
//  --- Private State Machine Customization Functions -----------------------------------------------------------------
//=====================================================================================================================


//=====================================================================================================================
// Tank Fill State Machine customization functions.
// NOTE: do not modify this header or the StateMachineCodeGenerator will not be able to find it.
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void InitializeTankFillVariables(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	Liters_In_Tub_Before_Fill = Liters_In_Tub;
	Liters_In_Tank_Before_Fill = Liters_In_Water_Tank;

	if (Liters_In_Water_Tank >= ((uint16)Tank_Fill_Data.Class_A_Fill_Parameters->Liters_For_Tank_Empty_Max * (uint16)5))
	{
		DISPATCH_FSM_EVENT(FSM_EVENT_FILLCOMPLETED);
	}
	else
	{
		if ((Liters_In_Tub >= ((uint16)Tank_Fill_Data.Class_A_Fill_Parameters->Liters_For_WI_Empty_Max * (uint16)5)) &&
			((Tank_State_Fill != TANK_STATE_PASSED) || (Tank_State_Drain != TANK_STATE_PASSED)))
		{
			DISPATCH_FSM_EVENT(FSM_EVENT_FILLCOMPLETED);
		}
		else
		{
			Tank_State_Fill = TANK_STATE_RUNNING;
			Fill__ClearBitmapBit(TANK_STATE_CLEAN);
			DISPATCH_FSM_EVENT(FSM_EVENT_STARTTANKFILL);
		}
	}
}


/**
 * @brief
 */
static void FillWater(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	switch (Fill__ClassAFillCore(&Tank_Fill_Data, &Tank_Fill_NV_Data, FILL_OPTION_TANK_FILL))
	{
		case FILL_CORE_NO_WATER_DETECTED:
			DISPATCH_FSM_EVENT(FSM_EVENT_NOWATERDETECTED);
			break;

		case FILL_CORE_WATER_FILL_OVER:
			DISPATCH_FSM_EVENT(FSM_EVENT_WATERFILLOVER);
			break;

		default:	// Includes FILL_CORE_WATER_CHECK_NEEDED (that conn't be returned
					// in case of Tank Fill) and FILL_CORE_NO_STATE_CHANGE
			break;
	}
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void FillWaterInitialCheck(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	Fill__ClassAFillCoreInit(&Tank_Fill_Data, &Tank_Fill_NV_Data);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void ResetAFSubcycleExecution(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	Tank_Fill_Data.Subcycle_Executed = FALSE;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void SetH2OAlarm(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	H2O_Alarm = TRUE; // Set in entry function to manage a specific use case in case of power fail
	Tank_Fill_NV_Data.H2O_Pause_Executed = FALSE;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void WaitAFSubcycleExecution(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	if (Tank_Fill_Data.Subcycle_Executed == FALSE)
	{
		(void)SubCycle__RequestStart(0, Tank_Fill_Data.Class_A_Fill_Parameters->Fill_Check_Water_Subcycle_Priority);
	}
	else
	{
		VWI_WATER_SENSE_TYPE last_valid_water_status;

		last_valid_water_status = Vwi__GetLastValidWaterStatus();

		if ((last_valid_water_status == WS_WATER) || (last_valid_water_status == WS_UNSTABLE_WATER))
		{
			// Water is present
			Liters_In_Water_Tank = 0;
			Tank_State_Fill = TANK_STATE_FAIL;
			Tank_State_Drain = TANK_STATE_UNKNOWN;

			Fault__ConditionDetected(FAULT_ID_WATER_TANK_VALVE_NOT_FUNCTIONING);
		}
		else
		{
			// No Water
			NoWaterFoundInAfterFillChecks();
		}

		DISPATCH_FSM_EVENT(FSM_EVENT_FILLCOMPLETED);
	}
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void WaitForPauseEnd(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	if (Tank_Fill_NV_Data.H2O_Pause_Executed == FALSE)
	{
		if (Fault__IsInFaultState(FAULT_ID_NO_WATER_FILL_VALVE_PROBLEM) == FALSE)
		{
			Fault__ConditionDetected(FAULT_ID_NO_WATER);
		}

		(void)Supervisor__SetStart(0, FS_PAUSE_CONDITION);
	}
	else
	{
		DISPATCH_FSM_EVENT(FSM_EVENT_RESTARTFILL);
	}
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void StartDelayTimer(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	Tank_Fill_NV_Data.Fill_Timer = 0;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void WaitForTankFillDelay(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	if (Tank_Fill_NV_Data.Fill_Timer < ((uint16)Tank_Fill_Data.Class_A_Fill_Parameters->Tank_Fill_Delay_Time * (uint16)(5 * FILL_CALLS_PER_SECOND)))
	{
		Tank_Fill_NV_Data.Fill_Timer ++;
	}
	else
	{
		if (Liters_In_Tub_Before_Fill <	((uint16)Tank_Fill_Data.Class_A_Fill_Parameters->Liters_For_WI_Empty_Max * (uint16)5))
		{
			if ((Tank_Fill_Data.Class_A_Fill_Parameters->Fill_Check_Water_Subcycle_Priority != 0U) && (Interpreter__GetStatus().Sub_Cycle[COMPARTMENT_DEFAULT] == 0U))
			{
				DISPATCH_FSM_EVENT(FSM_EVENT_AFTERFILLWATERCHECKNEEDED);
			}
			else
			{
				// Fill Check subcycle is not present in setting file, or Fill is being executed inside a subcycle:
				// it is not possible to start Fill Check Subcycle, recovery action is to assume water is not present
				NoWaterFoundInAfterFillChecks();

				DISPATCH_FSM_EVENT(FSM_EVENT_FILLCOMPLETED);
			}

		}
		else
		{
			if (Liters_In_Tub > Liters_In_Tub_Before_Fill)
			{
				Liters_In_Water_Tank = Liters_In_Tub - Liters_In_Tub_Before_Fill;
			}
			else
			{
				Liters_In_Water_Tank = 0;
			}
			Liters_In_Tub = Liters_In_Tub_Before_Fill;
			Tank_State_Fill = TANK_STATE_UNKNOWN;
			Tank_State_Drain = TANK_STATE_UNKNOWN;
			Fill__SetBitmapBit(TANK_STATE_CLEAN);

			DISPATCH_FSM_EVENT(FSM_EVENT_FILLCOMPLETED);
		}
	}
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void UpdateStatistics(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	StatisticsDish__UpdateFstFillWaterTemp();
}
