/*
 * LITTFaultMonitor.h
 *
 *  Created on: 6 lis 2018
 *      Author: WAZNYP
 */

#ifndef SOURCE_CATEGORY_APPLICATION_APPLICATIONDISH_MONITORS_LITTFAULTMONITOR_LITTFAULTMONITOR_H_
#define SOURCE_CATEGORY_APPLICATION_APPLICATIONDISH_MONITORS_LITTFAULTMONITOR_LITTFAULTMONITOR_H_

void LITTFaultMonitor__Initialize(void);
void LITTFaultMonitor__Execution(void);
void LITTFaultMonitor__CycleStarted(void);

#endif /* SOURCE_CATEGORY_APPLICATION_APPLICATIONDISH_MONITORS_LITTFAULTMONITOR_LITTFAULTMONITOR_H_ */
