/**
 *  @details     This module defines all parameters of the motor control loop for GWS Wash Pump.
 *               Generated by Eduardo H Couto
 *  @copyright   Copyright 2020.  Whirlpool Corporation.  All rights reserved - CONFIDENTIAL
 *
 */

//=====================================================================================================================
//-------------------------------------- PUBLIC (Extern Variables, Constants & Defines) -------------------------------
//=====================================================================================================================

#define  PARAMS_RATED                0

/*  Set Params to be Used */
#define  PARAMS_DEF       PARAMS_RATED

#if(PARAMS_DEF == PARAMS_RATED)
/*uint8 Motor_Wash_Type;                          6,\  */
/*uint8 Current_Voltage_Sensor_Mode;              0,\ */
/*float32 Winding_Resistance;                     8.2,\  */
/*float32 Winding_Inductance;                     0.132,\*/
/*uint8 Meas_Pulse_Angle;                         48,\ */
/*uint16 First_Pulse_Compensation_A;              13,\ */
/*uint16 First_Pulse_Compensation_B;              27,\ */
/*uint8 First_Pulse_Max_Limit;                    56,\ */
/*uint8 Open_Loop_Angle_Limit_Add;                10,\ */
/*uint8 Open_Loop_Max_Limit;                      46,\ */
/*uint8 Bemf_Shift_Reference;                     0,\  */
/*uint16 Power_Drop_Thr;                          5,\  */
/*uint16 Volt_At_Cycle_End_Thr;                   150,\  */
/*uint16 Voltage_Base;                            94,\  */
/*uint8 Current_Base;                             10,\  */
/*uint16 Power_Base;                              20,\ */
/*uint32 Current_Sensor_Gain;                     8537 "0.004071004389",\ */
/*uint32 Voltage_Sensor_Gain;                     240955 "0.1148965181",\*/
/*uint32 Shirt_Limiter_Coff_A;                    9000,\*/
/*uint32 Shirt_Limiter_Coff_B;                    6000,\  */
/*uint32 Mcisflac_Fast_Handler_Frequency;         5000,\*/
/*uint32 Mcisflac_Timer_Frequency;                6400000,\  */
/*uint16 Under_Curr_Thr;                          50L,\*/
/*uint16 Over_Curr_Thr;                           700,\*/
/*uint16 Current_Failure_Debounce_Time;           2000,\*/
/*uint16 Offset_Alpha_IIR;                        15,\ */
/*uint16 Bemf_Shift_Alpha_IIR;                    2,\  */
/*uint16 Semi_Period_Alpha_IIR;                   3,\  */
/*uint16 Bemf_Alpha_IIR;                          7,\  */
/*uint16 Bemf_Alpha_2_IIR;                        2,\  */
/*uint16 Bemf_Shift_Init_Value;                   30,\ */
/*float32 P2P_Detection_Period;                   0.022,\ */
/*uint16 Prescaler_for_Active_Power;              1024,\  */
/*uint16 Wait_Between_Meas_Time;                  500,\ */
/*uint16 Correct_Trigger_Debounce;                7,\  */
/*uint16 Commom_Meas_Pulse_Angle;                 48,\ */
/*uint16 ZC_Current_Detection_Thr;                150,\*/
/*uint16 ZC_Voltage_Detection_Thr;                250,\*/
/*uint16 Observer_Operation_Max_Limit;            900,\*/
/*uint16 Flat_Bemf_Detection_Thr;                 60,\ */
/*uint16 Motor_Stop_Detection_Thr;                32,\ */
/*sint32 Bemf_Shift_PI_A_Param;                   500,\ */
/*sint32 Bemf_Shift_PI_B_Param;                   -333,\*/
/*uint16 Bemf_Shift_PI_Max_Out;                   60,\ */
/*uint16 Bemf_Shift_PI_Ref_Update_Thr;            150,\*/
/*uint16 Triac_Trigger_Angle_Limit;               80,\ */
/*float32 Motor_Stop_Detection_Time;              3.5,\  */
/*uint16 Rotor_Debounce_Thr;                      10,\ */
/*uint16 Open_Loop_Timeout;                       500,\*/
/*uint8 Mci_Params_ID;                            102,\ */

uint8 Mci_GWS_Params_SF[115] =
{
/*uint8 Motor_Wash_Type;                          6,\  */  6,\
/*uint8 Current_Voltage_Sensor_Mode;              0,\ */   0,\
/*float32 Winding_Resistance_b1;                  51,\ */  51,\
/*float32 Winding_Resistance_b2;                  51,\ */  51,\
/*float32 Winding_Resistance_b3;                  3,\  */  3,\
/*float32 Winding_Resistance_b4;                  65,\ */  65,\
/*float32 Winding_Inductance_b1;                  2,\*/    2,\
/*float32 Winding_Inductance_b2;                  43,\ */  43,\
/*float32 Winding_Inductance_b3;                  7,\ */   7,\
/*float32 Winding_Inductance_b4;                  62,\ */  62,\
/*uint8 Meas_Pulse_Angle;                         48,\ */  48,\
/*uint16 First_Pulse_Compensation_A_b1;           13,\ */  13,\
/*uint16 First_Pulse_Compensation_A_b2;           0,\  */  0,\
/*uint16 First_Pulse_Compensation_B_b1;           27,\ */  27,\
/*uint16 First_Pulse_Compensation_B_b2;           0,\  */  0,\
/*uint8 First_Pulse_Max_Limit;                    56,\ */  56,\
/*uint8 Open_Loop_Angle_Limit_Add;                10,\ */  10,\
/*uint8 Open_Loop_Max_Limit;                      46,\ */  46,\
/*uint8 Bemf_Shift_Reference;                     0,\  */  0,\
/*uint16 Power_Drop_Thr_b1;                       5,\  */  5,\
/*uint16 Power_Drop_Thr_b2;                       0,\  */  0,\
/*uint16 Volt_At_Cycle_End_Thr_b1;                150,\*/  150,\
/*uint16 Volt_At_Cycle_End_Thr_b2;                0,\  */  0,\
/*uint16 Voltage_Base_b1;                         94,\*/   94,\
/*uint16 Voltage_Base_b2;                         0,\*/    0,\
/*uint8 Current_Base;                             10,\  */ 10,\
/*uint16 Power_Base_b1;                           20,\ */  20,\
/*uint16 Power_Base_b2;                           0,\  */  0,\
/*uint32 Current_Sensor_Gain_b1;                  89,\ */  89,\
/*uint32 Current_Sensor_Gain_b2;                  33,\ */  33,\
/*uint32 Current_Sensor_Gain_b3;                  0,\  */  0,\
/*uint32 Current_Sensor_Gain_b4;                  0,\  */  0,\
/*uint32 Voltage_Sensor_Gain_b1;                  59,\*/   59,\
/*uint32 Voltage_Sensor_Gain_b2;                  173,\*/  173,\
/*uint32 Voltage_Sensor_Gain_b3;                  3,\  */  3,\
/*uint32 Voltage_Sensor_Gain_b4;                  0,\  */  0,\
/*uint32 Shirt_Limiter_Coff_A_b1;                 40,\*/   40,\
/*uint32 Shirt_Limiter_Coff_A_b2;                 35,\*/   35,\
/*uint32 Shirt_Limiter_Coff_A_b3;                 0,\  */  0,\
/*uint32 Shirt_Limiter_Coff_A_b4;                 0,\  */  0,\
/*uint32 Shirt_Limiter_Coff_B_b1;                 112,\*/  112,\
/*uint32 Shirt_Limiter_Coff_B_b2;                 23,\ */   23,\
/*uint32 Shirt_Limiter_Coff_B_b3;                 0,\  */  0,\
/*uint32 Shirt_Limiter_Coff_B_b4;                 0,\  */  0,\
/*uint32 Mcisflac_Fast_Handler_Frequency_b1;      136,\*/  136,\
/*uint32 Mcisflac_Fast_Handler_Frequency_b2;      19,\ */  19,\
/*uint32 Mcisflac_Fast_Handler_Frequency_b3;      0,\  */  0,\
/*uint32 Mcisflac_Fast_Handler_Frequency_b4;      0,\  */  0,\
/*uint32 Mcisflac_Timer_Frequency_b1;             0,\  */  0,\
/*uint32 Mcisflac_Timer_Frequency_b2;             168,\*/  168,\
/*uint32 Mcisflac_Timer_Frequency_b3;             97,\ */  97,\
/*uint32 Mcisflac_Timer_Frequency_b4;             0,\  */  0,\
/*uint16 Under_Curr_Thr_b1;                       50L,\*/  50L,\
/*uint16 Under_Curr_Thr_b2;                       0,\  */  0,\
/*uint16 Over_Curr_Thr_b1;                        188,\*/  188,\
/*uint16 Over_Curr_Thr_b2;                        2,\  */  2,\
/*uint16 Current_Failure_Debounce_Time_b1;        208,\*/  208,\
/*uint16 Current_Failure_Debounce_Time_b2;        7,\  */  7,\
/*uint16 Offset_Alpha_IIR_b1;                     15,\ */  15,\
/*uint16 Offset_Alpha_IIR_b2;                     0,\  */  0,\
/*uint16 Bemf_Shift_Alpha_IIR_b1;                 2,\  */  2,\
/*uint16 Bemf_Shift_Alpha_IIR_b2;                 0,\  */  0,\
/*uint16 Semi_Period_Alpha_IIR_b1;                3,\  */  3,\
/*uint16 Semi_Period_Alpha_IIR_b2;                0,\  */  0,\
/*uint16 Bemf_Alpha_IIR_b1;                       7,\  */  7,\
/*uint16 Bemf_Alpha_IIR_b2;                       0,\  */  0,\
/*uint16 Bemf_Alpha_2_IIR_b1;                     2,\  */  2,\
/*uint16 Bemf_Alpha_2_IIR_b2;                     0,\  */  0,\
/*uint16 Bemf_Shift_Init_Value_b1;                30,\ */  30,\
/*uint16 Bemf_Shift_Init_Value_b2;                0,\  */  0,\
/*float32 P2P_Detection_Period_b1;                88,\ */  88,\
/*float32 P2P_Detection_Period_b2;                57,\ */  57,\
/*float32 P2P_Detection_Period_b3;                180,\*/  180,\
/*float32 P2P_Detection_Period_b4;                60,\ */  60,\
/*uint16 Prescaler_for_Active_Power_b1;           0,\  */  0,\
/*uint16 Prescaler_for_Active_Power_b2;           4,\  */  4,\
/*uint16 Wait_Between_Meas_Time_b1;               244,\*/   244,\
/*uint16 Wait_Between_Meas_Time_b2;               1,\  */  1,\
/*uint16 Correct_Trigger_Debounce_b1;             7,\  */  7,\
/*uint16 Correct_Trigger_Debounce_b2;             0,\  */  0,\
/*uint16 Commom_Meas_Pulse_Angle_b1;              48,\ */  48,\
/*uint16 Commom_Meas_Pulse_Angle_b2;              0,\  */  0,\
/*uint16 ZC_Current_Detection_Thr_b1;             150,\*/  150,\
/*uint16 ZC_Current_Detection_Thr_b2;             0,\  */  0,\
/*uint16 ZC_Voltage_Detection_Thr_b1;             250,\*/  250,\
/*uint16 ZC_Voltage_Detection_Thr_b2;             0,\  */  0,\
/*uint16 Observer_Operation_Max_Limit_b1;         132,\*/  132,\
/*uint16 Observer_Operation_Max_Limit_b2;         3,\  */  3,\
/*uint16 Flat_Bemf_Detection_Thr_b1;              60,\ */  60,\
/*uint16 Flat_Bemf_Detection_Thr_b2;              0,\  */  0,\
/*uint16 Motor_Stop_Detection_Thr_b1;             32,\ */  32,\
/*uint16 Motor_Stop_Detection_Thr_b2;             0,\  */  0,\
/*sint32 Bemf_Shift_PI_A_Param_b1;                244,\ */ 244,\
/*sint32 Bemf_Shift_PI_A_Param_b2;                1,\*/    1,\
/*sint32 Bemf_Shift_PI_A_Param_b3;                0,\  */  0,\
/*sint32 Bemf_Shift_PI_A_Param_b4;                0,\  */  0,\
/*sint32 Bemf_Shift_PI_B_Param_b1;                179,\*/  179,\
/*sint32 Bemf_Shift_PI_B_Param_b2;                254,\*/  254,\
/*sint32 Bemf_Shift_PI_B_Param_b3;                255,\*/  255,\
/*sint32 Bemf_Shift_PI_B_Param_b4;                255,\*/  255,\
/*uint16 Bemf_Shift_PI_Max_Out_b1;                60,\ */  60,\
/*uint16 Bemf_Shift_PI_Max_Out_b2;                0,\  */  0,\
/*uint16 Bemf_Shift_PI_Ref_Update_Thr_b1;         150,\*/  150,\
/*uint16 Bemf_Shift_PI_Ref_Update_Thr_b2;         0,\  */  0,\
/*uint16 Triac_Trigger_Angle_Limit_b1;            80,\ */  80,\
/*uint16 Triac_Trigger_Angle_Limit_b2;            0,\  */  0,\
/*float32 Motor_Stop_Detection_Time_b1;           0,\  */  0,\
/*float32 Motor_Stop_Detection_Time_B2;           0,\  */  0,\
/*float32 Motor_Stop_Detection_Time_b3;           96,\ */  96,\
/*float32 Motor_Stop_Detection_Time_b4;           64,\ */  64,\
/*uint16 Rotor_Debounce_Thr_b1;                   10,\ */  10,\
/*uint16 Rotor_Debounce_Thr_b2;                   0,\  */  0,\
/*uint16 Open_Loop_Timeout_b1;                    244,\*/  244,\
/*uint16 Open_Loop_Timeout_b2;                    1,\  */  1,\
/*uint8 Mci_Params_ID;                            102,\ */ 102,\
};
#endif
