/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */

/*
@startuml
	title Class A Fill State Machine
	'terminate function unused

	[*] --> FILL_WATER :/ InitializeClassAFillVariables

	FILL_WATER --> AFTER_FILL_CHECK_SUBCYCLE: AfterFillWaterCheckNeeded
	FILL_WATER --> NO_WATER: NoWaterDetected
	FILL_WATER --> FILL_CHECK_SUBCYCLE: WaterCheckNeeded
	FILL_WATER --> FILL_COMPLETE: FillCompleted

	FILL_WATER: entry / FillWaterInitialCheck
	FILL_WATER: do / FillWater

	FILL_CHECK_SUBCYCLE --> NO_WATER: NoWaterDetected
	FILL_CHECK_SUBCYCLE --> AFTER_FILL_CHECK_SUBCYCLE: AfterFillWaterCheckNeeded
	FILL_CHECK_SUBCYCLE --> FILL_COMPLETE: FillCompleted

	FILL_CHECK_SUBCYCLE: entry / ResetSubcycleExecution
	FILL_CHECK_SUBCYCLE: do / WaitSubcycleExecution


	AFTER_FILL_CHECK_SUBCYCLE --> FILL_COMPLETE: FillCompleted
	AFTER_FILL_CHECK_SUBCYCLE: entry / ResetAFSubcycleExecution

	AFTER_FILL_CHECK_SUBCYCLE: do / WaitAFSubcycleExecution

	NO_WATER --> FILL_WATER: RestartFill
	NO_WATER: entry / SetH2OAlarm
	NO_WATER: do / WaitForPauseEnd

	FILL_COMPLETE: entry / UpdateStatistics

@enduml
*/

//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
// -- This Module --
#include "ClassAFill.h"
#include "ClassAFill_fsm.h"
#include "Fill.h"
#include "SystemConfig.h"

// -- Other Modules --
#include "DishAuxVar.h"
#include "Fault.h"
#include "Log.h"
#include "Micro.h"
#include "NVData.h"
#include "Selector.h"
#include "SettingFile.h"
#include "Statistics.h"
#include <string.h>
#include "SubCycle.h"
#include "Supervisor.h"
#include "Vwi.h"


//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------
extern uint16 Liters_In_Tub;
extern uint16 Liters_Current_Fill;
extern BOOL_TYPE H2O_Alarm;

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_CLASS_A_FILL

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_CLASS_A_FILL_LOG_MESSAGE_ID_ENUM
{
    ERROR_LOADING_PARAMETERS			= 1,
} MODULE_CLASS_A_FILL_LOG_MESSAGE_ID_TYPE;

//! Return values for AfterFillCheck() function
typedef enum AFTER_FILL_CHECK_RET_ENUM
{
	AFTER_FILL_COMPLETE_FILL = 0,
	AFTER_FILL_WATER_CHECK_NEEDED
} AFTER_FILL_CHECK_RET_TYPE;

//! Volatile data for Class A Fill process
static CLASS_A_FILL_VOLATILE_DATA_TYPE Fill_Data;

//! Non volatile data for Class A Fill process
#pragma location = "_appliance_segment"
static CLASS_A_FILL_NV_DATA_TYPE Fill_NV_Data;

//! State machine state for Class A Fill process
#pragma location = "_appliance_segment"
static CLASSAFILL_FSM_STATE_TYPE Class_A_Fill_State;


//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
static PASS_FAIL_TYPE ReadProcessParameters(PROCESS_CONTROL_TYPE* control);
static AFTER_FILL_CHECK_RET_TYPE AfterFillCheck(void);
static void NoWaterFoundInAfterFillChecks(void);


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------

//---------------------------------------------------------------------------------------------------------------------


/**
 * Initialize the ClassAFill module's variables.
 */
void ClassAFill__Initialize(void)
{
	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		if (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != (NVDATA_RESTORE_TYPE)NVDATA_RESTORE_OKAY)
		{
			Class_A_Fill_State = FSM_STATE_NONE;
			Fill_NV_Data.Liters_Requested = 0;
			Fill_NV_Data.Fill_Timer = 0;
			Fill_NV_Data.H2O_Pause_Executed = FALSE;
		}

		memset(&Fill_Data, 0, sizeof(Fill_Data));

		Fill_Data.Process_Parameters_Loading = FAIL;
		Fill_Data.Subcycle_Executed = FALSE;
		Fill_Data.Flow_Rate_Calibration_Enabled = FALSE;
	}
}


/**
 * It implements the Class A Fill process
 */
PROCESS_RESULT_TYPE ClassAFill__Manager(PROCESS_CONTROL_TYPE* control)
{
	PROCESS_RESULT_TYPE result = PROCESS_COMPLETE;

	if ((control->Step_Initializing != (BOOL_TYPE)FALSE) ||
		(control->Resume_From_Reset != (BOOL_TYPE)FALSE) ||
		(control->Resume_From_Pause != (BOOL_TYPE)FALSE))
	{
		Fill_Data.Process_Parameters_Loading = ReadProcessParameters(control);
	}

	if (Fill_Data.Process_Parameters_Loading == PASS)
	{
		if (control->Step_Initializing != (BOOL_TYPE)FALSE)
		{
			// Initialize this instance of the ClassAFill process.
			ClassAFillFsmInitialize(&Class_A_Fill_State);
		}

		if (control->Resume_From_Reset == (BOOL_TYPE)FALSE)
		{
			// ClassAFillExecute() not called in first iteration after a cold reset to avoid a spurious Fill Valve turning on in case of
			// long power fail: actually, in this case, Fill process would be called for just one iteration before going in PAUSE.
			ClassAFillFsmExecute(&Class_A_Fill_State);
		}

		result = ((Class_A_Fill_State == FSM_STATE_FILL_COMPLETE) ? PROCESS_COMPLETE : PROCESS_BUSY);
	}

	return result;
}


/**
 * Called in SUB_CYCLE_END(), it checks if the ended subcycle is the Fill Check Water subcycle and,
 * if it is, it marks it as executed.
 */
void ClassAFill__SetSubcycleExecuted(uint8 compartment, uint8 subcycle_id, SUB_CYCLE_END_TYPE subcycle_end_code)
{
	if (Selector__GetCycleNameId(0, compartment , subcycle_id) == CYCLE_NAME_SPECIFIC_FILL_CHECK_WATER)
	{
		if ((subcycle_end_code == SUB_CYCLE_END_COMPLETED) || (subcycle_end_code == SUB_CYCLE_END_SET_STATE_PROCESS))
		{
			Fill_Data.Subcycle_Executed = TRUE;
		}
	}
}


/**
 * Called in PAUSE_EXIT(), it informs the process that the cycle has exited from PAUSE state.
 */
void ClassAFill__SetH2OPauseExecuted(void)
{
		Fill_NV_Data.H2O_Pause_Executed = TRUE;
}


/**
 * Called in SUB_CYCLE_START() and in PAUSE_ENTRY(), it disables the Flow Rate calibration
 */
void ClassAFill__DisableFlowRateCalibration(void)
{
	Fill_Data.Flow_Rate_Calibration_Enabled = FALSE;
}

//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

static PASS_FAIL_TYPE ReadProcessParameters(PROCESS_CONTROL_TYPE* control)
{
	PASS_FAIL_TYPE result = FAIL;
	SETTINGFILE_LOADER_TYPE loader;

	// Get the Fill process parameters from the setting file.
	if (SettingFile__MSettingBasicLoader(control->Setting_File_Index,
										 SF_PTR_ACU_PROCESS_FILL,
										 control->Data_Field_Index,
										 &loader) == FAIL)
	{
		LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, control->Data_Field_Index);
	}
	else
	{
		Fill_Data.Class_A_Fill_Process_Parameters = (CLASS_A_FILL_PROCESS_PARAMETER_TYPE *)(void *)loader.Data;

		if ( FAIL == SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS,
											  DISPL_CLASS_A_FILL,
											  &loader) )
		{
			LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, (uint16)SF_PTR_ACU_ALGORITHM_PARAMETERS);
		}
		else
		{
			Fill_Data.Class_A_Fill_Parameters = (CLASS_A_FILL_PARAMETER_TYPE *)(void *)loader.Data;

			result = PASS;
		}
	}

	return result;
}


static AFTER_FILL_CHECK_RET_TYPE AfterFillCheck(void)
{
	AFTER_FILL_CHECK_RET_TYPE ret_value = AFTER_FILL_COMPLETE_FILL;

	if ((Liters_In_Tub_Before_Fill < ((uint16)Fill_Data.Class_A_Fill_Parameters->Liters_For_WI_Empty_Max * (uint16)5)) &&
		(Liters_In_Tub > ((uint16)Fill_Data.Class_A_Fill_Parameters->Liters_For_WI_Full_Min * (uint16)5)))
	{
		if ((Fill_Data.Class_A_Fill_Parameters->Fill_Check_Water_Subcycle_Priority != 0U) && (Interpreter__GetStatus().Sub_Cycle[COMPARTMENT_DEFAULT] == 0U))
		{
			ret_value = AFTER_FILL_WATER_CHECK_NEEDED;
		}
		else
		{
			// Fill Check subcycle is not present in setting file, or Fill is being executed inside a subcycle:
			// it is not possible to start Fill Check Subcycle, process is completed without doing anything else.
		}
	}
	else
	{
		if (Liters_In_Water_Tank < ((uint16)Fill_Data.Class_A_Fill_Parameters->Liters_For_Tank_Empty_Max * (uint16)5))
		{
			sint32 sum = (sint32)Liters_Unchecked + (sint32)Liters_In_Tub - (sint32)Liters_In_Tub_Before_Fill;

			if (sum < 0)
			{
				sum = 0;
			}
			else if (sum > __UNSIGNED_SHORT_MAX__)
			{
				sum = __UNSIGNED_SHORT_MAX__;
			}
			else
			{
				// Do nothing, sum fits in uint16
			}
			Liters_Unchecked = (uint16)sum;

			if (Liters_Unchecked >= ((uint16)Fill_Data.Class_A_Fill_Parameters->Liters_Unchecked_Max * (uint16)5))
			{
				Tank_State_Fill = TANK_STATE_UNKNOWN;
				Tank_State_Drain = TANK_STATE_UNKNOWN;
			}
		}
	}

	return ret_value;
}

static void NoWaterFoundInAfterFillChecks(void)
{
	sint32 sum = (sint32)Liters_In_Water_Tank + (sint32)Liters_In_Tub - (sint32)Liters_In_Tub_Before_Fill;

	if (sum < 0)
	{
		sum = 0;
	}
	else if (sum > __UNSIGNED_SHORT_MAX__)
	{
		sum = __UNSIGNED_SHORT_MAX__;
	}
	else
	{
		// Do nothing, sum fits in uint16
	}

	if (Liters_In_Water_Tank < ((uint16)Fill_Data.Class_A_Fill_Parameters->Liters_For_Tank_Empty_Max * (uint16)5))
	{
		if (sum < ((sint32)Fill_Data.Class_A_Fill_Parameters->Liters_In_Tank_Max * 5))
		{
			Liters_In_Water_Tank = (uint16)sum;
		}
		else
		{
			Liters_In_Water_Tank = (uint16)Fill_Data.Class_A_Fill_Parameters->Liters_In_Tank_Max * (uint16)5;
		}

		Liters_In_Tub_Before_Fill = 0;
		Tank_State_Fill = TANK_STATE_UNKNOWN;
		Tank_State_Drain = TANK_STATE_FAIL;

		Fault__ConditionDetected(FAULT_ID_WATER_TANK_VALVE_NOT_FUNCTIONING);

		Fill__SetBitmapBit(SENSED_DRAIN_REQUESTED_BY_FILL);
	}
	else
	{
		if (sum < ((sint32)Fill_Data.Class_A_Fill_Parameters->Liters_In_Tank_Max * 5))
		{
			Liters_In_Water_Tank = (uint16)sum;
		}
		else
		{
			Liters_In_Water_Tank = (uint16)Fill_Data.Class_A_Fill_Parameters->Liters_In_Tank_Max * (uint16)5;
		}

		Tank_State_Fill = TANK_STATE_FAIL;
		Tank_State_Drain = TANK_STATE_FAIL;

		Fault__ConditionDetected(FAULT_ID_WATER_TANK_VALVE_STUCK_OPEN);
	}
}

//=====================================================================================================================
//  --- Private State Machine Customization Functions -----------------------------------------------------------------
//=====================================================================================================================


//=====================================================================================================================
// Class A Fill State Machine customization functions.
// NOTE: do not modify this header or the StateMachineCodeGenerator will not be able to find it.
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void InitializeClassAFillVariables(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	Fill__ClearBitmapBit(SENSED_DRAIN_REQUESTED_BY_FILL);
}


/**
 * @brief
 */
static void FillWater(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	switch (Fill__ClassAFillCore(&Fill_Data, &Fill_NV_Data, FILL_OPTION_CLASS_A_FILL))
	{
		case FILL_CORE_NO_WATER_DETECTED:
			DISPATCH_FSM_EVENT(FSM_EVENT_NOWATERDETECTED);
			break;

		case FILL_CORE_WATER_CHECK_NEEDED:
			DISPATCH_FSM_EVENT(FSM_EVENT_WATERCHECKNEEDED);
			break;

		case FILL_CORE_WATER_FILL_OVER:

			switch (AfterFillCheck())
			{
				case AFTER_FILL_WATER_CHECK_NEEDED:
					DISPATCH_FSM_EVENT(FSM_EVENT_AFTERFILLWATERCHECKNEEDED);
					break;

				default:
					DISPATCH_FSM_EVENT(FSM_EVENT_FILLCOMPLETED);
					break;
			}
			break;

		default:	// Includes FILL_CORE_NO_STATE_CHANGE
			break;
	}
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void FillWaterInitialCheck(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	Fill__ClassAFillCoreInit(&Fill_Data, &Fill_NV_Data);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void ResetAFSubcycleExecution(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	Fill_Data.Subcycle_Executed = FALSE;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void ResetSubcycleExecution(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	Fill_Data.Subcycle_Executed = FALSE;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void SetH2OAlarm(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	H2O_Alarm = TRUE; // Set in entry function to manage a specific use case in case of power fail
	Fill_NV_Data.H2O_Pause_Executed = FALSE;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void WaitAFSubcycleExecution(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	if (Fill_Data.Subcycle_Executed == FALSE)
	{
		(void)SubCycle__RequestStart(0, Fill_Data.Class_A_Fill_Parameters->Fill_Check_Water_Subcycle_Priority);
	}
	else
	{
		VWI_WATER_SENSE_TYPE last_valid_water_status;

		last_valid_water_status = Vwi__GetLastValidWaterStatus();

		if ((last_valid_water_status == WS_NOT_VALID) || (last_valid_water_status == WS_NO_WATER) || (last_valid_water_status == WS_UNSTABLE_NO_WATER))
		{
			// No Water
			NoWaterFoundInAfterFillChecks();
		}
		else
		{
			// Water is present, do nothing
		}

		DISPATCH_FSM_EVENT(FSM_EVENT_FILLCOMPLETED);
	}
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void WaitForPauseEnd(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	if (Fill_NV_Data.H2O_Pause_Executed == FALSE)
	{
		if (Fault__IsInFaultState(FAULT_ID_NO_WATER_FILL_VALVE_PROBLEM) == FALSE)
		{
			Fault__ConditionDetected(FAULT_ID_NO_WATER);
		}

		(void)Supervisor__SetStart(0, FS_PAUSE_CONDITION);
	}
	else
	{
		DISPATCH_FSM_EVENT(FSM_EVENT_RESTARTFILL);
	}
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void WaitSubcycleExecution(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	if (Fill_Data.Subcycle_Executed == FALSE)
	{
		(void)SubCycle__RequestStart(0, Fill_Data.Class_A_Fill_Parameters->Fill_Check_Water_Subcycle_Priority);
	}
	else
	{
		VWI_WATER_SENSE_TYPE last_valid_water_status;

		last_valid_water_status = Vwi__GetLastValidWaterStatus();

		if ((last_valid_water_status == WS_WATER) || (last_valid_water_status == WS_UNSTABLE_WATER))
		{
			// Water is present
			uint32 sum;
			uint16 water_since_last_regen = DishAuxVar__GetWaterLoadedSinceLastRegen();

			if (Fill_NV_Data.Liters_Requested > Liters_In_Tub_Before_Fill)
			{
				Liters_Current_Fill = Fill_NV_Data.Liters_Requested - Liters_In_Tub_Before_Fill;
			}
			else
			{
				Liters_Current_Fill = 0;
			}
			Liters_In_Tub = Fill_NV_Data.Liters_Requested;

			// Since flow meter is not working, it is not able to update Water_Loaded_Since_Last_Regen, so the variable
			// is updated adding to it the amount of water that is assumed to have been loaded in the current Fill.
			sum = (uint32)water_since_last_regen + Liters_Current_Fill;
			if (sum > (uint16)__UNSIGNED_SHORT_MAX__)
			{
				sum = __UNSIGNED_SHORT_MAX__;
			}
			water_since_last_regen = (uint16)sum;

			DishAuxVar__SetWaterLoadedSinceLastRegen(water_since_last_regen);

			// Update statistics with estimated water loaded
			StatisticsDish__IncreaseWaterCounter(Liters_Current_Fill);

			Fault__ConditionDetected(FAULT_ID_FLOW_METER);

			// After fill checks
			switch (AfterFillCheck())
			{
				case AFTER_FILL_WATER_CHECK_NEEDED:
					DISPATCH_FSM_EVENT(FSM_EVENT_AFTERFILLWATERCHECKNEEDED);
					break;

				default:
					DISPATCH_FSM_EVENT(FSM_EVENT_FILLCOMPLETED);
					break;
			}
		}
		else
		{
			// No Water
			DISPATCH_FSM_EVENT(FSM_EVENT_NOWATERDETECTED);
		}

	}
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void UpdateStatistics(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	StatisticsDish__UpdateFstFillWaterTemp();
}
