/**
 * @file
 * @brief       Private parameters for the API013MotionCtrl module.
 *
 * @details     Refer to the C source file for more detailed information.
 *
 * @copyright   Copyright 2016-2017 Whirlpool Corporation.  All rights reserved - CONFIDENTIAL.
 */

#ifndef API013REMOTEFUNCTION_PRV_H_
#define API013REMOTEFUNCTION_PRV_H_


//  --- Include Files -------------------------------------------------------------------------------------------------
#include "SystemConfig.h"

// -- This Module --

// -- Other Modules --

//=====================================================================================================================
//  --- Private Properties --------------------------------------------------------------------------------------------
//=====================================================================================================================


// -- Private Constant Declarations --

//! The maximum number of handlers that will process events generated by the API013_SERVER_FEATURE.
#define API013_MAX_CALLBACK_HANDLERS    2U

//! The maximum number of data elements that can be published in the API013_FBK_PUBLISH_CALCULATED_RESULTS message.
#define API013_MAX_PUBLISHED_DATA       16U

//! The maximum number of data elements that can be stored in memory at any point in time.
#define API013_MAX_STORED_DATA          16U

//! The number of milliseconds between calls to the API013MotionCtrl__Handler() function.
#define API013_MS_PER_BACKGROUND_CALL   25U


// -- Private Type Declarations --


// -- Private Flash-Based Constant Definitions --

#if (API013_CLIENT_FEATURE == ENABLED)
    //! An array of remote functions used in API013 Communication.
    //! This list has a one-to-one correspondence with the #API013_CLIENT_FUNCTION_INDEX_TYPE.
    //! The first parameter of each entry is the communication node of the server.
    //! The second parameter of each entry is the 0-based index of the remote function on the server.
    static const API013_FUNCTION_CONFIG_TYPE API013_CLIENT_FUNCTIONS[] =
    {
        //  {Server_Function_Id,                       Communication_Node}
            {SERVER_REMOTE_FUNCTION_READ_TAG,     			2            },
			{SERVER_REMOTE_FUNCTION_WRITE_TAG,     			2            },
			{SERVER_REMOTE_FUNCTION_WRITE_DEFAULT_TAG,     	2            },
			{SERVER_REMOTE_FUNCTION_GET_CARTRIDGE_STATUS,   2            },
			{SERVER_REMOTE_FUNCTION_CONSTANT_TRANSMIT,     	2            }
    };
#endif      // #if (API013_CLIENT_FEATURE == ENABLED)

#if (API013_SERVER_FEATURE == ENABLED)
    //! The list of configuration structures for each of the Background Analysis.
    static const REMOTE_FUNCTION_HOOK_TYPE API013_SERVER_FUNCTIONS[] =
    {
    //  {Background Function,               Command Function,                   Get Data Function,                  Get Status Function               Server Remote Function ID            }
        {REMOTE_FUNCTION_BACKGROUND_NULL,	RemoteFunctionCartridgeData__ReadTag,	REMOTE_FUNCTION_GET_DATA_NULL,	REMOTE_FUNCTION_GET_STATUS_NULL,  SERVER_REMOTE_FUNCTION_READ_TAG },
		{REMOTE_FUNCTION_BACKGROUND_NULL,   RemoteFunctionCartridgeData__WriteTag,    REMOTE_FUNCTION_GET_DATA_NULL,	REMOTE_FUNCTION_GET_STATUS_NULL,  SERVER_REMOTE_FUNCTION_WRITE_TAG },
		{REMOTE_FUNCTION_BACKGROUND_NULL,   RemoteFunctionCartridgeData__WriteDefaultTag,    REMOTE_FUNCTION_GET_DATA_NULL,	REMOTE_FUNCTION_GET_STATUS_NULL,  SERVER_REMOTE_FUNCTION_WRITE_DEFAULT_TAG },
        {REMOTE_FUNCTION_BACKGROUND_NULL,   RemoteFunctionCartridgeData__GetCartridgeStatus,    REMOTE_FUNCTION_GET_DATA_NULL,	REMOTE_FUNCTION_GET_STATUS_NULL,  SERVER_REMOTE_FUNCTION_GET_CARTRIDGE_STATUS },
        {REMOTE_FUNCTION_BACKGROUND_NULL,   RemoteFunctionCartridgeData__ConstantTransmit,    REMOTE_FUNCTION_GET_DATA_NULL,	REMOTE_FUNCTION_GET_STATUS_NULL,  SERVER_REMOTE_FUNCTION_CONSTANT_TRANSMIT }

    };
#endif      // #if (API013_SERVER_FEATURE == ENABLED)


//=====================================================================================================================
//  --- Private Methods -----------------------------------------------------------------------------------------------
//=====================================================================================================================


#endif      /* API013REMOTEFUNCTION_PRV_H_ */
