/**
 *  @file       SRException.c
 *  @defgroup   CLASS_B
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *---------------------------------------------------------------------------------------------------------------------
 *------------------- Copyright 2007.  Whirlpool Corporation.  All rights reserved - CONFIDENTIAL ---------------------
 *---------------------------------------------------------------------------------------------------------------------
 */

//-------------------------------------- Include Files ----------------------------------------------------------------
#include "SystemConfig.h"
#include "string.h"
#include "SRException.h"
#include "Micro.h"
#include "Log.h"

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
//------- Log Module messages ---------------------------------------
//! A list of log message IDs that are generated by this module.
typedef enum
{
    EVENT_TYPE = 0,
    EVENT_DATA1,
    EVENT_DATA2,
} MODULE_SREXCEPTION_LOG_MESSAGE_ID_TYPE;

#define MODULE_NAME MODULE_SREXCEPTION      //!< The name of this module for use by the Log module.

#define SREXCEPTION_LOGGED_EVENT_IS_VALID       ((uint16)0xDE51)

typedef struct
{
    SREXCEPTION_EVENT_TYPE Event;
    uint32 Data1;
    uint32 Data2;
    uint16 Signature;
}SREXCEPTION_EVENT_DATA_TYPE;

static NO_INIT SREXCEPTION_EVENT_DATA_TYPE SRException_Event_Data;

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
static void srexceptionforcereset(SREXCEPTION_EVENT_TYPE event,uint32 data1, uint32 data2);

//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================
/**
 * @brief -
 * @param event
 * @param data1
 * @param data2
 */
void SRException__LogLastException(void)
{
    if (SRException_Event_Data.Signature == SREXCEPTION_LOGGED_EVENT_IS_VALID)
    {
        LOG_ADD_EXCEPTION(EVENT_TYPE, (LOG_DATA_TYPE)SRException_Event_Data.Event);
        LOG_ADD_EXCEPTION(EVENT_DATA1, (LOG_DATA_TYPE)SRException_Event_Data.Data1);
        LOG_ADD_EXCEPTION(EVENT_DATA2, (LOG_DATA_TYPE)SRException_Event_Data.Data2);
    }

    memset(&SRException_Event_Data, 0, sizeof(SREXCEPTION_EVENT_DATA_TYPE));
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Enter brief description of function.
 *
 *  @param
 *
 *  @return
 */
void SRException__Queue(SREXCEPTION_EVENT_TYPE event,uint32 data1, uint32 data2)
{
    switch (event)
    {
        case SREXCEPTION_NONE:
        case SREXCEPTION_PRODUCT_LEVEL_RECOVERABLE:
    #if(CLASSB_FEATURE == DISABLED)
            // This exception is made for the boards which have to manage the Non Volatile Data management by external EEPROM
        case SREXCEPTION_SRTASKMON_SUSPEND_OVERRUN:
    #endif
            LOG_ADD_EXCEPTION(EVENT_TYPE, event);
            LOG_ADD_EXCEPTION(EVENT_DATA1, data1);
            LOG_ADD_EXCEPTION(EVENT_DATA2, data2);

            //NO RESET
            break;
        case SREXCEPTION_SRDATA_NOISE:
        case SREXCEPTION_APPLICATION_TASK_OVERRUN:
        case SREXCEPTION_ASSYNCHRONOUS_TASK_OVERRUN:
        case SREXCEPTION_COMMUNICATION_TASK_OVERRUN:
        case SREXCEPTION_SRCLOCK_TEST:
        case SREXCEPTION_SRCLOCK_OVERRUN:
        case SREXCEPTION_ATOD_CONFIGURATION_CORRUPTION:
        case SREXCEPTION_ATOD_STUCK:
        case SREXCEPTION_GPIO_CONFIGURATION_CORRUPTION:
        case SREXCEPTION_GPIO_DATA_CORRUPTION:
        case SREXCEPTION_SRDATA_BAD_MEMORY:
        case SREXCEPTION_SRDATA_NOT_ALLOWED:
        case SREXCEPTION_HBL_DATA_NOT_CONSISTENT:
        case SREXCEPTION_SRCHECK_DATA_NOT_CONSISTENT:
        case SREXCEPTION_SRACTION_DATA_NOT_CONSISTENT:
        case SREXCEPTION_SRTASKMON_ALREADY_ENABLED:
        case SREXCEPTION_SRTASKMON_NO_TASKS:
        case SREXCEPTION_SRTASKMON_TIMEOUT:
        case SREXCEPTION_SRTASKMON_ENTER_OUTOFRANGE:
        case SREXCEPTION_SRTASKMON_ENTER_INACTIVE:
        case SREXCEPTION_SRTASKMON_ALREADY_ENTER:
        case SREXCEPTION_SRTASKMON_EXIT_OUTOFRANGE:
        case SREXCEPTION_SRTASKMON_EXIT_INACTIVE:
        case SREXCEPTION_SRTASKMON_ALREADY_EXIT:
        case SREXCEPTION_SRTASKSEQ_WRONG_NUMBER:
        case SREXCEPTION_SRTASKSEQ_INCOMPLETED:
        case SREXCEPTION_SRTASKSEQ_TIMEOUT:
        case SREXCEPTION_SRISR_OVERRUN:
        case SREXCEPTION_SRISR_SEQUENCE_MISMATCH:
        case SREXCEPTION_SRISR_TIMEOUT:
        case SREXCEPTION_OS_ERROR:
        case SREXCEPTION_STACK_OVERFLOW:
        case SREXCEPTION_PRODUCT_LEVEL_NOT_RECOVERABLE:
        case SREXCEPTION_MICRO_RAM_INTEGRITY_TEST:
        case SREXCEPTION_MICRO_FLASH_INTEGRITY_TEST:
        case SREXCEPTION_MICRO_CPU_REGISTER_TEST:
        case SREXCEPTION_TIMER_DATA_CORRUPTION:
    #if(CLASSB_FEATURE == ENABLED)
        case SREXCEPTION_SRTASKMON_SUSPEND_OVERRUN:
    #endif

        default:

            // for this the log will be generated after the micro reset
            srexceptionforcereset(event, data1, data2);
            break;
    }
}

//SREXCEPTION_SRTASKMON_SUSPEND_OVERRUN
//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================
static void srexceptionforcereset(SREXCEPTION_EVENT_TYPE event,uint32 data1, uint32 data2)
{
    SRException_Event_Data.Event        = event;
    SRException_Event_Data.Data1        = data1;
    SRException_Event_Data.Data2        = data2;
    SRException_Event_Data.Signature    = SREXCEPTION_LOGGED_EVENT_IS_VALID;

    Micro__ForceReset(MICRO_RESET_MODE_COLD);
}
