/**
 *  @file       BrownOut.c
 *
 * @brief This module checks for BrownOut event and Trigger actions needs to be taken on BrownOut
 *
 * @details
 *  Created on: Dec 13, 2018
 *      Author: JAINB1
 *
 *
 * @note Regarding the suppressed PC-Lint warnings:
 * - The 506, suppresses "Constant value Boolean" where BROWNOUT_DETECTION_SOURCE, BROWNOUT_RECOVER_SOURCE, BROWNOUT__IS_VALID_SOURCE
 *     are used, since use of constant boolean value is allowed to disable a specific feature.
 *
@startuml
title BrownOut State machine

' use state = Brown_Out_State

[*] --> BrownOutInitialize

' BrownOutInitialize State
BrownOutInitialize: do / DetectStablePower()
BrownOutInitialize --> BrownOutDetect : evStablePower

' BrownOutDetect State
BrownOutDetect : do / DetectBrownOutEvent()
BrownOutDetect --> BrownOutRecover : evBrownOutDetected

' BrownOutRecover State
BrownOutRecover : do / DetectBrownOutRecover()
BrownOutRecover --> BrownOutDetect : evStablePower
@enduml
 *  @copyright  Copyright 2018 Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "SystemConfig.h"
#include "BrownOut.h"
#include "Log.h"

//---------------------------------------------------------------------------------------------------------------------
#ifndef STATUS_LED_FEATURE
    #define STATUS_LED_FEATURE      DISABLED
#elif(STATUS_LED_FEATURE == ENABLED)
    #include "StatusLed.h"
#endif

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_BROWNOUT

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
#ifndef BROWNOUT_DETECTION_SOURCE
    #define BROWNOUT_DETECTION_SOURCE()         FALSE
#endif

#ifndef BROWNOUT_RECOVER_SOURCE
    #define BROWNOUT_RECOVER_CHECK()       (BROWNOUT_DETECTION_SOURCE() == FALSE)
#else
    #define BROWNOUT_RECOVER_CHECK()       ((BROWNOUT_RECOVER_SOURCE() != FALSE) && (BROWNOUT_DETECTION_SOURCE() == FALSE))
#endif

#ifndef BROWNOUT__IS_VALID_SOURCE
    #define BROWNOUT_IS_MONITOR_RUNNING         (TRUE)
    #define USE_VALID_SOURCE_DETECTED           DISABLED
#else
    #define BROWNOUT_IS_MONITOR_RUNNING         (Valid_Source_Detected)
    #define USE_VALID_SOURCE_DETECTED           ENABLED
#endif

#ifndef BROWNOUT_DETECTION_FILTER_MS
    #define BROWNOUT_DETECTION_FILTER_MS        0
#endif

#ifndef BROWNOUT_RECOVER_FILTER_MS
    #define BROWNOUT_RECOVER_FILTER_MS          0
#endif

#if (!defined(BROWNOUT_EXEC_TIMING_MS) && ((BROWNOUT_DETECTION_FILTER_MS + BROWNOUT_RECOVER_FILTER_MS) > 0 ))
    #define BROWNOUT_EXEC_TIMING_MS             5
#endif

#ifndef BROWNOUT_DETECTED_ACTIONS
    #define BROWNOUT_DETECTED_ACTIONS()
#endif

#ifndef BROWNOUT_RECOVERED_ACTIONS
    #define BROWNOUT_RECOVERED_ACTIONS()
#endif

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_SETUP_LOG_MESSAGE_ID_ENUM
{
BROWNOUT_STABLE_POWER_DETECTED = 1,
BROWNOUT_EVENT_DETECTED,
} MODULE_BROWNOUT_LOG_MESSAGE_ID_TYPE;

//=====================================================================================================================
//=== StateEngineCrank (v2.8) Auto-Generated Definitions for Brown Out State Machine
//=====================================================================================================================
// !! StateEngineCrank cannot update this code if you change the header !!


//! Unique names used to identify states of the Brown Out state machine.
typedef enum BROWN_OUT_STATE_ENUM
{
    STATE_BROWN_OUT_NONE       = 0,

    STATE_BROWN_OUT_INITIALIZE = 1,                 //!< (initial_state)
    STATE_BROWN_OUT_DETECT     = 2,
    STATE_BROWN_OUT_RECOVER    = 3,

    STATE_BROWN_OUT_END        = 4
} BROWN_OUT_STATE_TYPE;

// -- Private Function Prototypes used by the state machine for customization functions --
static void DetectBrownOutEvent(void);
static void DetectBrownOutRecover(void);
static void DetectStablePower(void);

// -- Private Function Prototypes used by the state machine for standard state machine functions --
static void BrownOutExecute(void);
static void BrownOutInitialize(void);
static void EventBrownOutDetected(void);
static void EventStablePower(void);

// !! StateEngineCrank cannot update this code if you change the footer !!
// End of StateEngineCrank Auto-Generated Code.

// -- Private Variable Definitions --
//! Variable used to control brown out state machine
static BROWN_OUT_STATE_TYPE Brown_Out_State;
//! Variable used to hold status of brown out event
static BOOL_TYPE Brown_Out_Detected;
#if(USE_VALID_SOURCE_DETECTED != DISABLED)
    //! Variable used to latch up BROWNOUT__IS_VALID_SOURCE() result
    static BOOL_TYPE Valid_Source_Detected;
#endif

#if(BROWNOUT_DETECTION_FILTER_MS > 0)
static uint16 Brown_Out_Detection_Filter;
    #define BROWNOUT_IS_DETECTION_FILTER_EXPIRED()      (Brown_Out_Detection_Filter == 0)
    #define BROWNOUT_DETECTION_FILTER_UPDATE()          Brown_Out_Detection_Filter--
    #define BROWNOUT_DETECTION_FILTER_RESET()           Brown_Out_Detection_Filter = ((BROWNOUT_DETECTION_FILTER_MS + BROWNOUT_EXEC_TIMING_MS -1) / BROWNOUT_EXEC_TIMING_MS)
#else
    #define BROWNOUT_IS_DETECTION_FILTER_EXPIRED()      (TRUE)
    #define BROWNOUT_DETECTION_FILTER_UPDATE()
    #define BROWNOUT_DETECTION_FILTER_RESET()
#endif

#if(BROWNOUT_RECOVER_FILTER_MS > 0)
static uint16 Brown_Out_Recover_Filter;
#define BROWNOUT_IS_RECOVER_FILTER_EXPIRED()            (Brown_Out_Recover_Filter == 0)
#define BROWNOUT_RECOVER_FILTER_UPDATE()                Brown_Out_Recover_Filter--
#define BROWNOUT_RECOVER_FILTER_RESET()                 Brown_Out_Recover_Filter = ((BROWNOUT_RECOVER_FILTER_MS + BROWNOUT_EXEC_TIMING_MS -1) / BROWNOUT_EXEC_TIMING_MS)
#else
#define BROWNOUT_IS_RECOVER_FILTER_EXPIRED()            (TRUE)
#define BROWNOUT_RECOVER_FILTER_UPDATE()
#define BROWNOUT_RECOVER_FILTER_RESET()
#endif

//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the module BrownOut and its variables
 *
 */
void BrownOut__Initialize(void)
{
    Brown_Out_Detected = FALSE;
    #if(USE_VALID_SOURCE_DETECTED != DISABLED)
        Valid_Source_Detected = (BOOL_TYPE) BROWNOUT__IS_VALID_SOURCE();                    //lint !e506
    #endif
    BROWNOUT_DETECTION_FILTER_RESET();
    BROWNOUT_RECOVER_FILTER_RESET();
    BrownOutInitialize();
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      This API monitors the Brown out detection
 *
 */
void BrownOut__Monitor(void)
{
    #if(USE_VALID_SOURCE_DETECTED != DISABLED)
        if(Valid_Source_Detected == FALSE)
        {
            Valid_Source_Detected = (BOOL_TYPE) BROWNOUT__IS_VALID_SOURCE();                //lint !e506
        }
    #endif
    if(BROWNOUT_IS_MONITOR_RUNNING)                                                         //lint !e506
    {
        BrownOutExecute();
    }
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      This API returns the status of the Brown Out
 *
 * @return TRUE :- If Brown Out event Has been Detected
 *         FALSE:- Brown Out is not present
 */
BOOL_TYPE BrownOut__IsDetected(void)
{
    return Brown_Out_Detected;
}



//=====================================================================================================================
//  --- Private State Machine Customization Functions -----------------------------------------------------------------
//=====================================================================================================================


//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This function checks for brownout event and Takes actions after detection
 */
static void DetectBrownOutEvent(void)
{
    if (BROWNOUT_DETECTION_SOURCE())                        //lint !e506
    {
        if(BROWNOUT_IS_DETECTION_FILTER_EXPIRED())          //lint !e506
        {
            LOG_ADD_EVENT(BROWNOUT_EVENT_DETECTED,0);
            Brown_Out_Detected = TRUE;
            #if(STATUS_LED_FEATURE == ENABLED)
                StatusLed__Suspend();
            #endif
            BROWNOUT_DETECTED_ACTIONS();
            EventBrownOutDetected();
        }
        else
        {
            BROWNOUT_DETECTION_FILTER_UPDATE();
        }
    }
    else
    {
        BROWNOUT_DETECTION_FILTER_RESET();
    }

}


//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This function checks for brownout event recover and Takes action after Recovery
 */
static void DetectBrownOutRecover(void)
{
    if (BROWNOUT_RECOVER_CHECK())                           //lint !e506
    {
        if(BROWNOUT_IS_RECOVER_FILTER_EXPIRED())            //lint !e506
        {
            Brown_Out_Detected = FALSE;
            BROWNOUT_RECOVERED_ACTIONS();
            #if(STATUS_LED_FEATURE == ENABLED)
                StatusLed__Resume();
            #endif
            EventStablePower();
        }
        {
            BROWNOUT_RECOVER_FILTER_UPDATE();
        }
    }
    else
    {
        BROWNOUT_RECOVER_FILTER_RESET();
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief This function checks for stable power
 */
static void DetectStablePower(void)
{
    if (BROWNOUT_RECOVER_CHECK())                          //lint !e506
    {
        LOG_ADD_EVENT(BROWNOUT_STABLE_POWER_DETECTED,0);
        EventStablePower();
    }
}



/*
 *
 * */
//=====================================================================================================================
//=== StateEngineCrank (v2.8) Auto-Generated Functions for Brown Out State Machine
//=====================================================================================================================
// !! StateEngineCrank cannot update this code if you change the header !!


//---------------------------------------------------------------------------------------------------------------------
/**
 * The main execution function for the Brown Out state machine.
 * This function should be called periodically while the state machine is running.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void BrownOutExecute(void)
{
    switch(Brown_Out_State)
    {
        case STATE_BROWN_OUT_INITIALIZE:
            DetectStablePower();                    // Do function.
            break;

        case STATE_BROWN_OUT_DETECT:
            DetectBrownOutEvent();                  // Do function.
            break;

        case STATE_BROWN_OUT_RECOVER:
            DetectBrownOutRecover();                // Do function.
            break;

        default:
            // There is nothing to do for all other values of Brown_Out_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * The initialization function for the Brown Out state machine.
 * This function resets the state machine to the initial state.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void BrownOutInitialize(void)
{
    Brown_Out_State = STATE_BROWN_OUT_INITIALIZE;
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Brown Out Detected Event for the Brown Out state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventBrownOutDetected(void)
{
    switch (Brown_Out_State)
    {
        case STATE_BROWN_OUT_DETECT:
            Brown_Out_State = STATE_BROWN_OUT_RECOVER;
            break;

        default:
            // Event is ignored for all other values of Brown_Out_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Stable Power Event for the Brown Out state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventStablePower(void)
{
    switch (Brown_Out_State)
    {
        case STATE_BROWN_OUT_INITIALIZE:
        case STATE_BROWN_OUT_RECOVER:
            Brown_Out_State = STATE_BROWN_OUT_DETECT;
            break;

        default:
            // Event is ignored for all other values of Brown_Out_State.
            break;
    }
}


// !! StateEngineCrank cannot update this code if you change the footer !!
// End of StateEngineCrank Auto-Generated Code.
