/**
 * @file
 * @brief       Manages the activation, deactivation, and running of parallel tasks triggered by the cycle.
 *
 * @details
 *
 * ActivateTask Setting File Parameter Data
 *
 * <pre>
 *      Word Offset     First Byte              Second Byte
 *      -----------     ---------------         ----------------
 *      +0000h          Task_Code               Task_Displacement
 * </pre>
 *
 * Task_Code: The index that uniquely identifies the task. Can be used as an index into the
 * TASK_LIST[] array.
 *
 * Task_Displacement: The displacement used to access task parameters in the setting file.
 *
 *
 * $Header: ActivateTask.c 1.1 2015/08/10 14:10:55EDT Nelson Ferragut II (FERRANJ) Exp  $
 *
 * @copyright  Copyright 2014 - $Date: 2015/08/10 14:10:55EDT $  Whirlpool Corporation.  All rights reserved - CONFIDENTIAL.
 */

//  --- Include Files -------------------------------------------------------------------------------------------------

// -- This Module --
#include "C_Extensions.h"
#include "ActivateTask.h"
#include "ActivateTask_prv.h"

// -- Other Modules --
#include "Log.h"
#include "Micro.h"
#include "NVData.h"
#include "SettingFile.h"
#include "Task.h"
#include "Utilities.h"
#include <string.h>


// There must be exactly TASK_COUNT tasks defined in the TASK_LIST[] array.
#define TASK_COUNT ELEMENTS_IN_ARRAY(TASK_LIST)

// The number of compartments multiplied by the number of tasks must not exceed 255.
CT_ASSERT(APPLIANCE_MAX_COMPARTMENTS * TASK_COUNT < 256);

//  --- Private Properties --------------------------------------------------------------------------------------------

// -- Private Constant Declarations --

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_ACTIVATE_TASK


// -- Private Enumerated Constants Declarations --

//! List of values to compare with the F1_F0_Flags.
typedef enum ACTIVATE_TASK_OPTION_ENUM
{
    TASK_OPTION_ACTIVATE,                           //!< F1=0, F0=0
    TASK_OPTION_DEACTIVATE,                         //!< F1=0, F0=1
    TASK_OPTION_COUNT
} ACTIVATE_TASK_OPTION_TYPE;


//! A list of log message IDs that are generated by this module.
typedef enum MODULE_ACTIVATE_TASK_LOG_MESSAGE_ID_ENUM
{
    INVALID_PROCESS_CONTROL = 1,
    INVALID_PROCESS_PARAMETERS,
    INVALID_TASK_MANIPULATION_PARAMETER,
    NON_EXISTENT_TASK
} MODULE_ACTIVATE_TASK_LOG_MESSAGE_ID_TYPE;



// -- Private Type Declarations --

typedef struct ACTIVATE_TASK_PARAMETER_STRUCT
{
    uint8 Task_Code;
    uint8 Task_Displacement;
} ACTIVATE_TASK_PARAMETER_TYPE;


// -- Private Flash-Based Constant Definitions --

//! A data structure that can be compared to a task definition to see if it is disabled.
static const void* DISABLED_TASK[] = { NULL, NULL, NULL, NULL };


// -- Private Variable Definitions --
#pragma location = "_appliance_segment"
static uint8 Task_Active[BIT_STORAGE_SIZE(APPLIANCE_MAX_COMPARTMENTS * TASK_COUNT)];
static uint8 Task_Paused[BIT_STORAGE_SIZE(APPLIANCE_MAX_COMPARTMENTS * TASK_COUNT)];

//  --- Private Function Prototypes -----------------------------------------------------------------------------------

static void ExecuteTaskManipulation(uint8 compartment, uint8 task, BOOL_TYPE resume, TASK_EVENT_ACTION_TYPE action);

//=====================================================================================================================
//  --- Public Methods ------------------------------------------------------------------------------------------------
//=====================================================================================================================


//---------------------------------------------------------------------------------------------------------------------
/**
 * Initialize the ActivateTask module.
 * If non-volatile data was corrupted, then deactivate all tasks in all compartments.
 */
void ActivateTask__Initialize(void)
{
    uint8 compartment;
    uint8 task;
    uint8 task_bit;
    TASK_RECOVER_FUNCTION_TYPE recover;

    if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
    {
        if (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != NVDATA_RESTORE_OKAY)
        {
            // Corrupt non-volatile memory -- deactivate all tasks without terminating them.
            memset(Task_Active, 0, sizeof(Task_Active));
            memset(Task_Paused, 0, sizeof(Task_Paused));
        }
        else
        {
            // Inform all tasks running in any compartment that a reset has occurred.
            for (compartment = 0; compartment < APPLIANCE_MAX_COMPARTMENTS; compartment++)
            {
                for (task = 0; task < TASK_COUNT; task++)
                {
                    recover = TASK_LIST[task].Recover;
                    if (recover != TASK_NULL_RECOVER)
                    {
                        // Call the task's recover function if it was running before the reset.
                        task_bit = compartment * TASK_COUNT + task;
                        if (Utilities__GetBitInArray(Task_Active, task_bit) == ACTIVE)
                        {
                            recover(compartment);
                        }
                    }
                }
            }
        }
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief       The ActivateTask process.
 *
 * The ActivateTask Process enables and disables tasks in the appliance.
 *
 * @param control = The control parameters provided by the Interpreter.
 * @retval PROCESS_COMPLETE = The process is ready for the Interpreter to proceed to the next step.
 * @retval PROCESS_BUSY = The process is not ready for the Interpreter to proceed to the next step.
 */
PROCESS_RESULT_TYPE ActivateTask__Process(PROCESS_CONTROL_TYPE* control)
{
    PROCESS_RESULT_TYPE result;                     // Return value for the Interpreter.
    SETTINGFILE_LOADER_TYPE loader;                 // The structure filled by SettingFile module.
    ACTIVATE_TASK_PARAMETER_TYPE* parameter;        // Pointer to the setting file data structure.
    uint8 task_bit;                                 // Bit position for the task in the compartment.
    TASK_INIT_FUNCTION_TYPE init;                   // Pointer to the task initialize function.
    ACTIVE_TYPE active;                             // Task response to remain active.
    TASK_STOP_FUNCTION_TYPE stop;                   // Pointer to the task terminate function.

    result = PROCESS_COMPLETE;
    if ((control == NULL) ||
        (control->F1_F0_Flags >= (uint8)TASK_OPTION_COUNT) ||
        (control->Compartment >= APPLIANCE_MAX_COMPARTMENTS))
    {
        LOG_ADD_EXCEPTION(INVALID_PROCESS_CONTROL, (control != NULL));
    }
    else if ((SettingFile__MSettingBasicLoader(control->Setting_File_Index,
                                               SF_PTR_ACU_PROCESS_ACTIVATE_TASK,
                                               control->Data_Field_Index,
                                               &loader) == FAIL) ||
             (loader.Length < sizeof(ACTIVATE_TASK_PARAMETER_TYPE)))
    {
        LOG_ADD_EXCEPTION(INVALID_PROCESS_PARAMETERS, control->Data_Field_Index);
    }
    else
    {
        parameter = (void*)loader.Data;
        if ((parameter->Task_Code >= TASK_COUNT) ||
            (memcmp(&TASK_LIST[parameter->Task_Code], DISABLED_TASK, sizeof(DISABLED_TASK)) == 0))
        {
            LOG_ADD_EXCEPTION(NON_EXISTENT_TASK, COMBINE_BYTES(parameter->Task_Code, control->Data_Field_Index));
        }
        else
        {
            task_bit = control->Compartment * TASK_COUNT + parameter->Task_Code;
            if (control->Step_Initializing == TRUE)
            {
                switch ((ACTIVATE_TASK_OPTION_TYPE)control->F1_F0_Flags)
                {
                    case TASK_OPTION_ACTIVATE:
                        active = ACTIVE;
                        init = TASK_LIST[parameter->Task_Code].Init;
                        if (init != TASK_NULL_INIT)
                        {
                            active = init(control->Compartment, control->Setting_File_Index, parameter->Task_Displacement);
                        }
                        Utilities__SetBitInArray(Task_Active, task_bit, active);
                        Utilities__SetBitInArray(Task_Paused, task_bit, FALSE);
                        break;

                    case TASK_OPTION_DEACTIVATE:
                        stop = TASK_LIST[parameter->Task_Code].Stop;
                        if (Utilities__GetBitInArray(Task_Active, task_bit) == ACTIVE)
                        {
                            if (stop != TASK_NULL_STOP)
                            {
                                stop(control->Compartment);
                            }
                            Utilities__SetBitInArray(Task_Active, task_bit, INACTIVE);
                        }
                        break;

                    default:
                        // F1/F0 flag combination is not supported.
                        break;
                }
            }

            if (Utilities__GetBitInArray(Task_Active, task_bit) == ACTIVE)
            {
                result = PROCESS_BUSY;
            }
        }
    }

    return result;
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Stop all the tasks in a single compartment.
 *
 * Task control states are set to inactive.
 * Task stop functions are not called for tasks that are running.
 *
 * @param compartment = The compartment in which all the tasks should be stopped.
 */
void ActivateTask__ResetCompartment(uint8 compartment)
{
    uint8 first_task_bit;
    uint8 task;
    uint8 task_bit;
    TASK_STOP_FUNCTION_TYPE stop;

    first_task_bit = compartment * TASK_COUNT;
    for (task = 0; task < TASK_COUNT; task++)
    {
        task_bit = first_task_bit + task;
        if (Utilities__GetBitInArray(Task_Active, task_bit) == ACTIVE)
        {
            stop = TASK_LIST[task].Stop;
            if (stop != TASK_NULL_STOP)
            {
                stop(compartment);
            }
            Utilities__SetBitInArray(Task_Active, task_bit, INACTIVE);
        }
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Run all the tasks in a single compartment.
 *
 * Task functions are only called if they are initializing, running, or terminating.
 *
 * @param compartment = The compartment in which all the tasks should be run.
 */
void ActivateTask__RunCompartment(uint8 compartment)
{
    uint8 task;
    TASK_RUN_FUNCTION_TYPE run;
    uint8 task_bit;

    // Call each of the tasks that are active or just changed states.
    for (task = 0; task < TASK_COUNT; task++)
    {
        run = TASK_LIST[task].Run;
        if (run != TASK_NULL_RUN)
        {
            // Call the task function if it needs to be called.
            task_bit = compartment * TASK_COUNT + task;
            if ((Utilities__GetBitInArray(Task_Active, task_bit) == ACTIVE) &&
                (Utilities__GetBitInArray(Task_Paused, task_bit) == FALSE))
            {
                if (run(compartment) == INACTIVE)
                {
                    Utilities__SetBitInArray(Task_Active, task_bit, INACTIVE);
                }
            }
        }
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Pause all the tasks in a single compartment.
 *
 * Task control states are set in accordance with TASK_LIST configuration table .
 * Task stop functions are not called for tasks that are not running. It's stopped if the task is paused.
 *
 * @param compartment = The compartment in which all the tasks should be stopped.
 */
void ActivateTask__PauseCompartment(uint8 compartment)
{
    uint8 task;

    for (task = 0; task < TASK_COUNT; task++)
    {
        ExecuteTaskManipulation(compartment, task, FALSE, TASK_LIST[task].OnPause);
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Resume all the tasks in a single compartment.
 *
 * Task control states are set in accordance with TASK_LIST configuration table .
 * Task stop functions are not called for tasks that are not running. It's stopped if the task is paused.
 *
 * @param compartment = The compartment in which all the tasks should be stopped.
 */
void ActivateTask__ResumeCompartment(uint8 compartment)
{
    uint8 task;

    for (task = 0; task < TASK_COUNT; task++)
    {
        ExecuteTaskManipulation(compartment, task, TRUE, TASK_LIST[task].OnPause);
    }
}



//---------------------------------------------------------------------------------------------------------------------
/**
 * Pause all the tasks in a single compartment.
 *
 * Task control states are set in accordance with TASK_LIST_EVENT configuration table .
 * Task stop functions are not called for tasks that are not running. It's stopped if the task is paused.
 *
 * @param compartment = The compartment in which all the tasks should be stopped.
 */
void ActivateTask__SubCycleStarted(uint8 compartment)
{
    uint8 task;

    for (task = 0; task < TASK_COUNT; task++)
    {
        ExecuteTaskManipulation(compartment, task, FALSE, TASK_LIST[task].OnSubCycleStarted);
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Resume all the tasks in a single compartment.
 *
 * Task control states are set in accordance with TASK_LIST_EVENT configuration table .
 * Task stop functions are not called for tasks that are not running. It's stopped if the task is paused.
 *
 * @param compartment = The compartment in which all the tasks should be stopped.
 */
void ActivateTask__SubCycleEnded(uint8 compartment)
{
    uint8 task;

    for (task = 0; task < TASK_COUNT; task++)
    {
        ExecuteTaskManipulation(compartment, task, TRUE, TASK_LIST[task].OnSubCycleStarted);
    }
}



//=====================================================================================================================
//  --- Private Methods -----------------------------------------------------------------------------------------------
//=====================================================================================================================

static void ExecuteTaskManipulation(uint8 compartment, uint8 task, BOOL_TYPE resume, TASK_EVENT_ACTION_TYPE action)
{
    uint8 task_bit;
    TASK_STOP_FUNCTION_TYPE stop;
    uint8 first_task_bit;

    first_task_bit = compartment * TASK_COUNT;
    task_bit = first_task_bit + task;

    switch (action)
    {
        case TASK_OPTION_PAUSE_RESUME_BG_FUN:
        {
            if (resume == TRUE)
            {
                Utilities__SetBitInArray(Task_Paused, task_bit, FALSE);
            }
            else
            {
                Utilities__SetBitInArray(Task_Paused, task_bit, TRUE);
            }
            break;
        }
        case TASK_OPTION_TERMINATE:
        {
            if (resume == TRUE)
            {
                // Do nothing
            }
            else
            {
                Utilities__SetBitInArray(Task_Active, task_bit, INACTIVE);
                stop = TASK_LIST[task].Stop;
                if (stop != TASK_NULL_STOP)
                {
                    stop(compartment);
                }
            }
            break;
        }

        case TASK_OPTION_NO_CHANGE:
            // Do nothing
            break;

        default:
        {
            LOG_ADD_EXCEPTION(INVALID_TASK_MANIPULATION_PARAMETER, action);
            break;
        }
    }
}

