/**
 * @file
 * @brief       Manage the triggers and priorities of sub-cycles.
 *
 * @copyright   Copyright 2015-2018 Whirlpool Corporation.  All rights reserved - CONFIDENTIAL.
 */

//  --- Include Files -------------------------------------------------------------------------------------------------

// -- This Module --
#include "C_Extensions.h"
#include "SubCycle.h"

// -- Other Modules --
#include "Condition.h"
#include "Fault.h"
#include <limits.h>
#include "Log.h"
#include "Micro.h"
#include "SettingFile.h"
#include <string.h>


//  --- Private Properties --------------------------------------------------------------------------------------------

// -- Private Constant Declarations --

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_SUBCYCLE


// -- Private Type Declarations --

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_SUBCYCLE_LOG_MESSAGE_ID_ENUM
{
    ERROR_LOADING_SUB_CYCLE_DEFINITIONS = 1,
    UNEXPECTED_SUB_CYCLE_FORMAT
} MODULE_SUBCYCLE_LOG_MESSAGE_ID_TYPE;

//! A structure that associates a trigger condition with a sub-cycle.
typedef PACKED struct SUB_CYCLE_CONDITION_STRUCT
{
    uint8 Condition_Id;
    uint8 Cycle_Id;
} SUB_CYCLE_CONDITION_TYPE;

//! The structure of the sub-cycle data in the setting file.
typedef PACKED struct SUB_CYCLE_MAPPING_STRUCT
{
    uint8 Num_Of_Sub_Cycles;
    uint8 Size_Of_Sub_Cycle_Entry;

    //! Holds data for sub-cycles in the compartment.
    //! Size of each element is variable and defined by GESE.
    uint8 Sub_Cycles[255 * sizeof(SUB_CYCLE_CONDITION_TYPE)];
} SUB_CYCLE_MAPPING_TYPE;


// -- Private Flash-Based Constant Definitions --

//! Define a simple default sub-cycle definition block to use when the setting file has no data.
static const uint8 NO_SUB_CYCLES[] =
{
    0,                                              // 0 sub-cycles defined.
    sizeof(SUB_CYCLE_CONDITION_TYPE)                // Size of data for each sub-cycle entry.
};


// -- Private Variable Definitions --

//! The index of the requested sub-cycle for each compartment.
//! If no sub-cycle is requested, the value is UCHAR_MAX.
static uint8 Requested_Sub_Cycle[APPLIANCE_MAX_COMPARTMENTS];

//! Array of pointers to the sub-cycles definitions (per compartment) in the setting file.
static SUB_CYCLE_MAPPING_TYPE const * Sub_Cycle[APPLIANCE_MAX_COMPARTMENTS];


//  --- Private Function Prototypes -----------------------------------------------------------------------------------

static void CheckForPreFaultSubCycle(uint8 fault_monitor_id);
static SUB_CYCLE_CONDITION_TYPE const * GetSubCycleData(uint8 compartment, uint8 priority);


//=====================================================================================================================
//  --- Public Methods ------------------------------------------------------------------------------------------------
//=====================================================================================================================


//---------------------------------------------------------------------------------------------------------------------
/**
 * Initialize the SubCycle module variables.
 */
void SubCycle__Initialize(void)
{
    for (uint8 compartment = 0; compartment < APPLIANCE_MAX_COMPARTMENTS; compartment++)
    {
        SETTINGFILE_LOADER_TYPE loader;
        if (SettingFile__BasicLoader(SF_PTR_ACU_SUB_CYCLES, compartment, &loader) == FAIL)
        {
            Sub_Cycle[compartment] = (SUB_CYCLE_MAPPING_TYPE const *)(void*)&NO_SUB_CYCLES;
            LOG_ADD_EXCEPTION(ERROR_LOADING_SUB_CYCLE_DEFINITIONS, compartment);
        }
        else
        {
            SUB_CYCLE_MAPPING_TYPE const * sub_cycle_data = (SUB_CYCLE_MAPPING_TYPE const *)(void*)(loader.Data);
            if (sub_cycle_data->Size_Of_Sub_Cycle_Entry < sizeof(SUB_CYCLE_CONDITION_TYPE))
            {
                Sub_Cycle[compartment] = (SUB_CYCLE_MAPPING_TYPE const *)(void*)&NO_SUB_CYCLES;
                LOG_ADD_EXCEPTION(UNEXPECTED_SUB_CYCLE_FORMAT, compartment);
            }
            else
            {
                Sub_Cycle[compartment] = sub_cycle_data;
            }
        }
    }

    if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
    {
        memset(Requested_Sub_Cycle, UCHAR_MAX, sizeof(Requested_Sub_Cycle));
    }

    Fault__RegisterPreFaultEvents(CheckForPreFaultSubCycle);
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Request that a specific sub-cycle be started.
 *
 * @param compartment = The compartment in which the sub-cycle should be started.
 * @param priority = The 1-based priority of the sub-cycle being requested.
 *                  1 is the highest priority. 0 is rejected.
 * @return FALSE if the requested sub-cycle is invalid or pre-empted by a higher priority cycle.
 *          TRUE if the requested sub-cycle is planned to be run.
 */
BOOL_TYPE SubCycle__RequestStart(uint8 compartment, uint8 priority)
{
    // The sub-cycle index is similar to the priority.
    // Index 0 is the highest priority.
    uint8 sub_cycle_index = priority - 1;
    if (sub_cycle_index <= Requested_Sub_Cycle[compartment])
    {
        // Requested sub-cycle has a priority that is higher than or equal to the current sub-cycle (if any).
        Requested_Sub_Cycle[compartment] = sub_cycle_index;
        return TRUE;
    }
    else
    {
        return FALSE;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Check the triggers of any enabled monitors and return the sub-cycle that should be running based on priorities.
 *
 * @param compartment = The compartment in which the sub-cycle should run.
 *
 * @return  Zero if no subcycle should be running.
 *          Otherwise, the subcycle ID for the cycle that should be running.
 */
uint8 SubCycle__GetActive(uint8 compartment, uint8 current_sub_cycle_id)
{
    uint8 cycle_id = 0;
    uint8 sub_cycle_index = 0;
    SUB_CYCLE_CONDITION_TYPE const* sub_cycle;
    while (cycle_id == 0)
    {
        if (sub_cycle_index >= Sub_Cycle[compartment]->Num_Of_Sub_Cycles)
        {
            // There are no more sub-cycles for this compartment.
            break;                                  // Break out of the while() loop.
        }

        sub_cycle = GetSubCycleData(compartment, sub_cycle_index);
        if (sub_cycle_index == Requested_Sub_Cycle[compartment])
        {
            // The sub-cycle was requested by a pre-fault.
            cycle_id = sub_cycle->Cycle_Id;
        }
        else if (current_sub_cycle_id == sub_cycle->Cycle_Id)
        {
            // The sub-cycle is already running.
            cycle_id = current_sub_cycle_id;
        }
        else
        {
            // Check if the condition associated with the sub-cycle triggers the sub-cycle.
            uint8 condition_id = sub_cycle->Condition_Id;
            if (condition_id != 0xFF)
            {
                if (Condition__Evaluate(SF_PTR_ACU_CONDITION_TABLE, condition_id) == CONDITION_RESULT_TRUE)
                {
                    cycle_id = sub_cycle->Cycle_Id;
                }
            }
        }
        sub_cycle_index++;
    }

    // Erase any sub-cycle requests.
    Requested_Sub_Cycle[compartment] = UCHAR_MAX;

    return cycle_id;
}


//=====================================================================================================================
//  --- Private Methods -----------------------------------------------------------------------------------------------
//=====================================================================================================================


//---------------------------------------------------------------------------------------------------------------------
/**
 * Pre-Fault handler that triggers a sub-cycle associated with a pre-fault.
 * @param fault_monitor_id = The ID of the fault monitor in the Fault module.
 */
static void CheckForPreFaultSubCycle(uint8 fault_monitor_id)
{
    FAULT_CONFIG_TYPE* fault;

    Fault__GetEventInfo(fault_monitor_id, &fault);
    if (fault->Sub_Cycle != UCHAR_MAX)
    {
        SubCycle__RequestStart(fault->Compartment, fault->Sub_Cycle);
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Convert a sub-cycle priority to the pointer to the specific data for that sub-cycle.
 *
 * @param compartment = The compartment in which the sub-cycle data needs to be referenced.
 * @param sub_cycle_index = The 0-based index of the specific sub-cycle that needs to be referenced.
 * @return A pointer to the data for the sub-cycle specified by compartment and priority.
 */
static SUB_CYCLE_CONDITION_TYPE const * GetSubCycleData(uint8 compartment, uint8 sub_cycle_index)
{
    uint8 const * ptr;

    ptr = Sub_Cycle[compartment]->Sub_Cycles;
    ptr += Sub_Cycle[compartment]->Size_Of_Sub_Cycle_Entry * sub_cycle_index;

    return (SUB_CYCLE_CONDITION_TYPE const *)(void*)ptr;
}

