/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
/*
@startuml
        Title RinseAidDispense State Machine

        [*] --> INITIALIZE

        INITIALIZE : entry / ReadProcessParameters()
        INITIALIZE --> DISPENSER_ON : DispenserOn
        INITIALIZE --> EXIT : DispenserEnd

		DISPENSER_ON : entry  / SetCounterOn()
        DISPENSER_ON : do / ActivateDispenser() / DispenserOnTimerCheck()
        DISPENSER_ON --> DISPENSER_OFF : DispenserOff
        DISPENSER_ON --> EXIT : DispenserEnd
        DISPENSER_ON --> DISPENSER_ON : DispenserOn

		DISPENSER_OFF : entry / SetCounterOff()
        DISPENSER_OFF : do / DispenserOffTimerCheck()
        DISPENSER_OFF --> DISPENSER_ON : DispenserOn
        DISPENSER_OFF --> EXIT : DispenserEnd

        EXIT: do / returnTRUE()
@enduml
*/

//-------------------------------------- Include Files ----------------------------------------------------------------
// -- This Module --
#include "RinseAid.h"
#include "C_Extensions.h"

#include "Hbl.h"
#include "Log.h"
#include "Micro.h"
#include "Modifier.h"
#include "NVData.h"
#include "Regulations.h"
#include "SettingFile.h"
#include <string.h>
#include "SystemConfig.h"

//=====================================================================================================================
//=== StateEngineCrank (v2.8) Auto-Generated Definitions for Rinse Aid Dispense State Machine
//=====================================================================================================================
// !! StateEngineCrank cannot update this code if you change the header !!


//! Unique names used to identify states of the Rinse Aid Dispense state machine.
typedef enum RINSE_AID_DISPENSE_STATE_ENUM
{
    STATE_RINSE_AID_DISPENSE_NONE          = 0,

    STATE_RINSE_AID_DISPENSE_INITIALIZE    = 1,     //!< (initial_state)
    STATE_RINSE_AID_DISPENSE_DISPENSER_ON  = 2,
    STATE_RINSE_AID_DISPENSE_EXIT          = 3,
    STATE_RINSE_AID_DISPENSE_DISPENSER_OFF = 4,

    STATE_RINSE_AID_DISPENSE_END           = 5
} RINSE_AID_DISPENSE_STATE_TYPE;

//! The state variable for the Rinse Aid Dispense state machine.
//! State machines with a history pseudostate may write to this variable during initialization.
//! Other state machines must only write to this variable through auto-generated functions.
static RINSE_AID_DISPENSE_STATE_TYPE Rinse_Aid_Dispense_State;

//! The transition variable for the Rinse Aid Dispense state machine.
//! Flag used by the state machine to track when a transition occurs in the middle of a state's
//! Entry() or Do() action that contains more than one function.
static BOOL_TYPE Rinse_Aid_Dispense_Transitioned;

// -- Private Function Prototypes used by the state machine for customization functions --
static void ActivateDispenser(void);
static void DispenserOffTimerCheck(void);
static void DispenserOnTimerCheck(void);
static void ReadProcessParameters(void);
static void ReturnTRUE(void);
static void SetCounterOff(void);
static void SetCounterOn(void);

// -- Private Function Prototypes used by the state machine for standard state machine functions --
static void EventDispenserEnd(void);
static void EventDispenserOff(void);
static void EventDispenserOn(void);
static void RinseAidDispenseExecute(void);
static void RinseAidDispenseInitialize(void);
static void RinseAidDispenseTerminate(void);

// !! StateEngineCrank cannot update this code if you change the footer !!
// End of StateEngineCrank Auto-Generated Code.

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_RINSE_AID

//! Displacement value that indicates that the feature is not used.
#define UNUSED_FEATURE 0xFF


//! A list of log message IDs that are generated by this module.
typedef enum MODULE_RINSE_AID_LOG_MESSAGE_ID_ENUM
{
    ERROR_LOADING_PARAMETERS = 1
} MODULE_RINSE_AID_LOG_MESSAGE_ID_TYPE;

typedef enum DISPENSER_STATE_ENUM
{
	DISPENSER_STATE_OFF = 0,
	DISPENSER_STATE_ON
}DISPENSER_STATE_TYPE;

typedef PACKED struct RINSE_AID_DISPENSE_PARAMETER_STRUCT
{
    uint8 Dispenser_On_Time;
    uint8 Dispenser_Off_Time;
} RINSE_AID_DISPENSE_PARAMETER_TYPE;

typedef PACKED struct RINSE_AID_DISPENSE_PROCESS_PARAMETER_STRUCT
{
    uint8 Modifiers_Table_Index;
    uint8 Unused;
}RINSE_AID_DISPENSE_PROCESS_PARAMETER_TYPE;

typedef PACKED struct RINSE_AID_DISPENSE_INSTANCE_STRUCT
{
	uint16 Dispenser_On_Time;
    uint16 Dispenser_Off_Time;
    uint16 Counter_On;
    uint16 Counter_Off;
	uint8 Dispense_Times;
	RINSE_AID_DISPENSE_STATE_TYPE Dispense_Process_State;
} RINSE_AID_DISPENSE_INSTANCE_TYPE;



static BOOL_TYPE RinseAidDispense_Ready_To_Exit;
static PROCESS_CONTROL_TYPE* RAD_Control;

#pragma location = "_appliance_segment"
static RINSE_AID_DISPENSE_INSTANCE_TYPE RinseAidDispense;

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================
void RinseAid__Initialize(void)
{
	if ((Micro__GetResetMode() == MICRO_RESET_MODE_COLD) &&
	    (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != (NVDATA_RESTORE_TYPE)NVDATA_RESTORE_OKAY))
	{
		memset(&RinseAidDispense, 0, sizeof(RinseAidDispense));
	}
}

PROCESS_RESULT_TYPE RinseAid__Manager(PROCESS_CONTROL_TYPE* control)
{
    PROCESS_RESULT_TYPE result;

	RAD_Control = control;
	if ((uint8)control->Step_Initializing == (uint8)TRUE)
	{
		// Initialize this instance of the OWI ONe SHOT process.
		RinseAidDispense_Ready_To_Exit = FALSE;
		RinseAidDispenseInitialize();
	}
	else
	{
		Rinse_Aid_Dispense_State = RinseAidDispense.Dispense_Process_State;

		if (Rinse_Aid_Dispense_State != STATE_RINSE_AID_DISPENSE_NONE)
		{
			if (((uint8)control->Resume_From_Reset == (uint8)TRUE) ||	((uint8)control->Resume_From_Pause == (uint8)TRUE))
			{
				if ((RinseAidDispense.Dispense_Times > (uint8)0) && ((uint8)Rinse_Aid_Dispense_State == (uint8)STATE_RINSE_AID_DISPENSE_DISPENSER_ON))
				{
					RinseAidDispense.Dispense_Times--;
				}

				if (RinseAidDispense.Dispense_Times > (uint8)0)
				{
					EventDispenserOn();
				}
				else
				{
					EventDispenserEnd();
				}
			}
		}

		RinseAidDispenseExecute();

	}

    RinseAidDispense.Dispense_Process_State = Rinse_Aid_Dispense_State;


    if (Rinse_Aid_Dispense_State == STATE_RINSE_AID_DISPENSE_NONE)
    {
    	RinseAidDispense_Ready_To_Exit = TRUE;
    }

    result = ((uint8)RinseAidDispense_Ready_To_Exit == (uint8)TRUE)? PROCESS_COMPLETE : PROCESS_BUSY;

    return result;
}


//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void ReadProcessParameters(void)
{
	SETTINGFILE_LOADER_TYPE loader;
	RINSE_AID_DISPENSE_PARAMETER_TYPE* RinseAidDispense_Parameters;
	RINSE_AID_DISPENSE_PROCESS_PARAMETER_TYPE* RinseAidDispense_Process_Parameters;
	// Get the Rinse Aid Dispense parameters from the setting file machine structure.
	if ( FAIL == SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS,
											DSPL_RINSE_AID_DISPENSE,
										  &loader) )
	{
		LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, RAD_Control->Data_Field_Index);
		EventDispenserEnd();
	}
	else
	{
		// Read the setting file data into local variables for convenience.
		RinseAidDispense_Parameters = (RINSE_AID_DISPENSE_PARAMETER_TYPE*)(void*)loader.Data;

		RinseAidDispense.Dispenser_On_Time = ((RinseAidDispense_Parameters->Dispenser_On_Time/(uint16)5)*(uint16)10)+((RinseAidDispense_Parameters->Dispenser_On_Time%(uint16)5)*(uint16)2); // seconds in 100ms
		RinseAidDispense.Dispenser_Off_Time =((RinseAidDispense_Parameters->Dispenser_Off_Time/(uint16)5)*(uint16)10)+((RinseAidDispense_Parameters->Dispenser_Off_Time%(uint16)5)*(uint16)2); // seconds in 100ms

		// Get the Fill process parameters from the setting file.
		if (SettingFile__MSettingBasicLoader(RAD_Control->Setting_File_Index,
											 SF_PTR_ACU_PROCESS_RINSE_AID_DISPENSE,
											 RAD_Control->Data_Field_Index,
											 &loader) == FAIL)
		{
			LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, RAD_Control->Data_Field_Index);
			EventDispenserEnd();
		}
		else
		{
			uint8 rinse_aid_value;

			rinse_aid_value = (uint8)Regulations__GetMainValueByPosition(Regulations__GetPositionByFunctionID(FUNC_ID_RINSE_AID, 0));

			RinseAidDispense_Process_Parameters = (RINSE_AID_DISPENSE_PROCESS_PARAMETER_TYPE*)(void*)loader.Data;

			if ((uint8)UNUSED_FEATURE != RinseAidDispense_Process_Parameters->Modifiers_Table_Index)
			{
				sint32 modified_value;
				modified_value = Modifier__GetValue((sint32)(rinse_aid_value), RinseAidDispense_Process_Parameters->Modifiers_Table_Index);
				if (modified_value < 0)
				{
					modified_value = 0;
				}
				RinseAidDispense.Dispense_Times = (uint8)modified_value;
			}
			else
			{
				RinseAidDispense.Dispense_Times = rinse_aid_value;
			}

			if ((RinseAidDispense.Dispense_Times > (uint8)0) && (RinseAidDispense.Dispenser_On_Time > (uint8)0))
			{
				EventDispenserOn();
			}
			else
			{
				EventDispenserEnd();
			}
		}
	}
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void ReturnTRUE(void)
{
	RinseAidDispense_Ready_To_Exit = TRUE;
	RinseAidDispenseTerminate();
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void DispenserOffTimerCheck(void)
{
	if (RinseAidDispense.Counter_Off > (uint8)0)
	{
		RinseAidDispense.Counter_Off--;
	}
	if (RinseAidDispense.Counter_Off == (uint8)0)
	{
		if (RinseAidDispense.Dispense_Times > (uint8)0)
		{
			EventDispenserOn();
		}
		else
		{
			EventDispenserEnd();
		}
	}
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void DispenserOnTimerCheck(void)
{
	if (RinseAidDispense.Counter_On > (uint8)0)
	{
		RinseAidDispense.Counter_On--;
	}

	if (RinseAidDispense.Counter_On == (uint8)0)
	{
		if (RinseAidDispense.Dispense_Times > (uint8)0)
		{
			RinseAidDispense.Dispense_Times--;

			if (RinseAidDispense.Dispense_Times == (uint8)0)
			{
				EventDispenserEnd();
			}
			else
			{
				if (RinseAidDispense.Dispenser_Off_Time > (uint8)0)
				{
					EventDispenserOff();
				}
				else
				{
					EventDispenserOn();
				}
			}
		}
	}
}



//=====================================================================================================================
//  --- Private State Machine Customization Functions -----------------------------------------------------------------
//=====================================================================================================================


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void ActivateDispenser(void)
{
	DISPENSER_STATE_TYPE dispenser_state;

	dispenser_state = DISPENSER_STATE_ON;
	(PASS_FAIL_TYPE)Hbl__SetLoadRequestByLoadID(HBL_LOAD_DISPENSER, HBL_PRIORITY_APPLICATION_HI, (uint8 *) &dispenser_state); //lint !e928 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void SetCounterOff(void)
{

	RinseAidDispense.Counter_Off = RinseAidDispense.Dispenser_Off_Time;

}


//---------------------------------------------------------------------------------------------------------------------
/**
 *
 */
static void SetCounterOn(void)
{
	RinseAidDispense.Counter_On = RinseAidDispense.Dispenser_On_Time;
}


//=====================================================================================================================
//=== StateEngineCrank (v2.8) Auto-Generated Functions for Rinse Aid Dispense State Machine
//=====================================================================================================================
// !! StateEngineCrank cannot update this code if you change the header !!


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Dispenser End Event for the Rinse Aid Dispense state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventDispenserEnd(void)
{
    switch (Rinse_Aid_Dispense_State)
    {
        case STATE_RINSE_AID_DISPENSE_INITIALIZE:
        case STATE_RINSE_AID_DISPENSE_DISPENSER_ON:
        case STATE_RINSE_AID_DISPENSE_DISPENSER_OFF:
            Rinse_Aid_Dispense_State = STATE_RINSE_AID_DISPENSE_EXIT;
            Rinse_Aid_Dispense_Transitioned = TRUE;
            break;

        default:
            // Event is ignored for all other values of Rinse_Aid_Dispense_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Dispenser Off Event for the Rinse Aid Dispense state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventDispenserOff(void)
{
    switch (Rinse_Aid_Dispense_State)
    {
        case STATE_RINSE_AID_DISPENSE_DISPENSER_ON:
            Rinse_Aid_Dispense_State = STATE_RINSE_AID_DISPENSE_DISPENSER_OFF;
            SetCounterOff();                        // Entry Function.
            Rinse_Aid_Dispense_Transitioned = TRUE;
            break;

        default:
            // Event is ignored for all other values of Rinse_Aid_Dispense_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Process the Dispenser On Event for the Rinse Aid Dispense state machine.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void EventDispenserOn(void)
{
    switch (Rinse_Aid_Dispense_State)
    {
        case STATE_RINSE_AID_DISPENSE_INITIALIZE:
        case STATE_RINSE_AID_DISPENSE_DISPENSER_ON:
        case STATE_RINSE_AID_DISPENSE_DISPENSER_OFF:
            Rinse_Aid_Dispense_State = STATE_RINSE_AID_DISPENSE_DISPENSER_ON;
            SetCounterOn();                         // Entry Function.
            Rinse_Aid_Dispense_Transitioned = TRUE;
            break;

        default:
            // Event is ignored for all other values of Rinse_Aid_Dispense_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * The main execution function for the Rinse Aid Dispense state machine.
 * This function should be called periodically while the state machine is running.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void RinseAidDispenseExecute(void)
{
    Rinse_Aid_Dispense_Transitioned = FALSE;
    switch(Rinse_Aid_Dispense_State)
    {
        case STATE_RINSE_AID_DISPENSE_DISPENSER_ON:
            ActivateDispenser();                    // Do function.
            if (Rinse_Aid_Dispense_Transitioned == FALSE)
            {
                DispenserOnTimerCheck();            // Do function.
            }
            break;

        case STATE_RINSE_AID_DISPENSE_EXIT:
            ReturnTRUE();                           // Do function.
            break;

        case STATE_RINSE_AID_DISPENSE_DISPENSER_OFF:
            DispenserOffTimerCheck();               // Do function.
            break;

        default:
            // There is nothing to do for all other values of Rinse_Aid_Dispense_State.
            break;
    }
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * The initialization function for the Rinse Aid Dispense state machine.
 * This function resets the state machine to the initial state and executes the initial state's
 * entry function.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void RinseAidDispenseInitialize(void)
{
    Rinse_Aid_Dispense_State = STATE_RINSE_AID_DISPENSE_INITIALIZE;
    ReadProcessParameters();                        // Entry Function.
    Rinse_Aid_Dispense_Transitioned = TRUE;
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * The termination function for the Rinse Aid Dispense state machine.
 * This function disables the state machine. Calls to StateMachineExecute() will have no effect.
 * The StateMachineInitialize() function must be called again to restart the state machine.
 * If the current state has an exit function, it will be called.
 *
 *              >>> DO NOT MODIFY THIS FUNCTION <<<
 *
 * This function was auto-generated and must not be edited manually.
 * Change the UML used to generate this function and regenerate the source code.
 */
static void RinseAidDispenseTerminate(void)
{
    // None of the states have an Exit function.
    Rinse_Aid_Dispense_State = STATE_RINSE_AID_DISPENSE_NONE;
    Rinse_Aid_Dispense_Transitioned = TRUE;
}


// !! StateEngineCrank cannot update this code if you change the footer !!
// End of StateEngineCrank Auto-Generated Code.
