/**
 *  @file
 *
 *  @brief      Implements MotorPilot module.
 *
 *  @copyright  Copyright 2016-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */

//-------------------------------------- Include Files ----------------------------------------------------------------

//lint -e766 Suppress Info: header not used in module 'VirtualGI.c'
#include "SystemConfig.h"

#if (HBL_PILOT_NUM_MOTOR > 0)
#include "MotorPilot.h"

#include "API039MotionCtrl.h"
#include "Log.h"
#include <string.h>

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------


// -- Private Constant Declarations --

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_MOTOR_PILOT


// -- Private Enumerated Constant Declarations --

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_MOTOR_PILOT_LOG_MESSAGE_ID_ENUM
{
    MOTOR_COMMAND_TOO_BIG = 1
} MODULE_MOTOR_PILOT_LOG_MESSAGE_ID_TYPE;


// -- Private Structure Type Declarations --

//! Motor pilot parameters type definition.
typedef struct MOTOR_PILOT_DATA_STRUCT
{
    MOTOR_REQ_TYPE Requested;
    MOTOR_REQ_TYPE Processed;
} MOTOR_PILOT_DATA_TYPE;


// -- Private Variable Definitions --

//! Tracks the number of motor pilot allocations.
static uint8 Motor_Pilot_Allocation;

//! Motor pilot data array. One entry per motor pilot instance.
static MOTOR_PILOT_DATA_TYPE Motor_Pilot_Data[HBL_PILOT_NUM_MOTOR];


//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
#if (MOTO_PILOT_AUX_FUNC == ENABLED)
static uint8 GetMotorLoadIndex(HBL_LOAD_TYPE *load);
#endif

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief       It Initializes the module MotorPilot and its variables.
 */
void MotorPilot__Initialize(void)
{
    Motor_Pilot_Allocation = 0;
    memset(&Motor_Pilot_Data, 0, sizeof(Motor_Pilot_Data));
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Allocate instance for Motor pilot.
 *
 *  @return     uint8 retval - Allocation result.
 *  @retval     0-254 - Pilot allocation instance.
 *  @retval     0xFF - Allocation failed.
 */
uint8 MotorPilot__Allocate(void)
{
    uint8 retval;

    retval = 0xFF;

    if (Motor_Pilot_Allocation < HBL_PILOT_NUM_MOTOR)
    {
        retval = Motor_Pilot_Allocation;
        Motor_Pilot_Allocation++;
    }

    return (retval);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Initialize motor pilot instance.
 *
 *  @param      HBL_LOAD_TYPE *load - Pointer to associated motor load instance.
 *
 *  @return     PASS_FAIL_TYPE result - Result of motor pilot instance initialization.
 *  @retval     PASS - Instance initialization succeeded.
 *  @retval     FAIL - Instance initialization failed.
 */
PASS_FAIL_TYPE MotorPilot__InitializeInstance(HBL_LOAD_TYPE *load)
{
    PASS_FAIL_TYPE result;

    result = FAIL;

    if (load != NULL)
    {
        if (load->Pilot_Data_Index < Motor_Pilot_Allocation)
        {
            result = PASS;
        }
    }

    return (result);
}

//---------------------------------------------------------------------------------------------------------------------
/**
  *  @brief     Set motor pilot instance request.
 *
 *  @param      HBL_LOAD_TYPE *load - Pointer to associated motor load instance.
 *
 *  @param      void *data - Pointer to request data. Pass argument as uint8 *.
 *
 *  @return     PASS_FAIL_TYPE result - Result of motor pilot request.
 *  @retval     PASS - Instance request succeeded.
 *  @retval     FAIL - Instance request failed.
*/
PASS_FAIL_TYPE MotorPilot__Request(HBL_LOAD_TYPE *load, void *data)
{
    PASS_FAIL_TYPE result = FAIL;
    if ((load != NULL) && (data != NULL))
    {
        if (load->Pilot_Data_Index < Motor_Pilot_Allocation)
        {
            MOTOR_REQ_TYPE* source_buffer = data;
            if (source_buffer->Size > MOTOR_PILOT_MAX_BYTE_REQ_NUM)
            {
                LOG_ADD_EXCEPTION(MOTOR_COMMAND_TOO_BIG, (MOTOR_PILOT_MAX_BYTE_REQ_NUM << 8) | source_buffer->Size);
            }
            else if (source_buffer->Size == 0)
            {
                uint8 cmd[] =
                {
                    2,                                          // Number of bytes in the command
                    API039_ACTIVITY_STOP                        // Requested motor activity
                };
                memcpy(&Motor_Pilot_Data[load->Pilot_Data_Index].Requested, cmd, sizeof(cmd));
                result = PASS;
            }
            else
            {
                // Copy the highest priority request (so far) into the request buffer.
                memcpy(&Motor_Pilot_Data[load->Pilot_Data_Index].Requested, source_buffer, source_buffer->Size);
                result = PASS;
            }
        }
    }

    return (result);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Process motor pilot instance.
 *
 *  @param      HBL_LOAD_TYPE *load - Pointer to motor load instance.
 *
 *  @return     PASS_FAIL_TYPE result - Result of motor pilot instance process.
 *  @retval     PASS - Instance process succeeded.
 *  @retval     FAIL - Instance process failed.
 */
PASS_FAIL_TYPE MotorPilot__Process(HBL_LOAD_TYPE *load)
{
    PASS_FAIL_TYPE result;
    MOTOR_REQ_TYPE* current;
    MOTOR_REQ_TYPE* request;

    result = FAIL;

    if (load != NULL)
    {
        if (load->Pilot_Data_Index < Motor_Pilot_Allocation)
        {
            // Look for a change in the requested control of the motor.
            current = &Motor_Pilot_Data[load->Pilot_Data_Index].Processed;
            request = &Motor_Pilot_Data[load->Pilot_Data_Index].Requested;
            if ((request->ReqActivity != API039_ACTIVITY_NO_CHANGE) &&
                ((current->Size != request->Size) ||
                 (memcmp(current, request, current->Size))))
            {
//                API039MotionCtrl__SetMotorActivity(request->ReqActivity, request->Data, request->Size - sizeof(request->Size) - sizeof(request->ReqActivity));
                memcpy(current, request, request->Size);
            }

            result = PASS;
        }
    }

    return (result);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Get current motor pilot instance request.
 *
 *  @param      HBL_LOAD_TYPE *load - Pointer to associated motor load instance.
 *
 *  @return     void *requested - Requested instance data.
 *  @retval     Address of requested instance data. Cast it using *((uint8 *)ptr) to get values.
 *  @retval     NULL - Invalid load index.
 */
void * MotorPilot__GetRequested(HBL_LOAD_TYPE *load)
{
    void *requested;

    requested = NULL;

    if (load != NULL)
    {
        if (load->Pilot_Data_Index < Motor_Pilot_Allocation)
        {
            requested = &(Motor_Pilot_Data[load->Pilot_Data_Index].Requested);
        }
    }

    return (requested);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Get motor pilot instance processed request.
 *
 *  @param      HBL_LOAD_TYPE *load - Pointer to associated motor load instance.
 *
 *  @return     void *processed - Processed instance request.
 *  @retval     Address of processed instance request. Cast it using *((uint8 *)ptr) to get values.
 *  @retval     NULL - Invalid load index.
 */
void * MotorPilot__GetProcessed(HBL_LOAD_TYPE *load)
{
    void *processed;

    processed = NULL;

    if (load != NULL)
    {
        if (load->Pilot_Data_Index < Motor_Pilot_Allocation)
        {
            processed =  &(Motor_Pilot_Data[load->Pilot_Data_Index].Processed);
        }
    }

    return (processed);
}

void * MotorPilot__GetStatus(HBL_LOAD_TYPE *load)
{
    void *status;

    status = NULL;

    if (load != NULL)
    {
        if (load->Pilot_Data_Index < Motor_Pilot_Allocation)
        {
            status =  &(Motor_Pilot_Data[load->Pilot_Data_Index].Processed);
        }
    }

    return (status);
}
//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

#if (MOTO_PILOT_AUX_FUNC == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Get the motor load index for the external load.
 *
 *  @param      HBL_LOAD_TYPE *load - Pointer to ice dispenser door load instance.
 *
 *  @return     uint8 motor_load_index - value from setting file for load position in motor ACU loads buffer.
 */
static uint8 GetMotorLoadIndex(HBL_LOAD_TYPE *load)
{
    PASS_FAIL_TYPE load_success;
    uint8 motor_load_index;
    SETTINGFILE_LOADER_TYPE sf_loader_data;

    motor_load_index = 0;
    load_success = SettingFile__BasicLoader(SF_PTR_ACU_IO_DEVICE,
                                            load->Pilot_Type_Params_Offset,
                                            &sf_loader_data);
    if (load_success == PASS)
    {
        if (sf_loader_data.Length > 0)
        {
            motor_load_index = sf_loader_data.Data[0];
        }
    }

    return (motor_load_index);
}
#endif /* (MOTO_PILOT_AUX_FUNC == TRUE) */
#endif /* (HBL_PILOT_NUM_EXPANSION > 0) */
