/**
 *  @file       I2CRHTSensorLLI.c
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *              Design Consideration :
 *              1) Automic Reading :- TO read every one temperature/humidity reading it takes 1000 millisecond.
 *                 This Time need to be considered while designing the GI module
 *              2) This module handles only one device can be configured to read either temperature or Humidity or both Temperature and humidity value.
 *              3) Minimum Sampling rate to read One sensor value shall not be less then 100ms
 *              4) When more then one sensor is enabled on the same bus the handler will always service the first requested sensor only
 *  	 	 	   as per Hbl architecture (I2C read/Write commands are processed in 1ms handler)
 *  	 	 	   In order to avoid the conjunction on the I2C bus we will be processing the one sensor data at a time
 *
 *
 *
 *  	 	 	Special Design Consideration SHT2X :
 *  	 	 	    It is been observed that SHT2X I2C device gives wrong reading after few hours of operation or
 *  	 	 	    fluctuation of reading value with difference of more then 2 C for temperature and 10 % for Humidity
 *  	 	 	    Due to which the SHT2x Device needs to be Reset
 *  	 	 	    Resets are done on the below Conditions :
 *  	 	 	    i)   Reset After every 6 hours  Or
 *  	 	 	    ii)  Reset if the Delta observed between current reading and previous reading more then 2 C  or
 *  	 	 	    iii) Reset if the Delta observed between current reading and previous reading more then 10 % Humidity
 *
 *  	 	 	    i) On Power up do not monitor the reset condition and take the reading up to 1 minute
 *  	 	 	    ii) Do not take the reading for 1 minute once the device is reseted, up to this 1 minute publish the previous correct reading
 *
 *
 * @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------

//-------------------------------------- Include Files ----------------------------------------------------------------
#include "SystemConfig.h"

#if (HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR > 0) || (HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR > 0)
#include "I2CRHTSensorLLI.h"
#include "I2c.h"
#include "I2cMgr.h"
#include "Log.h"
#include "SystemTimers.h"
#include <string.h>
#include "stdlib.h"


//-------------------------------------- PUBLIC (Defines  ) -----------------------------------------------------------
// Time calculation
#ifndef SHT2X_SAMPLING_RATE_IN_MS
	#define SHT2X_SAMPLING_RATE_IN_MS 1000
#endif

#if (SHT2X_SAMPLING_RATE_IN_MS < 100)
	#error: "Sampling rate shall not be less then 100ms"
#endif


#define SHT2X_I2C_TIME_DELAY_BETWEEN_READING 20



#ifndef SHT2X_TOTAL_HUMIDITY_CHANNELS_USED
    #define SHT2X_TOTAL_HUMIDITY_CHANNELS_USED        0
#endif

#ifndef SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED
    #define SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED        0
#endif

//Add feature modules in the below compilation to make sure the user has selected atleast one device type
#if ((SHT2X_TOTAL_HUMIDITY_CHANNELS_USED == 0) && (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED == 0))
    #error: "At least one RHT Device shall be connected to use the I2CRHTSensorLLI module"
#endif

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_I2C_RHT_SENSOR_LLI_LOG_MESSAGE_ID_ENUM
{
    ERROR_COMMUNICATION  = 1,
    ERROR_DATA_STUCK,
}MODULE_I2C_RHT_SENSOR_LLI_LOG_MESSAGE_ID_TYPE;

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_I2C_RHT_SENSOR_LLI

//! Name of the RHT Device Type
typedef enum
{
    SHT2X_RHT_DEVICE_TYPE = 0,
	SHT2X_RHT_WRONG_TEMEPRATURE_READING = 1,
	SHT2X_RHT_WRONG_HUMIDITY_READING = 2,
    //Add new RHT devices
    MAX_RHT_DEVICE_TYPE
}RHT_DEVICE_TYPE;

// I2C Humidity Sensor State
typedef enum
{
	//Below states for the Humidity sensor
	I2C_HUMIDITY_SENSOR_STATE_WRITE = 0,
	I2C_HUMIDITY_SENSOR_STATE_WRITE_WAIT,
	I2C_HUMIDITY_SENSOR_STATE_DELAY,
	I2C_HUMIDITY_SENSOR_STATE_REQUEST,
	I2C_HUMIDITY_SENSOR_STATE_READ,
	I2C_HUMIDITY_SENSOR_STATE_INACTIVE_DELAY,

	//Below states for the temperature sensor
	I2C_TEMP_SENSOR_STATE_WRITE ,
	I2C_TEMP_SENSOR_STATE_WRITE_WAIT,
	I2C_TEMP_SENSOR_STATE_DELAY,
	I2C_TEMP_SENSOR_STATE_REQUEST,
	I2C_TEMP_SENSOR_STATE_READ,
	I2C_TEMP_SENSOR_STATE_INACTIVE_DELAY,

	//Below states for the RHT sensor
	I2C_ERROR_STATE

}SHT2X_SENSOR_STATE_TYPE;


//! RHT I2C Setting file configuration Data
PACKED typedef struct
{
	uint8 Reserved1;
	uint8 Reserved2;
	RHT_DEVICE_TYPE Device_Type   :2 ;
	I2C_SPEED_TYPE I2C_Speed      :2 ;
	I2C_ENUM_TYPE I2C_Channel     :4 ;
	uint8 Slave_Address;
	uint8 Reserved                :4 ;
	uint8 Automic_Reading         :4 ;
	uint8 Reserved3;
	uint8 Reserved4;
}I2C_RHT_SENSOR_PARAM_TYPE;

// Following enums are used instead of hardcoded numbers to provide delay
enum
{
	DELAY_1_MS     = 1,  		//   1 ms
	DELAY_2_MS     = 2,  		//   2 ms
	DELAY_5_MS     = 5,  		//   5 ms
	DELAY_20_MS    = 20, 		//   20 ms
	DELAY_1000_MS  = 1000, 		//   1000 ms
	DELAY_2000_MS  = 2000 		//   2000 ms
};

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------

#if ((SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0) || (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0))
    #define SHT2X_I2C_REQUEST_READ_BUFFER_SIZE          3
    #define SHT2X_I2C_READ_BUFFER_SIZE                  5
    #define SHT2X_I2C_WRITE_BUFFER_SIZE                 3
    // Below 3 macro are divide by 5 because we are using them as counter and decremented in asynch process which is getting called after 5 ms
	#define SHT2X_I2C_RESET_TIME_TIMEOUT                CONVERT_HOURS_TO_MILLISECONDS(6)/5 // 6 hour
	#define SHT2X_I2C_POWERUP_STABLE_TIME               CONVERT_MINUTES_TO_MILLISECOND(1)/5  // 1 minutes Power up stable time
	#define SHT2X_NEXT_READ_DELAY_AFTER_RESET	        CONVERT_MINUTES_TO_MILLISECOND(1)/5  // 1 minute timer after which reading should not take

	#define SHT2X_I2C_RESET_HMUIDTY_DELTA               (10) // Relative Humidity Delta Difference with Previous Reading to reset the I2C chip
	#define SHT2X_I2C_RESET_TEMPERATURE_DELTA           (2) //  Celcius Delta Difference with Previous Reading to reset the I2C chip


	// Enum for the Address of the SHT20 I2C
	typedef enum
	{
		SHT2X_I2C_ADDRESS_WRITE = 0x80,
		SHT2X_I2C_ADDRESS_READ  = 0x81
	}SENSOR_RHT_I2C_ADDRESS_TYPE;

	// sensor command to configure I2C device as per Table 6 of data sheet
	typedef enum
	{
		SHT2X_TRIG_T_MEASUREMENT_HM   = 0xE3,     // command trig. temp meas. hold master
		SHT2X_TRIG_RH_MEASUREMENT_HM  = 0xE5,     // command trig. humidity meas. hold master
		SHT2X_TRIG_T_MEASUREMENT_POLL = 0xF3,     // command trig. temp meas. no hold master
		SHT2X_TRIG_RH_MEASUREMENT_POLL= 0xF5,     // command trig. humidity meas. no hold master
		SHT2X_USER_REG_W              = 0xE6,     // command writing user register
		SHT2X_USER_REG_R              = 0xE7,     // command reading user register
		SHT2X_SOFT_RESET              = 0xFE      // command soft reset
	} SHT2X_COMMAND_TYPE;

	// Sensor Resolution to configure the I2C devices
	typedef enum
	{
		SHT2x_RES_12_14BIT = 0x00,  // RH=12bit, T=14bit
		SHT2x_RES_8_12BIT  = 0x01,  // RH= 8bit, T=12bit
		SHT2x_RES_10_13BIT = 0x80,  // RH=10bit, T=13bit
		SHT2x_RES_11_11BIT = 0x81,  // RH=11bit, T=11bit
		SHT2x_RES_MASK     = 0x81   // Mask for res. bits (7,0) in user reg.
	} SHT2X_RESOLUTION_TYPE;

	typedef enum
	{
		SHT2x_EOB_ON    = 0x40, // end of battery
		SHT2x_EOB_MASK  = 0x40  // Mask for EOB bit(6) in user reg.
	} SRHT_END_OF_BATTERY_TYPE;

	typedef enum
	{
		SHT2x_HEATER_ON     = 0x04, // heater on
		SHT2x_HEATER_OFF    = 0x00, // heater off
		SHT2x_HEATER_MASK   = 0x04  // Mask for Heater bit(2) in user reg.
	} SRHT_HEATER_COMMAND_TYPE;

//----------------------------------------------------------------------------------------------

	//! Humidity I2C Data
	PACKED typedef struct
	{
	    uint8 I2cMgr_Device_Handle;
	    uint16 Sensor_I2C_RH_Raw_Percentage;
	    uint32 Sensor_I2C_RH_Percentage;
	    uint16 Sensor_I2C_Relative_Humidity;
	    uint16 Sensor_I2C_Previous_Relative_Humidity;
	    uint8  Index_Average;
	    uint16 AD_RH_Buffer;
	}SHT2X_HUMIDITY_SENSOR_DATA_TYPE;

	//! Temperature I2C Data
	PACKED typedef struct
	{
	    uint8 I2cMgr_Device_Handle;
	    uint16 Sensor_I2C_Tempearture_Raw_Data;
	    sint16 Sensor_I2C_Tempearture_Raw_Celcius;
	    sint16 Sensor_I2C_Tempearture_Celcius;
	    sint16 Sensor_I2C_Tempearture_Previous_Celcius;
	    uint8  Index_Average;
	    uint16 Buffer;
	}SHT2X_TEMPERATURE_SENSOR_DATA_TYPE;

#endif  // (SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0)

#if ((SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0) || (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0))
	static SHT2X_SENSOR_STATE_TYPE  SHT2X_Device_State;

	// When more then one sensor is enabled on the same bus the handler will always service the first requested sensor only
	// as per Hbl architecture (I2C read/Write commands are processed in 1ms handler)
	// In order to avoid the conjunction on the I2C bus we will be processing the one sensor data at a time
	// The below variable will hold the handler index of the sensor to be processed if the 2nd sensor handle is called then its call will be ignored
	static SETTINGFILE_LOADER_TYPE *SHT2X_Instance_Handler_ID;
	static uint32 SHT2X_State_Delay_Counter;
	static uint8 SHT2X_Total_Sensor;

    static uint8 SHT2X_Read_Buffer[SHT2X_I2C_READ_BUFFER_SIZE];
    static uint8 SHT2X_Write_Buffer[SHT2X_I2C_WRITE_BUFFER_SIZE];

    static uint16  SHT2XI2C_Retry;         // number retries for reading data
    static uint16 SHT2XI2C_TimeOut;		// max time it takes to wait for communication w/ the device
    static uint32 SHT2X_Reset_Counter;
    static uint32 SHT2X_Powerup_Stable_Counter;
    static uint16 SHT2X_After_Reset_Stable_Counter;
    static BOOL_TYPE SHT2XI2C_Forced_Reset;
#endif

#if (HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR > 0)
	static uint8 I2CHumidity_Allocation;
	static uint8 I2CHumidity_Device_Data_Remap[HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR];
	// Add device specific data
	#if (SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0)
		static uint8 SHT2XHumidity_Allocation;
    	static SHT2X_HUMIDITY_SENSOR_DATA_TYPE SHT2XHumidity_Data[SHT2X_TOTAL_HUMIDITY_CHANNELS_USED];
	#endif
#endif

#if (HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR > 0)
    static uint8 I2CTemperature_Allocation;
    static uint8 I2CTemperature_Device_Data_Remap[HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR];
    // Add device specific data
    #if (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0)
        static uint8 SHT2XTemperature_Allocation;
    	static SHT2X_TEMPERATURE_SENSOR_DATA_TYPE SHT2XTemperature_Data[SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED];
    	static uint16 Temperature_Q15_Format;
	#endif
#endif

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------

#if ((SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0) || (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0))
    static void SHT2XResetHandler(HBL_LLI_TYPE * input);
    void SHT2xCounterHandler(void);
#endif

#if (SHT2X_TOTAL_HUMIDITY_CHANNELS_USED > 0)
	static void RHRawToPercent (HBL_LLI_TYPE * input);
	static void ProcessRHValue(HBL_LLI_TYPE * input);
	static void CheckRHNeedToReset(HBL_LLI_TYPE * input);
#endif

#if (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED > 0)
	static void TempRawToPercent (HBL_LLI_TYPE * input);
	static void ProcessTempValue(HBL_LLI_TYPE * input);
	static void ChecTempNeedToReset(HBL_LLI_TYPE * input);
#endif

//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   It Initializes the module I2CRHTSensor LLI and its variables
 */
void I2CRHTSensorLLI__Initialize(void)
{
	#if ((SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0) || (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0))
		// Initialization of the device related variables
		SHT2X_Instance_Handler_ID = NULL;
		SHT2X_State_Delay_Counter = 0;
		SHT2X_Total_Sensor = 0;
		SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_WRITE;
		SHT2XI2C_Retry = 0;
		SHT2XI2C_TimeOut = 0;
		SHT2XI2C_Forced_Reset = FALSE;
		SHT2X_Reset_Counter = SHT2X_I2C_RESET_TIME_TIMEOUT;
		SHT2X_Powerup_Stable_Counter = SHT2X_I2C_POWERUP_STABLE_TIME;
		SHT2X_After_Reset_Stable_Counter = 0;
		Temperature_Q15_Format = TEMPERATURE_INVALID_VALUE;
    #if (SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0)
		SHT2XHumidity_Allocation = 0;
    #endif
    #if (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0)
		SHT2XTemperature_Allocation = 0;
    #endif

		#if (HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR > 0)
			for (uint8 index = 0; index < HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR; index++)
			{
				memset(&SHT2XHumidity_Data[index],0,sizeof(SHT2XHumidity_Data[0]));
			}
			I2CHumidity_Allocation = 0;
		#endif

		#if (HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR > 0)
		   for (uint8 index = 0; index < HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR; index++)
		   {
			   memset(&SHT2XTemperature_Data[index],0,sizeof(SHT2XTemperature_Data[0]));
		   }
		   I2CTemperature_Allocation = 0;
		#endif
	#endif

}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   Determines the destination (index) of the data for the LLI.
 * @return  Index to a local buffer where the data will reside.
 */
#if (HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR > 0)
uint8 I2CRHTSensorLLI__AllocateHumidity(void)
{
    uint8 retval = 0xFF;

    if (I2CHumidity_Allocation < HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR)
    {
        retval = I2CHumidity_Allocation;
        I2CHumidity_Allocation++;
    }
    return (retval);
}
#endif

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   Determines the destination (index) of the data for the LLI.
 * @return  Index to a local buffer where the data will reside.
 */
#if (HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR > 0)
uint8 I2CRHTSensorLLI__AllocateTemperature(void)
{
    uint8 retval = 0xFF;

    if (I2CTemperature_Allocation < HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR)
    {
        retval = I2CTemperature_Allocation;
        I2CTemperature_Allocation++;
    }
    return (retval);
}
#endif

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   Initialize an instance of the LLI by extracting parameter data and initializing variables.
 * @param   input: data related to the instance of the LLI
 * @param   PASS if the initialization was successful, else FAIL
 */
#if (HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR > 0)
PASS_FAIL_TYPE I2CRHTSensorLLI__InitializeHumidityInstance(HBL_LLI_TYPE * input)
{
	PASS_FAIL_TYPE retval = FAIL;

    if (input->Data_Index < HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR)
    {
        I2C_RHT_SENSOR_PARAM_TYPE *param_ptr = (I2C_RHT_SENSOR_PARAM_TYPE *) (void *)(input->Parameter_Ptr.Data);

        switch (param_ptr->Device_Type)
        {
            #if (SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0)
            case SHT2X_RHT_DEVICE_TYPE:
            	I2CHumidity_Device_Data_Remap[input->Data_Index] = SHT2XHumidity_Allocation;

                if (SHT2XHumidity_Allocation < SHT2X_TOTAL_HUMIDITY_CHANNELS_USED)
                {
                    SHT2XHumidity_Data[I2CHumidity_Device_Data_Remap[input->Data_Index]].I2cMgr_Device_Handle = I2cMgr__GetDeviceHandle(param_ptr->I2C_Channel);

                    if (SHT2XHumidity_Data[I2CHumidity_Device_Data_Remap[input->Data_Index]].I2cMgr_Device_Handle != I2CMGR_HANDLE_INVALID)
                    {
                        //Initialize Device related Variables
                    	retval = (PASS_FAIL_TYPE)I2c__Initialize(param_ptr->I2C_Channel, param_ptr->I2C_Speed, I2C_ADDR_7BITS, param_ptr->Slave_Address);
                    	if(retval)
                    	{
                    		SHT2X_Instance_Handler_ID = &(input->Parameter_Ptr);
                    		SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_WRITE;
                    		SHT2XHumidity_Allocation++;
                    		SHT2X_Total_Sensor++;
                    		retval = PASS;
                    	}
                    }
                }
                break;
            #endif

            default:
                break;
        }
    }
	return (retval);
}
#endif

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   Initialize an instance of the LLI by extracting parameter data and initializing variables.
 * @param   input: data related to the instance of the LLI
 * @param   PASS if the initialization was successful, else FAIL
 */
#if (HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR > 0)
PASS_FAIL_TYPE I2CRHTSensorLLI__InitializeTemperatureInstance(HBL_LLI_TYPE * input)
{
    PASS_FAIL_TYPE retval = FAIL;

    if (input->Data_Index < HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR)
    {
        I2C_RHT_SENSOR_PARAM_TYPE *param_ptr = (I2C_RHT_SENSOR_PARAM_TYPE *) (void *)(input->Parameter_Ptr.Data);

        switch (param_ptr->Device_Type)
        {
            #if (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0)
            case SHT2X_RHT_DEVICE_TYPE:
            	I2CTemperature_Device_Data_Remap[input->Data_Index] = SHT2XTemperature_Allocation;
                if (SHT2XTemperature_Allocation < SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED)
                {
                	SHT2XTemperature_Data[I2CTemperature_Device_Data_Remap[input->Data_Index]].I2cMgr_Device_Handle = I2cMgr__GetDeviceHandle(param_ptr->I2C_Channel);

                    if (SHT2XTemperature_Data[I2CTemperature_Device_Data_Remap[input->Data_Index]].I2cMgr_Device_Handle != I2CMGR_HANDLE_INVALID)
                    {
                    	//Initialize Device related Variables
                    	retval = (PASS_FAIL_TYPE)I2c__Initialize(param_ptr->I2C_Channel, param_ptr->I2C_Speed, I2C_ADDR_7BITS, param_ptr->Slave_Address);
                    	if(retval)
                    	{
                    		SHT2X_Instance_Handler_ID = &input->Parameter_Ptr;
                    		SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_WRITE;
                    		SHT2XTemperature_Allocation++;
                    		SHT2X_Total_Sensor++;
                    		retval = PASS;
                    	}
                    }
                }
                break;
            #endif

            default:
                break;
        }
    }
    return (retval);
}
#endif
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   Retrieves the current value of the LLI
 * @param   input: data related to the instance of the LLI
 * @return  The current value of the LLI
 */
#if (HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR > 0)
void * I2CRHTSensorLLI__GetHumidity(HBL_LLI_TYPE * input)
{
	I2C_RHT_SENSOR_PARAM_TYPE *param_ptr = (I2C_RHT_SENSOR_PARAM_TYPE *) (void *)(input->Parameter_Ptr.Data);

	switch (param_ptr->Device_Type)
	{
	#if (SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0)
		case SHT2X_RHT_DEVICE_TYPE:
			return ((void *)&SHT2XHumidity_Data[I2CHumidity_Device_Data_Remap[input->Data_Index]].Sensor_I2C_Relative_Humidity);
	#endif

		default:
			return NULL;
		}
}
#endif

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   Retrieves the current value of the LLI
 * @param   input: data related to the instance of the LLI
 * @return  The current value of the LLI
 */
#if (HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR > 0)
void * I2CRHTSensorLLI__GetTemperature(HBL_LLI_TYPE * input)
{
    I2C_RHT_SENSOR_PARAM_TYPE *param_ptr = (I2C_RHT_SENSOR_PARAM_TYPE *) (void *)(input->Parameter_Ptr.Data);

    switch (param_ptr->Device_Type)
    {
     #if (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0)
     	 case SHT2X_RHT_DEVICE_TYPE:
     		Temperature_Q15_Format = ((SHT2XTemperature_Data[I2CTemperature_Device_Data_Remap[input->Data_Index]].Sensor_I2C_Tempearture_Celcius)*SHRT_MAX)/TEMPERATURE_BASE_SCALE;
     		return ((void *)&Temperature_Q15_Format);
	#endif

        default:
        	 return NULL;
     }
}
#endif

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   Asynchronous processing of a the LLI
 * @param   input: data related to the instance of the LLI
 * @return  PASS if the LLI was successfully processed, else FAIL
 */
BOOL_TYPE I2CRHTSensorLLI__AsynchProcess(HBL_LLI_TYPE * input)
{
	BOOL_TYPE retval = FALSE;

    if ((input->Data_Index < HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR) || (input->Data_Index < HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR))
    {
		I2C_RHT_SENSOR_PARAM_TYPE *param_ptr = (I2C_RHT_SENSOR_PARAM_TYPE *) (void *)(input->Parameter_Ptr.Data);

        switch (param_ptr->Device_Type)
        {
			#if ((SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0) || (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0))
            case SHT2X_RHT_DEVICE_TYPE:
                if(SHT2X_Instance_Handler_ID == &(input->Parameter_Ptr))
                {
                    SHT2xCounterHandler();
                    SHT2XResetHandler(input);
                }
                break;
            #endif

            default:
                break;
        }
        retval = TRUE;
    }
	return (retval);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief - This API is called at every 1ms
 * @param   input: data related to the instance of the LLI
 * @return  PASS if the OneMsProcess was successfully processed, else FAIL
 */
#if (HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR > 0) && (HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR > 0)
BOOL_TYPE I2CRHTSensorLLI__OneMsProcess(HBL_LLI_TYPE * input)
{
	BOOL_TYPE retval = FALSE;
	I2C_RHT_SENSOR_PARAM_TYPE *param_ptr = (I2C_RHT_SENSOR_PARAM_TYPE *) (void *)(input->Parameter_Ptr.Data);

	// This is to make sure to process the algorithm per device in sequentially
	if(SHT2X_Instance_Handler_ID == &(input->Parameter_Ptr))
   	{
		SHT2X_State_Delay_Counter++;

		switch (param_ptr->Device_Type)
		{
			#if ((SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0) || (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0))
				case SHT2X_RHT_DEVICE_TYPE:
				switch (SHT2X_Device_State)
				{
				/**
				 * Below state machine Handles the reading of the Humidity
				 */
				#if (SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0)
				case I2C_HUMIDITY_SENSOR_STATE_WRITE:
					if(I2cMgr__RequestBus(SHT2XHumidity_Data[input->Data_Index].I2cMgr_Device_Handle) == TRUE)
					{
						SHT2X_Device_State = I2C_ERROR_STATE;
						if(I2c__Initialize(param_ptr->I2C_Channel, param_ptr->I2C_Speed, I2C_ADDR_7BITS, param_ptr->Slave_Address) == TRUE)
						{
							if(I2c__Write(param_ptr->I2C_Channel, SHT2X_TRIG_RH_MEASUREMENT_POLL,SHT2X_Write_Buffer, 0) == TRUE)     // trigger a humidity measurement
							{
								SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_WRITE_WAIT;
								SHT2XI2C_TimeOut = DELAY_20_MS;
								SHT2XI2C_Retry = DELAY_5_MS;
							}
						}
					}
					break;

				case I2C_HUMIDITY_SENSOR_STATE_WRITE_WAIT:
					if ((I2c__GetStatus(param_ptr->I2C_Channel, I2C_STATUS_ERROR)) == I2C_ERROR_ACK)
					{

							SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_WRITE;
							I2cMgr__ReleaseBus(SHT2XHumidity_Data[input->Data_Index].I2cMgr_Device_Handle);
					}
					else
					{
						if ((I2c__GetStatus(param_ptr->I2C_Channel, I2C_STATUS_STATE)) == I2C_STATE_IDLE)
						{
							SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_DELAY;
							SHT2XI2C_Retry = DELAY_20_MS;
							SHT2XI2C_TimeOut = DELAY_20_MS;
							I2cMgr__ReleaseBus(SHT2XHumidity_Data[input->Data_Index].I2cMgr_Device_Handle);
						}
					}
					break;

				case I2C_HUMIDITY_SENSOR_STATE_DELAY:
					if (SHT2XI2C_Retry > 0)
					{
						SHT2XI2C_Retry--;
						SHT2XI2C_TimeOut = DELAY_20_MS;
					}
					else
					{
						SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_REQUEST;
						SHT2XI2C_Retry = DELAY_2_MS;
					}
					break;
				case I2C_HUMIDITY_SENSOR_STATE_REQUEST:
					if(I2cMgr__RequestBus(SHT2XHumidity_Data[input->Data_Index].I2cMgr_Device_Handle) == TRUE)
					{
						I2c__Initialize(param_ptr->I2C_Channel, param_ptr->I2C_Speed, I2C_ADDR_7BITS, param_ptr->Slave_Address);
						I2c__RequestRead(param_ptr->I2C_Channel, SHT2X_I2C_REQUEST_READ_BUFFER_SIZE);
						SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_READ;
					}
					break;

				case I2C_HUMIDITY_SENSOR_STATE_READ:
					if ((I2c__GetStatus(param_ptr->I2C_Channel, I2C_STATUS_ERROR)) == I2C_ERROR_ACK)
					{
						if (SHT2XI2C_Retry > 0)
						{
							SHT2XI2C_Retry--;
							SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_REQUEST;
							I2cMgr__ReleaseBus(SHT2XHumidity_Data[input->Data_Index].I2cMgr_Device_Handle);
						}
						else
						{
							SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_WRITE;
							I2cMgr__ReleaseBus(SHT2XHumidity_Data[input->Data_Index].I2cMgr_Device_Handle);
						}
					}
					else
					{
						if (I2c__GetStatus(param_ptr->I2C_Channel, I2C_STATUS_STATE) == I2C_STATE_IDLE)
						{
							I2c__Read(param_ptr->I2C_Channel, &SHT2X_Read_Buffer[1], SHT2X_I2C_READ_BUFFER_SIZE);
							I2cMgr__ReleaseBus(SHT2XHumidity_Data[input->Data_Index].I2cMgr_Device_Handle);
							SHT2X_Read_Buffer[0] = (SHT2X_I2C_ADDRESS_WRITE | 1);

							SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_RH_Raw_Percentage = (uint16)SHT2X_Read_Buffer[1];
							SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_RH_Raw_Percentage <<= 8;  // Shift to MSB Byte
							SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_RH_Raw_Percentage |= SHT2X_Read_Buffer[2];
							SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_RH_Raw_Percentage = SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_RH_Raw_Percentage & 0xfffC; // blank the last two bits-- status bits
							// get the data into the HumidithI2c_Buffer variable.
							SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_INACTIVE_DELAY;


							//Process the Humidity value
							RHRawToPercent(input);
							ProcessRHValue(input);

							sint16 remain_time = (SHT2X_SAMPLING_RATE_IN_MS / SHT2X_Total_Sensor) - SHT2X_State_Delay_Counter;

							if(remain_time > 0)
							{
								SHT2XI2C_Retry = remain_time;
								SHT2XI2C_TimeOut = remain_time + DELAY_5_MS;
							}
							else
							{
								SHT2XI2C_Retry = 0;
								SHT2XI2C_TimeOut = DELAY_20_MS;
							}
						}
					}
					break;

				case I2C_HUMIDITY_SENSOR_STATE_INACTIVE_DELAY:
					if(SHT2XI2C_Retry > 0)
					{
						SHT2XI2C_Retry--;
					}
					else
					{
						SHT2XI2C_TimeOut = DELAY_20_MS;
						#if (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0)
						if(SHT2XTemperature_Allocation > 0)
						{
							SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_WRITE;
						}
						else
						{
							SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_WRITE;
						}
						#else
						SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_WRITE;
						#endif
						SHT2X_State_Delay_Counter = 0;
					}
					break;

				#endif

					/**
					 * Below state machine Handles the reading of the temperature
					 */
				#if (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0)
				case I2C_TEMP_SENSOR_STATE_WRITE:
					if(I2cMgr__RequestBus(SHT2XTemperature_Data[input->Data_Index].I2cMgr_Device_Handle) == TRUE)
					{
						SHT2X_Device_State = I2C_ERROR_STATE;
						if(I2c__Initialize(param_ptr->I2C_Channel, param_ptr->I2C_Speed, I2C_ADDR_7BITS, param_ptr->Slave_Address) == TRUE )
						{
							if(I2c__Write(param_ptr->I2C_Channel, SHT2X_TRIG_T_MEASUREMENT_POLL,SHT2X_Write_Buffer, 0) == TRUE )     // trigger a humidity measurement
							{
								SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_WRITE_WAIT;
								SHT2XI2C_TimeOut = DELAY_20_MS;
								SHT2XI2C_Retry = DELAY_5_MS;
							}
						}
					}
					break;

				case I2C_TEMP_SENSOR_STATE_WRITE_WAIT:
					if ((I2c__GetStatus(param_ptr->I2C_Channel, I2C_STATUS_ERROR)) == I2C_ERROR_ACK)
					{
						SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_WRITE;
						I2cMgr__ReleaseBus(SHT2XTemperature_Data[input->Data_Index].I2cMgr_Device_Handle);
					}
					else
					{
						if ((I2c__GetStatus(param_ptr->I2C_Channel, I2C_STATUS_STATE)) == I2C_STATE_IDLE)
						{
							SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_DELAY;
							SHT2XI2C_Retry = DELAY_20_MS;
							SHT2XI2C_TimeOut = DELAY_20_MS;
							I2cMgr__ReleaseBus(SHT2XTemperature_Data[input->Data_Index].I2cMgr_Device_Handle);
						}
					}
					break;

				case I2C_TEMP_SENSOR_STATE_DELAY:
					if (SHT2XI2C_Retry > 0)
					{
						SHT2XI2C_Retry--;
						SHT2XI2C_TimeOut = DELAY_20_MS;
					}
					else
					{
						SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_REQUEST;
						SHT2XI2C_Retry = DELAY_1_MS;
					}
					break;

				case I2C_TEMP_SENSOR_STATE_REQUEST:
					if(I2cMgr__RequestBus(SHT2XTemperature_Data[input->Data_Index].I2cMgr_Device_Handle) == TRUE)
					{
						I2c__Initialize(param_ptr->I2C_Channel, param_ptr->I2C_Speed, I2C_ADDR_7BITS, param_ptr->Slave_Address);
						I2c__RequestRead(param_ptr->I2C_Channel, SHT2X_I2C_REQUEST_READ_BUFFER_SIZE);
						SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_READ;
					}
					break;

				case I2C_TEMP_SENSOR_STATE_READ:
					if ((I2c__GetStatus(param_ptr->I2C_Channel, I2C_STATUS_ERROR)) == I2C_ERROR_ACK)
					{
						if (SHT2XI2C_Retry > 0)
						{
							SHT2XI2C_Retry--;
							SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_REQUEST;
							I2cMgr__ReleaseBus(SHT2XTemperature_Data[input->Data_Index].I2cMgr_Device_Handle);
						}
						else
						{
							SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_WRITE;
							I2cMgr__ReleaseBus(SHT2XTemperature_Data[input->Data_Index].I2cMgr_Device_Handle);
						}
					}
					else
					{
						if (I2c__GetStatus(param_ptr->I2C_Channel, I2C_STATUS_STATE) == I2C_STATE_IDLE)
						{
							//	I2c__Initialize(param_ptr->I2C_Channel, param_ptr->I2C_Speed, param_ptr->I2C_Address_Type, param_ptr->Slave_Address);
							I2c__Read(param_ptr->I2C_Channel, &SHT2X_Read_Buffer[1], SHT2X_I2C_READ_BUFFER_SIZE);
							I2cMgr__ReleaseBus(SHT2XTemperature_Data[input->Data_Index].I2cMgr_Device_Handle);
							SHT2X_Read_Buffer[0] = (SHT2X_I2C_ADDRESS_WRITE | 1);
							// get the data into the I2CTemperature_Data variable.
							SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Raw_Data = (uint16) SHT2X_Read_Buffer[1];
							SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Raw_Data <<= 8; // Shift to MSB Byte
							SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Raw_Data |= SHT2X_Read_Buffer[2];
							SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Raw_Data = SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Raw_Data & 0xfffc; // blank last two bits status bits
							SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_INACTIVE_DELAY;


							//Process the Temperature value
							TempRawToPercent(input);
							ProcessTempValue(input);

							sint16 remain_time = (SHT2X_SAMPLING_RATE_IN_MS / SHT2X_Total_Sensor) - SHT2X_State_Delay_Counter;

							if(remain_time > 0)
							{
								SHT2XI2C_Retry = remain_time;
								SHT2XI2C_TimeOut = remain_time + DELAY_5_MS;
							}
							else
							{
								SHT2XI2C_Retry = 0;
								SHT2XI2C_TimeOut = DELAY_20_MS;
							}
						}
					}
					break;

				case I2C_TEMP_SENSOR_STATE_INACTIVE_DELAY:
					if(SHT2XI2C_Retry > 0)
					{
						SHT2XI2C_Retry--;
					}
					else
					{
						SHT2XI2C_TimeOut = DELAY_20_MS;
						#if (SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0)
						if(SHT2XHumidity_Allocation > 0)
						{
							SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_WRITE;
						}
						else
						{
							SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_WRITE;
						}
						#else
						SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_WRITE;
						#endif
						SHT2X_State_Delay_Counter = 0;
					}
					break;

				case I2C_ERROR_STATE:
					if(I2c__Initialize(param_ptr->I2C_Channel, param_ptr->I2C_Speed, I2C_ADDR_7BITS, param_ptr->Slave_Address) == TRUE)
					{
						#if (SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0)
							if(SHT2XHumidity_Allocation > 0)
							{
								SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_WRITE;
							}
						#elif (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0)
							if(SHT2XTemperature_Allocation > 0)
							{
								SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_WRITE;
							}
						#endif
					}
					break;

				#endif

				default:

					#if (SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0)
					if(SHT2XHumidity_Allocation > 0)
					{
						SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_WRITE;
					}
					#elif (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0)
					if(SHT2XTemperature_Allocation > 0)
					{
						SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_WRITE;
					}
					#endif
					SHT2X_State_Delay_Counter = 0;
					break;
				}
				break;
				#endif
				// Add New dvice type here
				default:
					break;
		}
		retval = TRUE;
    }

 // THis below code is to observe the timeout and initialize the SHT2X sensor initialization state
	#if ((SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0) || (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0))
		if (SHT2XI2C_TimeOut != 0)
		{
			if(SHT2X_Total_Sensor > 0)
			{
				SHT2XI2C_TimeOut--;
			}
		}
		else
		{
		#if (SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0)
				if(SHT2XHumidity_Allocation > 0)
				{
					SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_WRITE;
				}
		#elif (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0)
				if(SHT2XTemperature_Allocation > 0)
				{
					SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_WRITE;
				}
		#endif
		}
	#endif

	return (retval);
}
#endif

//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================
/**
 * @brief   This function convert raw value to percentage value
 *          Formula for conversion is given in Datasheet SHT20,
 *          section 6.1 Relative Humidity Conversion, page 10
 * @param   input: data related to the instance of the LLI
 */
#if (HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR > 0)
static void RHRawToPercent (HBL_LLI_TYPE * input)
{
    uint16 hum_us = 0;
    uint32 hum_ul = 0;

    hum_ul = ((uint32) SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_RH_Raw_Percentage * 125);
    hum_us = (uint16) (hum_ul / 65536);
    SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_RH_Percentage = hum_us - 6;
}
#endif
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   this function is accumulation raw percentage value, taking average and the checking for error status
 * @param   input: data related to the instance of the LLI
 */
#if (HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR > 0)
static void ProcessRHValue(HBL_LLI_TYPE * input)
{
	if (input->Data_Index < HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR)
	{
        I2C_RHT_SENSOR_PARAM_TYPE *param_ptr = (I2C_RHT_SENSOR_PARAM_TYPE *) (void *)(input->Parameter_Ptr.Data);

        if((SHT2XI2C_Forced_Reset == FALSE) && (SHT2X_After_Reset_Stable_Counter == 0))  //  This check is to maker sure not to take the reading when RHT chip is reseting
        {																																					 // The RHT after reset delay time is running
			if (SHT2XHumidity_Data[input->Data_Index].Index_Average < param_ptr->Automic_Reading)
			{
				SHT2XHumidity_Data[input->Data_Index].Index_Average++;    // Increment number of sample @ 1sec
				SHT2XHumidity_Data[input->Data_Index].AD_RH_Buffer += SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_RH_Percentage; // accumulate sample
			}
			else
			{   // take average of accumulated samples
				SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_Relative_Humidity = (uint8)(SHT2XHumidity_Data[input->Data_Index].AD_RH_Buffer / param_ptr->Automic_Reading); //


				CheckRHNeedToReset(input);

				SHT2XHumidity_Data[input->Data_Index].Index_Average = 0; // clear counter
				SHT2XHumidity_Data[input->Data_Index].AD_RH_Buffer = 0; // clear previous value
			}
		}
	}
}
#endif

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   This is primarily being done due to the fact that I2C Sensor behaves random after few days / hours of operation.
 *          Originally was resolved by Doing every 12 Hr I2C Chip reset. Now failure was seen that Sensor give abnormal value
 *          and recovers after 12 hrs which affects product operation
 * @param   input: data related to the instance of the LLI
 */
#if (HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR > 0)
static void CheckRHNeedToReset(HBL_LLI_TYPE * input)
{
	if((abs(SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_Relative_Humidity - SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_Previous_Relative_Humidity) >= SHT2X_I2C_RESET_HMUIDTY_DELTA) && //  monitor the RH delta for the failure of sensor
	   (SHT2X_Powerup_Stable_Counter == 0))                                  // this check is there to wait for Power up stable time and after that only need to detect the logic for the reset
	{
		SHT2XI2C_Forced_Reset = TRUE;
		SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_Relative_Humidity = SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_Previous_Relative_Humidity;
		LOG_ADD_EVENT(SHT2X_RHT_WRONG_HUMIDITY_READING, SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_Previous_Relative_Humidity);
	}
	else
	{
		SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_Previous_Relative_Humidity = SHT2XHumidity_Data[input->Data_Index].Sensor_I2C_Relative_Humidity; //if sensor is not detect as error state then assign the current trading to previous reading
	}
}
#endif

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   This function convert raw value to percentage value
 *          Formula for conversion is given in Datasheet SHT20,
 *          section 6.1 Relative Humidity Conversion, page 10
 * @param   input: data related to the instance of the LLI
 *
 */
#if (HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR > 0)
static void TempRawToPercent (HBL_LLI_TYPE * input)
{
	float32 temp_us = 0;
	float32 temp_ul = 0;

	temp_ul =  SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Raw_Data * 175.72;
	temp_us = (temp_ul / 65536);
	SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Raw_Celcius= (sint16)(temp_us - 46.85);
}
#endif
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   this function is accumulation raw percentage value, taking average and the checking for error status
 * @param   input: data related to the instance of the LLI
 */
#if (HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR > 0)
static void ProcessTempValue(HBL_LLI_TYPE * input)
{
	if(input->Data_Index < HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR)
	{
		I2C_RHT_SENSOR_PARAM_TYPE *param_ptr = (I2C_RHT_SENSOR_PARAM_TYPE *) (void *)(input->Parameter_Ptr.Data);

		if((SHT2XI2C_Forced_Reset == FALSE) && (SHT2X_After_Reset_Stable_Counter == 0))    //  This check is to maker sure not to take the reading when RHT chip is reseting
		{																																					 // The RHT after reset delay time is running
			if (SHT2XTemperature_Data[input->Data_Index].Index_Average < param_ptr->Automic_Reading)
			{
				SHT2XTemperature_Data[input->Data_Index].Index_Average++;    // Increment number of sample @ 1sec
				SHT2XTemperature_Data[input->Data_Index].Buffer += SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Raw_Celcius;// accumulate sample
			}
			else
			{   // take average of accumulated samples
				SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Celcius = (uint8)(SHT2XTemperature_Data[input->Data_Index].Buffer / param_ptr->Automic_Reading);
				ChecTempNeedToReset(input);
				SHT2XTemperature_Data[input->Data_Index].Index_Average = 0; // clear counter
				SHT2XTemperature_Data[input->Data_Index].Buffer = 0; // clear previous value
			}
		}
	}
}
#endif

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   This is primarily being done due to the fact that I2C Sensor behaves random after few days / hours of operation.
 *          Originally was resolved by Doing every 12 Hr I2C Chip reset. Now failure was seen that Sensor give abnormal value
 *          and recovers after 12 hrs which affects product operation
 * @param   input: data related to the instance of the LLI
 */
#if (HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR > 0)
static void ChecTempNeedToReset(HBL_LLI_TYPE * input)
{
	if((abs(SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Celcius - SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Previous_Celcius) >= SHT2X_I2C_RESET_TEMPERATURE_DELTA)&&  //  monitor the temperature delta for the failure of sensor
	   (SHT2X_Powerup_Stable_Counter == 0))                                  // this check is there to wait for Power up stable time and after that only need to detect the logic for the reset
	{
		SHT2XI2C_Forced_Reset = TRUE;
		SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Celcius = SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Previous_Celcius;  // if Sensor error is detected then take the previous correct reading for application
		LOG_ADD_EVENT(SHT2X_RHT_WRONG_TEMEPRATURE_READING, SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Previous_Celcius);
	}
	else
	{
		SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Previous_Celcius = SHT2XTemperature_Data[input->Data_Index].Sensor_I2C_Tempearture_Celcius;  //if sensor is not detect as error state then assign the current trading to previous reading
	}
}
#endif

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   this function Handle the RHT2x Chip Reset Logic.
 * @param   input: data related to the instance of the LLI
 */
#if (HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR > 0) || (HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR > 0)
static void SHT2XResetHandler(HBL_LLI_TYPE * input)
{
	if((SHT2X_Reset_Counter == 0) || (SHT2XI2C_Forced_Reset == TRUE))
	{
		I2C_RHT_SENSOR_PARAM_TYPE *param_ptr = (I2C_RHT_SENSOR_PARAM_TYPE *) (void *)(input->Parameter_Ptr.Data);

		#if (SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0)
			if(SHT2XHumidity_Allocation > 0)
			{
				if(I2cMgr__RequestBus(SHT2XHumidity_Data[input->Data_Index].I2cMgr_Device_Handle) == TRUE)
				{
		#elif (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0)
		if(SHT2XTemperature_Allocation > 0)
			{
				if(I2cMgr__RequestBus(SHT2XTemperature_Data[input->Data_Index].I2cMgr_Device_Handle) == TRUE)
				{
		#endif
				if(I2c__Initialize(param_ptr->I2C_Channel, param_ptr->I2C_Speed, I2C_ADDR_7BITS, param_ptr->Slave_Address) == TRUE )
				{
					if(I2c__Write(param_ptr->I2C_Channel, SHT2X_SOFT_RESET,SHT2X_Write_Buffer, 0) == TRUE )     // trigger a soft reset
					{
						if(SHT2XI2C_Forced_Reset == TRUE)      //  if the chip is reset due to temperature or Humidity delta then only we need to relaod the
						{                                                          //  Next reset Delay counter to not take the reading after Reset command
							SHT2XI2C_Forced_Reset = FALSE;
							SHT2X_After_Reset_Stable_Counter = SHT2X_NEXT_READ_DELAY_AFTER_RESET ;
						}
						SHT2X_Reset_Counter = SHT2X_I2C_RESET_TIME_TIMEOUT; // reload the next reset timeout timer

						// Below code is added to reset the RHT2X state machine when I2C chip is reset
						#if (SHT2X_TOTAL_HUMIDITY_CHANNELS_USED != 0)
							if(SHT2XHumidity_Allocation > 0)
							{
								I2cMgr__ReleaseBus(SHT2XTemperature_Data[input->Data_Index].I2cMgr_Device_Handle);
								SHT2X_Device_State = I2C_HUMIDITY_SENSOR_STATE_WRITE;
							}
						#elif (SHT2X_TOTAL_TEMPERATURE_CHANNELS_USED != 0)
							if(SHT2XTemperature_Allocation > 0)
							{
								I2cMgr__ReleaseBus(SHT2XTemperature_Data[input->Data_Index].I2cMgr_Device_Handle);
								SHT2X_Device_State = I2C_TEMP_SENSOR_STATE_WRITE;
							}
						#endif
						SHT2X_State_Delay_Counter = 0;
					}
				}
			}
		}
	}
}
#endif

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   this function Handle the RHT2x Counter for the Power up stable, Next read Delay, Reset timeuot after 6 hr
 */
#if (HBL_LLI_NUM_I2C_RHT_HUMIDITY_SENSOR > 0) || (HBL_LLI_NUM_I2C_RHT_TEMPERATURE_SENSOR > 0)
void SHT2xCounterHandler(void)
{
	if(SHT2X_After_Reset_Stable_Counter > 0)
	{
		SHT2X_After_Reset_Stable_Counter--;
	}

	if(SHT2X_Reset_Counter > 0)
	{
		SHT2X_Reset_Counter--;
	}

	if(SHT2X_Powerup_Stable_Counter > 0)
	{
		SHT2X_Powerup_Stable_Counter--;
	}
}
#endif

#endif //(HBL_LLI_NUM_I2C_RHT_SENSOR > 0)
