/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "C_Extensions.h"
#include "Sanitization.h"

#include "DishAuxVar.h"
#include "DoorMonitor.h"
#include "Hbl.h"
#include "Log.h"
#include "Variable.h"
//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------
#pragma location = "_appliance_segment"     // Need to save data on a black out event
static uint16 Sanitization_Minimum_Temperature;
//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_SANITIZATION

static BOOL_TYPE Stop_Task;

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_SANITIZATION_LOG_MESSAGE_ID_ENUM
{
	ERROR_LOADING_PARAMETERS       = 1,
} MODULE_SANITIZATION_LOG_MESSAGE_ID_TYPE;

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the module Sanitization and its variables
 *
 */
ACTIVE_TYPE Sanitization__Initialize(uint8 compartment, uint8 sf_index, uint8 displacement)
{
    SETTINGFILE_LOADER_TYPE loader;
    sint32 wash_probe_value;
    ACTIVE_TYPE return_value = ACTIVE;
    Stop_Task = FALSE;

    Sanitization_Result = TASK_SANITIZATION_SUCCESSFUL;

	if ( FAIL == SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS, DISPL_SANITIZATION, &loader) )
	{
		LOG_ADD_EXCEPTION(0, DISPL_SANITIZATION);
		Sanitization_Result = TASK_SANITIZATION_FAILED;
		return_value = INACTIVE;
	}
	else
	{
		Sanitization_Minimum_Temperature = ENDIANU16_STON(*((uint16*)((void*)(loader.Data))));  // Read the data from the setting file

		(void)Variable__GetValue(VARIABLE_WATER_TEMPERATURE,0,(sint32*)((void*)(&wash_probe_value)));

		if (wash_probe_value < (sint32)Sanitization_Minimum_Temperature)
		{
			Sanitization_Result = TASK_SANITIZATION_FAILED;
			return_value = INACTIVE;
		}
	}



    return ( return_value );
}

/**
 * @brief The function called at the initialise of the task after NVdata restore
 *        It Initialises the Time Elapse Module and its variables
 *
 * @param compartment that run the task (unused)
 *
 * @return  None
 */

void Sanitization__NVDataRestore(uint8 compartment)
{
	Stop_Task = TRUE;
}

/**
 * The function called during the execution of the task
 * @param compartment that run the task (inside)
 * @return the status of the task (ACTIVE or INACTIVE)
 */
ACTIVE_TYPE Sanitization__Task(uint8 compartment)
{
	DOOR_STATUS_TYPE door_status;
	ACTIVE_TYPE return_value = ACTIVE;
    door_status = DoorMonitor__GetDoorStatus();

    //if ((wash_probe_value < Sanitization_Minimum_Temperature)||(door_status == DOOR_STATUS_OPEN) || (Stop_Task == TRUE))
    if ((door_status == DOOR_STATUS_OPEN) || ((uint8)Stop_Task == (uint8)TRUE))
    {
    	Sanitization_Result = TASK_SANITIZATION_FAILED;
    	return_value = INACTIVE;
    }
    else
    {
    	Sanitization_Result = TASK_SANITIZATION_SUCCESSFUL;
    }
    return(return_value);
}

/**
 * The function used when the task terminate. It reinitialise the Counter and corresponding variables of the task
 * @param compartment the compartment that uses the task (unused)
 *
 * @return : None
 */
void Sanitization__Terminate(uint8 compartment)
{

}


void Sanitization__SetResultVariable(TASK_SANITIZATION_RESULT_TYPE result)
{
	Sanitization_Result = result;
}


//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================


