/**
 *  @file       RinseAidMonitor.c
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *---------------------------------------------------------------------------------------------------------------------
 *------------------- Copyright 2011.  Whirlpool Corporation.  All rights reserved - CONFIDENTIAL ---------------------
 *---------------------------------------------------------------------------------------------------------------------
 */

//-------------------------------------- Include Files ----------------------------------------------------------------
#include "C_Extensions.h"
#include "RinseAidMonitor.h"

#include "DoorMonitor.h"
#include "Hbl.h"
#include "Interpreter.h"
#include "Log.h"
#include "Micro.h"
#include "Millis.h"
#include "NVData.h"
#include "Selector.h"
#include "Supervisor.h"

#define DISPENSER_MAX_USAGE 			(uint8)(51)
#define PROGRAMMING_MEASURE_DELAY_SEC 	(2)

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------
uint8 Rinse_Aid_Status;

typedef enum RINSE_AID_STATUS_ENUM
{
    RINSE_AID_STATUS_LED_OFF 		= 0,
    RINSE_AID_STATUS_LED_SOLID_ON 	= 1,
	RINSE_AID_STATUS_LED_BLINK 		= 2
} RINSE_AID_STATUS_TYPE;



typedef enum RINSE_AID_SENSOR_ENUM
{
    RINSE_AID_SENSOR_EMPTY 			= 0,
    RINSE_AID_SENSOR_FULL			= 1,
	RINSE_AID_SENSOR_INVALID_VALUE  = 2	 //This value is reserved for MSA sensor so schouldn't be used in RinseAid module
}RINSE_AID_SENSOR_TYPE;

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------

RINSE_AID_MONITOR_INSTANCE_TYPE Sf_RinseAid_Data;

#pragma location = "_appliance_segment"
static RINSE_AID_SENSOR_TYPE Last_Rinse_Aid_Status;

#pragma location = "_appliance_segment"
uint8 RinseAid_Dispenser_Use_Cnt;

#pragma location = "_appliance_segment"
static BOOL_TYPE RinseAid_IsUnlocked; //Module will be activate after first usage

#pragma location = "_appliance_segment"
static BOOL_TYPE Check_RinsAid_State;

static ON_OFF_TYPE Dispenser_State;
static ON_OFF_TYPE Dispenser_State_Prev;
static MILLIS_TIMER_TYPE Rinse_Aid_Timer;
static BOOL_TYPE Programming_Measurment_Done;


//! The name of this module for use by the Log module.
#define MODULE_NAME 	MODULE_RINSE_AID_MONITOR

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_RINSE_AID_MONITOR_LOG_MESSAGE_ID_ENUM
{
	ERROR_LOADING_PARAMETERS       = 1,
} MODULE_RINSE_AID_MONITOR_LOG_MESSAGE_ID_TYPE;

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------

void ReadRinsAidLevel(void);
void DetectRinseAidInjection(void);
void UpdateRinseAidStatus(void);
RINSE_AID_STATUS_TYPE EvaluateRinseAid_State(uint8 Thr1, uint8 Thr2, uint8 current_val);
//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the module RinseAidMonitor and its variables
 *
 */
void RinseAidMonitor__Initialize(void)
{
	SETTINGFILE_LOADER_TYPE loader;

	//Initialize NVData values
	if (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != (NVDATA_RESTORE_TYPE)NVDATA_RESTORE_OKAY)
	{
		Last_Rinse_Aid_Status = RINSE_AID_SENSOR_EMPTY;
		RinseAid_Dispenser_Use_Cnt = 0;
		RinseAid_IsUnlocked = FALSE;
		Check_RinsAid_State = FALSE;
	}


	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		if (SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS, DSPL_RINSE_AID, &loader) == PASS)
		{
			Sf_RinseAid_Data.Door_Close_Timer = ((RINSE_AID_MONITOR_INSTANCE_TYPE*)(void*)(loader.Data))->Door_Close_Timer;
			Sf_RinseAid_Data.Threshold_1 	  = ((RINSE_AID_MONITOR_INSTANCE_TYPE*)(void*)(loader.Data))->Threshold_1;
			Sf_RinseAid_Data.Threshold_2 	  = ((RINSE_AID_MONITOR_INSTANCE_TYPE*)(void*)(loader.Data))->Threshold_2;
		}
		else
		{
			LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, SF_PTR_ACU_ALGORITHM_PARAMETERS);

			Sf_RinseAid_Data.Door_Close_Timer = 30; //Default value from SettingFile

			//If THR1 and THR2 are set to 0 we we will always have RINSE_AID_STATUS_LED_OFF
			Sf_RinseAid_Data.Threshold_1 = 0;
			Sf_RinseAid_Data.Threshold_2 = 0;
		}

		Dispenser_State = OFF;
		Dispenser_State_Prev = OFF;
		Rinse_Aid_Status = RINSE_AID_STATUS_LED_OFF; //Default value
		Programming_Measurment_Done = FALSE;

	    Millis__Start(&Rinse_Aid_Timer);
	}
}

/**
 * @brief Main handler for RinseAidMonitor module
 */
void RinseAidMonitor__Execution(void)
{
	//In service and EOL test we want to have specific behavior for Rinse_Aid_Status
	if ((uint8)Supervisor__IsTestCycleActive() == (uint8)TRUE)
	{
		RINSE_AID_SENSOR_TYPE temp;

		temp = (RINSE_AID_SENSOR_TYPE)Hbl__GetGIDataConvertedByIndex(Hbl__GetGIIndexByGIID(HBL_GI_RINSE_AID));

		if(temp == RINSE_AID_SENSOR_EMPTY)
		{
			Rinse_Aid_Status = RINSE_AID_STATUS_LED_OFF;
		}
		else if( temp == RINSE_AID_SENSOR_FULL)
		{
			Rinse_Aid_Status = RINSE_AID_STATUS_LED_SOLID_ON;
		}
	}
	else
	{
		//Check RinseAid sensor to detect refill
		ReadRinsAidLevel();

		//Start estimate RinseAid when we will detect empty condition on sensor
		DetectRinseAidInjection();

		//Update RinseAid Regulation value
		UpdateRinseAidStatus();
	}
}


/**
 * @brief	Function which should be invoked when cycle is started or started with delay
 */
void RinseAidMonitor__CheckEvent(void)
{
    Check_RinsAid_State = TRUE;
}
//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

/**
 * @brief 	Detect if user refill RinseAid
 */
void ReadRinsAidLevel(void)
{
	CYCLE_PHASE_STATEMENT_TYPE cps = Interpreter__GetCurrentStatement(COMPARTMENT_DEFAULT);
	CYCLE_STATE_TYPE cycle_state = (Selector__GetCycleState(0, COMPARTMENT_DEFAULT, cps.Cycle));

	if (DOOR_STATUS_CLOSE == DoorMonitor__GetDoorStatus())
	{
		if ((cycle_state == CYCLE_STATE_PROGRAMMING) && (cps.Phase != (uint8)0))
		{
			if ((Millis__GetElapsedSeconds(&Rinse_Aid_Timer) >= (uint32)PROGRAMMING_MEASURE_DELAY_SEC) &&
				(Programming_Measurment_Done == FALSE))
			{
				uint8 *ra_activation_state_ptr;
				uint8 ra_activation_state;
				RINSE_AID_SENSOR_TYPE temp;

				ra_activation_state_ptr = (uint8*)Hbl__GetLoadStatusByLoadID(HBL_LOAD_RINSE_AID_INPUT_ACTIVATION);

				if (ra_activation_state_ptr != NULL)
				{
					ra_activation_state = *ra_activation_state_ptr;
				}
				else
				{
					ra_activation_state = (uint8)ON;
				}

				if (ra_activation_state == (uint8)ON)
				{
					temp = (RINSE_AID_SENSOR_TYPE)Hbl__GetGIDataConvertedByIndex(Hbl__GetGIIndexByGIID(HBL_GI_RINSE_AID));

					//Update variables only if we read RinseAid not MSA
					if(temp < RINSE_AID_SENSOR_INVALID_VALUE)
					{
						//Detect Rising Edge
						if((Last_Rinse_Aid_Status == RINSE_AID_SENSOR_EMPTY) &&
						   (temp == RINSE_AID_SENSOR_FULL))
						{
							RinseAid_Dispenser_Use_Cnt = 0;
							//Unlock RinseAid status display after first refill
							RinseAid_IsUnlocked = TRUE;

							Last_Rinse_Aid_Status = temp; //Update this value only if we have falling edge (refill retection)
						}

						Programming_Measurment_Done = TRUE;
					}
				}
			}
		}
		else
		{
			Programming_Measurment_Done = FALSE;

			if ((cycle_state == CYCLE_STATE_RUN) || (cycle_state == CYCLE_STATE_DELAY))
			{
				if ((Millis__GetElapsedSeconds(&Rinse_Aid_Timer) >= Sf_RinseAid_Data.Door_Close_Timer) &&
					((uint8)Check_RinsAid_State == (uint8)TRUE))
				{
					uint8 *ra_activation_state_ptr;
					uint8 ra_activation_state;
					RINSE_AID_SENSOR_TYPE temp;

					ra_activation_state_ptr = (uint8*)Hbl__GetLoadStatusByLoadID(HBL_LOAD_RINSE_AID_INPUT_ACTIVATION);

					if (ra_activation_state_ptr != NULL)
					{
						ra_activation_state = *ra_activation_state_ptr;
					}
					else
					{
						ra_activation_state = (uint8)ON;
					}

					if (ra_activation_state == (uint8)ON)
					{
						temp = (RINSE_AID_SENSOR_TYPE)Hbl__GetGIDataConvertedByIndex(Hbl__GetGIIndexByGIID(HBL_GI_RINSE_AID));

						//Update variables only if we read RinseAid not MSA
						if(temp < RINSE_AID_SENSOR_INVALID_VALUE)
						{
							//Detect Rising Edge
							if((Last_Rinse_Aid_Status == RINSE_AID_SENSOR_EMPTY) &&
							   (temp == RINSE_AID_SENSOR_FULL))
							{
								RinseAid_Dispenser_Use_Cnt = 0;
								//Unlock RinseAid status display after first refill
								RinseAid_IsUnlocked = TRUE;
							}

							Last_Rinse_Aid_Status = temp;
							Check_RinsAid_State = FALSE;
						}
					}
				}
			}
		}
	}
	else
	{
	    Millis__Start(&Rinse_Aid_Timer);
		Programming_Measurment_Done = FALSE;
	}
}


/**
 * 	@brief 	Detect if dispenser was used and increment RinseAid usage counter
 */
void DetectRinseAidInjection(void)
{
    uint8 *load_state_ptr;

    //Detect dispenser injection
    load_state_ptr = (uint8*)(Hbl__GetLoadStatusByLoadID(HBL_LOAD_DISPENSER));
    if (load_state_ptr != NULL)
    {
		Dispenser_State = (load_state_ptr[0] == (uint8)ON) ? ON:OFF;
    }

	//Detect Rising Edge
	if (Dispenser_State != Dispenser_State_Prev)
	{
		Dispenser_State_Prev = Dispenser_State;

		if((Dispenser_State == ON) &&
		   (RinseAid_Dispenser_Use_Cnt < DISPENSER_MAX_USAGE))
		{
			if(Last_Rinse_Aid_Status == RINSE_AID_SENSOR_EMPTY)
			{
				RinseAid_Dispenser_Use_Cnt++;
			}
		}
	}
}


/**
 *  @brief	Updates status of RinseAid regulation
 */
void UpdateRinseAidStatus(void)
{
	//We want to show status until user will activate module by first refill
	if(RinseAid_IsUnlocked == FALSE)
	{
		Rinse_Aid_Status = RINSE_AID_STATUS_LED_OFF;
	}
	else
	{
		Rinse_Aid_Status = EvaluateRinseAid_State(Sf_RinseAid_Data.Threshold_1, Sf_RinseAid_Data.Threshold_2, RinseAid_Dispenser_Use_Cnt);
	}
}


/**
 *
 *  @brief	Function which evaluate current state of Rinse_Aid_Status regulation
 *
 *   ------------------------------------------------------------------------------------------------------------------------
 *	|					CONDITION	 	 	 	 	    0                     THR1      			 THR2					 |
 *	|---------------------------------------------------|----------------------|----------------------|----------------------|
 *	|  (THR1 = 0) AND (THR2 > 0):      	  			    | LED_OFF 			   | LED_OFF 		      | LED_BLINK			 |
 *	|---------------------------------------------------|----------------------|----------------------|----------------------|
 *	|  (THR1 > 0) AND (THR2 = 0):      				    | LED_OFF 			   | LED_SOLID_ON 		  | LED_SOLID_ON		 |
 *	|---------------------------------------------------|----------------------|----------------------|----------------------|
 *	|  (THR1 = 0) AND (THR2 = 0):      				    | LED_OFF 			   | LED_OFF 		  	  | LED_OFF		 		 |
 *	|---------------------------------------------------|----------------------|----------------------|----------------------|
 *	|  (THR1 < THR2) AND ((THR1 > 0) AND (THR2 > 0)):   | LED_OFF 			   | LED_SOLID_ON 		  | LED_BLINK			 |
 *	|---------------------------------------------------|----------------------|----------------------|----------------------|
 *	|  (THR1 > THR2) AND ((THR1 > 0) AND (THR2 > 0)):   | LED_OFF 			   | LED_BLINK 		      | LED_SOLID_ON		 |
 * 	|---------------------------------------------------|----------------------|----------------------|----------------------|
 *	|  (THR1 = THR2) AND ((THR1 > 0) AND (THR2 > 0)):   | LED_OFF 			   | LED_SOLID_ON 		  | LED_SOLID_ON		 |
 *	 ---------------------------------------------------|----------------------|----------------------|----------------------
 *
 *
 * @param Thr1 - Setting File threshold1
 * @param Thr2 - Setting File threshold2
 * @param current_val - Amount of dispenser usage
 * @return RinseAid status
 *
 */
RINSE_AID_STATUS_TYPE EvaluateRinseAid_State(uint8 Thr1, uint8 Thr2, uint8 current_val)
{
	RINSE_AID_STATUS_TYPE retval;
	if((Thr1 == (uint8)0) || (Thr2 == (uint8)0))
	{
		if(Thr1 > (uint8)0)
		{
			if(current_val < Thr1)
			{
				retval = RINSE_AID_STATUS_LED_OFF;
			}
			else
			{
				retval = RINSE_AID_STATUS_LED_SOLID_ON;
			}
		}
		else if(Thr2 > (uint8)0)
		{
			if(current_val < Thr2)
			{
				retval = RINSE_AID_STATUS_LED_OFF;
			}
			else
			{
				retval = RINSE_AID_STATUS_LED_BLINK;
			}
		}
		else // if((Thr1 == 0) && (Thr2 == 0))
		{
			retval = RINSE_AID_STATUS_LED_OFF;
		}
	}
	else
	{
		if(Thr1 < Thr2)
		{
			if(current_val < Thr1)
			{
				retval = RINSE_AID_STATUS_LED_OFF;
			}
			else if((current_val >= Thr1) && (current_val < Thr2))
			{
				retval = RINSE_AID_STATUS_LED_SOLID_ON;
			}
			else
			{
				retval = RINSE_AID_STATUS_LED_BLINK;
			}
		}
		else if(Thr1 > Thr2)
		{
			if(current_val < Thr2)
			{
				retval = RINSE_AID_STATUS_LED_OFF;
			}
			else if((current_val >= Thr2) && (current_val < Thr1))
			{
				retval = RINSE_AID_STATUS_LED_BLINK;
			}
			else
			{
				retval = RINSE_AID_STATUS_LED_SOLID_ON;
			}
		}
		else //if(Thr1 == Thr2)
		{
			if(current_val < Thr1)
			{
				retval = RINSE_AID_STATUS_LED_OFF;
			}
			else
			{
				retval = RINSE_AID_STATUS_LED_SOLID_ON;
			}
		}
	}

	return retval;
}



