/**
 *  @file		SaltSensingMonitor.c
 *
 *  @brief		It implements the execution of the Salt Sensing Monitor.
 *
 *  @details	It manages the reading of the Salt Sensor and updates the status of Salt_Alarm_Led
 *  			variable according to the requirements.
 *
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
// -- This Module --
#include "SystemConfig.h"
#include "SaltSensingMonitor.h"

// -- Other Modules --
#include "Hbl.h"
#include "Log.h"
#include "Micro.h"
#include "NVData.h"
#include "Regenerate.h"
#include "SettingFile.h"
#include "Supervisor.h"


//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------
//! Status of the Salt Alarm LED to be communicated to the HMI
SALT_ALARM_LED_STATE_TYPE Salt_Alarm_Led;


//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
//! The name of this module to be used by the Log module.
#define MODULE_NAME MODULE_SALT_SENSING_MONITOR

//! The number of times that the SaltSensingMonitor__Execution function will be called every second while running.
#define SALT_SENSING_MONITOR_CALLS_PER_SECOND 	10

// If the call rate of the monitor is different from 10, Salt_Stability_Counter has to be rescaled
CT_ASSERT(SALT_SENSING_MONITOR_CALLS_PER_SECOND == 10);

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_SALT_SENSING_MONITOR_LOG_MESSAGE_ID_ENUM
{
	ERROR_MISSING_PARAMETERS  = 1,
} MODULE_SALT_SENSING_MONITOR_LOG_MESSAGE_ID_TYPE;

typedef struct SALT_SENSOR_DATA_STRUCT
{
	WATER_SOFTENER_SF_PARAMS_TYPE* Water_Softener_Params_Ptr;
	SALT_SENSOR_STATE_TYPE Salt_GI_Unfiltered;
	SALT_SENSOR_STATE_TYPE Salt_GI_Filtered;
	uint8 Salt_Stability_Counter;
} SALT_SENSOR_DATA_TYPE;

typedef struct SALT_SENSOR_NV_DATA_STRUCT
{
	SALT_SENSOR_STATE_TYPE Prev_Salt_GI_Filtered;
} SALT_SENSOR_NV_DATA_TYPE;

//! Volatile data for Salt Sensor management
static SALT_SENSOR_DATA_TYPE Salt_Sensor_Data;

//! Non Volatile data for Salt Sensor management
#pragma location = "_appliance_segment"
static SALT_SENSOR_NV_DATA_TYPE Salt_Sensor_NV_Data;


//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
void UpdatSaltAlarmLedStatus(void);

//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//----------------------------------------------------------------------------
/**
 * It initializes the Salt Sensing Monitor and its data, also loading data from setting file.
 *
 * @return None
 *
 */
void SaltSensingMonitor__Initialize(void)
{
	SETTINGFILE_LOADER_TYPE loader;

	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		Salt_Alarm_Led = SALT_ALARM_LED_STATE_OFF; // Default initialization if Salt Sensor Input is not present
		Salt_Sensor_Data.Salt_GI_Unfiltered = SALT_SENSOR_INVALID_VALUE; // To force restart stability counter when the first valid read is done
		Salt_Sensor_Data.Salt_GI_Filtered = SALT_SENSOR_INVALID_VALUE;
		if (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != (NVDATA_RESTORE_TYPE)NVDATA_RESTORE_OKAY)
		{
			Salt_Sensor_NV_Data.Prev_Salt_GI_Filtered = SALT_NOT_PRESENT; // To detect a salt rising edge if the customer refill the salt tank
		}

		Salt_Sensor_Data.Salt_Stability_Counter = 0;

		// Get the required parameters from the setting file.
		if (SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS, DSPL_WATER_SOFTENER, &loader) == PASS)
		{
			Salt_Sensor_Data.Water_Softener_Params_Ptr = (WATER_SOFTENER_SF_PARAMS_TYPE *)(void*)loader.Data;
		}
		else
		{
			// Parameters missing
			Salt_Sensor_Data.Water_Softener_Params_Ptr = (WATER_SOFTENER_SF_PARAMS_TYPE *)NULL;

			LOG_ADD_EXCEPTION(ERROR_MISSING_PARAMETERS, DSPL_WATER_SOFTENER);
		}
	}
}


//----------------------------------------------------------------------------
/**
 * It implements the execution of the Salt Sensing Monitor.
 * It manages the reading of the Salt Sensor and updates the status of Salt_Alarm_Led variable according to the requirements.
 *
 * @return None
 *
 */
void SaltSensingMonitor__Execution(void)
{
	uint8 salt_gi_index;
	uint8 salt_input_activation_load_index;
	uint8 salt_gi_sequence_id;
	SALT_SENSOR_STATE_TYPE salt_GI_value;

	salt_gi_index = Hbl__GetGIIndexByGIID(HBL_GI_SALT);
	if ((salt_gi_index != (uint8)HBL_INDEX_INVALID) && (Salt_Sensor_Data.Water_Softener_Params_Ptr != NULL))
	{
		salt_input_activation_load_index = Hbl__GetLoadIndexByLoadID(HBL_LOAD_SALT_INPUT_ACTIVATION);

		if ((salt_input_activation_load_index == (uint8)HBL_INDEX_INVALID) || (*((uint8 *)Hbl__GetProcessedLoad(salt_input_activation_load_index)) != (uint8)OFF))
		{
			// Salt input activation load absent or present and activated: salt input can be read
			salt_gi_sequence_id = Hbl__GetGISequenceIDByIndex(salt_gi_index);
			if (salt_gi_sequence_id > (uint8)0)
			{
				salt_GI_value = (SALT_SENSOR_STATE_TYPE)Hbl__GetGIDataConvertedByIndex(salt_gi_index);

				if (salt_GI_value < SALT_SENSOR_INVALID_VALUE )
				{
					if (salt_GI_value != Salt_Sensor_Data.Salt_GI_Unfiltered)
					{
						// Restart stability counter
						Salt_Sensor_Data.Salt_Stability_Counter = Salt_Sensor_Data.Water_Softener_Params_Ptr->Salt_Input_Stability_Time;
					}

					// Check stability counter
					if (Salt_Sensor_Data.Salt_Stability_Counter > (uint8)0)
					{
						Salt_Sensor_Data.Salt_Stability_Counter --;
					}
					else
					{
						Salt_Sensor_Data.Salt_GI_Filtered = salt_GI_value;
					}
				}
				Salt_Sensor_Data.Salt_GI_Unfiltered = salt_GI_value;
			}
		}
		else
		{
			// Salt input activation load present and not activated: salt input is considered not valid
			Salt_Sensor_Data.Salt_GI_Unfiltered = SALT_SENSOR_INVALID_VALUE; // To force restart stability counter when the first valid read is done
			Salt_Sensor_Data.Salt_GI_Filtered = SALT_SENSOR_INVALID_VALUE;
		}


		// Update Salt rising and falling edges
		if (Salt_Sensor_Data.Salt_GI_Filtered < SALT_SENSOR_INVALID_VALUE)
		{
			if (Salt_Sensor_Data.Salt_GI_Filtered != Salt_Sensor_NV_Data.Prev_Salt_GI_Filtered)
			{
				if (Salt_Sensor_Data.Salt_GI_Filtered == SALT_PRESENT)
				{
					// Salt Rising edge
					if (((uint8)Regenerate__GetBitmapBit(SALT_RISING_EDGE) == (uint8)TRUE) && ((uint8)Regenerate__GetBitmapBit(SALT_FALLING_EDGE) == (uint8)TRUE))
					{
						Regenerate__ClearBitmapBit(SALT_FALLING_EDGE);
					}
					else
					{
						Regenerate__SetBitmapBit(SALT_RISING_EDGE);
					}
				}
				else
				{
					// Salt Falling edge
					if (((uint8)Regenerate__GetBitmapBit(SALT_RISING_EDGE) == (uint8)TRUE) && ((uint8)Regenerate__GetBitmapBit(SALT_FALLING_EDGE) == (uint8)TRUE))
					{
						Regenerate__ClearBitmapBit(SALT_RISING_EDGE);
					}
					else
					{
						Regenerate__SetBitmapBit(SALT_FALLING_EDGE);
					}
				}

				Salt_Sensor_NV_Data.Prev_Salt_GI_Filtered = Salt_Sensor_Data.Salt_GI_Filtered;
			}
		}

		// Update Salt_Alarm_Led based on Salt_GI_Filtered
		UpdatSaltAlarmLedStatus();
	}
	else
	{
		// Salt sensor not present or setting file parameters missing, do nothing
	}
}


/**
 * It returns the filtered value of the Salt GI
 *
 */
SALT_SENSOR_STATE_TYPE SaltSensingMonitor__GetSaltGIFiltered(void)
{
	return Salt_Sensor_Data.Salt_GI_Filtered;

}

/**
 * It returns the last valid filtered value of the Salt GI. It may differs from Salt_GI_Filtered if
 * this is INVALID, typically after a cold reset or after the Salt input activation load has been
 * deactivated.
 *
 */
SALT_SENSOR_STATE_TYPE SaltSensingMonitor__GetPrevSaltGIFiltered(void)
{
	return Salt_Sensor_NV_Data.Prev_Salt_GI_Filtered;
}

//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

void UpdatSaltAlarmLedStatus(void)
{
	SALT_ALARM_LED_STATE_TYPE salt_alm_led;

	salt_alm_led = SALT_ALARM_LED_STATE_OFF; // Default assignment to save code

	if ((uint8)Supervisor__IsTestCycleActive() == (uint8)TRUE)
	{
		if (Salt_Sensor_Data.Salt_GI_Unfiltered == SALT_PRESENT)
		{
			salt_alm_led = SALT_ALARM_LED_STATE_SOLID_ON;
		}
		else
		{
			// SALT_ALARM_LED_STATE_OFF;
		}
	}
	else
	{
		uint8 water_hardness_func_pos = Regulations__GetPositionByFunctionID(FUNC_ID_WATER_HARDNESS_LEVEL, COMPARTMENT_DEFAULT);
		BOOL_TYPE force_salt_alm_led_off = FALSE;
		SALT_SENSOR_STATE_TYPE salt_GI_value;
		uint8 n_reg_max_on = Salt_Sensor_Data.Water_Softener_Params_Ptr->N_Reg_Max_On;
		uint8 n_reg_max_blink = Salt_Sensor_Data.Water_Softener_Params_Ptr->N_Reg_Max_Blink;
		uint8 n_reg_max = Regenerate__GetNumRegeneration();

		if (water_hardness_func_pos < Regulations__GetTotalSize())
		{
			// Water Hardness function is present in setting file

			if (Regulations__GetMainValueByPosition(water_hardness_func_pos) == 0)
			{
				force_salt_alm_led_off = TRUE;
			}
		}

		if (Salt_Sensor_Data.Salt_GI_Filtered != SALT_SENSOR_INVALID_VALUE)
		{
			// First filtered read of Salt GI available
			salt_GI_value = Salt_Sensor_Data.Salt_GI_Filtered;
		}
		else
		{
			// First filtered read of Salt GI not available, use last filtered read
			salt_GI_value = Salt_Sensor_NV_Data.Prev_Salt_GI_Filtered;
		}


		if ((salt_GI_value == SALT_NOT_PRESENT) && (force_salt_alm_led_off == FALSE))
		{
			// Check thresholds
			if (n_reg_max_on == (uint8)0)
			{
				if (n_reg_max_blink != (uint8)0)
				{
					if (n_reg_max >= n_reg_max_blink)
					{
						salt_alm_led = SALT_ALARM_LED_STATE_BLINK;
					}
					else
					{
						// SALT_ALARM_LED_STATE_OFF;
					}
				}
				else
				{
					// Both thresholds == 0, SALT_ALARM_LED_STATE_OFF;
				}
			}
			else if (n_reg_max_blink == (uint8)0)
			{
				// n_reg_max_on for sure != 0
				if (n_reg_max >= n_reg_max_on)
				{
					salt_alm_led = SALT_ALARM_LED_STATE_SOLID_ON;
				}
				else
				{
					// SALT_ALARM_LED_STATE_OFF;
				}
			}
			else if (n_reg_max_on >= n_reg_max_blink)
			{
				if (n_reg_max >= n_reg_max_on)
				{
					salt_alm_led = SALT_ALARM_LED_STATE_SOLID_ON;
				}
				else if (n_reg_max >= n_reg_max_blink)
				{
					salt_alm_led = SALT_ALARM_LED_STATE_BLINK;
				}
				else
				{
					// SALT_ALARM_LED_STATE_OFF;
				}
			}
			else
			{
				// n_reg_max_blink > n_reg_max_on
				if (n_reg_max >= n_reg_max_blink)
				{
					salt_alm_led = SALT_ALARM_LED_STATE_BLINK;
				}
				else if (n_reg_max >= n_reg_max_on)
				{
					salt_alm_led = SALT_ALARM_LED_STATE_SOLID_ON;
				}
				else
				{
					// SALT_ALARM_LED_STATE_OFF;
				}
			}
		}
		else
		{
			// SALT_ALARM_LED_STATE_OFF;
		}
	}

	Salt_Alarm_Led = salt_alm_led;
}

