/**
 * @file
 * @brief       Public interface declarations for Fault Debounce modules.
 *
 * @details     Fault Debounce functionality is implemented by individual modules and managed by the Fault module.
 *
 * @copyright   Copyright 2016,2018 Whirlpool Corporation.  All rights reserved - CONFIDENTIAL.
 */

#ifndef FAULTDEBOUNCEINTERFACE_H_
#define FAULTDEBOUNCEINTERFACE_H_


//  --- Include Files -------------------------------------------------------------------------------------------------

// -- This Module --

// -- Other Modules --


//=====================================================================================================================
//  --- Public Properties ---------------------------------------------------------------------------------------------
//=====================================================================================================================

// -- Public Constant Declarations --


// -- Private Enumeration Type Declarations --

//! Enumerated list of events that can be generated by the fault debounce method.
typedef enum FAULT_DEBOUNCE_EVENT_ENUM
{
    FAULT_DEBOUNCE_EVENT_NONE   = 0,
    FAULT_DEBOUNCE_EVENT_REPEAT = 1,
    FAULT_DEBOUNCE_EVENT_NEXT   = 2,
    FAULT_DEBOUNCE_EVENT_CANCEL = 3
} FAULT_DEBOUNCE_EVENT_TYPE;

typedef enum FAULT_DEBOUNCE_FUNCTION_ID_ENUM
{
    FDM_SETUP,
    FDM_CONDITION_DETECTED,
    FDM_CONDITION_REMOVED,
    FDM_TIME_PASSED,
    FDM_NUM_OF_FUNCTIONS
} FAULT_DEBOUNCE_FUNCTION_ID_TYPE;


// -- Public Type Declarations --

//! Setting File data for fault debouncing methods.
typedef struct FAULT_SF_DEBOUNCE_STRUCT
{
    uint8 Prescalar         : 3;
    uint8 Unused2           : 1;
    uint8 Debounce_Method   : 2;
    uint8 Unused1           : 2;
    uint8 Delay;
} FAULT_DEBOUNCE_TYPE;

//! A union of structures that are used by the various fault debounce methods.
typedef union FAULT_DEBOUNCE_PROPERTIES_UNION
{
    uint8 Counter;
    struct FDM_TIMER_DATA_STRUCT
    {
        uint32 Time         : 31;
        uint32 Detecting    : 1;
    } Timer;
} FAULT_DEBOUNCE_PROPERTIES_TYPE;


//=====================================================================================================================
//  --- Public Methods ------------------------------------------------------------------------------------------------
//=====================================================================================================================


//---------------------------------------------------------------------------------------------------------------------
/**
 * All functions of the debounce method class use the same function prototype.
 * The specific function behavior depends on the position in the array.
 * @param config = Pointer to setting file configuration data for the Fault Debounce module.
 * @param data = Pointer to the data used by the Fault Debounce module.
 * @return The event that should be triggered on the parent state machine.
 */
typedef FAULT_DEBOUNCE_EVENT_TYPE (* FAULT_DEBOUNCE_FUNCTION_TYPE) (FAULT_DEBOUNCE_TYPE* config, FAULT_DEBOUNCE_PROPERTIES_TYPE* data);


//=====================================================================================================================
//  --- Class Declarations --------------------------------------------------------------------------------------------
//=====================================================================================================================


//! Structure that holds pointers to all the fault debounce method API functions.
typedef FAULT_DEBOUNCE_FUNCTION_TYPE FAULT_DEBOUNCE_HOOK_TYPE[FDM_NUM_OF_FUNCTIONS];


#endif      /* FAULTDEBOUNCEINTERFACE_H_ */
