/**
 *  @file       SetLoadQueue.c
 *
 *  @brief      Module where API005 Set Load requests are stored and executed on Application layer
 *
 *  @details    This module can be used in API005LowLevel module replacing direct Hbl__SetLoadRequest calls
 *              It stores all data into a SETLOADQUEUE_MAX_LENGTH bytes buffer when e.g. PC-Control mode is engaged
 *              and calls Hbl__SetLoadRequest() to set that request in SetLoadQueue__Handler() that can be called in Application layer.
 *              - SETLOADQUEUE_MAX_LENGTH defines maximum size for buffer to store data; for every load it saves 3 bytes + Load data size.
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2018-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "SetLoadQueue.h"
#include "string.h"
#include "Mode.h"
#include "Crc8.h"
#include "Log.h"

//! Maximum queue length available
//! NOTE: Every load will require 3 bytes + Load Data size
//! SetLoadQueue_Max_Len variable holds maximum size required for current setting file
#ifndef SETLOADQUEUE_MAX_LENGTH
#define SETLOADQUEUE_MAX_LENGTH     128
#endif

//! A list of log message IDs that are generated by this module.
typedef enum
{
    QUEUE_DATA_SIZE_TOO_SMALL
} MODULE_SETLOADQUEUE_LOG_MESSAGE_ID_TYPE;

#define MODULE_NAME MODULE_SETLOADQUEUE      //!< The name of this module for use by the Log module.

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------
uint8 SetLoadQueue_Data[SETLOADQUEUE_MAX_LENGTH];
uint8 SetLoadQueue_Max_Len;
uint8 SetLoadQueue_Index;

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the module SetLoadQueue and its variables
 *              This module can be added in SRMain_AppMgr_Initialize[] list and every time queue should be set empty
 *
 */
void SetLoadQueue__Initialize(void)
{
    uint8 load_index;

    SetLoadQueue_Max_Len = 0;
    for (load_index = 0; load_index < Hbl__GetNumLoads(); load_index++)
    {
        uint8 load_len = Hbl__GetLoadDataSize(load_index);
        SetLoadQueue_Max_Len += load_len + 3;
    }

    if (SetLoadQueue_Max_Len > SETLOADQUEUE_MAX_LENGTH)
    {
        LOG_ADD_ERROR(QUEUE_DATA_SIZE_TOO_SMALL, SetLoadQueue_Max_Len);
    }

    memset(SetLoadQueue_Data, 0, sizeof(SetLoadQueue_Data));
    SetLoadQueue_Index = 0;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      SetLoadQueue Handler function - checks if there are items into the queue and calls Hbl__SetLoadRequest
 *              This module can be added in SRMain_AppMgr_Handler[] list
 *
 */
void SetLoadQueue__Handler(void)
{
    if (SetLoadQueue_Index != 0)
    {
        if (Mode__IsPCControlEngaged() == TRUE)
        {
            uint8 current_index = 0;
            uint8 load_index;
            uint8 load_priority;
            uint8 load_data_size;

            while (current_index < SetLoadQueue_Index)
            {
                uint8 crc;
                load_index = SetLoadQueue_Data[current_index];
                load_data_size = Hbl__GetLoadDataSize(load_index);
                crc = Crc8(0xFF, &SetLoadQueue_Data[current_index], load_data_size+2);
                if ((load_data_size > 0) &&
                    (crc == SetLoadQueue_Data[current_index+load_data_size+2]))
                {
                    load_priority = SetLoadQueue_Data[current_index+1];
                    (void) Hbl__SetLoadRequestByIndex(load_index,
                        (HBL_PRIORITY_TYPE) load_priority,
                        &SetLoadQueue_Data[current_index+2]);
                    current_index += load_data_size + 3;
                }
                else
                {
                    SetLoadQueue_Index = current_index;
                }
            }
        }
        else
        {
            SetLoadQueue_Index = 0;
        }
    }
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      SetLoadQueue function to add load request (addressed by load index) into the queue
 *              This module can be called instead of Hbl__SetLoadRequestByIndex
 *  @param      load_index - Position of load into Output map table
 *  @param      priority - Priority level for Hbl__SetLoadRequest
 *  @param      data - Load request data pointer
 *  @return     PASS if Load request has been added into queue
 *  @return     FAIL if Load cannot be found or if queue is full
 *
 *
 */
PASS_FAIL_TYPE SetLoadQueue__SetLoadRequestByIndex(uint8 load_index, HBL_PRIORITY_TYPE priority, uint8 * data)
{
    PASS_FAIL_TYPE ret_val = FAIL;
    uint8 current_index = 0;
    uint8 load_data_size = Hbl__GetLoadDataSize(load_index);

    if (load_data_size > 0)
    {
        uint8 crc;
        uint8 current_load_index;
        uint8 current_load_data_size;

        // Find if Load request is already into the queue
        while (current_index < SetLoadQueue_Index)
        {
            current_load_index = SetLoadQueue_Data[current_index];
            current_load_data_size = Hbl__GetLoadDataSize(current_load_index);
            crc = Crc8(0xFF, &SetLoadQueue_Data[current_index], current_load_data_size+2);

            if ((current_load_data_size > 0) &&
                (crc == SetLoadQueue_Data[current_index+current_load_data_size+2]))
            {
                if (current_load_index == load_index)
                {
                    ret_val = PASS;
                    break;
                }
                else
                {
                    current_index += (current_load_data_size + 3);
                }
            }
            else
            {
                break;
            }
        }

        // Increase SetLoadQueue_Index to add a new Load request into buffer - prevents buffer overflow
        if ((current_index == SetLoadQueue_Index) &&
            ((current_index + load_data_size + 3) <= SETLOADQUEUE_MAX_LENGTH))
        {
            SetLoadQueue_Index += load_data_size + 3;
            ret_val = PASS;
        }

        // Copy Load Request data into buffer
        if (ret_val == PASS)
        {
            uint8 crc;
            SetLoadQueue_Data[current_index] = (uint8) load_index;
            SetLoadQueue_Data[current_index+1] = (uint8) priority;
            memcpy(&SetLoadQueue_Data[current_index+2], data, load_data_size);
            crc = Crc8(0xFF, &SetLoadQueue_Data[current_index], load_data_size + 2);
            SetLoadQueue_Data[current_index+load_data_size+2] = crc;
        }
    }

    return(ret_val);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      SetLoadQueue function to add load request (addressed by Load ID) into the queue
 *              This module can be called instead of Hbl__SetLoadRequestByIndex
 *  @param      load_id - Load ID
 *  @param      priority - Priority level for Hbl__SetLoadRequest
 *  @param      data - Load request data pointer
 *  @return     PASS if Load request has been added into queue
 *  @return     FAIL if Load cannot be found or if queue is full
 *
 */
PASS_FAIL_TYPE SetLoadQueue__SetLoadRequestByLoadID(HBL_LOAD_ENUM_TYPE load_id, HBL_PRIORITY_TYPE priority, uint8 * data)
{
    return(SetLoadQueue__SetLoadRequestByIndex(Hbl__GetLoadIndexByLoadID(load_id), priority, data));
}

//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================
