/**
 *  @file
 *
 *  @brief      Provides methods to get Selector data from the setting file.
 *
 *  @copyright  Copyright 2015-$Date: 2015/08/10 08:42:02EDT $. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//-------------------------------------- Include Files ----------------------------------------------------------------
// -- This Module --
#include "SystemConfig.h"
#include "Selector.h"

// -- Other Modules --
#include "Log.h"
#include "SettingFile.h"

//  --- Private Declarations ------------------------------------------------------------------------------------------
//! Pointers to compartment selectors. Contains the offsets to reach memory areas for the phases of the cavity.
SETTINGFILE_OFFSET_TYPE const Selector_Data_Pointers[] =
{
    SF_PTR_ACU_SELECTOR_TARGET_0,
    SF_PTR_ACU_SELECTOR_TARGET_1,
    SF_PTR_ACU_SELECTOR_TARGET_2,
    SF_PTR_ACU_SELECTOR_TARGET_3,
    SF_PTR_ACU_SELECTOR_TARGET_4,
    SF_PTR_ACU_SELECTOR_TARGET_5,
    SF_PTR_ACU_SELECTOR_TARGET_6,
    SF_PTR_ACU_SELECTOR_TARGET_7,
    SF_PTR_ACU_SELECTOR_TARGET_8,
    SF_PTR_ACU_SELECTOR_TARGET_9,
    SF_PTR_ACU_SELECTOR_TARGET_10
};

//! Pointers to compartment selectors. Contains the offsets to reach memory areas for the phases of the cavity.
SETTINGFILE_OFFSET_TYPE const Program_Heading_Pointers[] =
{
    SF_PTR_UI_PROGRAM_HEADING_TARGET_0,
    SF_PTR_UI_PROGRAM_HEADING_TARGET_1,
    SF_PTR_UI_PROGRAM_HEADING_TARGET_2,
    SF_PTR_UI_PROGRAM_HEADING_TARGET_3,
    SF_PTR_UI_PROGRAM_HEADING_TARGET_4,
    SF_PTR_UI_PROGRAM_HEADING_TARGET_5,
    SF_PTR_UI_PROGRAM_HEADING_TARGET_6,
    SF_PTR_UI_PROGRAM_HEADING_TARGET_7,
    SF_PTR_UI_PROGRAM_HEADING_TARGET_8,
    SF_PTR_UI_PROGRAM_HEADING_TARGET_9,
    SF_PTR_UI_PROGRAM_HEADING_TARGET_10
};

//! Offset of cycle state in setting file program heading data
#define CYCLE_STATE_OFFSET  (1)

//! Mask of cycle state in setting file program heading data
#define CYCLE_STATE_MASK (0x0F)

//! Offset to User Phase Name Data.
#define USER_PHASE_NAMES_OFFSET (6)

// --- LOG MODULE SETTINGS ---------------------------
//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_SELECTOR

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_SELECTOR_LOG_MESSAGE_ID_ENUM
{
    NUMBER_OF_CYCLES_OUT_OF_RANGE           = 1,    //!< Number of cycles starting at 1.
    SF_PTR_CROSS_PRODUCT_CONFIG_FAIL        = 2,    //!< Setting file failed to find hw config.
    SELECTOR_DATA_OVERFLOW                  = 3,    //!< Selector Compartments 0 - 7
    CYCLE_OUT_OF_RANGE                      = 4,    //!< Cycles start at 0.
    PHASE_OUT_OF_RANGE                      = 5,    //!< Phases start 0.
    SF_PHASE_DATA                           = 7,    //!< Phase Data Settings File Error.
    SF_HI_STATEMENTS                        = 8,    //!< Hi Statements Settings File Error.
    SF_LO_STATEMENTS                        = 9,    //!< Lo Statements Settings File Error.
    SF_PROGRAM_HEADING_TARGET_FAIL          = 10,   //!< Error retrieving program heading data from setting file.
    SF_PROGRAM_HEADING_ITEM_SIZE            = 11,   //!< Setting File program heading data error.
    CYCLE_NOT_FOUND                         = 12    //!< Failed to find cycle by label or label and group.
} MODULE_SELECTOR_LOG_MESSAGE_ID_TYPE;

//  --- Private Definitions -------------------------------------------------------------------------------------------
//! Default low statement data index length table.
//! Hard-coded data that can be used as a when the setting file data is not present (backwards compatibility).
//! Supports one byte Lo statement data index.
const uint16 LO_STATEMENT_DATA_INDEX_LENGTH_HARD_CODED = 0x0000;


//  --- Private Function Prototypes -----------------------------------------------------------------------------------
static PASS_FAIL_TYPE GetProgramHeadingPointer(uint8 setting_file, uint8 compartment, uint8 cycle,  uint8 const **cycle_heading);

//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the module Selector and its variables
 *
 */
void Selector__Initialize(void)
{
    // No variables.
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Check if a compartment exists based on setting file selector data.
 *
 *  @param      uint8 sf_index - setting file to check.
 *  @param      compartment = The compartment number to check for.
 *
 *  @return     TRUE if the compartment data exists in the setting file selector data.
 */
BOOL_TYPE Selector__DoesCompartmentExist(uint8 sf_index, uint8 compartment)
{
    BOOL_TYPE compartment_exists;

    compartment_exists = FALSE;
    if (compartment < ELEMENTS_IN_ARRAY(Selector_Data_Pointers))
    {
        if (SettingFile__GetNumDisplacements(sf_index, Selector_Data_Pointers[compartment]) > 0)
        {
            compartment_exists = TRUE;
        }
    }

    return compartment_exists;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Get number_of_cycles from the project setting file.
 *
 *  @param      uint8 sf_index - setting file to check.
 */
uint8 Selector__GetNumberOfCycles(uint8 sf_index, uint8 compartment)
{
    SETTINGFILE_LOADER_TYPE sf_loader_data;
    PASS_FAIL_TYPE load_success;
    uint8 number_of_cycles;

    number_of_cycles = 0;

    load_success = SettingFile__MSettingBasicLoader(sf_index, SF_PTR_UI_PRODUCT_CONFIG, SF_DISPL_CYCLES_NUMBER, &sf_loader_data);
    if (load_success == PASS)
    {
        if (sf_loader_data.Data[compartment] <= MAX_CYCLES)
        {
            number_of_cycles = sf_loader_data.Data[compartment];
        }
        else
        {
          LOG_ADD_EXCEPTION(NUMBER_OF_CYCLES_OUT_OF_RANGE, sf_loader_data.Data[compartment]);
        }
    }
    else
    {
        LOG_ADD_EXCEPTION(SF_PTR_CROSS_PRODUCT_CONFIG_FAIL, sf_index);
    }

    return (number_of_cycles);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Load phase_data for compartment from the setting file specified by sf_index.
 *
 *  @param      uint8 setting_file - setting file index where to find phase data
 *  @param      uint8 compartment - identifier appliance compartment (0 based, 0 for single compartment appliances).
 *  @param      uint8 cycle - Cycle for requested data.
 *  @param      uint8 phase - Phase for requested data.
 *  @param      PHASE_DATA_TYPE phase_data - Pointer to structure to be filled.
 *
 *  @return     PASS_FAIL_TYPE - PASS: Phase data loaded without errors.
 *                               FAIL: Errors encountered while loading phase data.
 *
 */
PASS_FAIL_TYPE Selector__LoadPhaseData(uint8 sf_index, uint8 compartment, uint8 cycle, uint8 phase, PHASE_DATA_TYPE* phase_data)
{
    PASS_FAIL_TYPE load_success;
    SETTINGFILE_LOADER_TYPE sf_loader_data;
    uint16 phase_hi_statements_index, phase_lo_statements_index;
    uint8 hi_index_length;
    uint8 lo_index_length;
    uint8 struct_length;

    phase_data->Time_Estimation_Index = 0xFFu;
    load_success = FAIL;

    if (compartment >= ELEMENTS_IN_ARRAY(Selector_Data_Pointers))
    {
        LOG_ADD_EXCEPTION(SELECTOR_DATA_OVERFLOW, compartment);
    }
    else if (cycle >= MAX_CYCLES)
    {
        LOG_ADD_EXCEPTION(CYCLE_OUT_OF_RANGE, cycle);
    }
    else if( (phase >= MAX_PHASES))
    {
        LOG_ADD_EXCEPTION(PHASE_OUT_OF_RANGE, phase);
    }
    else
    {
        load_success = SettingFile__MSettingBasicLoader(sf_index,
                                                        (SETTINGFILE_OFFSET_TYPE)Selector_Data_Pointers[compartment],
                                                        cycle,
                                                        &sf_loader_data);
        if (load_success == PASS)
        {
            hi_index_length = 1;
            lo_index_length = 1;

            if (SettingFile__IsExtendedDisplacement(sf_index, SF_PTR_ACU_HI_STATEMENTS) == TRUE)
            {
                hi_index_length = 2;
            }
            if (SettingFile__IsExtendedDisplacement(sf_index, SF_PTR_ACU_LO_STATEMENTS) == TRUE)
            {
                lo_index_length = 2;
            }
            struct_length = hi_index_length +  lo_index_length;

            if (SettingFile__IsPlatformPointerUsed(sf_index, SF_PTR_ACU_TIME_ESTIMATION) == TRUE)
            {
                struct_length++;
            }

            phase_data->Number_Of_Cycle_Phases = sf_loader_data.Length / struct_length;

            if (phase < phase_data->Number_Of_Cycle_Phases)
            {
                sf_loader_data.Data += phase * (struct_length);

                if (hi_index_length == 2)
                {
                    phase_hi_statements_index = ENDIANU16_STON(*((uint16 PACKED *)(void *)(sf_loader_data.Data)));
                }
                else
                {
                    phase_hi_statements_index = sf_loader_data.Data[0];
                }

                if (lo_index_length == 2)
                {
                    phase_lo_statements_index = ENDIANU16_STON(*((uint16 PACKED *)(void *)(&sf_loader_data.Data[hi_index_length])));
                }
                else
                {
                    phase_lo_statements_index = sf_loader_data.Data[hi_index_length];
                }

                phase_data->Time_Estimation_Index = sf_loader_data.Data[hi_index_length +  lo_index_length];

                load_success = SettingFile__MSettingBasicLoader(sf_index,
                                                                SF_PTR_ACU_HI_STATEMENTS,
                                                                (phase_hi_statements_index),
                                                                &sf_loader_data);
                if (load_success == PASS)
                {
                    phase_data->Number_Of_Phase_Statements = (sf_loader_data.Length);
                    phase_data->Hi_Statements = (HI_STATEMENT_TYPE *)(void *)(sf_loader_data.Data);

                    load_success = SettingFile__MSettingBasicLoader(sf_index,
                                                                    SF_PTR_ACU_LO_STATEMENTS,
                                                                    (phase_lo_statements_index),
                                                                    &sf_loader_data);
                    if (load_success == PASS)
                    {
                        phase_data->Lo_Statements = sf_loader_data.Data;
                    }
                    else
                    {
                        LOG_ADD_EXCEPTION(SF_LO_STATEMENTS, phase_lo_statements_index);
                    }
                }
                else
                {
                    LOG_ADD_EXCEPTION(SF_HI_STATEMENTS, phase_hi_statements_index);
                }
            }
            else
            {
                LOG_ADD_EXCEPTION(PHASE_OUT_OF_RANGE, phase);
                load_success = FAIL;
            }
        }
        else
        {
            // Not logging a message because all compartments may not have selector data.
            // Logging a message created undesirable bus traffic.
        }
    }

    return (load_success);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Get Supervisor state cycle (e.g. PROGRAMMING, DELAY, END, PAUSE, FAULT).
 *
 *  @param      uint8 setting_file - setting file to search
 *  @param      uint8 compartment - identifier appliance compartment (0 based, 0 for single compartment appliances)
 *  @param      uint8 state_cycle - state cycle to search for
 *
 *  @retval     0xFF Invalid - state cycle not found
 *  @retval     0-128 Valid state cycle found
 *
*/
uint8 Selector__GetStateCycle(uint8 sf_index, uint8 compartment, uint8 state_cycle)
{

    uint8 cycle = 0xFF;
    uint8 number_of_cycles = Selector__GetNumberOfCycles(sf_index, compartment);

    uint8 const *cycle_header_ptr;

    for (uint8 index = 0; ((index < number_of_cycles) && (cycle == 0xFF)); index++)
    {
        if (GetProgramHeadingPointer(sf_index, compartment, index,  &cycle_header_ptr) == PASS)
        {
            if ((cycle_header_ptr[CYCLE_STATE_OFFSET] & CYCLE_STATE_MASK) == state_cycle)
            {
                cycle = index;
            }
        }
    }

    if (cycle == 0xFF)
    {
        LOG_ADD_EXCEPTION(CYCLE_NOT_FOUND, state_cycle);
    }

    return (cycle);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Get the program header state for cycle.
 *
 *  @param      uint8 setting_file - setting file index for where to find program header
 *  @param      uint8 compartment - identifier appliance compartment (0 based, 0 for single compartment appliances).
 *  @param      uint8 cycle - displacement of label in settings file program header
 *
 *  @return      CYCLE_STATE_TYPE cycle_state - cycle state for given parameters
 *
*/
CYCLE_STATE_TYPE Selector__GetCycleState(uint8 sf_index, uint8 compartment, uint8 cycle)
{
    CYCLE_STATE_TYPE cycle_state = CYCLE_STATE_INVALID;

    uint8 const *cycle_header;
    if (GetProgramHeadingPointer(sf_index, compartment, cycle, &cycle_header) == PASS)
    {
        cycle_state = (CYCLE_STATE_TYPE)(cycle_header[CYCLE_STATE_OFFSET] & CYCLE_STATE_MASK);
    }

    return (cycle_state);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Get the cycle indicated by cycle_name.
 *
 *  @param      uint8  setting_file - setting file index for where to find program header
 *  @param      uint8  compartment  - identifier appliance compartment (0 based, 0 for single compartment appliances)
 *  @param      CYCLE_NAME_TYPE cycle_name   - cycle name enumeration id to search for
 *
 *  @retval     0xFF  Invalid - cycle not found
 *  @retval     0-128 Valid   - cycle found
 *
*/
uint8 Selector__GetCycleByName(uint8 sf_index, uint8 compartment, CYCLE_NAME_TYPE cycle_name)
{
    uint8 cycle = 0xFF;
    uint8 number_of_cycles = Selector__GetNumberOfCycles(sf_index, compartment);

    for (uint8 index = 0; ((index < number_of_cycles) && (cycle == 0xFF)); index++)
    {
        if (Selector__GetCycleNameId(sf_index, compartment, index) == cycle_name)
        {
            cycle = index;
        }
    }

    if (cycle == 0xFF)
    {
        LOG_ADD_EXCEPTION(CYCLE_NOT_FOUND, cycle_name);
    }

    return (cycle);
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Get the Cycle Name ID label for sf_index, compartment and cycle.
 *
 *  @param      uint8 setting_file - setting file index for where to find program header
 *  @param      uint8 compartment - identifier appliance compartment (0 based, 0 for single compartment appliances).
 *  @param      uint8 cycle - displacement of Cycle Name ID in settings file program header
 *
 *  @return     CYCLE_NAME_TYPE cycle_name_id - Cycle name enumeration id for compartment cycle.
 *  @retval     0xFFFF  - Invalid Cycle (not found).
 *  @retval     1-65534 - Cycle name enumeration id for compartment cycle.
 *
*/
CYCLE_NAME_TYPE Selector__GetCycleNameId(uint8 sf_index, uint8 compartment, uint8 cycle)
{
    CYCLE_NAME_TYPE cycle_name_id = CYCLE_NAME_INVALID;

    uint8 const *cycle_header;

    if (GetProgramHeadingPointer(sf_index, compartment, cycle, &cycle_header) == PASS)
    {
        #define CYCLE_NAME_ID_OFFSET 4
        cycle_name_id = *(CYCLE_NAME_TYPE *)(void *)&cycle_header[CYCLE_NAME_ID_OFFSET];
    }

    return (cycle_name_id);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Get the group using sf_index, compartment and cycle.
 *
 *  @param      uint8 setting_file - setting file index for where to find program header
 *  @param      uint8 compartment - identifier appliance compartment (0 based, 0 for single compartment appliances).
 *  @param      uint8 cycle - displacement of Cycle Name ID in settings file program header
 *
 *  @return     CYCLE_GROUP_TYPE cycle_group - Used to identify related cycles.
 *  @retval     0 - 127  - Cycle group enumeration id for compartment cycle.
 *
*/
CYCLE_GROUP_TYPE Selector__GetCycleGroup(uint8 sf_index, uint8 compartment, uint8 cycle)
{
    uint8 cycle_group = CYCLE_GROUP_GENERIC;

    uint8 const *cycle_header;

    if (GetProgramHeadingPointer(sf_index, compartment, cycle, &cycle_header) == PASS)
    {
        #define CYCLE_GROUP_OFFSET_LOWER_4_BITS 1
        cycle_group = (cycle_header[CYCLE_GROUP_OFFSET_LOWER_4_BITS] & 0xF0) >> 4;

        #define CYCLE_GROUP_OFFSET_UPPER_3_BITS 0
        cycle_group |= (cycle_header[CYCLE_GROUP_OFFSET_UPPER_3_BITS] & 0xE0);
    }

    return ((CYCLE_GROUP_TYPE)cycle_group);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Check program header to see if it is OK to pause cycle.
 *
 *  @param      uint8 setting_file - setting file index for where to find program header
 *  @param      uint8 compartment - identifier appliance compartment (0 based, 0 for single compartment appliances).
 *  @param      uint8 cycle - displacement of label in settings file program header
 *
 *  @return     BOOL_TYPE ok_to_pause
 *  @retval     TRUE - Cycle is allowed to pause.
 *  @retval     FALSE - Cycle is not allowed to pause.
*/
BOOL_TYPE Selector__OkToPauseCycle(uint8 sf_index, uint8 compartment, uint8 cycle)
{
    BOOL_TYPE ok_to_pause;
    uint8 const *cycle_header;

    ok_to_pause = FALSE;

    if (GetProgramHeadingPointer(sf_index, compartment, cycle, &cycle_header) == PASS)
    {
        #define CYCLE_HEADING_PAUSE_BYTE (0)
        #define CYCLE_HEADING_PAUSE_BIT (0x10)

        // 0 = Disable pause for this cycle.
        // 1 = Enable pause for this cycle.
        if ((cycle_header[CYCLE_HEADING_PAUSE_BYTE] & CYCLE_HEADING_PAUSE_BIT) == CYCLE_HEADING_PAUSE_BIT)
        {
            ok_to_pause = TRUE;
        }
    }

    return (ok_to_pause);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Get cold reset behavior from cycle heading.
 *
 *  @param      uint8 setting_file - setting file index for where to find program header
 *  @param      uint8 compartment - identifier appliance compartment (0 based, 0 for single compartment appliances).
 *  @param      uint8 cycle - displacement of label in settings file program header
 *
 *  @return     CYCLE_COLD_RESET_BEHAVIOR_TYPE  restore_data
*/
CYCLE_COLD_RESET_BEHAVIOR_TYPE Selector__GetColdResetBehavior(uint8 sf_index, uint8 compartment, uint8 cycle)
{
    uint8  restore_data;
    uint8 const* cycle_header;

    restore_data = CYCLE_COLD_RESET_BEHAVIOR_CANCEL;


    if (GetProgramHeadingPointer(sf_index, compartment, cycle, &cycle_header) == PASS)
    {
        #define RESET_BEHAVIOR_OFFSET   (0)
        #define RESET_BEHAVIOR_MASK (0x07)

        restore_data = cycle_header[RESET_BEHAVIOR_OFFSET] & RESET_BEHAVIOR_MASK;
    }

    return ((CYCLE_COLD_RESET_BEHAVIOR_TYPE)restore_data);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Get the Cycle User Phase Name for sf_index compartment cycle phase.
 *
 *  @param      uint8 sf_index - Setting file index for where to find program header.
 *  @param      uint8 compartment - Identifier appliance compartment (0 based, 0 for single compartment appliances).
 *  @param      uint8 cycle - Displacement of Cycle in settings file program header pointer.
 *  @param      uint8 phase - Cycle Phase of requested User Phase Name.
 *
 *  @return     USER_PHASE_NAME_TYPE user_phase_name_id - User phase name enumeration id for compartment cycle phase.
 *  @retval     0xFFFF  - Invalid Cycle (not found).
 *  @retval     0x0000  - Default, cycle developer did not set a user phase name for this or previous phases.
 *  @retval     1-65534 - User phase name enumeration id for compartment cycle phase.
 *
*/
USER_PHASE_NAME_TYPE Selector__GetUserPhaseName(uint8 sf_index, uint8 compartment, uint8 cycle, uint8 phase)
{
    USER_PHASE_NAME_TYPE user_phase_name = USER_PHASE_NAME_INVALID;

    if (Selector__GetCycleState(sf_index, compartment, cycle) == CYCLE_STATE_RUN)
    {
        SETTINGFILE_LOADER_TYPE sf_loader;
        PASS_FAIL_TYPE load_success = SettingFile__MSettingBasicLoader(sf_index, Program_Heading_Pointers[compartment],
                                                                       cycle, &sf_loader);
        if (load_success == PASS)
        {
            user_phase_name = USER_PHASE_NAME_DEFAULT;
            uint8 user_phase_name_data_size = sf_loader.Length - USER_PHASE_NAMES_OFFSET;
            for (uint8 index = 0; index < user_phase_name_data_size; index += 3)
            {
                if (sf_loader.Data[USER_PHASE_NAMES_OFFSET + index] == 0xFF)
                {
                    // if padded for word alignment or if displacement data structure extended in the future.
                    break;
                }
                if (sf_loader.Data[USER_PHASE_NAMES_OFFSET + index] <= phase)
                {
                    user_phase_name = (USER_PHASE_NAME_TYPE)COMBINE_BYTES(sf_loader.Data[USER_PHASE_NAMES_OFFSET + index + 2],
                                                                             sf_loader.Data[USER_PHASE_NAMES_OFFSET + index + 1]);
                }
            }
        }
    }

    return (user_phase_name);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief  Get a pointer to the low statement data index length table.
 *
 *  @return uint16 * lo_statement_data_length_ptr - Pointer to the low statement data index length table.
 *  @retval pointer to default lo_statement data index length if setting file data can not be found.
 */
uint16 * Selector__GetLoStatmentIndexLengthPtr(void)
{
    uint16 * lo_statement_data_length_ptr = NULL;
    SETTINGFILE_LOADER_TYPE loader;

    if (SettingFile__BasicLoader((SF_PTR_ACU_CROSS_PRODUCT_CONFIG), SF_DISPL_LO_STATEMENT_DISPLACEMENT_SIZE, &loader) == PASS)
    {
        lo_statement_data_length_ptr = (uint16 *)(void *)loader.Data;
    }
    else
    {
        //LOG_ADD_EXCEPTION(SF_LIGHT_CONFIG_READ_FAIL, 0);
        lo_statement_data_length_ptr = (uint16 *)(void *)&LO_STATEMENT_DATA_INDEX_LENGTH_HARD_CODED;
    }

    return lo_statement_data_length_ptr;
}

//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Set cycle_heading to location of cycle heading data in setting_file.
 *
 *  @param      uint8 setting_file - index of setting file to get heading data pointer from
 *  @param      uint8 cycle - displacement into cycle heading data
 *  @param      uint8 const **cycle_heading - pointer to pointer to constant uint8 cycle heading data
 *
 *  @return    PASS_FAIL_TYPE load_success: TRUE -  cycle_heading set to desired heading data location
 *                                          FALSE - cycle_heading set to NULL
*/
static PASS_FAIL_TYPE GetProgramHeadingPointer(uint8 setting_file, uint8 compartment, uint8 cycle,  uint8 const **cycle_heading)
{
    SETTINGFILE_LOADER_TYPE sf_loader_data;
    PASS_FAIL_TYPE load_success;

    *cycle_heading = NULL;
    load_success = SettingFile__MSettingBasicLoader(setting_file,
                                                    Program_Heading_Pointers[compartment],
                                                    cycle,
                                                    &sf_loader_data);
    if (load_success == PASS)
    {
        //! Minimum size for program heading data.
        #define PROGRAM_HEADING_ITEM_SIZE   ((uint16)6)

        if (sf_loader_data.Length >= PROGRAM_HEADING_ITEM_SIZE)
        {
            *cycle_heading = sf_loader_data.Data;
            return PASS;
        }
        else
        {
            LOG_ADD_EXCEPTION(SF_PROGRAM_HEADING_ITEM_SIZE, setting_file);
        }
    }
    else
    {
        LOG_ADD_EXCEPTION(SF_PROGRAM_HEADING_TARGET_FAIL, setting_file);
    }

    return (FAIL);
}

