/**
 *  @file       
 *
 *  @brief      Tank Drain Process
 *
 *  @details    This module manage the Tank Drain Process
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
/*
@startuml
	title Tank Drain State Machine
	'terminate function unused

	[*] --> TANK_DRAIN

	TANK_DRAIN --> FILL_CHECK_SUBCYCLE: WaterCheck
	TANK_DRAIN --> TANK_DRAIN_COMPLETE: TankDrainCompleted
	TANK_DRAIN: entry / TankDrainInitialCheck()
	TANK_DRAIN: do / TankDrain()

	FILL_CHECK_SUBCYCLE --> TANK_DRAIN_COMPLETE: TankDrainCompleted
	FILL_CHECK_SUBCYCLE: entry / ResetSubcycleExecution()
	FILL_CHECK_SUBCYCLE: do / WaitSubcycleExecution()
@enduml
*/

//-------------------------------------- Include Files ----------------------------------------------------------------
// -- This Module --
#include "TankDrain.h"
#include "TankDrain_fsm.h"
#include "SystemConfig.h"

// -- Other Modules --
#include "DishAuxVar.h"
#include "Fill.h"
#include "Fault.h"
#include "Hbl.h"
#include "Log.h"
#include "Micro.h"
#include "NVData.h"
#include "Selector.h"
#include "SettingFile.h"
#include <string.h>
#include "SubCycle.h"
#include "Vwi.h"

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_TANK_DRAIN

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_TANK_DRAIN_LOG_MESSAGE_ID_ENUM
{
    ERROR_LOADING_PARAMETERS	= 1,
} MODULE_TANK_DRAIN_LOG_MESSAGE_ID_TYPE;

//! Volatile data structure for Tank Drain process
typedef struct TANK_DRAIN_VOLATILE_DATA_STRUCT
{
	CLASS_A_FILL_PARAMETER_TYPE *Class_A_Fill_Parameters;
	BOOL_TYPE Subcycle_Executed;
	PASS_FAIL_TYPE Process_Parameters_Loading;
} TANK_DRAIN_VOLATILE_DATA_TYPE;

//! Non volatile data structure for Tank Drain process
typedef struct TANK_DRAIN_NV_DATA_STRUCT
{
	uint16 Tank_Drain_Timer;
} TANK_DRAIN_NV_DATA_TYPE;

//! Volatile data for Tank Drain process
static TANK_DRAIN_VOLATILE_DATA_TYPE TankDrain_Data;

//! Non volatile data for Tank Drain process
#pragma location = "_appliance_segment"
static TANK_DRAIN_NV_DATA_TYPE TankDrain_NV_Data;

//! State machine state for Tank Drain process
#pragma location = "_appliance_segment"
static TANKDRAIN_FSM_STATE_TYPE Tank_Drain_State;

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
static PASS_FAIL_TYPE ReadProcessParameters(PROCESS_CONTROL_TYPE* control);

//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------

//---------------------------------------------------------------------------------------------------------------------
/**
 * Initialize the TankDrain module's variables
 */
void TankDrain__Initialize(void)
{
	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		if (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != (NVDATA_RESTORE_TYPE)NVDATA_RESTORE_OKAY)
		{
			Tank_Drain_State = FSM_STATE_NONE;
			TankDrain_NV_Data.Tank_Drain_Timer = 0;
		}

		memset(&TankDrain_Data, 0, sizeof(TankDrain_Data));

		TankDrain_Data.Process_Parameters_Loading = FAIL;
		TankDrain_Data.Subcycle_Executed = FALSE;
	}
}


/**
 * It implements the Tank Drain process
 */
PROCESS_RESULT_TYPE TankDrain__Manager(PROCESS_CONTROL_TYPE* control)
{
	PROCESS_RESULT_TYPE result = PROCESS_COMPLETE;

	if ((control->Step_Initializing != (BOOL_TYPE)FALSE) ||
		(control->Resume_From_Reset != (BOOL_TYPE)FALSE) ||
		(control->Resume_From_Pause != (BOOL_TYPE)FALSE))
	{
		TankDrain_Data.Process_Parameters_Loading = ReadProcessParameters(control);
	}

	if (TankDrain_Data.Process_Parameters_Loading == PASS)
	{
		if (control->Step_Initializing != (BOOL_TYPE)FALSE)
		{
			// Initialize this instance of the Tank Drain process.
			TankDrainFsmInitialize(&Tank_Drain_State);
		}

		if (control->Resume_From_Reset == (BOOL_TYPE)FALSE)
		{
			// TankDrainFsmExecute() not called in first iteration after a cold reset to avoid a spurious Valve turning on in case of
			// long power fail: actually, in this case, Tank Drain process would be called for just one iteration before going in PAUSE.
			TankDrainFsmExecute(&Tank_Drain_State);
		}

		result = ((Tank_Drain_State == FSM_STATE_TANK_DRAIN_COMPLETE) ? PROCESS_COMPLETE : PROCESS_BUSY);
	}

	return result;
}

void TankDrain__SetSubcycleExecuted(uint8 compartment, uint8 subcycle_id, SUB_CYCLE_END_TYPE subcycle_end_code)
{
	if (Selector__GetCycleNameId(0, compartment , subcycle_id) == CYCLE_NAME_SPECIFIC_FILL_CHECK_WATER)
	{
		if ((subcycle_end_code == SUB_CYCLE_END_COMPLETED) || (subcycle_end_code == SUB_CYCLE_END_SET_STATE_PROCESS))
		{
			TankDrain_Data.Subcycle_Executed = TRUE;
		}
	}
}

//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================
static PASS_FAIL_TYPE ReadProcessParameters(PROCESS_CONTROL_TYPE* control)
{
	PASS_FAIL_TYPE result = FAIL;
	SETTINGFILE_LOADER_TYPE loader;

	if ( FAIL == SettingFile__BasicLoader(SF_PTR_ACU_ALGORITHM_PARAMETERS,
										  DISPL_CLASS_A_FILL,
										  &loader) )
	{
		LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, (uint16)SF_PTR_ACU_ALGORITHM_PARAMETERS);
	}
	else
	{
		TankDrain_Data.Class_A_Fill_Parameters = (CLASS_A_FILL_PARAMETER_TYPE *)(void*)loader.Data;
		result = PASS;
	}

	return result;
}


//=====================================================================================================================
// Tank Drain State Machine customization functions.
// NOTE: do not modify this header or the StateMachineCodeGenerator will not be able to find it.
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void ResetSubcycleExecution(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	TankDrain_Data.Subcycle_Executed = FALSE;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void TankDrain(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	ON_OFF_TYPE valve_state = ON;

	if (TankDrain_NV_Data.Tank_Drain_Timer < ((uint16)TankDrain_Data.Class_A_Fill_Parameters->Time_For_Tank_Drain * (uint16)(5 * FILL_CALLS_PER_SECOND)))
	{
		(void)Hbl__SetLoadRequestByLoadID(HBL_LOAD_UPPER_TANK_VALVE, HBL_PRIORITY_APPLICATION_HI, (uint8 *) &valve_state);	//lint !e928 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
		TankDrain_NV_Data.Tank_Drain_Timer ++;
	}
	else
	{
		if ((TankDrain_Data.Class_A_Fill_Parameters->Fill_Check_Water_Subcycle_Priority != 0U) && (Interpreter__GetStatus().Sub_Cycle[COMPARTMENT_DEFAULT] == 0U))
		{
			DISPATCH_FSM_EVENT(FSM_EVENT_WATERCHECK);
		}
		else
		{
			// Fill Check subcycle is not present in setting file, or Tank Drain is being executed inside a subcycle:
			// it is not possible to start Fill Check Subcycle, recovery action is to assume water is not present
			Tank_State_Fill = TANK_STATE_UNKNOWN;
			Tank_State_Drain = TANK_STATE_FAIL;
			Fill__ClearBitmapBit(TANK_STATE_CLEAN);
			Fault__ConditionDetected(FAULT_ID_WATER_TANK_VALVE_NOT_FUNCTIONING);

			Fill__SetBitmapBit(SENSED_DRAIN_REQUESTED_BY_TANK_DRAIN);

			DISPATCH_FSM_EVENT(FSM_EVENT_TANKDRAINCOMPLETED);
		}

	}
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void TankDrainInitialCheck(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	Liters_In_Tub_Before_Fill = Liters_In_Tub;
	Liters_In_Tank_Before_Fill = Liters_In_Water_Tank;

	Fill__ClearBitmapBit(SENSED_DRAIN_REQUESTED_BY_TANK_DRAIN);

	if ((Liters_In_Water_Tank < ( (uint16)TankDrain_Data.Class_A_Fill_Parameters->Liters_For_Tank_Empty_Max *(uint16)5 )) ||
		(Liters_In_Tub >= ( (uint16)TankDrain_Data.Class_A_Fill_Parameters->Liters_For_WI_Empty_Max * (uint16)5 )))

	{
		DISPATCH_FSM_EVENT(FSM_EVENT_TANKDRAINCOMPLETED);
	}
	else
	{
		Fill__ClearBitmapBit(DRAIN_CONFIRMED);
		Fill__ClearBitmapBit(TANK_STATE_CLEAN);
		TankDrain_NV_Data.Tank_Drain_Timer = 0;
	}
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief
 */
static void WaitSubcycleExecution(FSM_CUSTOMIZATION_FUNCTION_ARGUMENT)
{
	if (TankDrain_Data.Subcycle_Executed == FALSE)
	{
		(void)SubCycle__RequestStart(0, TankDrain_Data.Class_A_Fill_Parameters->Fill_Check_Water_Subcycle_Priority);
	}
	else
	{
		VWI_WATER_SENSE_TYPE last_valid_water_status;

		last_valid_water_status = Vwi__GetLastValidWaterStatus();

		if ((last_valid_water_status == WS_WATER) || (last_valid_water_status == WS_UNSTABLE_WATER))
		{
			// Water is present
			uint32 sum;
			sum = (uint32)Liters_In_Tub + Liters_In_Water_Tank;
			if (sum > (uint16)__UNSIGNED_SHORT_MAX__)
			{
				sum = __UNSIGNED_SHORT_MAX__;
			}
			Liters_In_Tub = (uint16)sum;

			Liters_In_Tub_Before_Fill = Liters_In_Tub;
			Liters_In_Water_Tank = 0;
			Tank_State_Drain = TANK_STATE_PASSED;
			Fill__SetBitmapBit(TANK_STATE_CLEAN);
			Liters_Unchecked = 0;
		}
		else
		{
			// No Water
			Tank_State_Fill = TANK_STATE_UNKNOWN;
			Tank_State_Drain = TANK_STATE_FAIL;
			Fill__ClearBitmapBit(TANK_STATE_CLEAN);
			Fault__ConditionDetected(FAULT_ID_WATER_TANK_VALVE_NOT_FUNCTIONING);

			Fill__SetBitmapBit(SENSED_DRAIN_REQUESTED_BY_TANK_DRAIN);
		}

		DISPATCH_FSM_EVENT(FSM_EVENT_TANKDRAINCOMPLETED);
	}
}

