/**
 * @file
 * @brief       Communications to control a remote motor or motor-controlled device.
 *
 * @details     The same API221MotionCtrl module is used on the client and the server.
 *                  Client Definitions:
 *                      API221_CLIENT_FEATURE should be ENABLED
 *                      API221_SERVER_FEATURE should be DISABLED
 *                  Server Definitions:
 *                      API221_CLIENT_FEATURE should be DISABLED
 *                      API221_SERVER_FEATURE should be ENABLED
 *              Using the same module on the client and server helps ensure that the client and
 *              server are using the same type and version of the API.
 *
 *              API221MotionCtrl allows each client to control one or more motor control servers
 *              that each controls one or more motor. For each of the system motors, the API
 *              manages four types of data:
 *                  - Behaviors
 *                  - Events
 *                  - Failure Flags
 *                  - Data Acquisition
 *
 *              Behaviors:
 *              Behaviors are executed by the motor or device. The Stop and Run Behaviors are
 *              standard behaviors that must be implemented by every motor controller for every
 *              motor or device. Any motor controller can define additional platform-specific
 *              behaviors.
 *
 *              Events:
 *              Events are generated by each motor or device in the system. The motor controller
 *              generates the events as they occur. Each time an event is generated, an event
 *              message is sent to the Client. There are standard events that every motor or
 *              device can generate. Any motor controller can define additional platform-specific
 *              events.
 *
 *              Failure Flags:
 *              TRUE/FALSE flags that are normally FALSE. When a failure is detected, the flag
 *              that corresponds to the failure is set to TRUE. The motor controller sets the
 *              Failure Flags as necessary. The Client has the ability to read the Failure Flags
 *              and request that all the flags be reset to FALSE.
 *
 *              Data Acquisition:
 *              The API provides some limited data acquisition features for platform-specific
 *              analog data channels. The client can choose the analog data channels to monitor
 *              and the rate at which the motor controller should publish the analog data. API221
 *              will use a single publication period for all the motors and their analog data
 *              values on the same motor controller.
 *
 * @copyright   Copyright 2016-2020 Whirlpool Corporation.  All rights reserved - CONFIDENTIAL.
 */

//  --- Include Files -------------------------------------------------------------------------------------------------


// -- This Module --
#include "SystemConfig.h"

#ifndef API221_CLIENT_FEATURE
    // API221_CLIENT_FEATURE should be ENABLED for applications that interact with motor controllers.
    #error API221_CLIENT_FEATURE must be defined via SystemConfig.h as ENABLED or DISABLED.
#endif
#ifndef API221_SERVER_FEATURE
    // API221_SERVER_FEATURE should be ENABLED for applications that implement a motor controller.
    #error API221_SERVER_FEATURE must be defined via SystemConfig.h as ENABLED or DISABLED.
#endif

#if ((API221_CLIENT_FEATURE == ENABLED) || (API221_SERVER_FEATURE == ENABLED))

#include "API221MotionCtrl.h"
#include "API221MotionCtrl_prv.h"

// -- Other Modules --
#if (API221_CLIENT_FEATURE == ENABLED)
    #include "Callback.h"
#endif
#include "Log.h"
#include <limits.h>
#include "Micro.h"
#include <string.h>
#include "Utilities.h"


// -- Compile-Time Assertions --

// The number of milliseconds per call to background must be greater than 0.
// This is required to avoid divide-by-zero pre-compiler errors.
CT_ASSERT(API221_MS_PER_CALL_TO_BACKGROUND > 0);

// Verify that API221 event values will fit in 6 bits.
// This is required by the events that use only six bits to represent the event.
CT_ASSERT(API221_EVENT_COUNT <= 0x40);

#if (API221_SERVER_FEATURE == ENABLED)
    #ifndef API221_DEVICE_RUN
    #error  "The API221_DEVICE_RUN() macro must be defined."
    #endif
    #ifndef API221_DEVICE_STOP
    #error  "The API221_DEVICE_STOP() macro must be defined."
    #endif
    #ifndef API221_READ_MOTOR_STATUS
    #error  "The API221_READ_MOTOR_STATUS() macro must be defined."
    #endif
#endif

//  --- Private Declarations ------------------------------------------------------------------------------------------


// -- Private Constant Declarations --

//! The maximum number of analog data channels that can be associated with a motor.
#define MAX_CHANNELS_PER_MOTOR 32

//! The minimum number of milliseconds allowed between periodic data publications.
#define MINIMUM_PUBLICATION_MILLISECONDS 200

//! Number of payload bytes used to communicate analog data.
//!     One byte for the server motor index
//!     One byte for analog data channel
//!     Four little-endian bytes for signed data
#define SIZE_OF_ANALOG_DATA_PAYLOAD 6

#if (API221_SERVER_FEATURE == ENABLED)
    // Set TIMEOUT_TO_STOP based on API221_MS_TIMEOUT_TO_STOP.
    // Force TIMEOUT_TO_STOP to a default value if API221_MS_TIMEOUT_TO_STOP is undefined.
    //! Number of background function calls to wait before forcing a stop of the motor.
    #ifndef API221_MS_TIMEOUT_TO_STOP
        #define TIMEOUT_TO_STOP                         (5000 / API221_MS_PER_CALL_TO_BACKGROUND)
    #elif (API221_MS_TIMEOUT_TO_STOP == 0)
        #define TIMEOUT_TO_STOP                         (0)
    #elif (API221_MS_TIMEOUT_TO_STOP < 1000)
        #define TIMEOUT_TO_STOP                         (1000 / API221_MS_PER_CALL_TO_BACKGROUND)
    #elif (API221_MS_TIMEOUT_TO_STOP > 15000)
        #define TIMEOUT_TO_STOP                         (15000 / API221_MS_PER_CALL_TO_BACKGROUND)
    #else
        #define TIMEOUT_TO_STOP                         (API221_MS_TIMEOUT_TO_STOP / API221_MS_PER_CALL_TO_BACKGROUND)
    #endif
    // Ensure that the auto-stop time is in the valid range.
    CT_ASSERT((TIMEOUT_TO_STOP >= 0) && (TIMEOUT_TO_STOP <= USHRT_MAX));
#endif      // #if (API221_SERVER_FEATURE == ENABLED)

//! The name of this module for use by the Log module.
#define MODULE_NAME                                 MODULE_API221_MOTION_CTRL

#if (API221_CLIENT_FEATURE == ENABLED)
    //! The total number of system motors controlled by the client.
    #define API221_SYSTEM_MOTOR_COUNT               ELEMENTS_IN_ARRAY(API221_MOTOR_IDS)

    #ifndef API221_MAX_FAILURE_EVENT_HANDLERS
        #define API221_MAX_FAILURE_EVENT_HANDLERS 1
    #endif

    #ifndef API221_MAX_STATUS_EVENT_HANDLERS
        #define API221_MAX_STATUS_EVENT_HANDLERS 1
    #endif

    // Verify that API221 client motor index will fit in 2 bits.
    // This is required by the events that use only two bits to represent the motor.
    CT_ASSERT(API221_SYSTEM_MOTOR_COUNT <= 0x4);

    // Set KEEP_RUNNING_TIMER based on API221_MS_KEEP_RUNNING_TIMER.
    // Force KEEP_RUNNING_TIMER to a default value if API221_MS_KEEP_RUNNING_TIMER is undefined.
    //! Number of background function calls to wait between sending keep running commands to a client.
    #ifndef API221_MS_KEEP_RUNNING_TIMER
        #define KEEP_RUNNING_TIMER                      (2000 / API221_MS_PER_CALL_TO_BACKGROUND)
    #elif (API221_MS_KEEP_RUNNING_TIMER == 0)
        #define KEEP_RUNNING_TIMER                      (0)
    #elif (API221_MS_KEEP_RUNNING_TIMER < 500)
        #define KEEP_RUNNING_TIMER                      (500 / API221_MS_PER_CALL_TO_BACKGROUND)
    #elif (API221_MS_KEEP_RUNNING_TIMER > 14500)
        #define KEEP_RUNNING_TIMER                      (14500 / API221_MS_PER_CALL_TO_BACKGROUND)
    #else
        #define KEEP_RUNNING_TIMER                      (API221_MS_KEEP_RUNNING_TIMER / API221_MS_PER_CALL_TO_BACKGROUND)
    #endif
    // Ensure that the keep running timer is in the valid range.
    CT_ASSERT((KEEP_RUNNING_TIMER >= 0) && (KEEP_RUNNING_TIMER <= USHRT_MAX));
#endif      // #if (API221_CLIENT_FEATURE == ENABLED)


// -- Private Macro Declarations --

//! A macro to combine a motor index and an event index into a motor_event.
#define BUILD_MOTOR_EVENT(motor, event) ((((motor) & 0x03) << 6) + ((event) & 0x3F))


// -- Private Enumerated Constant Declarations --

//! All the API221 command and feedback OpCodes.
typedef enum API221MOTIONCTRL_OPCODE_ENUM
{
    API221_NO_OPCODE                        = 0,
    API221_CMD_REQUEST_FAILURE_FLAGS        = 1,    //!< Request all failure flags
    API221_CMD_CLEAR_FAILURE_FLAGS          = 2,    //!< Clear all failure flags
    API221_CMD_KEEP_RUNNING                 = 3,    //!< Keep the previous command activated
    API221_CMD_STOP                         = 4,    //!< Stop the motor
    API221_CMD_RUN                          = 5,    //!< Start to run the motor
    API221_CMD_SET_MOTION_BEHAVIOR          = 6,    //!< Start a platform-specific motion behavior
    API221_CMD_REQUEST_MOTOR_STATUS         = 7,    //!< Request the current status of the motor
    API221_CMD_REQUEST_ANALOG_DATA          = 8,    //!< Request an analog input value
    API221_CMD_SET_DATA_PUBLICATION_PERIOD  = 9,    //!< Set the publication data rate for periodic data
    API221_CMD_ADD_PERIODIC_DATA_CHANNELS   = 10,   //!< Add a set of analog input values to the periodic data
    API221_CMD_REMOVE_PERIODIC_DATA_CHANNELS= 11,   //!< Remove a set of analog input values from the periodic data
    API221_CMD_REQUEST_PERIODIC_DATA_STATUS = 12,   //!< Request the status of the periodic data publication
    API221_CMD_WASH                         = 13,   //!< Start the wash motion.
    API221_CMD_ROTATE_X_DEGREES             = 14,   //!< Start the rotate X degrees motion.
    API221_CMD_PULSE_IMMEDIATE              = 15,   //!< Start a new pulse now.
    API221_CMD_PULSE_MODIFY                 = 16,   //!< Modify the currently running pulse.
    API221_CMD_PULSE_QUEUE                  = 17,   //!< Queue the next pulse.

    API221_FBK_PUBLISH_FAILURE_FLAGS        = 1,    //!< Publish all failure flags
    API221_FBK_PUBLISH_EVENT                = 3,    //!< Publish an event
    API221_FBK_PUBLISH_MOTOR_STATUS         = 7,    //!< Publish the current status of the motor
    API221_FBK_PUBLISH_ANALOG_DATA          = 8,    //!< Publish single requested analog input value
    API221_FBK_PUBLISH_PERIODIC_DATA        = 9,    //!< Publish the requested set of analog input values periodically
    API221_FBK_PUBLISH_PERIODIC_DATA_STATUS = 12    //!< Publish the status of the periodic data publication
} API221MOTIONCTRL_OPCODE_TYPE;

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_API221_MOTION_CTRL_LOG_MESSAGE_ID_ENUM
{
    MOTOR_STOPPED_DUE_TO_TIMEOUT = 1,
    MOTOR_REJECTED_STOP_FROM_TIMEOUT,
    PERIODIC_PUBLICATION_FAILED,
    FEEDBACK_OPCODE_NOT_SUPPORTED,
    ADD_CHANS_INVALID_PARAMS,
    CLEAR_FAILURES_INVALID_PARAMS,
    MOTION_INVALID_PARAMS,
    PULSE_INVALID_PARAMS,
    PULSE_INVALID_COMMAND,
    ROTATE_INVALID_PARAMS,
    RUN_INVALID_PARAMS,
    STOP_INVALID_PARAMS,
    WASH_INVALID_PARAMS,
    GET_DATA_INVALID_PARAMS,
    GET_SYNC_DATA_INVALID_PARAMS,
    IS_MOTOR_PRESENT_INVALID_PARAMS,
    DEPRECATED_KEEP_RUNNING_API,
    REMOVE_CHANS_INVALID_PARAMS,
    REQ_ANALOG_DATA_INVALID_PARAMS,
    REQ_FAILURES_INVALID_PARAMS,
    REQ_PER_DATA_STATUS_INVALID_PARAMS,
    REQ_STATUS_INVALID_PARAMS,
    SET_PERIOD_INVALID_PARAMS
} MODULE_API221_MOTION_CTRL_LOG_MESSAGE_ID_TYPE;


// -- Private Structure Type Declarations --

//! The structure used to store a single analog data value.
typedef struct API221_STORED_DATA_STRUCT
{
    sint32 Value;
    API221_CLIENT_MOTOR_INDEX_TYPE Motor;
    uint8 Channel;
    uint8 Sequence;
} API221_STORED_DATA_TYPE;

//! The data structure that holds most of the RAM used by this module.
typedef struct API221_DATA_STRUCT
{
    #if (API221_CLIENT_FEATURE == ENABLED)
        //! A handler for processing the motor failure flags message.
        API221_FAILURES_HANDLER_TYPE Failures_Handler[API221_SYSTEM_MOTOR_COUNT][API221_MAX_FAILURE_EVENT_HANDLERS];

        //! A handler for processing the status of a motor.
        API221_MOTOR_STATUS_HANDLER_TYPE Motor_Status_Handler[API221_SYSTEM_MOTOR_COUNT][API221_MAX_STATUS_EVENT_HANDLERS];

        //! A handler for processing the status of the periodic data.
        API221_PER_DATA_STATUS_HANDLER_TYPE Periodic_Data_Status_Handler;

        //! Array of the maximum number of analog input values that can be buffered by the API221_Client.
        API221_STORED_DATA_TYPE Data[API221_STORED_ANALOG_INPUTS];

        #if (KEEP_RUNNING_TIMER > 0)
            //! Counters to measure the time between messages to request that the motor keep running.
            uint16 Keep_Running_Timer[API221_SYSTEM_MOTOR_COUNT];
        #endif
    #endif      // #if (API221_CLIENT_FEATURE == ENABLED)

    #if (API221_SERVER_FEATURE == ENABLED)
        //! A bitmap of the analog input channels requested for periodic publication.
        uint32 Requested[API221_SERVER_MOTOR_COUNT];

        //! The bitmap of the status flags.
        uint8 Status_Flags[API221_SERVER_MOTOR_COUNT];

        #ifdef API221_READ_FAILURE_FLAGS
            //! The bitmap of the failure flags.
            uint32 Failure_Flags[API221_SERVER_MOTOR_COUNT];
        #endif

        #if (TIMEOUT_TO_STOP > 0)
            //! Counters to measure the time that no message has been sent to force a motor stop.
            uint16 Stop_Timeout[API221_SERVER_MOTOR_COUNT];
        #endif

        //! The total number of requested analog inputs for all motors.
        uint8 Num_Of_Requested_Analog_Inputs;

        //! The counter used to measure time between periodic publications of analog inputs.
        uint8 Publication_Counter;

        //! The amount of time between periodic publications of analog inputs.
        uint8 Publication_Period;

        //! The WIN node that requested the periodic publication of analog inputs.
        uint8 Requesting_Node;
    #endif      // #if (API221_SERVER_FEATURE == ENABLED)
} API221_DATA_TYPE;


//  --- Private Definitions -------------------------------------------------------------------------------------------


// -- Private Flash-Based Constant Definitions --

#if (API221_SERVER_FEATURE == ENABLED)
    //! This table is used to convert bits that represent the previous and current motor status into
    //! events. The key (used as an index into the array) consists of the following bits:
    //!     bit 3 = Was previously reached target
    //!     bit 2 = Was previously stopped
    //!     bit 1 = Is currently reached target
    //!     bit 0 = Is currently stopped
    //! For the two bits 'Reached Target' and 'Stopped', the following is assumed:
    //!     Reached Target   and   Stopped  results in   State
    //!     --------------         -------              -------
    //!         False               False               Ramping
    //!         False               True                Stopped
    //!         True                False               Plateau
    //!         True                True                Stopped
    static const API221_MOTOR_EVENT_TYPE KEY_TO_EVENT[] =
    {
        API221_EVENT_NONE,                      //!< Was ramping and is ramping
        API221_EVENT_STOPPED,                   //!< Was ramping and is stopped
        API221_EVENT_REACHED_TARGET,            //!< Was ramping and is plateau
        API221_EVENT_STOPPED,                   //!< Was ramping and is stopped
        API221_EVENT_RAMP_STARTED,              //!< Was stopped and is ramping
        API221_EVENT_NONE,                      //!< Was stopped and is stopped
        API221_EVENT_REACHED_TARGET,            //!< Was stopped and is plateau
        API221_EVENT_NONE,                      //!< Was stopped and is stopped
        API221_EVENT_RAMP_STARTED,              //!< Was plateau and is ramping
        API221_EVENT_STOPPED,                   //!< Was plateau and is stopped
        API221_EVENT_NONE,                      //!< Was plateau and is plateau
        API221_EVENT_STOPPED,                   //!< Was plateau and is stopped
        API221_EVENT_RAMP_STARTED,              //!< Was stopped and is ramping
        API221_EVENT_NONE,                      //!< Was stopped and is stopped
        API221_EVENT_REACHED_TARGET,            //!< Was stopped and is plateau
        API221_EVENT_NONE                       //!< Was stopped and is stopped
    };
#endif      // #if (API221_SERVER_FEATURE == ENABLED)


// -- Private Variable Definitions --

//! Define variables for the API221MotionCtrl module.
static API221_DATA_TYPE Api221;

#if (API221_CLIENT_FEATURE == ENABLED)
    // Declare variables for the Callback module.
    DEFINE_CALLBACK_CONTROL_STRUCTURE(Api221_Callback, API221_MAX_EVENT_HANDLERS);
#endif


//  --- Private Function Prototypes -----------------------------------------------------------------------------------


#if (API221_CLIENT_FEATURE == ENABLED)
    static API221_CLIENT_MOTOR_INDEX_TYPE ConvertServerMotorIndexToClientMotorIndex(uint8 node, uint8 server_motor);
    static BOOL_TYPE PostEvent(uint8 communication_node, uint8 server_motor, API221_MOTOR_EVENT_TYPE event);
    static BOOL_TYPE RequestPeriodicDataChannels(BOOL_TYPE add, API221_CLIENT_MOTOR_INDEX_TYPE client_motor, uint32 channels);
    #if (KEEP_RUNNING_TIMER > 0)
        static void SendKeepRunningMessages(void);
    #endif
    static BOOL_TYPE SendStandardCommand(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, API221MOTIONCTRL_OPCODE_TYPE op_code, uint16* params, uint8 num_of_params);
    #if (API221_STORED_ANALOG_INPUTS > 0)
        static void StoreAnalogInput(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, uint8 channel, sint32 value);
    #endif
#endif      // #if (API221_CLIENT_FEATURE == ENABLED)

#if (API221_SERVER_FEATURE == ENABLED)
    #if (TIMEOUT_TO_STOP > 0)
        static void AutoStopCheck(uint8 server_motor);
    #endif
    static void CheckForMotorStatusChangeEvents(uint8 server_motor);
    static BOOL_TYPE PublishMotorStatus(uint8 requesting_node, uint8 server_motor);
    #ifdef API221_READ_ANALOG_DATA
        static void CheckIfTimeToPublishPeriodicData(void);
        static BOOL_TYPE GeneratePeriodicData(void);
        static BOOL_TYPE PublishAnalogData(uint8 requesting_node, uint8 server_motor, uint8 channel);
        static BOOL_TYPE PublishPeriodicDataStatus(uint8 node);
        static PASS_FAIL_TYPE RevealAddAnalogInput(REVEAL_COMMAND_TYPE* msg, uint8 server_motor, uint8 channel);
        static BOOL_TYPE SetPublicationPeriod(uint8 node, uint16 milliseconds);
        static void UpdatePeriodicDataChannels(BOOL_TYPE add, uint8 server_motor, uint32 channels);
    #endif
    #ifdef API221_READ_FAILURE_FLAGS
        static void CheckForRemovedFailureFlags(uint8 server_motor);
        static REVEAL_RECIPE_STATUS_TYPE PublishFailureFlags(uint8 requesting_node, uint8 server_motor);
    #endif
#endif      // #if (API221_SERVER_FEATURE == ENABLED)


//=====================================================================================================================
//  --- Public Functions ----------------------------------------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 * Initialize the API221MotionCtrl module variables.
 */
void API221MotionCtrl__Initialize(void)
{
    if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
    {
        memset(&Api221, 0, sizeof(Api221));

        #if (API221_CLIENT_FEATURE == ENABLED)
            Callback__Initialize(&Api221_Callback);
            memset(&Api221.Data, UCHAR_MAX, sizeof(Api221.Data));
        #endif
    }
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Periodically publish analog inputs that were requested.
 */
void API221MotionCtrl__Background(void)
{
    #if ((API221_CLIENT_FEATURE == ENABLED) && (KEEP_RUNNING_TIMER > 0))
        SendKeepRunningMessages();
    #endif

    #if (API221_SERVER_FEATURE == ENABLED)
        // Iterate through the server motors
        for (uint8 server_motor = 0; server_motor < API221_SERVER_MOTOR_COUNT; server_motor++)
        {
            #if (TIMEOUT_TO_STOP > 0)
                AutoStopCheck(server_motor);
            #endif
            #ifdef API221_READ_FAILURE_FLAGS
                CheckForRemovedFailureFlags(server_motor);
            #endif

            CheckForMotorStatusChangeEvents(server_motor);
        }

        #ifdef API221_READ_ANALOG_DATA
            CheckIfTimeToPublishPeriodicData();
        #endif
    #endif      // #if (API221_SERVER_FEATURE == ENABLED)
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * This method parses API221 commands sent to a broadcast or exclusively to this node.
 * @param cmd = Pointer to the received command message.
 * @return REVEAL_RECIPE_STATUS_TYPE that expresses the result of the parsing.
 */
REVEAL_RECIPE_STATUS_TYPE API221MotionCtrl__CommandParser(REVEAL_MSG_TYPE* cmd)
{
    // Assume that the message will be incorrectly formatted.
    REVEAL_RECIPE_STATUS_TYPE reveal_response = NVO_RS_UNSUP_INVALID_PARAM;

    #if (API221_SERVER_FEATURE == ENABLED)
        // Assume that the first byte of the payload identifies the motor and evaluate it once for all
        // OpCodes that use it.
        uint8 server_motor = cmd->payload[0];
    #endif

    // Parse the command based on the OpCode.
    switch (cmd->op_code)
    {
#if (API221_SERVER_FEATURE == ENABLED)
    #ifdef API221_READ_FAILURE_FLAGS
        case API221_CMD_REQUEST_FAILURE_FLAGS:
            // Expected Payload:
            //      One byte for the server motor index
            if ((cmd->size >= 1) && (server_motor < API221_SERVER_MOTOR_COUNT))
            {
                reveal_response = PublishFailureFlags(cmd->node_id, server_motor);
            }
            break;
    #endif      // #ifdef API221_READ_FAILURE_FLAGS

    #ifdef API221_CLEAR_FAILURES
        case API221_CMD_CLEAR_FAILURE_FLAGS:
            // Expected Payload:
            //      One byte for the server motor index
            if ((cmd->size >= 1) && (server_motor < API221_SERVER_MOTOR_COUNT))
            {
                API221_CLEAR_FAILURES(server_motor);
                reveal_response = NVO_RS_READY;
            }
            break;
    #endif      // #ifdef API221_CLEAR_FAILURES

        case API221_CMD_KEEP_RUNNING:
            // Expected Payload:
            //      One byte for the server motor index
            if ((cmd->size >= 1) && (server_motor < API221_SERVER_MOTOR_COUNT))
            {
                if (BIT_TEST(Api221.Status_Flags[server_motor], API221_STS_IS_MOTOR_STOPPED))
                {
                    reveal_response = NVO_RS_UNSUP_UNAVAILABLE;
                }
                else
                {
                    // Restart the timeout to stop the motor.
                    #if (TIMEOUT_TO_STOP > 0)
                        Api221.Stop_Timeout[server_motor] = TIMEOUT_TO_STOP;
                    #endif
                    reveal_response = NVO_RS_READY;
                }
            }
            break;

        case API221_CMD_STOP:
            // Expected Payload:
            //      One byte for the server motor index
            //      Two big-endian bytes for the deceleration rate
            if ((cmd->size >= 3) && (server_motor < API221_SERVER_MOTOR_COUNT))
            {
                uint16 deceleration = Utilities__ConvertArrayTo16bits(&cmd->payload[1]);
                if (API221_DEVICE_STOP(server_motor, deceleration) == TRUE)
                {
                    // Disable the timeout-based stopping since a stop command was accepted.
                    #if (TIMEOUT_TO_STOP > 0)
                        Api221.Stop_Timeout[server_motor] = 0;
                    #endif
                    reveal_response = NVO_RS_READY;
                }
                else
                {
                    reveal_response = NVO_RS_UNSUP_UNAVAILABLE;
                }
            }
            break;

        case API221_CMD_RUN:
            // Expected Payload:
            //      One byte for the server motor index
            //      Two big-endian bytes for the velocity
            //      Two big-endian bytes for the acceleration
            if ((cmd->size >= 5) && (server_motor < API221_SERVER_MOTOR_COUNT))
            {
                sint16 velocity = (sint16)Utilities__ConvertArrayTo16bits(&cmd->payload[1]);
                uint16 acceleration = Utilities__ConvertArrayTo16bits(&cmd->payload[3]);
                if (API221_DEVICE_RUN(server_motor, velocity, acceleration) == TRUE)
                {
                    // Enable the timeout-based stopping since a command was accepted.
                    #if (TIMEOUT_TO_STOP > 0)
                        Api221.Stop_Timeout[server_motor] = TIMEOUT_TO_STOP;
                    #endif
                    reveal_response = NVO_RS_READY;
                }
                else
                {
                    reveal_response = NVO_RS_UNSUP_UNAVAILABLE;
                }
            }
            break;

    #ifdef API221_DEVICE_MOTION
        case API221_CMD_SET_MOTION_BEHAVIOR:
            // Expected Payload:
            //      One byte for the server motor index
            //      One or more parameter bytes to describe the requested motion behavior.
            if ((cmd->size >= 2) && (server_motor < API221_SERVER_MOTOR_COUNT))
            {
                if (API221_DEVICE_MOTION(server_motor, &cmd->payload[1], cmd->size - 1) == TRUE)
                {
                    // Enable the timeout-based stopping since a command was accepted.
                    #if (TIMEOUT_TO_STOP > 0)
                        Api221.Stop_Timeout[server_motor] = TIMEOUT_TO_STOP;
                    #endif
                    reveal_response = NVO_RS_READY;
                }
                else
                {
                    reveal_response = NVO_RS_UNSUP_UNAVAILABLE;
                }
            }
            break;
    #endif      // #ifdef API221_DEVICE_MOTION

        case API221_CMD_REQUEST_MOTOR_STATUS:
            // Expected Payload:
            //      One byte for the server motor index
            if ((cmd->size >= 1) && (server_motor < API221_SERVER_MOTOR_COUNT))
            {
                if (PublishMotorStatus(cmd->node_id, server_motor) == TRUE)
                {
                    reveal_response = NVO_RS_READY;
                }
                else
                {
                    reveal_response = NVO_RS_UNSUP_UNAVAILABLE;
                }
            }
            break;

    #ifdef API221_READ_ANALOG_DATA
        case API221_CMD_REQUEST_ANALOG_DATA:
            // Expected Payload:
            //      One byte for the server motor index
            //      One byte for the analog channel
            if ((cmd->size >= 2) &&
                (server_motor < API221_SERVER_MOTOR_COUNT) &&
                (cmd->payload[1] < 32))
            {
                uint8 channel = cmd->payload[1];
                if (PublishAnalogData(cmd->node_id, server_motor, channel) == TRUE)
                {
                    reveal_response = NVO_RS_READY;
                }
                else
                {
                    reveal_response = NVO_RS_UNSUP_UNAVAILABLE;
                }
            }
            break;

        case API221_CMD_SET_DATA_PUBLICATION_PERIOD:
            // Expected Payload:
            //      Two big-endian bytes with the publication period.
            if (cmd->size >= 2)
            {
                if (SetPublicationPeriod(cmd->node_id, Utilities__ConvertArrayTo16bits(&cmd->payload[0])) == TRUE)
                {
                    reveal_response = NVO_RS_READY;
                }
            }
            break;

        case API221_CMD_ADD_PERIODIC_DATA_CHANNELS:
        case API221_CMD_REMOVE_PERIODIC_DATA_CHANNELS:
            // Expected Payload:
            //      One byte for the server motor index
            //      Four big-endian bytes of bits for a combination of up to 32 analog channels.
            if ((cmd->size >= 5) && (server_motor < API221_SERVER_MOTOR_COUNT))
            {
                BOOL_TYPE add = (BOOL_TYPE)(cmd->op_code == API221_CMD_ADD_PERIODIC_DATA_CHANNELS);
                uint32 channels_bitmap = Utilities__ConvertArrayTo32bits(&cmd->payload[1]);
                UpdatePeriodicDataChannels(add, server_motor, channels_bitmap);
                reveal_response = NVO_RS_READY;
            }
            break;

        case API221_CMD_REQUEST_PERIODIC_DATA_STATUS:
            // Expected No Payload
            if (PublishPeriodicDataStatus(cmd->node_id) == TRUE)
            {
                reveal_response = NVO_RS_READY;
            }
            else
            {
                reveal_response = NVO_RS_REJECTED;
            }
            break;
    #endif      // #ifdef API221_READ_ANALOG_DATA

    #ifdef API221_DEVICE_WASH
        case API221_CMD_WASH:
            // Expected Payload:
            //      One byte for the server motor index
            //      Two big-endian bytes for the on time
            //      Two big-endian bytes for the off time
            //      Two big-endian bytes for the velocity
            //      Two big-endian bytes for the acceleration
            //      Two big-endian bytes for the deceleration
            if ((cmd->size >= 11) && (server_motor < API221_SERVER_MOTOR_COUNT))
            {
                EMP_WASH_PARAM_TYPE wash;
                wash.On_Time = Utilities__ConvertArrayTo16bits(&cmd->payload[1]);
                wash.Off_Time = Utilities__ConvertArrayTo16bits(&cmd->payload[3]);
                wash.Velocity = (sint16)Utilities__ConvertArrayTo16bits(&cmd->payload[5]);
                wash.Acceleration = Utilities__ConvertArrayTo16bits(&cmd->payload[7]);
                wash.Deceleration = Utilities__ConvertArrayTo16bits(&cmd->payload[9]);
                if (API221_DEVICE_WASH(server_motor, &wash) == TRUE)
                {
                    // Enable the timeout-based stopping since a command was accepted.
                    #if (TIMEOUT_TO_STOP > 0)
                        Api221.Stop_Timeout[server_motor] = TIMEOUT_TO_STOP;
                    #endif
                    reveal_response = NVO_RS_READY;
                }
                else
                {
                    reveal_response = NVO_RS_UNSUP_UNAVAILABLE;
                }
            }
            break;
    #endif      // #ifdef API221_DEVICE_WASH

    #ifdef API221_DEVICE_ROTATE
        case API221_CMD_ROTATE_X_DEGREES:
            // Expected Payload:
            //      One byte for the server motor index
            //      Two big-endian bytes for the angular distance to rotate (in degrees)
            //      Two big-endian bytes for the velocity
            //      Two big-endian bytes for the acceleration
            if ((cmd->size >= 7) && (server_motor < API221_SERVER_MOTOR_COUNT))
            {
                EMP_ROTATE_PARAM_TYPE rotate;
                rotate.Degrees = (sint16)Utilities__ConvertArrayTo16bits(&cmd->payload[1]);
                rotate.Velocity = (sint16)Utilities__ConvertArrayTo16bits(&cmd->payload[3]);
                rotate.Acceleration = Utilities__ConvertArrayTo16bits(&cmd->payload[5]);
                if (API221_DEVICE_ROTATE(server_motor, &rotate) == TRUE)
                {
                    // Enable the timeout-based stopping since a command was accepted.
                    #if (TIMEOUT_TO_STOP > 0)
                        Api221.Stop_Timeout[server_motor] = TIMEOUT_TO_STOP;
                    #endif
                    reveal_response = NVO_RS_READY;
                }
                else
                {
                    reveal_response = NVO_RS_UNSUP_UNAVAILABLE;
                }
            }
            break;
    #endif      // #ifdef API221_DEVICE_ROTATE

    #ifdef API221_DEVICE_PULSE
        case API221_CMD_PULSE_IMMEDIATE:
        case API221_CMD_PULSE_MODIFY:
        case API221_CMD_PULSE_QUEUE:
            // Expected Payload:
            //      One byte for the server motor index
            //      Two big-endian bytes for the on time
            //      Two big-endian bytes for the off time
            //      Two big-endian bytes for the velocity
            //      Two big-endian bytes for the acceleration
            //      Two big-endian bytes for the deceleration
            if ((cmd->size >= 11) && (server_motor < API221_SERVER_MOTOR_COUNT))
            {
                uint8 command = (EXTERNAL_MOTOR_PULSE_IMMEDIATE + cmd->op_code - API221_CMD_PULSE_IMMEDIATE);
                EMP_PULSE_PARAM_TYPE pulse;
                pulse.On_Time = Utilities__ConvertArrayTo16bits(&cmd->payload[1]);
                pulse.Off_Time = Utilities__ConvertArrayTo16bits(&cmd->payload[3]);
                pulse.Velocity = (sint16)Utilities__ConvertArrayTo16bits(&cmd->payload[5]);
                pulse.Acceleration = Utilities__ConvertArrayTo16bits(&cmd->payload[7]);
                pulse.Deceleration = Utilities__ConvertArrayTo16bits(&cmd->payload[9]);
                if (API221_DEVICE_PULSE(server_motor, (EXTERNAL_MOTOR_SIMPLE_COMMAND_TYPE)command, &pulse) == TRUE)
                {
                    // Enable the timeout-based stopping since a command was accepted.
                    #if (TIMEOUT_TO_STOP > 0)
                        Api221.Stop_Timeout[server_motor] = TIMEOUT_TO_STOP;
                    #endif
                    reveal_response = NVO_RS_READY;
                }
                else
                {
                    reveal_response = NVO_RS_UNSUP_UNAVAILABLE;
                }
            }
            break;
    #endif      // #ifdef API221_DEVICE_PULSE

#endif      // #if (API221_SERVER_FEATURE == ENABLED)
        default:
            reveal_response = NVO_RS_UNSUP_OP_CODE;
            break;
    }

    return reveal_response;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * This method parses API221 feedbacks sent to a broadcast or exclusively to this node.
 * @param fbk = Pointer to the received feedback message.
 */
void API221MotionCtrl__FeedbackParser(REVEAL_MSG_TYPE* fbk)
{
    // Parse the command based on the OpCode.
    switch (fbk->op_code)
    {
#if (API221_CLIENT_FEATURE == ENABLED)
        case API221_FBK_PUBLISH_EVENT:
            // Expected Payload:
            //      One byte for the server motor index (0-3)
            //      One byte for event code (0-63)
            if (fbk->size >= 2)
            {
                PostEvent(fbk->node_id, fbk->payload[0], (API221_MOTOR_EVENT_TYPE)fbk->payload[1]);
            }
            break;

    #if (API221_STORED_ANALOG_INPUTS > 0)
        case API221_FBK_PUBLISH_ANALOG_DATA:
        case API221_FBK_PUBLISH_PERIODIC_DATA:
            // Expected Payload:
            //      6 Bytes for each analog value:
            //          One byte for the server motor index
            //          One byte for analog data channel
            //          Four little-endian bytes for signed data
            if (fbk->size >= SIZE_OF_ANALOG_DATA_PAYLOAD)
            {
                uint8* payload = fbk->payload;
                for (uint8 index = 0; index < fbk->size; index += SIZE_OF_ANALOG_DATA_PAYLOAD)
                {
                    API221_CLIENT_MOTOR_INDEX_TYPE client_motor = ConvertServerMotorIndexToClientMotorIndex(fbk->node_id, payload[index]);
                    uint8 channel = payload[index + 1];
                    if ((client_motor < API221_SYSTEM_MOTOR_COUNT) && (channel < MAX_CHANNELS_PER_MOTOR))
                    {
                        sint32 value = *((PACKED sint32*)(void*)&payload[index + 2]);
                        StoreAnalogInput(client_motor, channel, value);
                    }
                }
            }
            break;
    #endif      // #if (API221_STORED_ANALOG_INPUTS > 0)

        case API221_FBK_PUBLISH_FAILURE_FLAGS:
            // Expected Payload:
            //      One byte for the server motor index
            //      Four big-endian bytes for bitmap of failure flags
            if (fbk->size >= 5)
            {
                API221_CLIENT_MOTOR_INDEX_TYPE client_motor = ConvertServerMotorIndexToClientMotorIndex(fbk->node_id, fbk->payload[0]);
                if (client_motor < API221_SYSTEM_MOTOR_COUNT)
                {
                    uint32 failure_flags = Utilities__ConvertArrayTo32bits(&fbk->payload[1]);
                    API221_FAILURES_HANDLER_TYPE* handlers = Api221.Failures_Handler[client_motor];
                    for (uint8 handler_index = 0; handler_index < API221_MAX_FAILURE_EVENT_HANDLERS; handler_index++)
                    {
                        if (handlers[handler_index] == NULL)
                        {
                            // There are no more handlers for the failure flags.
                            break;                  // Break out of the for() loop.
                        }
                        handlers[handler_index](client_motor, failure_flags);
                        handlers[handler_index] = NULL;
                    }
                }
            }
            break;

        case API221_FBK_PUBLISH_MOTOR_STATUS:
            // Expected Payload:
            //      One byte for the server motor index
            //      One byte for the motor status
            if (fbk->size >= 2)
            {
                API221_CLIENT_MOTOR_INDEX_TYPE client_motor = ConvertServerMotorIndexToClientMotorIndex(fbk->node_id, fbk->payload[0]);
                if (client_motor < API221_SYSTEM_MOTOR_COUNT)
                {
                    uint8 status_flags = fbk->payload[1];
                    API221_MOTOR_STATUS_HANDLER_TYPE* handlers = Api221.Motor_Status_Handler[client_motor];
                    for (uint8 handler_index = 0; handler_index < API221_MAX_STATUS_EVENT_HANDLERS; handler_index++)
                    {
                        if (handlers[handler_index] == NULL)
                        {
                            // There are no more handlers for the motor status.
                            break;                  // Break out of the for() loop.
                        }
                        handlers[handler_index](client_motor, status_flags);
                        handlers[handler_index] = NULL;
                    }
                }
            }
            break;

        case API221_FBK_PUBLISH_PERIODIC_DATA_STATUS:
            // Expected Payload:
            //      Two big-endian bytes for publication period in milliseconds
            //      Four big-endian bytes for each motor's channel bitmap
            if ((fbk->size >= 6) && (Api221.Periodic_Data_Status_Handler != NULL))
            {
                uint16 millisecond_period = Utilities__ConvertArrayTo16bits(fbk->payload);
                uint8 num_of_motors = (fbk->size - sizeof(millisecond_period)) / sizeof(uint32);
                uint32* channels_bitmaps = (uint32*)(void*)&fbk->payload[sizeof(millisecond_period)];
                for (uint8 m = 0; m < num_of_motors; m++)
                {
                    channels_bitmaps[m] = Utilities__ConvertArrayTo32bits((uint8*)(void*)&channels_bitmaps[m]);
                }
                Api221.Periodic_Data_Status_Handler(millisecond_period, channels_bitmaps, num_of_motors);
                Api221.Periodic_Data_Status_Handler = NULL;
            }
            break;
#endif      // #if (API221_CLIENT_FEATURE == ENABLED)

        default:
            LOG_ADD_EXCEPTION(FEEDBACK_OPCODE_NOT_SUPPORTED, fbk->op_code);
            break;
    }
}


//=====================================================================================================================
//  --- Public Functions (Client Only) --------------------------------------------------------------------------------
//=====================================================================================================================


#if (API221_CLIENT_FEATURE == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 * Add analog data channels from the periodically published data.
 * @param client_motor = The value used to uniquely identify the system device on the client.
 * @param channels_bitmap = The analog input channels to add to the request for periodic data.
 *                          Each bit represents an analog data channel.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__AddPeriodicDataChannels(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, uint32 channels_bitmap)
{
    if (client_motor >= API221_SYSTEM_MOTOR_COUNT)
    {
        LOG_ADD_EXCEPTION(ADD_CHANS_INVALID_PARAMS, COMBINE_BYTES(client_motor, 0));
    }
    else
    {
        return RequestPeriodicDataChannels(TRUE, client_motor, channels_bitmap);
    }
    return FALSE;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Request that all failure flags be cleared for the specified motor.
 * @param client_motor = The value used to uniquely identify the system motor on the client.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__ClearFailureFlags(API221_CLIENT_MOTOR_INDEX_TYPE client_motor)
{
    BOOL_TYPE result = FALSE;
    if (client_motor >= API221_SYSTEM_MOTOR_COUNT)
    {
        LOG_ADD_EXCEPTION(CLEAR_FAILURES_INVALID_PARAMS, COMBINE_BYTES(client_motor, 0));
    }
    else
    {
        uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
        uint8 server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
        #if (API221_SERVER_FEATURE == ENABLED)
            if (motor_node == WIN_NODE)
            {
                #ifdef API221_CLEAR_FAILURES
                    if (server_motor < API221_SERVER_MOTOR_COUNT)
                    {
                        API221_CLEAR_FAILURES(server_motor);
                        result = TRUE;
                    }
                #endif
            }
            else
        #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        {
            result = Reveal__QueueMessageU8(API221MOTIONCTRL_NUM, API221_CMD_CLEAR_FAILURE_FLAGS, motor_node, TRUE, FALSE, server_motor);
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Send a command to run the specified motor or motor-controlled device using a platform-specific behavior.
 * @param client_motor = The value used to uniquely identify the system device on the client.
 * @param buffer = Pointer to an array of platform-specific parameters.
 * @param size = Size of the 'buffer' array.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__DeviceMotion(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, uint8* buffer, uint8 size)
{
    BOOL_TYPE result = FALSE;
    if ((client_motor >= API221_SYSTEM_MOTOR_COUNT) ||
        (buffer == NULL) ||
        (size <= 0) || (EXTERNAL_MOTOR_MAX_COMMAND_SIZE - 1 < size))
    {
        LOG_ADD_EXCEPTION(MOTION_INVALID_PARAMS, COMBINE_BYTES(((buffer == NULL) ? 0x80 : 0x00) + client_motor, size));
    }
    else
    {
        uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
        uint8 server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
      #if (API221_SERVER_FEATURE == ENABLED)
        if (motor_node == WIN_NODE)
        {
            #ifdef API221_DEVICE_MOTION
                if (server_motor < API221_SERVER_MOTOR_COUNT)
                {
                    result = API221_DEVICE_MOTION(server_motor, buffer, size);
                }
            #endif
        }
        else
      #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        {
            REVEAL_COMMAND_TYPE* cmd = Reveal__NewCommand(API221MOTIONCTRL_NUM, API221_CMD_SET_MOTION_BEHAVIOR, motor_node, size + 1);
            result = (BOOL_TYPE)((Reveal__AddDataU8(cmd, server_motor) == PASS) &&
                                 (Reveal__AddDataU8Buffer(cmd, buffer, size) == PASS) &&
                                 (Reveal__QueueCommand(cmd) == TRUE));
            #if (KEEP_RUNNING_TIMER > 0)
                if (result == TRUE)
                {
                    Api221.Keep_Running_Timer[client_motor] = KEEP_RUNNING_TIMER;
                }
            #endif
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Send a command to run the specified motor or motor-controlled device with the specified pulse pattern.
 * @param client_motor = The value used to uniquely identify the system device on the client.
 * @param command = The type of pulse command.
 * @param pulse = A pointer to the pulse parameters.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__DevicePulse(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, EXTERNAL_MOTOR_SIMPLE_COMMAND_TYPE command, EMP_PULSE_PARAM_TYPE* pulse)
{
    BOOL_TYPE result = FALSE;
    if ((client_motor >= API221_SYSTEM_MOTOR_COUNT) ||
        (pulse == NULL))
    {
        LOG_ADD_EXCEPTION(PULSE_INVALID_PARAMS, COMBINE_BYTES(client_motor, (pulse == NULL)));
    }
    else
    {
        #if (API221_SERVER_FEATURE == ENABLED)
            uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
            if (motor_node == WIN_NODE)
            {
                #ifdef API221_DEVICE_PULSE
                    uint8 server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
                    if (server_motor < API221_SERVER_MOTOR_COUNT)
                    {
                        result = API221_DEVICE_PULSE(server_motor, command, pulse);
                    }
                #endif
            }
            else
        #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        {
            API221MOTIONCTRL_OPCODE_TYPE op_code = API221_NO_OPCODE;
            switch (command)
            {
                case EXTERNAL_MOTOR_PULSE_IMMEDIATE:
                    op_code = API221_CMD_PULSE_IMMEDIATE;
                    break;

                case EXTERNAL_MOTOR_PULSE_MODIFY:
                    op_code = API221_CMD_PULSE_MODIFY;
                    break;

                case EXTERNAL_MOTOR_PULSE_QUEUE:
                    op_code = API221_CMD_PULSE_QUEUE;
                    break;

                default:
                    LOG_ADD_EXCEPTION(PULSE_INVALID_COMMAND, COMBINE_BYTES(client_motor, command));
                    break;
            }
            if (op_code > 0)
            {
                result = SendStandardCommand(client_motor, op_code, (uint16*)(void*)pulse, sizeof(EMP_PULSE_PARAM_TYPE) / sizeof(uint16));
            }
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Send a command to run the specified motor or motor-controlled device with the angular rotation pattern.
 * @param client_motor = The value used to uniquely identify the system device on the client.
 * @param rotate = A pointer to the rotate parameters.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__DeviceRotate(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, EMP_ROTATE_PARAM_TYPE* rotate)
{
    BOOL_TYPE result = FALSE;
    if ((client_motor >= API221_SYSTEM_MOTOR_COUNT) ||
        (rotate == NULL))
    {
        LOG_ADD_EXCEPTION(ROTATE_INVALID_PARAMS, COMBINE_BYTES(client_motor, (rotate == NULL)));
    }
    else
    {
        #if (API221_SERVER_FEATURE == ENABLED)
            uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
            if (motor_node == WIN_NODE)
            {
                #ifdef API221_DEVICE_ROTATE
                    uint8 server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
                    if (server_motor < API221_SERVER_MOTOR_COUNT)
                    {
                        result = API221_DEVICE_ROTATE(server_motor, rotate);
                    }
                #endif
            }
            else
        #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        {
            result = SendStandardCommand(client_motor, API221_CMD_ROTATE_X_DEGREES, (uint16*)(void*)rotate, sizeof(EMP_ROTATE_PARAM_TYPE) / sizeof(uint16));
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Send a command to run the specified motor or motor-controlled device to a new velocity.
 * @param client_motor = The value used to uniquely identify the system device on the client.
 * @param velocity = The target velocity for the motor or motor-controlled device.
 * @param acceleration = The acceleration rate for the motor or motor-controlled device.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__DeviceRun(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, sint16 velocity, uint16 acceleration)
{
    BOOL_TYPE result = FALSE;
    if (client_motor >= API221_SYSTEM_MOTOR_COUNT)
    {
        LOG_ADD_EXCEPTION(RUN_INVALID_PARAMS, COMBINE_BYTES(client_motor, 0));
    }
    else
    {
        #if (API221_SERVER_FEATURE == ENABLED)
            uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
            if (motor_node == WIN_NODE)
            {
                uint8 server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
                if (server_motor < API221_SERVER_MOTOR_COUNT)
                {
                    result = API221_DEVICE_RUN(server_motor, velocity, acceleration);
                }
            }
            else
        #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        {
            EMP_RUN_PARAM_TYPE run;
            run.Velocity = velocity;
            run.Acceleration = acceleration;
            result = SendStandardCommand(client_motor, API221_CMD_RUN, (uint16*)(void*)&run, sizeof(EMP_RUN_PARAM_TYPE) / sizeof(uint16));
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Send a command to stop the specified motor or motor-controlled device.
 * @param client_motor = The value used to uniquely identify the system device on the client.
 * @param deceleration = The deceleration rate for the motor or the motor-controlled device.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__DeviceStop(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, uint16 deceleration)
{
    BOOL_TYPE result = FALSE;
    if (client_motor >= API221_SYSTEM_MOTOR_COUNT)
    {
        LOG_ADD_EXCEPTION(STOP_INVALID_PARAMS, COMBINE_BYTES(client_motor, 0));
    }
    else
    {
        #if (API221_SERVER_FEATURE == ENABLED)
            uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
            if (motor_node == WIN_NODE)
            {
                uint8 server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
                if (server_motor < API221_SERVER_MOTOR_COUNT)
                {
                    result = API221_DEVICE_STOP(server_motor, deceleration);
                }
            }
            else
        #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        {
            result = SendStandardCommand(client_motor, API221_CMD_STOP, &deceleration, 1);
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Send a command to run the specified motor or motor-controlled device with the specified wash pattern.
 * @param client_motor = The value used to uniquely identify the system device on the client.
 * @param wash = A pointer to the wash parameters.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__DeviceWash(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, EMP_WASH_PARAM_TYPE* wash)
{
    BOOL_TYPE result = FALSE;
    if ((client_motor >= API221_SYSTEM_MOTOR_COUNT) ||
        (wash == NULL))
    {
        LOG_ADD_EXCEPTION(WASH_INVALID_PARAMS, COMBINE_BYTES(client_motor, (wash == NULL)));
    }
    else
    {
        #if (API221_SERVER_FEATURE == ENABLED)
            uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
            if (motor_node == WIN_NODE)
            {
                #ifdef API221_DEVICE_WASH
                    uint8 server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
                    if (server_motor < API221_SERVER_MOTOR_COUNT)
                    {
                        result = API221_DEVICE_WASH(server_motor, wash);
                    }
                #endif
            }
            else
        #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        {
            result = SendStandardCommand(client_motor, API221_CMD_WASH, (uint16*)(void*)wash, sizeof(EMP_WASH_PARAM_TYPE) / sizeof(uint16));
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Get the specified analog input channel.
 * Returns the same value if called again and no new value has been received.
 * @param client_motor = The value used to uniquely identify the system motor on the client.
 * @param channel = The analog input channel whose value is requested.
 * @param data = A pointer to where the value should be stored if it is available.
 * @return TRUE if the analog input value was available and copied into *data; otherwise FALSE.
 */
BOOL_TYPE API221MotionCtrl__GetData(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, uint8 channel, sint32* data)
{
    BOOL_TYPE result = FALSE;
    if ((client_motor >= API221_SYSTEM_MOTOR_COUNT) ||
        (channel >= MAX_CHANNELS_PER_MOTOR) ||
        (data == NULL))
    {
        LOG_ADD_EXCEPTION(GET_DATA_INVALID_PARAMS, COMBINE_BYTES(((data == NULL) ? 0x80 : 0x00) + client_motor, channel));
    }
    else
    {
        #if (API221_SERVER_FEATURE == ENABLED)
            uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
            if (motor_node == WIN_NODE)
            {
                #ifdef API221_READ_ANALOG_DATA
                    uint8 server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
                    *data = API221_READ_ANALOG_DATA(server_motor, channel);
                    result = TRUE;
                #endif
            }
            else
        #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        {
            #if (API221_STORED_ANALOG_INPUTS > 0)
                for (uint8 i = 0; i < API221_STORED_ANALOG_INPUTS; i++)
                {
                    API221_STORED_DATA_TYPE* stored = &Api221.Data[i];
                    if ((channel == stored->Channel) &&
                        (client_motor == stored->Motor) &&
                        (stored->Sequence != 0xFF))
                    {
                        *data = stored->Value;
                        result = TRUE;
                        break;
                    }
                }
            #endif      // #if (API221_STORED_ANALOG_INPUTS > 0)
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Get the specified analog input only if it is a new value that was not previously read.
 * @param client_motor = The value used to uniquely identify the system motor on the client.
 * @param channel = The analog input channel whose value is requested.
 * @param sync = The synchronization byte used to detect new values that were not previously read.
 * @param data = A pointer to where the value should be stored if it is available.
 * @return TRUE if the analog input value was available, new, and copied into *data; otherwise FALSE.
 */
BOOL_TYPE API221MotionCtrl__GetSynchronizedData(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, uint8 channel, uint8* sync, sint32* data)
{
    BOOL_TYPE result = FALSE;
    if ((client_motor >= API221_SYSTEM_MOTOR_COUNT) ||
        (channel >= MAX_CHANNELS_PER_MOTOR) ||
        (sync == NULL) ||
        (data == NULL))
    {
        LOG_ADD_EXCEPTION(GET_SYNC_DATA_INVALID_PARAMS, COMBINE_BYTES(((data == NULL) ? 0x80 : 0x00) + ((sync == NULL) ? 0x40 : 0x00) + client_motor, channel));
    }
    else
    {
        #if (API221_STORED_ANALOG_INPUTS > 0)
            for (uint8 i = 0; i < API221_STORED_ANALOG_INPUTS; i++)
            {
                API221_STORED_DATA_TYPE* stored = &Api221.Data[i];
                if ((channel == stored->Channel) &&
                    (client_motor == stored->Motor) &&
                    (*sync != stored->Sequence) &&
                    (stored->Sequence != UCHAR_MAX))
                {
                    *data = stored->Value;
                    *sync = stored->Sequence;
                    result = TRUE;
                    break;                      // Break out of the for() loop.
                }
            }
        #endif      // #if (API221_STORED_ANALOG_INPUTS > 0)
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Determine whether the specified motor is present on the communications bus.
 * @param client_motor = The value used to uniquely identify the system device on the client.
 * @return TRUE if the specified motor is present on the communications bus; otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__IsMotorPresentOnBus(API221_CLIENT_MOTOR_INDEX_TYPE client_motor)
{
    BOOL_TYPE result = FALSE;
    if (client_motor >= API221_SYSTEM_MOTOR_COUNT)
    {
        LOG_ADD_EXCEPTION(IS_MOTOR_PRESENT_INVALID_PARAMS, COMBINE_BYTES(client_motor, 0));
    }
    else
    {
        uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
        #if (API221_SERVER_FEATURE == ENABLED)
            if (motor_node == WIN_NODE)
            {
                result = TRUE;
            }
            else
        #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        {
            result = (BOOL_TYPE)(BIT_TEST(Reveal__GetNodestatus(), motor_node));
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Inform the server that the client is still present and wishes to keep the control of the motor unchanged.
 * @param client_motor = The client-side motor index for the motor whose control should remain unchanged.
 * @return TRUE if the message was successfully sent; otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__KeepRunning(API221_CLIENT_MOTOR_INDEX_TYPE client_motor)
{
    LOG_ADD_EXCEPTION(DEPRECATED_KEEP_RUNNING_API, COMBINE_BYTES(client_motor, 0));
    return FALSE;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Register for motor events received on the communications bus.
 * @param event_handler = Pointer to a function that handles motor events.
 */
void API221MotionCtrl__RegisterForEvents(API221_EVENT_MOTOR_HANDLER_TYPE event_handler)
{
    Callback__Register(&Api221_Callback, (CALLBACK_HANDLER_TYPE)(void*)event_handler);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Remove analog data channels from the periodically published data.
 * @param client_motor = The value used to uniquely identify the system device on the client.
 * @param channels_bitmap = The analog input channels to remove from the request for periodic data.
 *                          Each bit represents an analog data channel.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__RemovePeriodicDataChannels(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, uint32 channels_bitmap)
{
    if (client_motor >= API221_SYSTEM_MOTOR_COUNT)
    {
        LOG_ADD_EXCEPTION(REMOVE_CHANS_INVALID_PARAMS, COMBINE_BYTES(client_motor, 0));
    }
    else
    {
        return RequestPeriodicDataChannels(FALSE, client_motor, channels_bitmap);
    }
    return FALSE;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Request an analog input for a specified motor from the remote device.
 * The caller can use synchronized data and polling to know when the requested value has been received.
 * @param client_motor = The value used to uniquely identify the system device on the client.
 * @param channel = The analog input channel whose value is requested.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__RequestAnalogData(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, uint8 channel)
{
    BOOL_TYPE result = FALSE;
    if ((client_motor >= API221_SYSTEM_MOTOR_COUNT) ||
        (channel >= MAX_CHANNELS_PER_MOTOR))
    {
        LOG_ADD_EXCEPTION(REQ_ANALOG_DATA_INVALID_PARAMS, COMBINE_BYTES(client_motor, channel));
    }
    else
    {
        uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
        uint8 server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
        #if (API221_SERVER_FEATURE == ENABLED)
            if (motor_node == WIN_NODE)
            {
                #ifdef API221_READ_ANALOG_DATA
                    sint32 value = API221_READ_ANALOG_DATA(server_motor, channel);
                    StoreAnalogInput(client_motor, channel, value);
                    result = TRUE;
                #endif
            }
            else
        #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        {
            REVEAL_COMMAND_TYPE* cmd = Reveal__NewCommand(API221MOTIONCTRL_NUM, API221_CMD_REQUEST_ANALOG_DATA, motor_node, 2);
            result = (BOOL_TYPE)((Reveal__AddDataU8(cmd, server_motor) == PASS) &&
                                 (Reveal__AddDataU8(cmd, channel) == PASS) &&
                                 (Reveal__QueueCommand(cmd) == TRUE));
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Request all failure flags from the node that controls the specified motor.
 * @param client_motor = The value used to uniquely identify the system motor on the client.
 * @param failures_handler = Pointer to a function that can handle the motor failure flags message.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__RequestFailureFlags(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, API221_FAILURES_HANDLER_TYPE failures_handler)
{
    BOOL_TYPE result = FALSE;
    if ((client_motor >= API221_SYSTEM_MOTOR_COUNT) ||
        (failures_handler == NULL))
    {
        LOG_ADD_EXCEPTION(REQ_FAILURES_INVALID_PARAMS, COMBINE_BYTES(client_motor, (failures_handler == NULL)));
    }
    else
    {
        uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
        uint8 server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
        #if (API221_SERVER_FEATURE == ENABLED)
            if (motor_node == WIN_NODE)
            {
                #ifdef API221_READ_FAILURE_FLAGS
                    if (server_motor < API221_SERVER_MOTOR_COUNT)
                    {
                        failures_handler(client_motor, Api221.Failure_Flags[server_motor]);
                        result = TRUE;
                    }
                #endif
            }
            else
        #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        {
            API221_FAILURES_HANDLER_TYPE* handlers = Api221.Failures_Handler[client_motor];
            for (uint8 handler_index = 0; handler_index < API221_MAX_FAILURE_EVENT_HANDLERS; handler_index++)
            {
                if ((handlers[handler_index] == NULL) ||
                    (handlers[handler_index] == failures_handler))
                {
                    // Found an open slot for a failure flags handler.
                    result = TRUE;                      // Assume that the request was already sent.
                    if (handler_index == 0)
                    {
                        // Since this is the first request, send the request message.
                        result = Reveal__QueueMessageU8(API221MOTIONCTRL_NUM, API221_CMD_REQUEST_FAILURE_FLAGS, motor_node, TRUE, FALSE, server_motor);
                    }
                    if (result == TRUE)
                    {
                        handlers[handler_index] = failures_handler;
                    }
                    break;                              // Break out of the for() loop.
                }
            }
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Request the current settings for the periodic data feature.
 * @param client_motor = Used to identify the server based on just one of the motors that it controls.
 * @param per_data_status_handler = Pointer to a function that can handle the periodic data status message.
 * @return TRUE if the request was sent. Otherwise FALSE.
 */
BOOL_TYPE API221MotionCtrl__RequestPeriodicDataStatus(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, API221_PER_DATA_STATUS_HANDLER_TYPE per_data_status_handler)
{
    BOOL_TYPE result = FALSE;

    if ((client_motor >= API221_SYSTEM_MOTOR_COUNT) ||
        (per_data_status_handler == NULL))
    {
        LOG_ADD_EXCEPTION(REQ_PER_DATA_STATUS_INVALID_PARAMS, COMBINE_BYTES(client_motor, (per_data_status_handler == NULL)));
    }
    else
    {
        uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
        #if (API221_SERVER_FEATURE == ENABLED)
            if (motor_node == WIN_NODE)
            {
                uint16 millisecond_period = Api221.Publication_Period * API221_MS_PER_CALL_TO_BACKGROUND;
                per_data_status_handler(millisecond_period, Api221.Requested, API221_SERVER_MOTOR_COUNT);
                result = TRUE;
            }
            else
        #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        if (Api221.Periodic_Data_Status_Handler == NULL)
        {
            result = Reveal__QueueMessageNoData(API221MOTIONCTRL_NUM, API221_CMD_REQUEST_PERIODIC_DATA_STATUS, motor_node, TRUE, FALSE);
            if (result == TRUE)
            {
                Api221.Periodic_Data_Status_Handler = per_data_status_handler;
            }
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Request the current status of a motor.
 * @param client_motor = Motor for which the status is being requested.
 * @param motor_status_handler = Pointer to a function that can handle the motor status message.
 * @return TRUE if the request was sent. Otherwise FALSE.
 */
BOOL_TYPE API221MotionCtrl__RequestStatus(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, API221_MOTOR_STATUS_HANDLER_TYPE motor_status_handler)
{
    BOOL_TYPE result = FALSE;
    if ((client_motor >= API221_SYSTEM_MOTOR_COUNT) ||
        (motor_status_handler == NULL))
    {
        LOG_ADD_EXCEPTION(REQ_STATUS_INVALID_PARAMS, COMBINE_BYTES(client_motor, (motor_status_handler == NULL)));
    }
    else
    {
        uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
        API221_CLIENT_MOTOR_INDEX_TYPE server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
        #if (API221_SERVER_FEATURE == ENABLED)
            if (motor_node == WIN_NODE)
            {
                motor_status_handler(server_motor, Api221.Status_Flags[server_motor]);
                result = TRUE;
            }
            else
        #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        {
            API221_MOTOR_STATUS_HANDLER_TYPE* handlers = Api221.Motor_Status_Handler[client_motor];
            for (uint8 handler_index = 0; handler_index < API221_MAX_STATUS_EVENT_HANDLERS; handler_index++)
            {
                if ((handlers[handler_index] == NULL) ||
                    (handlers[handler_index] == motor_status_handler))
                {
                    if (handler_index == 0)
                    {
                        result = Reveal__QueueMessageU8(API221MOTIONCTRL_NUM, API221_CMD_REQUEST_MOTOR_STATUS, motor_node, TRUE, FALSE, server_motor);
                    }
                    else
                    {
                        result = TRUE;
                    }
                    if (result == TRUE)
                    {
                        handlers[handler_index] = motor_status_handler;
                    }
                    break;                          // Break out of the for() loop.
                }
            }
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Set the data publication period for data that is periodically published by a motor controller.
 * If the requested data publication period is not supported, the motor controller will NAK the command.
 * Note that only one period is supported at a time. So, if a motor controller controls two
 * motors, then the last requested data publication period will be used for both motors.
 * @param client_motor = The value used to uniquely identify the system device on the client.
 * @param milliseconds = The requested number of milliseconds between publishing periodic data.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__SetDataPublicationPeriod(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, uint16 milliseconds)
{
    BOOL_TYPE result = FALSE;
    if (client_motor >= API221_SYSTEM_MOTOR_COUNT)
    {
        LOG_ADD_EXCEPTION(SET_PERIOD_INVALID_PARAMS, COMBINE_BYTES(client_motor, 0));
    }
    else
    {
        uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
        #if (API221_SERVER_FEATURE == ENABLED)
            if (motor_node == WIN_NODE)
            {
                #ifdef API221_READ_ANALOG_DATA
                    result = SetPublicationPeriod(motor_node, milliseconds);
                #endif
                if (result == FALSE)
                {
                    LOG_ADD_EXCEPTION(SET_PERIOD_INVALID_PARAMS, COMBINE_BYTES(client_motor, milliseconds));
                }
            }
            else
        #endif      // #if (API221_SERVER_FEATURE == ENABLED)
        {
            result = Reveal__QueueMessageU16(API221MOTIONCTRL_NUM, API221_CMD_SET_DATA_PUBLICATION_PERIOD, motor_node, TRUE, FALSE, milliseconds);
        }
    }
    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Synchronize the client so that it can receive only new samples of the analog inputs as they are received.
 * @param client_motor = The value used to uniquely identify the system motor on the client.
 * @param channel = The analog input channel whose value is requested.
 * @param sync = Pointer to a byte used to synchronize the client.
 */
void API221MotionCtrl__SynchronizeData(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, uint8 channel, uint8* sync)
{
    #if (API221_STORED_ANALOG_INPUTS > 0)
        for (uint8 i = 0; i < API221_STORED_ANALOG_INPUTS; i++)
        {
            API221_STORED_DATA_TYPE* stored = &Api221.Data[i];
            if ((channel == stored->Channel) && (client_motor == stored->Motor))
            {
                *sync = stored->Sequence;
                return;
            }
        }
    #endif      // #if (API221_STORED_ANALOG_INPUTS > 0)
    *sync = UCHAR_MAX;                              // Consider any data found as new data.
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Unregister for motor events received on the communications bus.
 * @param event_handler = Pointer to a function that handles motor events.
 */
void API221MotionCtrl__UnregisterForEvents(API221_EVENT_MOTOR_HANDLER_TYPE event_handler)
{
    Callback__Unregister(&Api221_Callback, (CALLBACK_HANDLER_TYPE)(void*)event_handler);
}
#endif      // #if (API221_CLIENT_FEATURE == ENABLED)


//=====================================================================================================================
//  --- Public Functions (Server Only) --------------------------------------------------------------------------------
//=====================================================================================================================


#if (API221_SERVER_FEATURE == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 * Publish a motor event on the communications bus.
 * @param server_motor = The server-based motor index.
 * @param event = The specific event value to publish.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
BOOL_TYPE API221MotionCtrl__PostEvent(uint8 server_motor, API221_MOTOR_EVENT_TYPE event)
{
    #if (API221_CLIENT_FEATURE == ENABLED)
        return PostEvent(WIN_NODE, server_motor, event);
    #else
        if ((server_motor < API221_SERVER_MOTOR_COUNT) && (event < API221_EVENT_COUNT))
        {
            REVEAL_COMMAND_TYPE* msg = Reveal__NewFeedback(API221MOTIONCTRL_NUM, API221_FBK_PUBLISH_EVENT, REVEAL_BROADCAST_NODE, 2);
            return (BOOL_TYPE)((Reveal__AddDataU8(msg, server_motor) == PASS) &&
                               (Reveal__AddDataU8(msg, event) == PASS) &&
                               (Reveal__QueueCommand(msg) == TRUE));
        }
        return FALSE;
    #endif
}
#endif      // #if (API221_SERVER_FEATURE == ENABLED)


//=====================================================================================================================
//  --- Private Functions (Client) ------------------------------------------------------------------------------------
//=====================================================================================================================

#if (API221_CLIENT_FEATURE == ENABLED)
//---------------------------------------------------------------------------------------------------------------------
/**
 * Convert the motor ID communicated on API221 to a client-side motor index.
 * @param server_motor = The server-side motor index.
 * @return The client-side motor index or an out-of-range value if there is no corresponding motor index.
 */
static API221_CLIENT_MOTOR_INDEX_TYPE ConvertServerMotorIndexToClientMotorIndex(uint8 node, uint8 server_motor)
{
    for (API221_CLIENT_MOTOR_INDEX_TYPE client_motor = (API221_CLIENT_MOTOR_INDEX_TYPE)0;
         client_motor < API221_SYSTEM_MOTOR_COUNT;
         client_motor++)
    {
        if ((API221_MOTOR_IDS[client_motor].Communication_Node == node) &&
            (API221_MOTOR_IDS[client_motor].Motor_Index == server_motor))
        {
            return client_motor;
        }
    }
    return (API221_CLIENT_MOTOR_INDEX_TYPE)API221_SYSTEM_MOTOR_COUNT;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Post a motor event to the API221 client.
 * @param communication_node = The node that generated the event.
 * @param server_motor = The motor on the API221 server that generated the event.
 * @param event = The generated event.
 * @return TRUE if the event was posted.
 */
static BOOL_TYPE PostEvent(uint8 communication_node, uint8 server_motor, API221_MOTOR_EVENT_TYPE event)
{
    API221_CLIENT_MOTOR_INDEX_TYPE client_motor = ConvertServerMotorIndexToClientMotorIndex(communication_node, server_motor);
    if ((client_motor < API221_SYSTEM_MOTOR_COUNT) &&
        (event < API221_EVENT_COUNT))
    {
        uint8 motor_event = BUILD_MOTOR_EVENT(client_motor, event);
        Callback__Notify(&Api221_Callback, motor_event);
        return TRUE;
    }
    return FALSE;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Update the request for periodic publication of analog data channels.
 * All these parameters are guaranteed to be in range since they are controlled within this module.
 * @param add = TRUE to add channels; FALSE to remove channels.
 * @param client_motor = The value used to uniquely identify the system device on the client.
 * @param channels = The analog input channels to remove from the request for periodic data.
 *                   Each bit represents an analog data channel.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
static BOOL_TYPE RequestPeriodicDataChannels(BOOL_TYPE add, API221_CLIENT_MOTOR_INDEX_TYPE client_motor, uint32 channels)
{
    BOOL_TYPE result = FALSE;
    uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
    uint8 server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
    #if (API221_SERVER_FEATURE == ENABLED)
        if (motor_node == WIN_NODE)
        {
            #ifdef API221_READ_ANALOG_DATA
                UpdatePeriodicDataChannels(add, server_motor, channels);
                result = TRUE;
            #endif
        }
        else
    #endif      // #if (API221_SERVER_FEATURE == ENABLED)
    {
        API221MOTIONCTRL_OPCODE_TYPE op_code = (API221MOTIONCTRL_OPCODE_TYPE)
                (add ? (uint8)API221_CMD_ADD_PERIODIC_DATA_CHANNELS : (uint8)API221_CMD_REMOVE_PERIODIC_DATA_CHANNELS);
        REVEAL_COMMAND_TYPE* cmd = Reveal__NewCommand(API221MOTIONCTRL_NUM, op_code, motor_node, 5);
        result = (BOOL_TYPE)((Reveal__AddDataU8(cmd, server_motor) == PASS) &&
                             (Reveal__AddDataU32(cmd, channels) == PASS) &&
                             (Reveal__QueueCommand(cmd) == TRUE));
    }
    return result;
}

#if (KEEP_RUNNING_TIMER > 0)
//---------------------------------------------------------------------------------------------------------------------
/**
 * Send API221_CMD_KEEP_RUNNING to any server motors that are running to keep them from timing out.
 */
static void SendKeepRunningMessages(void)
{
    for (API221_CLIENT_MOTOR_INDEX_TYPE client_motor = (API221_CLIENT_MOTOR_INDEX_TYPE)0;
         client_motor < API221_SYSTEM_MOTOR_COUNT;
         client_motor++)
    {
        uint16 timer = Api221.Keep_Running_Timer[client_motor];
        if (timer == 0)
        {
            // Motor is not running -- do nothing.
        }
        else if (timer == 1)
        {
            uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
          #if (API221_SERVER_FEATURE == ENABLED)
            if (motor_node != WIN_NODE)
          #endif
            {
                uint8 server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
                BOOL_TYPE result = Reveal__QueueMessageU8(API221MOTIONCTRL_NUM, API221_CMD_KEEP_RUNNING, motor_node, TRUE, FALSE, server_motor);
                if (result == TRUE)
                {
                    Api221.Keep_Running_Timer[client_motor] = KEEP_RUNNING_TIMER;
                }
            }
        }
        else
        {
            Api221.Keep_Running_Timer[client_motor] = timer - 1;
        }
    }
}
#endif      // #if (KEEP_RUNNING_TIMER > 0)

//---------------------------------------------------------------------------------------------------------------------
/**
 * Send a standard command to the specified motor or motor-controlled device.
 * All standard commands contain arrays of uint16 values stored in little-endian format that must
 * be converted to big-endian format in the Reveal message.
 * @param client_motor = The value used to uniquely identify the system device on the client.
 * @param op_code = The Reveal OpCode that identifies the type of standard command.
 * @param params = A pointer to the uint16 parameters that should be placed on the Reveal payload.
 * @param size = The number of bytes to copy from the params[] array.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
static BOOL_TYPE SendStandardCommand(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, API221MOTIONCTRL_OPCODE_TYPE op_code, uint16* params, uint8 num_of_params)
{
    BOOL_TYPE result = FALSE;
    uint8 motor_node = API221_MOTOR_IDS[client_motor].Communication_Node;
    uint8 size = 2 * num_of_params + 1;
    REVEAL_COMMAND_TYPE* cmd = Reveal__NewCommand(API221MOTIONCTRL_NUM, op_code, motor_node, size);
    uint8 server_motor = API221_MOTOR_IDS[client_motor].Motor_Index;
    if (Reveal__AddDataU8(cmd, server_motor) == PASS)
    {
        result = TRUE;
        for (uint8 param_index = 0; param_index < num_of_params; param_index++)
        {
            if (Reveal__AddDataU16(cmd, params[param_index]) == FAIL)
            {
                result = FALSE;
                break;                              // Break out of for() loop.
            }
        }
        if (result == TRUE)
        {
            result = Reveal__QueueCommand(cmd);
            #if (KEEP_RUNNING_TIMER > 0)
                if (result == TRUE)
                {
                    if (op_code == API221_CMD_STOP)
                    {
                        Api221.Keep_Running_Timer[client_motor] = 0;
                    }
                    else
                    {
                        Api221.Keep_Running_Timer[client_motor] = KEEP_RUNNING_TIMER;
                    }
                }
            #endif
        }
    }
    return result;
}


#if (API221_STORED_ANALOG_INPUTS > 0)
//---------------------------------------------------------------------------------------------------------------------
/**
 * Insert an analog input value into the array of all analog input values, Api221.Data[].
 * Replace any previously stored analog input value with the same analog input ID.
 * Maintain the array order so that the analog input values are sorted from newest to oldest.
 * Drop the oldest analog input value if it does not fit in the array.
 * Api221.Data[0] will contain the inserted analog input value when done.
 * @param data = The structure that holds the motor index, channel index, and analog input value.
 */
static void StoreAnalogInput(API221_CLIENT_MOTOR_INDEX_TYPE client_motor, uint8 channel, sint32 value)
{
    // Look for the presence of the analog input ID in the existing stored data array.
    uint8 num_of_analog_inputs_to_shift = API221_STORED_ANALOG_INPUTS - 1;
    uint8 new_sequence_number = 0;                  // Assume this is the first occurrence in the stored data.

    // The last analog input must be checked to avoid unnecessarily losing the sequence number.
    for (uint8 i = 0; i < API221_STORED_ANALOG_INPUTS; i++)
    {
        API221_STORED_DATA_TYPE* stored = &Api221.Data[i];

        if ((stored->Channel == channel) && (stored->Motor == client_motor))
        {
            num_of_analog_inputs_to_shift = i;
            if (stored->Sequence < UCHAR_MAX - 1)
            {
                new_sequence_number = stored->Sequence + 1;
            }
            else
            {
                new_sequence_number = 1;
            }
            break;                                  // Break out of the for() loop.
        }
    }

    // Shift the array elements.
    //      This will remove any previously stored copy of the analog input, and...
    //      it will make space for the new analog input at the start of the array.
    if (num_of_analog_inputs_to_shift > 0)
    {
        memmove(&Api221.Data[1], &Api221.Data[0],
                num_of_analog_inputs_to_shift * sizeof(API221_STORED_DATA_TYPE));
    }

    // Store the new analog input at the start of the array.
    Api221.Data[0].Value = value;
    Api221.Data[0].Motor = client_motor;
    Api221.Data[0].Channel = channel;
    Api221.Data[0].Sequence = new_sequence_number;
}
#endif      // #if (API221_STORED_ANALOG_INPUTS > 0)
#endif      // #if (API221_CLIENT_FEATURE == ENABLED)


//=====================================================================================================================
//  --- Private Functions (Server) ------------------------------------------------------------------------------------
//=====================================================================================================================


#if (API221_SERVER_FEATURE == ENABLED)
#if (TIMEOUT_TO_STOP > 0)
//---------------------------------------------------------------------------------------------------------------------
/**
 * Implement Auto-Stop feature on the server.
 * Automatically stop the motor if timeout occurs before expected messages from the client.
 * @param server_motor = The server-based motor index.
 */
static void AutoStopCheck(uint8 server_motor)
{
    uint8 timeout = Api221.Stop_Timeout[server_motor];
    if (timeout == 0)
    {
        // Do nothing.
    }
    else if (timeout == 1)
    {
        if (API221_DEVICE_STOP(server_motor, API221_DEFAULT_DECELERATION) == TRUE)
        {
            LOG_ADD_EVENT(MOTOR_STOPPED_DUE_TO_TIMEOUT, server_motor);
            Api221.Stop_Timeout[server_motor] = 0;
        }
        else
        {
            LOG_ADD_EXCEPTION(MOTOR_REJECTED_STOP_FROM_TIMEOUT, server_motor);
        }
    }
    else
    {
        Api221.Stop_Timeout[server_motor] = timeout - 1;
    }
}
#endif      // #if (TIMEOUT_TO_STOP > 0)

//---------------------------------------------------------------------------------------------------------------------
/**
 * Check the motor status and react to changes.
 * @param server_motor = The server-side motor index which is associated with the status.
 */
static void CheckForMotorStatusChangeEvents(uint8 server_motor)
{
    uint8 prev_status = Api221.Status_Flags[server_motor];
    uint8 next_status = API221_READ_MOTOR_STATUS(server_motor);
    if (prev_status != next_status)
    {
        // Save the new status.
        Api221.Status_Flags[server_motor] = next_status;

        // Determine if any error occurred.
        if ((BIT_TEST(prev_status, API221_STS_ANY_ERROR_FOUND) == 0) &&
            (BIT_TEST(next_status, API221_STS_ANY_ERROR_FOUND) == 1))
        {
            API221MotionCtrl__PostEvent(server_motor, API221_EVENT_ERROR);
        }

        // Look for events derived from previous and current status.
        //      Setup a key with the following bits:
        //          bit 3 = Had previously reached target
        //          bit 2 = Was previously stopped
        //          bit 1 = Has currently reached target
        //          bit 0 = Is currently stopped
        uint8 key = ((prev_status << 1) & 0x0C) + ((next_status >> 1) & 0x03);
        //      Use the key to look up the event in a table.
        API221_MOTOR_EVENT_TYPE event = KEY_TO_EVENT[key];
        if (event != API221_EVENT_NONE)
        {
            API221MotionCtrl__PostEvent(server_motor, event);
        }
    }
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Publish the status for a specific motor controlled by the server.
 * @param requesting_node = The node that requested the motor status.
 * @param server_motor = The server-side motor index whose status should be published.
 * @return TRUE if the request was sent. Otherwise FALSE.
 */
static BOOL_TYPE PublishMotorStatus(uint8 requesting_node, uint8 server_motor)
{
    REVEAL_COMMAND_TYPE* msg = Reveal__NewFeedback(API221MOTIONCTRL_NUM, API221_FBK_PUBLISH_MOTOR_STATUS, requesting_node, 2);
    return (BOOL_TYPE)((Reveal__AddDataU8(msg, server_motor) == PASS) &&
                       (Reveal__AddDataU8(msg, Api221.Status_Flags[server_motor]) == PASS) &&
                       (Reveal__QueueCommand(msg) == TRUE));
}

#ifdef API221_READ_ANALOG_DATA
//---------------------------------------------------------------------------------------------------------------------
/**
 * Publish periodic data if it was requested and it is time to publish it.
 */
static void CheckIfTimeToPublishPeriodicData(void)
{
    if (Api221.Publication_Period > 0)
    {
        if (Api221.Publication_Counter > 0)
        {
            Api221.Publication_Counter--;
        }
        if ((Api221.Publication_Counter == 0) &&
            (Api221.Requested != 0))
        {
            if (GeneratePeriodicData() == TRUE)
            {
                // Setup the counter for the next publication.
                Api221.Publication_Counter = Api221.Publication_Period;
            }
            else
            {
                LOG_ADD_EXCEPTION(PERIODIC_PUBLICATION_FAILED, Api221.Num_Of_Requested_Analog_Inputs);
            }
        }
    }
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Generate all the requested analog inputs.
 * The API221 Client/Server will save the results in a local array.
 * The API221 Server Only will publish the results on Reveal
 * @return TRUE if a message with the analog inputs was sent to Reveal; otherwise FALSE.
 */
static BOOL_TYPE GeneratePeriodicData(void)
{
    #if (API221_CLIENT_FEATURE == ENABLED)
        // Iterate through all the server_motors and their associated analog inputs.
        for (uint8 server_motor = 0; server_motor < API221_SERVER_MOTOR_COUNT; server_motor++)
        {
            uint32 requested = Api221.Requested[server_motor];
            if (requested > 0)
            {
                API221_CLIENT_MOTOR_INDEX_TYPE client_motor = ConvertServerMotorIndexToClientMotorIndex(WIN_NODE, server_motor);
                for (uint8 channel = 0; requested > 0; channel++)
                {
                    if (BIT_TEST(requested, channel) != 0)
                    {
                        // Analog input 'channel' is requested for 'server_motor'.
                        BIT_CLR(requested, channel);
                        sint32 value = API221_READ_ANALOG_DATA(server_motor, channel);
                        StoreAnalogInput(client_motor, channel, value);
                    }
                }
            }
        }
        return TRUE;
    #else
        // Create a feedback message.
        uint8 payload_size = Api221.Num_Of_Requested_Analog_Inputs * SIZE_OF_ANALOG_DATA_PAYLOAD;
        REVEAL_COMMAND_TYPE* msg = Reveal__NewFeedback(API221MOTIONCTRL_NUM, API221_FBK_PUBLISH_PERIODIC_DATA, Api221.Requesting_Node, payload_size);
        if (msg == NULL)
        {
            return FALSE;                               // Could not get a Reveal feedback message.
        }

        // Iterate through all the server_motors and their associated analog inputs.
        for (uint8 server_motor = 0; server_motor < API221_SERVER_MOTOR_COUNT; server_motor++)
        {
            uint32 requested = Api221.Requested[server_motor];
            for (uint8 channel = 0; requested > 0; channel++)
            {
                if (BIT_TEST(requested, channel) != 0)
                {
                    // Analog input 'channel' is requested for 'server_motor'.
                    BIT_CLR(requested, channel);
                    if (RevealAddAnalogInput(msg, server_motor, channel) == FAIL)
                    {
                        return FALSE;                   // Failed to add the analog input to the payload.
                    }
                }
            }
        }
        return (BOOL_TYPE)(Reveal__QueueCommand(msg) == TRUE);
    #endif
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Publish a single analog input value.
 * @param requesting_node = The node that requested the analog input value.
 * @param server_motor = The server-side motor index whose analog data should be published.
 * @param channel = The analog input ID.
 * @return TRUE if the request was sent. Otherwise, FALSE.
 */
static BOOL_TYPE PublishAnalogData(uint8 requesting_node, uint8 server_motor, uint8 channel)
{
    REVEAL_COMMAND_TYPE* msg = Reveal__NewFeedback(API221MOTIONCTRL_NUM, API221_FBK_PUBLISH_ANALOG_DATA, requesting_node, SIZE_OF_ANALOG_DATA_PAYLOAD);
    return (BOOL_TYPE)((RevealAddAnalogInput(msg, server_motor, channel) == PASS) &&
                       (Reveal__QueueCommand(msg) == TRUE));
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Publish information about the current status of the periodic publication feature.
 * @param requesting_node = The node to which the periodic data should be sent.
 * @return TRUE if the packet was sent successfully. Otherwise FALSE.
 */
static BOOL_TYPE PublishPeriodicDataStatus(uint8 requesting_node)
{
    REVEAL_COMMAND_TYPE* msg = Reveal__NewFeedback(API221MOTIONCTRL_NUM,
                                                   API221_FBK_PUBLISH_PERIODIC_DATA_STATUS,
                                                   requesting_node,
                                                   sizeof(uint16) + API221_SERVER_MOTOR_COUNT * sizeof(uint32));
    PASS_FAIL_TYPE pass = Reveal__AddDataU16(msg, API221_MS_PER_CALL_TO_BACKGROUND * Api221.Publication_Period);
    for (uint8 server_motor = 0; (pass == PASS) && (server_motor < API221_SERVER_MOTOR_COUNT); server_motor++)
    {
        pass = Reveal__AddDataU32(msg, Api221.Requested[server_motor]);
    }

    if (pass == PASS)
    {
        return (BOOL_TYPE)Reveal__QueueCommand(msg);
    }
    else
    {
        return FALSE;
    }
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Add a single analog input to a Reveal packet that is under construction.
 * @param msg = Pointer to the REVEAL_COMMAND_TYPE that holds the message being built.
 * @param server_motor = The server-side motor index.
 * @param channel = The analog input ID.
 * @return PASS if the analog input data was successful added to the Reveal message; otherwise FAIL.
 */
static PASS_FAIL_TYPE RevealAddAnalogInput(REVEAL_COMMAND_TYPE* msg, uint8 server_motor, uint8 channel)
{
    sint32 value = API221_READ_ANALOG_DATA(server_motor, channel);
    return (PASS_FAIL_TYPE)((Reveal__AddDataU8(msg, server_motor) == PASS) &&
                            (Reveal__AddDataU8(msg, channel) == PASS) &&
                            (Reveal__AddDataU8Buffer(msg, (uint8*)(void*)&value, sizeof(value)) == PASS));
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Set the publication period for all periodic data published by this communication node.
 * @param milliseconds = The requested number of milliseconds between periodically published data.
 * @return TRUE if the requested period is supported; otherwise FALSE.
 */
static BOOL_TYPE SetPublicationPeriod(uint8 node, uint16 milliseconds)
{
    if ((milliseconds == 0) || (milliseconds >= MINIMUM_PUBLICATION_MILLISECONDS))
    {
        // Verify that the requested millisecond publication rate can be supported.
        uint16 calls_to_background = milliseconds / API221_MS_PER_CALL_TO_BACKGROUND;
        if ((milliseconds % API221_MS_PER_CALL_TO_BACKGROUND == 0) &&
            (calls_to_background <= UCHAR_MAX))
        {
            if (Api221.Publication_Period != (uint8)calls_to_background)
            {
                Api221.Publication_Period = (uint8)calls_to_background;
            }
            Api221.Requesting_Node = node;
            return TRUE;
        }
    }
    return FALSE;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Add or remove analog data channels from the list of periodically published data.
 * @param add = TRUE to add channels; FALSE to remove channels.
 * @param server_motor = The server-side motor index.
 * @param channels = A mask of the analog data channels to add or remove.
 *                   Bit 'n' of this value represents an analog data channel #n.
 */
static void UpdatePeriodicDataChannels(BOOL_TYPE add, uint8 server_motor, uint32 channels)
{
    if (add == TRUE)
    {
        Api221.Requested[server_motor] |= channels;
    }
    else
    {
        Api221.Requested[server_motor] &= ~channels;
    }
    Api221.Num_Of_Requested_Analog_Inputs = Utilities__CountOneBitsInArray((uint8*)(Api221.Requested), sizeof(Api221.Requested));   //lint !e928 Suppress Info: cast from pointer to pointer [MISRA 2004 rule 11.4]
}
#endif      // #ifdef API221_READ_ANALOG_DATA

#ifdef API221_READ_FAILURE_FLAGS
//---------------------------------------------------------------------------------------------------------------------
/**
 * Publish event if any failure flags have been removed through the motor interface.
 * @param server_motor = The server-side motor index which is associated with the failure flags.
 */
static void CheckForRemovedFailureFlags(uint8 server_motor)
{
    uint32 next_failure_flags = API221_READ_FAILURE_FLAGS(server_motor);
    uint32 prev_failure_flags = Api221.Failure_Flags[server_motor];

    // Save the new failure flags.
    Api221.Failure_Flags[server_motor] = next_failure_flags;

    // Check if a failure has been removed (any bit changed from 1 to 0)
    if ((prev_failure_flags & (prev_failure_flags ^ next_failure_flags)) != 0)
    {
        API221MotionCtrl__PostEvent(server_motor, API221_EVENT_REMOVED_ERROR);
    }
}

//---------------------------------------------------------------------------------------------------------------------
/**
 * Publish all the failure flags.
 * @param requesting_node = The node that requested the failure flags.
 * @param server_motor = The server-side motor index which is associated with the failure flags.
 * @return NVO_RS_READY if the message was successfully sent; otherwise NVO_RS_REJECTED.
 */
static REVEAL_RECIPE_STATUS_TYPE PublishFailureFlags(uint8 requesting_node, uint8 server_motor)
{
    REVEAL_COMMAND_TYPE* msg = Reveal__NewFeedback(API221MOTIONCTRL_NUM, API221_FBK_PUBLISH_FAILURE_FLAGS, requesting_node, 5);
    if ((Reveal__AddDataU8(msg, server_motor) == PASS) &&
        (Reveal__AddDataU32(msg, Api221.Failure_Flags[server_motor]) == PASS) &&
        (Reveal__QueueCommand(msg) == TRUE))
    {
        return NVO_RS_READY;
    }
    else
    {
        return NVO_RS_REJECTED;
    }
}
#endif      // #ifdef API221_READ_FAILURE_FLAGS
#endif      // #if (API221_SERVER_FEATURE == ENABLED)

#endif      // #if ((API221_CLIENT_FEATURE == ENABLED) || (API221_SERVER_FEATURE == ENABLED))
