/**
 *  @file		VoltageRangeMonitor.c
 *
 *  @brief      Voltage Range monitor module implementation
 *
 *  @details    This module checks voltage value and compares to thresholds set
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2016-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "C_Extensions.h"
#include "VoltageRangeMonitor.h"
#include "VoltageRangeMonitor_prv.h"

#include "DoorMonitor.h"
#include "Interpreter.h"
#include "Hbl.h"
#include "Log.h"
#include "Micro.h"
#include "Selector.h"
#include "SettingFile.h"
#include "StatisticsDish.h"
#include "SubCycle.h"

//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
#ifndef VOLTAGERANGE_GETREFERENCE
#define VOLTAGERANGE_GETREFERENCE()			0
#endif

#ifndef VOLTAGERANGE_EXEC_TIME_MS
#define VOLTAGERANGE_EXEC_TIME_MS			100
#endif

#define VOLTAGERANGE_PARAM_TIME_CONVERT(s)		( ((uint16) (s)) * (uint16)(1000 / VOLTAGERANGE_EXEC_TIME_MS))

typedef struct
{
	uint16 Low_Voltage_Low_Thres;
	uint16 Low_Voltage_High_Thres;
	uint16 High_Voltage_Low_Thres;
	uint16 High_Voltage_High_Thres;
	uint8 Out_Range_Time;
	uint8 In_Range_Time;
	uint8 Unused;
	uint8 Voltage_Out_Range_Cycle_Priority;
} VOLTAGERANGE_PARAM_TYPE;

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_VOLTAGE_RANGE

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_VOLTAGE_RANGE_LOG_MESSAGE_ID_ENUM
{
    VOLTAGERANGE_STATUS_CHANGED       = 1,
    VOLTAGERANGE_INSTABILITY_COUNTER  = 2,
} MODULE_VOLTAGE_RANGE_LOG_MESSAGE_ID_TYPE;

static uint16 VRM_Good_Range_Counter;
static uint16 VRM_Low_Range_Counter;
static uint16 VRM_High_Range_Counter;
static uint16 VRM_Instability_Counter;

VOLTAGERANGE_STATE_TYPE Voltage_Range_Status;
static VOLTAGERANGE_STATE_TYPE VRM_Instant_Voltage_Range_Status;

//! The volatile data required by the Voltage Range monitor.
static VOLTAGERANGE_PARAM_TYPE *VRM_Data;

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------
static void VoltageOutRangeManageSubCycle(uint8 priority);
static BOOL_TYPE CheckConditionToRunCycle(void);
static BOOL_TYPE IsMonitorEnabled(void);
//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the module VoltageRange and its variables
 *
 */
void VoltageRangeMonitor__Initialize(void)
{
	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		SETTINGFILE_LOADER_TYPE ptr;
		if (SettingFile__BasicLoader(SF_PTR_ACU_PRODUCT_CONFIGURATION_DATA, DSPL_VOLTAGE_RANGE_PARAMS, &ptr) == PASS)
		{
			VRM_Data = (VOLTAGERANGE_PARAM_TYPE *)(void *) ptr.Data;
		}
		else
		{
			VRM_Data = (VOLTAGERANGE_PARAM_TYPE *) VOLTAGERANGE_DEFAULT_PARAM_PTR;
		}

		VRM_Good_Range_Counter = 0;
		VRM_Low_Range_Counter = 0;
		VRM_High_Range_Counter = 0;
		Voltage_Range_Status = VOLTAGERANGE_STATE_UNDEFINED;
		VRM_Instant_Voltage_Range_Status = VOLTAGERANGE_STATE_UNDEFINED;
	}
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief		Monitor to check voltage range against thresholds and timeout set
 *
 */
void VoltageRangeMonitor__Execution(void)
{
	BOOL_TYPE update_status;
	uint32 voltage_ref;
	uint16 instability_ref;

	if (VRM_Data != NULL)
	{
		/* in subcycle VOLTAGE RANGE RECOVERY we turn on the PILOT RELAY to keep the monitor enabled */
		if (Interpreter__IsSubCycleRunning(COMPARTMENT_DEFAULT))
		{
			CYCLE_NAME_TYPE subcycle_name;
			subcycle_name = Selector__GetCycleNameId(Interpreter__GetCurrentSFIndex(COMPARTMENT_DEFAULT),
														COMPARTMENT_DEFAULT,
														Interpreter__GetStatus().Sub_Cycle[COMPARTMENT_DEFAULT]);

			if (subcycle_name == CYCLE_NAME_VOLTAGE_RANGE_RECOVERY)
			{
				uint8 pilot_relay_index;
				uint8 relay_enable_index;
				ON_OFF_TYPE value_state = ON;

				pilot_relay_index = Hbl__GetLoadIndexByLoadID(HBL_LOAD_PILOT_RELAY);
				relay_enable_index = Hbl__GetLoadIndexByLoadID(HBL_LOAD_RELAY_ENABLE);

				if (pilot_relay_index != (uint8)HBL_INDEX_INVALID)
				{
					(void)Hbl__SetLoadRequestByIndex(pilot_relay_index, HBL_PRIORITY_SUPERVISOR_EXT_MONITOR, (uint8 *) &value_state); //lint !e928 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
				}
				if (relay_enable_index != (uint8)HBL_INDEX_INVALID)
				{
					(void)Hbl__SetLoadRequestByIndex(relay_enable_index, HBL_PRIORITY_SUPERVISOR_EXT_MONITOR, (uint8 *) &value_state); //lint !e928 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
				}
			}
		}

	    if (IsMonitorEnabled())  /* this check point is to verify if ACLINE is present, PILOT RELAY is closed, RELAY ENABLE is closed, DOOR is closed and ZeroCross is present */
		{
			update_status = FALSE;
			voltage_ref = VOLTAGERANGE_GETREFERENCE();

			if (voltage_ref < ENDIANU16_STON(VRM_Data->Low_Voltage_Low_Thres))
			{
				/*Low Voltage condition occurred*/
				VRM_Instant_Voltage_Range_Status = VOLTAGERANGE_STATE_LOWVOLTAGE;
				if ((Voltage_Range_Status != VRM_Instant_Voltage_Range_Status) ||
					((VRM_High_Range_Counter + VRM_Good_Range_Counter) > (uint16)0))
				{
					VRM_Low_Range_Counter++;
				}

				if (VRM_Low_Range_Counter > VOLTAGERANGE_PARAM_TIME_CONVERT(VRM_Data->Out_Range_Time))
				{
					update_status = TRUE;
					StatisticsDish__IncreaseLowVoltageEventCounter();
				}
			}
			else if (voltage_ref > ENDIANU16_STON(VRM_Data->High_Voltage_High_Thres))
			{
				/*High Voltage condition occurred*/
				VRM_Instant_Voltage_Range_Status = VOLTAGERANGE_STATE_HIGHVOLTAGE;
				if ((Voltage_Range_Status != VRM_Instant_Voltage_Range_Status) ||
					((VRM_Low_Range_Counter + VRM_Good_Range_Counter) > (uint16)0))
				{
					VRM_High_Range_Counter++;
				}

				if (VRM_High_Range_Counter > VOLTAGERANGE_PARAM_TIME_CONVERT(VRM_Data->Out_Range_Time))
				{
					update_status = TRUE;
					StatisticsDish__IncreaseHighVoltageEventCounter();
				}
			}
			else if ((Voltage_Range_Status == VOLTAGERANGE_STATE_UNDEFINED) ||
					((voltage_ref >= ENDIANU16_STON(VRM_Data->Low_Voltage_High_Thres))
					&& (voltage_ref <= ENDIANU16_STON(VRM_Data->High_Voltage_Low_Thres))) )
			{
				/* Good Voltage condition occurred
				   When state is undefined, skip hysteresis thresholds */
				VRM_Instant_Voltage_Range_Status = VOLTAGERANGE_STATE_GOODRANGE;
				if ((Voltage_Range_Status != VRM_Instant_Voltage_Range_Status) ||
					((VRM_High_Range_Counter + VRM_Low_Range_Counter) > (uint16)0))
				{
					VRM_Good_Range_Counter++;
				}

				if (VRM_Good_Range_Counter > VOLTAGERANGE_PARAM_TIME_CONVERT(VRM_Data->In_Range_Time))
				{
					update_status = TRUE;
				}
			}
			else
			{
				/* No other actions required */
			}

			if ((uint8)update_status == (uint8)TRUE)
			{
				if (Voltage_Range_Status != VRM_Instant_Voltage_Range_Status)
				{
					LOG_ADD_EVENT(VOLTAGERANGE_STATUS_CHANGED, Voltage_Range_Status);
				}

				if (VRM_Instant_Voltage_Range_Status == VOLTAGERANGE_STATE_GOODRANGE)
				{
					instability_ref = VOLTAGERANGE_PARAM_TIME_CONVERT(VRM_Data->In_Range_Time);
				}
				else
				{
					instability_ref = VOLTAGERANGE_PARAM_TIME_CONVERT(VRM_Data->Out_Range_Time);
					VoltageOutRangeManageSubCycle(VRM_Data->Voltage_Out_Range_Cycle_Priority); /* RUN sub cycle for this particular situation */
				}

				VRM_Instability_Counter = VRM_Good_Range_Counter + VRM_High_Range_Counter + VRM_Low_Range_Counter;

				if (VRM_Instability_Counter > instability_ref)
				{
					LOG_ADD_EVENT(VOLTAGERANGE_INSTABILITY_COUNTER, VRM_Instability_Counter);
				}

				Voltage_Range_Status = VRM_Instant_Voltage_Range_Status;
				StatisticsDish__UpdateVoltageRangeStatus(Voltage_Range_Status);
				VRM_Good_Range_Counter = 0;
				VRM_Low_Range_Counter = 0;
				VRM_High_Range_Counter = 0;
			}
		}
	    else
		{
			Voltage_Range_Status = VOLTAGERANGE_STATE_UNDEFINED;
			VRM_Instant_Voltage_Range_Status = VOLTAGERANGE_STATE_UNDEFINED;
			StatisticsDish__UpdateVoltageRangeStatus(Voltage_Range_Status);
			VRM_Good_Range_Counter = 0;
			VRM_Low_Range_Counter = 0;
			VRM_High_Range_Counter = 0;
		}
	}
	else
	{
		Voltage_Range_Status = VOLTAGERANGE_STATE_UNDEFINED;
		VRM_Instant_Voltage_Range_Status = VOLTAGERANGE_STATE_UNDEFINED;
		StatisticsDish__UpdateVoltageRangeStatus(Voltage_Range_Status);
	}
}



//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief		Returns current voltage range Voltage_Range_Status
 *
 */
VOLTAGERANGE_STATE_TYPE VoltageRangeMonitor__GetStatus(void)
{
	return(Voltage_Range_Status);
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief		Returns if current voltage is within good range or not
 *
 */

BOOL_TYPE VoltageRangeMonitor__IsGoodRange(void)
{
	return((BOOL_TYPE) (Voltage_Range_Status == VOLTAGERANGE_STATE_GOODRANGE));
}

//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================

/**
 * this function run the Sub Cycle if the conditions exist
 * @param priority
 */
static void VoltageOutRangeManageSubCycle(uint8 priority)
{
    if (priority > 0U)
    {
        if ((uint8)CheckConditionToRunCycle() == (uint8)TRUE)
        {
            (void)SubCycle__RequestStart(COMPARTMENT_DEFAULT, priority);
        }
    }
}

/**
 *
 * @return
 */
static BOOL_TYPE CheckConditionToRunCycle(void)
{
    BOOL_TYPE result;
    INTERPRETER_STATUS_TYPE interpreter_status;
    CYCLE_NAME_TYPE cycle_name,subcycle_name;
    uint8 sf_index;

    result = FALSE;

    interpreter_status = Interpreter__GetStatus();

    sf_index = Interpreter__GetCurrentSFIndex(COMPARTMENT_DEFAULT);

    cycle_name = Selector__GetCycleNameId(sf_index, COMPARTMENT_DEFAULT, (uint8)(interpreter_status.Main_Cycle[COMPARTMENT_DEFAULT]));

    subcycle_name = Selector__GetCycleNameId(sf_index, COMPARTMENT_DEFAULT,	(uint8)interpreter_status.Sub_Cycle[COMPARTMENT_DEFAULT]);

    if ((cycle_name != CYCLE_NAME_DEMO_0) && (subcycle_name != CYCLE_NAME_DEMO_0) &&
    	(cycle_name != CYCLE_NAME_EOL_0) &&
    	(cycle_name != CYCLE_NAME_EOL_1) &&
    	(cycle_name != CYCLE_NAME_EOL_2) &&
    	(cycle_name != CYCLE_NAME_SERVICE_0) &&
    	(cycle_name != CYCLE_NAME_SERVICE_1) )
    {
        result = TRUE;
    }

    return result;
}

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief		Returns TRUE if ACLINE is present, PILOT RELAY is closed, RELAY ENABLE is closed, DOOR is closed and ZeroCross is present
 *
 */
static BOOL_TYPE IsMonitorEnabled(void)
{
	BOOL_TYPE result = FALSE;
	uint8 pilot_relay_state;
	uint8 relay_enable_state;

	if (Hbl__GetLoadIndexByLoadID(HBL_LOAD_PILOT_RELAY) != (uint8)HBL_INDEX_INVALID)
	{
		pilot_relay_state = ((uint8*)(Hbl__GetLoadStatusByLoadID(HBL_LOAD_PILOT_RELAY)))[0];
	}
	else
	{
		pilot_relay_state = ON;
	}

	if (Hbl__GetLoadIndexByLoadID(HBL_LOAD_RELAY_ENABLE) != (uint8)HBL_INDEX_INVALID)
	{
		relay_enable_state = ((uint8*)(Hbl__GetLoadStatusByLoadID(HBL_LOAD_RELAY_ENABLE)))[0];
	}
	else
	{
		relay_enable_state = ON;
	}

	if ((Hbl__GetGIIndexByGIID(HBL_GI_AC_LINE) != (uint8)HBL_INDEX_INVALID) &&
		((uint8)Hbl__IsZeroCrossPresent() == (uint8)TRUE) &&
		(DoorMonitor__GetDoorStatus() == DOOR_STATUS_CLOSE) &&
		(pilot_relay_state == (uint8)ON) &&
		(relay_enable_state == (uint8)ON))
	{
		result = TRUE;
	}

	return result;
}

