/**
 *  @file       
 *
 *  @brief      Basic description of file contents
 *
 *  @details    Detailed description of the file contents
 *
 *  @section    Applicable_Documents
 *					List here all the applicable documents if needed. <tr>	
 *
 *  $Header: $
 *
 *  @copyright  Copyright 2017-$Date$. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "AutostartFactoryCycleMonitor.h"

#include "C_Extensions.h"
#include "DishAuxVar.h"
#include "HotHighPotMonitor.h"
#include "Interpreter.h"
#include "Log.h"
#include "Micro.h"
#include "NVData.h"
#include "SettingFile.h"
#include "Supervisor.h"
#include "SystemTimers.h"
//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------
static SYSTEMTIMER_NV_TIMER_TYPE First_Reset_Timer_Handle;
static BOOL_TYPE Autostarted;
static uint8 AFC_Autostart_Factory_Cycle_Procedure;
static BOOL_TYPE EoL_Cycle_Running;

#pragma location = "_appliance_segment"
static uint8 AFC_Num_Reset;
#pragma location = "_appliance_segment"
static BOOL_TYPE AFC_AutoStart_Factory_Cycle_Enable;
//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_AUTOSTARTFACTORYCYCLE_MONITOR

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_AUTOSTARTFACTORYCYCLE_MONITOR_LOG_MESSAGE_ID_ENUM
{
	ERROR_LOADING_PARAMETERS       = 1,
	ERROR_READING_SELECTOR_DATA    = 2,
} MODULE_AUTOSTARTFACTORYCYCLE_MONITOR_LOG_MESSAGE_ID_TYPE;

//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the module HotHighPotMonitor and its variables
 *
 */
void AutostartFactoryCycle__Initialize(void)
{
	SETTINGFILE_LOADER_TYPE loader;

	if (Micro__GetResetMode() == MICRO_RESET_MODE_COLD)
	{
		if (NVData__GetLastRestoreStatus()->Bit.Appliance_Data_Recovered != (NVDATA_RESTORE_TYPE)NVDATA_RESTORE_OKAY)
		{
			AFC_Num_Reset = 0;
			AFC_Autostart_Factory_Cycle_Procedure = 0U;
			AFC_AutoStart_Factory_Cycle_Enable = FALSE;
		}

		DishAuxVar__SetDoFactoryCycle(FALSE);

		// Get the HotHighPotMonitor parameters from the setting file.
		if (SettingFile__BasicLoader(SF_PTR_ACU_PRODUCT_CONFIGURATION_DATA,
									 DSPL_HOTHIGHPOT_PARAMS,
									&loader) == FAIL)
		{
			LOG_ADD_EXCEPTION(ERROR_LOADING_PARAMETERS, 0);
		}
		else
		{
			// Read the setting file data into local variables for convenience.
			AFC_Autostart_Factory_Cycle_Procedure = (uint8)(((HOTHIGHPOT_MONITOR_INSTANCE_TYPE *)(void*)loader.Data)->Autostart_Factory_Cycle_Procedure);
		}

		if (AFC_Autostart_Factory_Cycle_Procedure == (uint8)TRUE)
		{
			if (AFC_Num_Reset == (uint8)0)
			{
				AFC_AutoStart_Factory_Cycle_Enable = TRUE;
			    (void)SystemTimers__NVSetTimerMS(&First_Reset_Timer_Handle, 30000, SYSTEMTIMERS_TYPE_DOWN_COUNTER);
			}
			else if ((AFC_Num_Reset >= (uint8)1) && (AFC_Num_Reset <= (uint8)4))
			{
				(void)SystemTimers__NVSetTimerMS(&First_Reset_Timer_Handle, 30000, SYSTEMTIMERS_TYPE_DOWN_COUNTER);
			}
			else
			{
				//do nothing
			}


			if (AFC_Num_Reset <= (uint8)5)
			{
				AFC_Num_Reset++;
			}
		}
	}
	EoL_Cycle_Running = FALSE;

}

void AutostartFactoryCycle__Execution(void)
{
	CYCLE_PHASE_STATEMENT_TYPE cps;
	CYCLE_NAME_TYPE cycle_name;
	PHASE_DATA_TYPE phase_data;

	// Autostart Factory Cycle Procedure
	if (AFC_Autostart_Factory_Cycle_Procedure == (uint8)TRUE)
	{
		if (SystemTimers__NVCheckTimer(&First_Reset_Timer_Handle) == SYSTEMTIMERS_STATE_DONE)
		{
			AFC_AutoStart_Factory_Cycle_Enable = FALSE; // Disable Procedure
			DishAuxVar__SetDoFactoryCycle(FALSE);
			SystemTimers__NVResetTimer(&First_Reset_Timer_Handle);
		}

		if ((AFC_Num_Reset >= (uint8)2) && (AFC_Num_Reset <= (uint8)5))
		{
			if ((uint8)HotHighPotMonitor__GetHotHighPotDone() == (uint8)TRUE)
			{
				if (((uint8)AFC_AutoStart_Factory_Cycle_Enable == (uint8)TRUE) && (DishAuxVar__GetDoFactoryCycle() == 0U))
				{
					DishAuxVar__SetDoFactoryCycle(TRUE);
				}
			}
		}

		// check Factory cycle
		if (Supervisor__IsTestCycleActive() != FALSE)
		{
			SystemTimers__NVResetTimer(&First_Reset_Timer_Handle);
			cps = Interpreter__GetCurrentStatement(COMPARTMENT_DEFAULT);
			cycle_name = Selector__GetCycleNameId(0,COMPARTMENT_DEFAULT,cps.Cycle);
			if ((CYCLE_NAME_EOL_0 == cycle_name) ||
				(CYCLE_NAME_EOL_1 == cycle_name) ||
				(CYCLE_NAME_EOL_2 == cycle_name))
			{
				if (DishAuxVar__GetDoFactoryCycle() == (uint8)TRUE) // Mean the Factory cycle is started automatically
				{
					AFC_AutoStart_Factory_Cycle_Enable = FALSE; // Disable Procedure
					DishAuxVar__SetDoFactoryCycle(FALSE);
					Autostarted = TRUE;
				}
				else if (Autostarted == FALSE) // Mean the Factory cycle is started manually
				{
					AFC_Num_Reset = 0;
					AFC_AutoStart_Factory_Cycle_Enable = TRUE; // Enable Procedure

					if (Selector__LoadPhaseData(0,
												COMPARTMENT_DEFAULT,
					                            cps.Cycle,
					                            cps.Phase,
					                            &phase_data) == FAIL)
					{
						LOG_ADD_EXCEPTION(ERROR_READING_SELECTOR_DATA, COMBINE_BYTES(cps.Cycle,cps.Phase));
					}
					else
					{
						if (cps.Phase >= (phase_data.Number_Of_Cycle_Phases - (uint8)1))
						{
							AFC_Num_Reset = (uint8)5;
							AFC_AutoStart_Factory_Cycle_Enable = FALSE; // Disable Procedure
						}
					}
				}
				else
				{
					//do nothing
				}
			}
		}
		else
		{
			Autostarted = FALSE;
		}
	}
}

void AutostartFactoryCycle__CycleStartEvent(void)
{
	CYCLE_PHASE_STATEMENT_TYPE cps;
	CYCLE_NAME_TYPE cycle_name;

	cps = Interpreter__GetCurrentStatement(COMPARTMENT_DEFAULT);
	cycle_name = Selector__GetCycleNameId(0,COMPARTMENT_DEFAULT,cps.Cycle);
	if ((CYCLE_NAME_EOL_0 == cycle_name) ||
		(CYCLE_NAME_EOL_1 == cycle_name) ||
		(CYCLE_NAME_EOL_2 == cycle_name))
	{
		EoL_Cycle_Running = TRUE;
	}
	else
	{
		EoL_Cycle_Running = FALSE;
	}
}

void AutostartFactoryCycle__CycleEndEvent(void)
{
	if((uint8)EoL_Cycle_Running == (uint8)TRUE)
	{
		EoL_Cycle_Running = FALSE;
		DishAuxVar__SetDoFactoryCycle(FALSE);	// Make sure autostart variable is reset when EoL ends

		if (Autostarted == FALSE)
		{
			AFC_Num_Reset = (uint8)5;
		    AFC_AutoStart_Factory_Cycle_Enable = FALSE; // Disable Procedure
		}
	}
}
//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================


